Bluetooth: fix potential unaligned access in CS HCI fields
This commit fixes an issue reported by LLVM Clang compiler
when building with -Wunaligned-access:
```
bluetooth/hci_types.h:4044:2: error: field  within
'struct bt_hci_le_cs_step_data_mode_1'
is less aligned than 'union bt_hci_le_cs_step_data_mode_1::
(include/zephyr/bluetooth/hci_types.h:4044:2)' and is usually due to
'struct bt_hci_le_cs_step_data_mode_1' being packed, which can lead
to unaligned accesses [-Werror,-Wunaligned-access]
```
and similar issues for other CS-specific types containing
unions

(cherry picked from commit f0c26dfb85b8e6903ff8bedcca8fd16f03ced895)

Original-Signed-off-by: Ivan Iushkov <ivan.iushkov@nordicsemi.no>
GitOrigin-RevId: f0c26dfb85b8e6903ff8bedcca8fd16f03ced895
Cr-Build-Id: 8692588942390808017
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692588942390808017
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ibce97fad07afa405fbdbc5610add377ea15b9567
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7487552
Tested-by: Jeremy Bettis <jbettis@chromium.org>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Reviewed-by: Jeremy Bettis <jbettis@chromium.org>