drivers: hda: insert an empty ";" statement before switch() labels
Only statements can be labeled in C, a declaration is not valid. This is
an FAQ.

While compilers currently in use don't seem to care, the "sparse" static
analyzer complains loudly (and cryptically):

```
drivers/dma/dma_intel_adsp_hda.c:190:17: error: typename in expression
drivers/dma/dma_intel_adsp_hda.c:190:26: error: Expected ; at end of stmt
drivers/dma/dma_intel_adsp_hda.c:190:26: error: got rp
```

Add an empty ";" statement after each label makes `sparse` and probably
others happy.

Also add missing `const` to constants for clarity.

Fixes commit a0263704619c ("drivers: hda: use interrupt for timing L1
exit on host DMA")

(cherry picked from commit f0fd9f1713426397d120897d5aadb2456fc8e9d3)

Original-https: //github.com/thesofproject/sof/actions/runs/6052920348/job/16427323549
Original-Original-Signed-off-by: Marc Herbert <marc.herbert@intel.com>
Original-GitOrigin-RevId: f0fd9f1713426397d120897d5aadb2456fc8e9d3
Original-Change-Id: I5d9f96a7ce2b9d99ea9d952bb0907b6a4d1068da
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4837468
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: c877e121d5018ed7d0ac16ed38da2b0fe1194cad
Cr-Build-Id: 8693162543395197713
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693162543395197713
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ide5a413d4265b456aa255a84829ae254bcafd103
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7422429
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>