scripts: sanitycheck: If error happens accessing YAML data, go on
Extend exception handling to cover not just YAML loading, but any
error while accessing parsed data too. That may catch e.g. schema
mismatch errors (for folks who don't have pykwalify installed, which
is optional). So, now error will be logged, but processing of other
tests will continue.

For example, I had a local, uncommitted test which wasn't converted
per 23f81eeb42668e and caused:

Traceback (most recent call last):
  File "./scripts/sanitycheck", line 2456, in <module>
    main()
  File "./scripts/sanitycheck", line 2324, in main
    options.outdir, options.coverage)
  File "./scripts/sanitycheck", line 1445, in __init__
    for name in parsed_data.tests.keys():

Original-AttributeError: 'list' object has no attribute 'keys'
Original-Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>
GitOrigin-RevId: 100474d99d44bfb46765bb38585097c967f3d6dd
Cr-Build-Id: 8694589597225911713
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694589597225911713
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ib020f1f9c37923366e167499d698fd13f3253b6c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7322762
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>