BACKPORT: media: mediatek: vcodec: mark vdec_vp9_slice_map_counts_eob_coef noinline
With KASAN enabled, clang fails to optimize the inline version of
vdec_vp9_slice_map_counts_eob_coef() properly, leading to kilobytes
of temporary values spilled to the stack:

drivers/media/platform/mediatek/vcodec/decoder/vdec/vdec_vp9_req_lat_if.c:1526:12: error: stack frame size (2160) exceeds limit (2048) in 'vdec_vp9_slice_update_prob' [-Werror,-Wframe-larger-than]

This seems to affect all versions of clang including the latest (clang-20),
but the degree of stack overhead is different per release.

Marking the function as noinline_for_stack is harmless here and avoids
the problem completely.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Nathan Chancellor <nathan@kernel.org>
Signed-off-by: Sebastian Fricke <sebastian.fricke@collabora.com>
Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>
(cherry picked from commit 8b55f8818900c99dd4f55a59a103f5b29e41eb2c)

BUG=b:424460404
TEST=USE=buildtest emerge-arm64-generic

Backport note: the file this function is located in changed between the
upstream commit and the 5.15 branch, so this CL updates the old file.

Change-Id: I97f233c8dc76ea7f37f035fb1cc5b872c5ecbce7
Signed-off-by: George Burgess IV <gbiv@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/6664499
Commit-Queue: George Burgess <gbiv@chromium.org>
Reviewed-by: Tomasz Figa <tfiga@chromium.org>
Tested-by: George Burgess <gbiv@chromium.org>