calypso: Re-enable GCC QSPI clock branches disabled by BL31
Coreboot enables the GCC QSPI clock branches during board
initialization, but BL31 (ARM Trusted Firmware) disables them as
part of its clock management before handing control to the payload.
As a result, the QSPI SPI-NOR flash controller is non-functional
when depthcharge attempts to access it.

Add GCC CBCR register defines to calypso.h and a qspi_clock_setup()
function in board.c that restores the CLK_ENABLE bit (bit 0) in each
affected CBCR prior to flash_setup().

TEST=SPI-NOR flash read/write functional on Calypso after BL31
     clock teardown.

LOGS:

Starting depthcharge on Calypso...
Looking for NVMe Controller 0xdb1f43f0 @ 01:00:00
Calypso: adding `reboot=warm` to kernel cmdline
Wipe memory regions:
        [0x00000081860000, 0x00000081a00000)
        [0x00000081d00000, 0x00000081e00000)
        [0x00000082000000, 0x00000082700000)
        [0x00000082800000, 0x00000084000000)
        [0x00000084400000, 0x00000084a00000)
        [0x00000085300000, 0x000000868d4000)
        [0x00000093f00000, 0x000000d7029000)
        [0x000000d70f1000, 0x000000d7180000)
        [0x000000d9400000, 0x000000db000000)
        [0x000000e01f8350, 0x000000ffe00000)
        [0x00000880000000, 0x00001000000000)
vb2_secdata_kernel_get: VB2_SECDATA_KERNEL_FLAGS not supported for secdata_kernel v0, return 0
vb2_secdata_kernel_get: VB2_SECDATA_KERNEL_FLAGS not supported for secdata_kernel v0, return 0
vb2_secdata_kernel_set: VB2_SECDATA_KERNEL_FLAGS not supported for secdata_kernel v0, silently ignore
vb2api_kernel_phase1: This is developer-signed firmware.
vb2api_kernel_phase2: GBB flags are 0x80000039
CBFS: Found 'locales' @0x226dc0 size 0x17 in mcache @0x86decca8
vb2_secdata_kernel_get: VB2_SECDATA_KERNEL_FLAGS not supported for secdata_kernel v0, return 0
vb2_digest_init: 23 bytes, hash algo 2, HW acceleration forbidden
get_locale_data: Supported locales: en es zh-CN ja (4 locales)
Initializing NVMe controller 144d:a810
Identified NVMe model SAMSUNG MZVLC1T0HFLU-00B07
Added NVMe drive "NVMe Namespace 1" lbasize:512, count:0x773bd2b0
start_fastboot_if_requested: ERROR: Fastboot not allowed
ui_loop_impl: <Developer mode> menu item <Boot from internal disk>
ui_display: screen=0x300, locale=0, focused_item=2, disabled_item_mask=0x0, hidden_item_mask=0x10, timer_disabled=0, current_page=0, error=0x0
display is not available hence, skip calling other display functions.
ui_display: init_screen() returned 0x100c0001
developer_mode_action: Booting default target after 2s
Trying disk: NVMe Namespace 1
GptNextKernelEntry: GptNextKernelEntry looking at new prio partition 7
GptNextKernelEntry: GptNextKernelEntry s0 t11 p15
GptNextKernelEntry: GptNextKernelEntry looking at new prio partition 8
GptNextKernelEntry: GptNextKernelEntry s0 t0 p0
GptNextKernelEntry: GptNextKernelEntry looking at new prio partition 13
GptNextKernelEntry: GptNextKernelEntry s0 t0 p0
GptNextKernelEntry: GptNextKernelEntry looking at new prio partition 14
GptNextKernelEntry: GptNextKernelEntry s0 t0 p0
GptNextKernelEntry: GptNextKernelEntry likes partition 7
vb2api_load_kernel: Found Android kernel entry at 17047552 size 8192
reserve_buffer_for_partition: Reserved buffer for 'boot' 0xa0000000[4000000]
reserve_buffer_for_partition: Reserved buffer for 'vendor_boot' 0xa4000000[6000000]
reserve_buffer_for_partition: Reserved buffer for 'init_boot' 0xaa000000[2000000]
reserve_buffer_for_partition: Reserved buffer for 'pvmfw' 0x868d6000[400000]
reserve_buffer_for_partition: Reserved buffer for 'dtbo' 0xac000000[200]
get_preloaded_partition: Load boot_a into 0xa0000000 bytes:4000000
get_preloaded_partition: Load dtbo_a into 0xac000000 bytes:200
avb_slot_verify.c:442: ERROR: dtbo_a: Hash of data does not match digest in descriptor.
get_preloaded_partition: Load init_boot_a into 0xaa000000 bytes:2000000
get_preloaded_partition: Load pvmfw_a into 0x868d6000 bytes:400000
get_preloaded_partition: Load vendor_boot_a into 0xa4000000 bytes:6000000
read_is_device_unlocked: true
vb2api_load_kernel: Combined version: 0x3f0
vb2api_load_kernel: Good partition 7
WriteAndFreeGptData: Updating GPT header 1
WriteAndFreeGptData: Updating GPT entries 1
WriteAndFreeGptData: Updating GPT header 2
WriteAndFreeGptData: Updating GPT entries 2
vb2api_load_kernel() = 0x0
Wrong android_misc_oem_cmdline magic (got: 0x0, expected 0x4c4d4346)
is_dtbo_image_valid: Invalid DTBO magic: 0x00000000
bootconfig_append_cmdline: androidboot.vbmeta.device=PARTUUID=518b3562-3c6f-4167-924e-c6debce1fd26 androidboot.vbmeta.public_key_digest=2b6cec325de9828429ae8e900aa6647d40fa84d0c862e7cead551b81c252c837 androidboot.vbmeta.avb_version=1.3 androidboot.vbmeta.device_state=unlocked androidboot.vbmeta.hash_alg=sha256 androidboot.vbmeta.size=6976 androidboot.vbmeta.digest=7c59902b2852256536dba0ba97cba5bb2616295626820cedf5c04b019a1a1748 androidboot.veritymode=disabled androidboot.vbmeta.boot.hash_alg=sha256 androidboot.vbmeta.boot.digest=3055044b2562893e987dbbf49f1b4295a24c0e3558262761acaff553c7fddc89 androidboot.vbmeta.dtbo.hash_alg=sha256 androidboot.vbmeta.dtbo.digest=96516a0af7dd2a2dc642d94e673f343c7dcb24fc0528bdbb03d4587600cf5c98 androidboot.vbmeta.init_boot.hash_alg=sha256 androidboot.vbmeta.init_boot.digest=01c9ad6eda5eff81b3ecea169f3672866d984f459687971a942d7ec9e8eb0da6 androidboot.vbmeta.pvmfw.hash_alg=sha256 androidboot.vbmeta.pvmfw.digest=0909e0f9f2882f379d1004d184e3d1e9a423fb071335f936cfb33afadd3b8fb8 androidboot.vbmeta.vendor_boot.hash_alg=sha256 androidboot.vbmeta.vendor_boot.digest=881546c35141621231f2593eedcb746c39dd97f51c1cdc63a45071245f4d933b androidboot.verifiedbootstate=orange androidboot.slot_suffix=_a androidboot.force_normal_boot=1
append_param: androidboot.boot_part_uuid=518b3562-3c6f-4167-924e-c6debce1fd26
hardware_descriptor not found in VPD, fall back to HWID.
append_param: androidboot.product.hardware.id=CALYPSO TEST 0166
mfg_sku_id not found in VPD
serial_number not found in VPD
append_param: androidboot.surface_flinger.primary_display_orientation=ORIENTATION_0
append_param: androidboot.product.vendor.sku=calypso_4294967295
append_param: androidboot.boot_source=internal
append_param: androidboot.bootloader=depthcharge-Google_Calypso.16670.0.0/Google_Calypso.16670.0.0
ERROR: Unable to get physical memory size from sysinfo
append_param: androidboot.vbmeta.public_key_digest:=0000000000000000000000000000000000000000000000000000000000000000
Modified kernel command line: dtb=x1e80100-crd.dtb clk_ignore_unused pd_ignore_unused efi=noruntime efi=novamap earlycon console=ttyMSM0,115200n8 kasan.stacktrace=off stack_depot_disable=off page_owner=on no_hash_pointers panic_on_taint=0x20 memory_dump_v2.enable_dynamic_memdump=1 video=vfb:640x400,bpp=32,memsize=3072000 printk.devkmsg=on qcom_geni_serial.con_enabled=1 kvm-arm.mode=protected arm64_sw.hvhe=0 id_aa64mmfr1.vh=0 kvm-arm.protected_modules=pkvm-geni,pkvm-smc-filter,qcom_smmu_v2_v3_dispatcher earlycon ufshcd_core.uic_cmd_timeout=2000 bootconfig rootwait ro init=/init silent_boot.mode=nonsilent pcie_aspm=off pcie_port_pm=off earlycon=qcom_geni,0x894000 android_arch_task_struct_size=512 irqaffinity=0-3 loglevel=6 androidboot.usbcontroller=a600000.dwc3 androidboot.baseband=apq pcie_ports=compat cpufreq.default_governor=performance printk.devkmsg=on DEBUG=2 8250.nr_uarts=4 log_buf_len=4M cgroup_disable=pressure root=/dev/ram0 firmware_class.path=/vendor/firmware_mnt reserve_mem=20M:2M:trace trace_instance=boot_mapped^traceoff@trace drm.trace=0x106 earlycon cpufreq.default_governor=performance cpuidle.governor=teo bootconfig reboot=warm
Loading FIT.
Image fdt@1 has 11640 bytes.
Image kernel@1 has 20181570 bytes.
Compat preference: google,calypso
Config conf@1 (default), kernel kernel@1, fdt fdt@1, compat qcom,mahua
No match, choosing default conf@1.
VPD entry 'bluetooth_mac0' does not exist
VPD entry 'wifi_mac0' does not exist
Disabling NVMe controller.
nvdata unchanged
Shutting down all USB controllers.
Exiting depthcharge with code 4 at timestamp: 25078599
LZ4 decompressing kernel@1
LZ4 decompressing kernel@1
append_param: androidboot.boottime=firmware:25120,splash:0
jumping to kernel

Change-Id: I9187556f8e1e4c6595824d5a96c5f8823d7beafb
Signed-off-by: Hari L <haril@qualcomm.corp-partner.google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/7902119
Reviewed-by: Subrata Banik <subratabanik@chromium.org>
Tested-by: Subrata Banik <subratabanik@chromium.org>