sys: device_mmio.h replace <toolchain/common.h> with <toolchain.h>
In include/sys/device_mmio.h, replacing <toolchain/common.h>
fixes the following warning:

$ west build -b qemu_x86  tests/arch/x86/static_idt/

In file included from zephyr/include/toolchain.h:50,
             from zephyr/include/linker/section_tags.h:12,
             from zephyr/include/linker/sections.h:132,
             from zephyr/include/sys/device_mmio.h:19,
             from zephyr/include/drivers/interrupt_controller/loapic.h:14,
             from zephyr/include/drivers/interrupt_controller/sysapic.h:10,
             from zephyr/include/arch/x86/arch.h:231,
             from zephyr/include/arch/cpu.h:15,
             from zephyr/tests/arch/x86/static_idt/src/test_stubs.S:17:
zephyr/include/toolchain/gcc.h:61: error: BUILD_ASSERT redefined [-Werror]
   61 | #define BUILD_ASSERT(EXPR, MSG...) _Static_assert(EXPR, "" MSG)
      |
In file included from zephyr/include/sys/device_mmio.h:18,
             from zephyr/include/drivers/interrupt_controller/loapic.h:14,
             from zephyr/include/drivers/interrupt_controller/sysapic.h:10,
             from zephyr/include/arch/x86/arch.h:231,
             from zephyr/include/arch/cpu.h:15,
             from zephyr/tests/arch/x86/static_idt/src/test_stubs.S:17:
zephyr/include/toolchain/common.h:165: note: this is the location of the
  previous definition
  165 | #define BUILD_ASSERT(EXPR, MSG...) \

<toolchain.h> provides a compiler-specific BUILD_ASSERT.
<toolchain/common.h> provides a generic, fallback BUILD_ASSERT and
should probably never be included directly.

Thanks to Gerard Marull-Paretas for recommending this fix.

Related to commit af20208cd942 ("devices: mark device MMIO declarations
to boot/pinned sections") that added #include <linker/sections.h>

(cherry picked from commit 61fe69dded30ee63444101c7fc69c8a490909a03)

Original-Signed-off-by: Marc Herbert <marc.herbert@intel.com>
Original-GitOrigin-RevId: 61fe69dded30ee63444101c7fc69c8a490909a03
Original-Change-Id: Idd7458f73ca03030243a028a2804b764f080a3fd
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3374458
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: eff6aa81a769729abc8d101da36e30f8417f874e
Cr-Build-Id: 8693650382705028001
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693650382705028001
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ic4fd59e788f3f80e6b7aa967bb2108b31dbbaa26
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7387149
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>