vrend: Fix int-conversion fatal build error with GCC-14
Getting below error int conversion during compilation as one the
platforms where EGLNativeDisplayType is an int instead of a pointer.

| ../git/src/vrend_winsys_egl.c: In function 'virgl_egl_init':
| ../git/src/vrend_winsys_egl.c:364:62: error: passing argument 2 of 'egl->funcs.epoxy_eglGetPlatformDisplay' makes pointer from
|   364 |                                                              (EGLNativeDisplayType)egl->gbm->device, NULL);
|       |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                                              |
|       |                                                              int
| ../git/src/vrend_winsys_egl.c:364:62: note: expected 'void *' but argument is of type 'int'

Signed-off-by: Purushottam Choudhary <purushottam27.kumar@lge.com>
Part-of: <https://gitlab.freedesktop.org/virgl/virglrenderer/-/merge_requests/1440>