chromeos-base/cryptohome: Add missing BDEPEND
```
FAILED: gen/bfbs/structures_generated.h
FileNotFoundError: [Errno 2] No such file or directory: 'flatc'

FAILED: gen/include/cryptohome/cryptorecovery/cryptorecovery.pb.cc gen/include/cryptohome/cryptorecovery/cryptorecovery.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'

FAILED: gen/include/cryptohome_key_delegate/dbus-proxies.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/cryptohome:9999

Change-Id: I0d81184efa696250e54c46426ecfe985dd57d945
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692092
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>