chromeos-base/rgbkbd: Add missing BDEPEND
```
FAILED: gen/include/rgbkbd/dbus_adaptors/org.chromium.Rgbkbd.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

```
/build/arm64-generic/etc/portage/hooks/install/check-seccomp.sh: line 27: compile_seccomp_policy: command not found
 * ERROR: chromeos-base/rgbkbd-9999::chromiumos failed:
 ```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/rgbkbd:9999

Change-Id: I6312c5a270a2b6e9ecc9d2d7fb6a51343048075e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692128
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>