net: capture: enable capturing of IPv6/v4 only
Net capturing would not link when either IPv6 or IPv4 was switched off
due to missing symbols. This change allows for capturing a single IP
protocol only.

To reproduce:

samples/net/sockets/http_client/prj.conf
```
-CONFIG_NET_IPV4=y
+CONFIG_NET_IPV4=n
-CONFIG_NET_CONFIG_NEED_IPV4=y
+CONFIG_NET_CONFIG_NEED_IPV4=n
+
+CONFIG_NET_CAPTURE=y
```

This will cause the following linker error:
```
.../subsys/net/lib/capture/capture.c:648:
    undefined reference to `net_if_ipv4_get_ttl'
```

(cherry picked from commit 9d1874f7f91be79d9dddd15d407a1cb7f9d8ee9d)

Original-Signed-off-by: Florian Grandel <fgrandel@code-for-humans.de>
GitOrigin-RevId: 9d1874f7f91be79d9dddd15d407a1cb7f9d8ee9d
Cr-Build-Id: 8738508474594683537
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8738508474594683537
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ic64d1e336a7886da6817167e6cb0a03e2ef37873
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5814313
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>