Autoupdate of 2 submodules
*chromite updated to 4e20028ef520161f48a7d0aebfdbc5cc88b7964c
contrib: add atria to generate_firmware_configs.py

BUG=b:502649111
TEST=Verify Manifest

Fixes this error message:
ERROR: No config for atria. Can't determine the source of ec branch

TODO: Clean this up to be scalable

Change-Id: I7d90851a70147f4193baa874161b811f13191616
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/8133486
Reviewed-by: YH Lin <yueherngl@chromium.org>
Tested-by: Bob Moragues <moragues@google.com>
Reviewed-by: Ivan Chen <yulunchen@google.com>
Commit-Queue: Bob Moragues <moragues@google.com>
Reviewed-by: Gilberto Contreras <gcontreras@google.com>

*infra/chromite-HEAD updated to 4e20028ef520161f48a7d0aebfdbc5cc88b7964c
contrib: add atria to generate_firmware_configs.py

BUG=b:502649111
TEST=Verify Manifest

Fixes this error message:
ERROR: No config for atria. Can't determine the source of ec branch

TODO: Clean this up to be scalable

Change-Id: I7d90851a70147f4193baa874161b811f13191616
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/8133486
Reviewed-by: YH Lin <yueherngl@chromium.org>
Tested-by: Bob Moragues <moragues@google.com>
Reviewed-by: Ivan Chen <yulunchen@google.com>
Commit-Queue: Bob Moragues <moragues@google.com>
Reviewed-by: Gilberto Contreras <gcontreras@google.com>