mbedtls: fix _mbedtls_init() invocation
SYS_INIT() requires pointer to function that takes `void` now, instead of
pointer to device structure. Since the commit was developed before that
switch, it still invoked it with NULL. Fix that now.

  zephyr/modules/mbedtls/zephyr_init.c: In function 'mbedtls_init':
  zephyr/modules/mbedtls/zephyr_init.c:108:16: error: too many arguments \
                                              to function '_mbedtls_init'
    108 |         return _mbedtls_init(NULL);
        |                ^~~~~~~~~~~~~
  zephyr/modules/mbedtls/zephyr_init.c:86:12: note: declared here
     86 | static int _mbedtls_init(void)
        |

(cherry picked from commit 630555d9f6ead7530b3d1e5a5fba96104607550c)

Original-Fixes:
Original-Original-Signed-off-by: Marcin Niestroj <m.niestroj@emb.dev>
Original-GitOrigin-RevId: 630555d9f6ead7530b3d1e5a5fba96104607550c
Original-Change-Id: Id96e0e76a4b91d556393805d34aca63656753932
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4670183
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: 5068902f7018fba614ad8ac7cda2bb146ea2ba61
Cr-Build-Id: 8693191221522410721
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693191221522410721
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I91519e581162d28b59df92759b907cbc2880b6a2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7419423
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>