sys: timeutil: check for 32-bit time_t to avoid warning
A warning was propogated to error when building for
native_sim/native.

```
timeutil.h:519:17: error: result of comparison of constant \
  -9223372036854775808 with expression of type '__time_t' (aka 'long') \
  is always false [-Werror,-Wtautological-constant-out-of-range-compare]
```

This is due to the issue described in #90029.

Add workarounds for `timespec_to_timeout()` and `timespec_negate()`
until 90029 is resolved.

(cherry picked from commit d61a7a80ad9cd316460af2822bbaa5bdff318dbd)

Original-Signed-off-by: Chris Friedt <cfriedt@tenstorrent.com>
GitOrigin-RevId: d61a7a80ad9cd316460af2822bbaa5bdff318dbd
Cr-Build-Id: 8713630084945030369
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8713630084945030369
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Iec2fdeaf813aa765bc6f128b9db772d2cbfce245
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6582206
Tested-by: Jeremy Bettis <jbettis@chromium.org>
Tested-by: Al Semjonovs <asemjonovs@google.com>
Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Al Semjonovs <asemjonovs@google.com>