chromeos-base/permission_broker: Add missing BDEPEND
```
FAILED: gen/include/permission_broker/dbus_adaptors/org.chromium.PermissionBroker.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/permission_broker:9999

Change-Id: Iac5081aa2bc04201dede07400d2d7d03e40e95e7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692122
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>