FROMGIT: scsi: ufs: host: mediatek: Require CONFIG_PM
[ Upstream commit bbb8d98fb4536594cb104fd630ea0f7dce3771d6 ]

The added print statement from a recent fix causes the driver to fail
building when CONFIG_PM is disabled:

drivers/ufs/host/ufs-mediatek.c: In function 'ufs_mtk_resume':
drivers/ufs/host/ufs-mediatek.c:1890:40: error: 'struct dev_pm_info' has no member named 'request'
 1890 |                         hba->dev->power.request,

It seems unlikely that the driver can work at all without CONFIG_PM, so
just add a dependency and remove the existing ifdef checks, rather than
adding another ifdef.

Fixes: 15ef3f5aa822 ("scsi: ufs: host: mediatek: Enhance recovery on resume failure")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: AngeloGioacchino Del Regno <angelogioacchino.delregno@collabora.com>
Link: https://patch.msgid.link/20260202095052.1232703-1-arnd@kernel.org
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit eb10468cef22191db937dd43377851b34e253ee7
 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
 linux-6.12.y)

BUG=b:515178734
TEST=cq

Change-Id: I7fcd1405eb390603be63f4f04a9673d3744ddbe4
Disallow-Recycled-Builds: test-failures
Signed-off-by: Lina Versace <linyaa@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/7898741
Reviewed-by: Sean Paul <sean@poorly.run>
Reviewed-by: Jędrzej Ciupis <jciupis@google.com>