Autoupdate of 2 submodules
*chromite updated to 4faf36903b271b39893ea37462623c29838293dd
cli: Remove "cros buildstore"

This command no longer works with current LUCI-based infra.  All I can
get it to report is:

ERROR: No build found. Perhaps not started?

Considering nobody has complained this is broken, let's just delete
it.

BUG=none
TEST=CQ

Change-Id: Icc5863fbd61bcf0a26519bfa6a59dbe7676dca32
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/5786096
Auto-Submit: Jack Rosenthal <jrosenth@chromium.org>
Reviewed-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Jack Rosenthal <jrosenth@chromium.org>

*infra/chromite-HEAD updated to 4faf36903b271b39893ea37462623c29838293dd
cli: Remove "cros buildstore"

This command no longer works with current LUCI-based infra.  All I can
get it to report is:

ERROR: No build found. Perhaps not started?

Considering nobody has complained this is broken, let's just delete
it.

BUG=none
TEST=CQ

Change-Id: Icc5863fbd61bcf0a26519bfa6a59dbe7676dca32
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/5786096
Auto-Submit: Jack Rosenthal <jrosenth@chromium.org>
Reviewed-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Jack Rosenthal <jrosenth@chromium.org>