lib/xe/xe_ioctl: Fix compilation on 32-bit armhf
Fix some compilation errors on 32-bit platforms like armhf:

../lib/xe/xe_ioctl.c:443:7: error: conflicting types for xe_bo_map_fixed void *xe_bo_map_fixed(int fd, uint32_t bo, size_t size, uint64_t addr)
       ^~~~~~~~~~~~~~~
In file included from ../lib/xe/xe_ioctl.c:46:
../lib/xe/xe_ioctl.h:89:7: note: previous declaration of xe_bo_map_fixed was here
 void *xe_bo_map_fixed(int fd, uint32_t bo, size_t size, long unsigned int addr);
       ^~~~~~~~~~~~~~~
../lib/xe/xe_ioctl.c: In function xe_bo_map_fixed:
../lib/xe/xe_ioctl.c:449:13: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  map = mmap((void *)addr, size, PROT_WRITE, MAP_SHARED | MAP_FIXED, fd, mmo);
             ^
cc1: some warnings being treated as errors

Fixes: 9eda33fedff7 ("tests/xe: Add system_allocator test")
Cc: Matthew Brost <matthew.brost@intel.com>
Cc: Jonathan Cavitt <jonathan.cavitt@intel.com>
Cc: Francois Dugast <francois.dugast@intel.com>
Signed-off-by: Kamil Konieczny <kamil.konieczny@linux.intel.com>
Reviewed-by: Francois Dugast <francois.dugast@intel.com>
Reviewed-by: Matthew Brost <matthew.brost@intel.com>