Add `target_compatible_with` on `copy_config` in `xz` (#2508)
Main change is to add `target_compatible_with` on `copy_config` as we
ran into
```
ERROR: /home/user/.cache/bazel/_bazel_user/5f48ff965103b174f3c248651ebad24d/external/xz~/BUILD.bazel:71:10: configurable attribute "src" in @@xz~//:copy_config doesn't match this configuration. Would a default condition help?

Conditions checked:
 @@platforms//os:android
 @@xz~//:linux_arm64
 @@xz~//:linux_x86_64
 @@xz~//:osx_arm64
 @@xz~//:osx_x86_64
 @@platforms//os:ios
 @@platforms//os:watchos
 @@platforms//os:tvos
 @@platforms//os:windows

To see a condition's definition, run: bazel query --output=build <condition label>.

This instance of @@xz~//:copy_config has configuration identifier 5075a55. To inspect its configuration, run: bazel config 5075a55.

For more help, see https://bazel.build/docs/configurable-attributes#faq-select-choose-condition.
```
and the OS this is configured for isn't in that list.

The other change is to switch to using `overlay` instead of patches
because it's almost impossible to read the patch files. The files are
otherwise unchanged.

I would have loved to upgrade to
https://github.com/tukaani-project/xz/releases/tag/v5.6.2 but I can only
`./configure` for my local Linux and don't know how to produce
`config.lzma-android.h` and friends.