chromeos-config-host: Add missing deps
Add missing runtime dependencies on things that cros_config_host
needs at runtime.

These were discovered in the chromeos-base/chromeos-assets build
under Bazel Alchemy, which currently fails with the following
errors:

```
13:16:34.632 >>> Install chromeos-base/chromeos-assets-0.0.2-r380 into /build/amd64-generic/tmp/portage/chromeos-base/chromeos-assets-0.0.2-r380/image
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/cros_config_host", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
 * ERROR: chromeos-base/chromeos-assets-0.0.2-r380::chromeos failed (install phase):
```

```
  File "/usr/lib/python3.8/site-packages/cros_config_host/libcros_schema.py", line 17, in <module>
    from jsonschema import validate  # pylint: disable=import-error
ModuleNotFoundError: No module named 'jsonschema'
```

```
  File "/usr/lib/python3.8/site-packages/cros_config_host/libcros_schema.py", line 18, in <module>
    import yaml  # pylint: disable=import-error
ModuleNotFoundError: No module named 'yaml'
```

BUG=b:305971616
TEST=cros_sdk -- bash -c 'BOARD=amd64-generic /mnt/host/source/chromite/bin/bazel build @portage//target/chromeos-base/chromeos-assets'

Change-Id: I17425673e4fb29c07661c49a27b5afd3f7f0ca7b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4953293
Reviewed-by: Jesse McGuire <jessemcguire@google.com>
Tested-by: Maksim Ivanov <emaxx@chromium.org>
Reviewed-by: Ryo Hashimoto <hashimoto@chromium.org>
Commit-Queue: Ryo Hashimoto <hashimoto@chromium.org>