tracing: rtio: fix building error in rtio header file
This patch is to fix the following building issue:
include/zephyr/rtio/rtio.h:1773:51: error: 'rtio' undeclared
(first use in this function)

(cherry picked from commit e2d6af1f55a50ef3856a83f4ba317028a047526b)

Original-Original-Signed-off-by: Jiafei Pan <Jiafei.Pan@nxp.com>
Original-GitOrigin-RevId: e2d6af1f55a50ef3856a83f4ba317028a047526b
Original-Cr-Build-Id: 8698221080423948257
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8698221080423948257
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ic4b2d9a17cc0b9f6c3511fa0209caf778e263bfa
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7158246
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: b7c624eda608f966a12b88a689d6f391c6c5c7e5
Cr-Build-Id: 8692642471503419777
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692642471503419777
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ie6decf1fa585db73ec269465f4bc423ed4f75eaa
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7480261
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>