drivers: sensor: Remove unused function
Building with clang warns:

drivers/sensor/st/ism330dhcx/ism330dhcx.c:107:19: error: unused function
'ism330dhcx_reboot' [-Werror,-Wunused-function]
static inline int ism330dhcx_reboot(const struct device *dev)

(cherry picked from commit 337ca4e4780b9a8aacf081b935c7c15b68f52c13)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: 337ca4e4780b9a8aacf081b935c7c15b68f52c13
Cr-Build-Id: 8723052172249940737
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723052172249940737
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I962b57f71694adb754a79259111355c3b04eb0df
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6261364
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>