chromeos-base/crosh: Add missing BDEPEND
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MissingCodegen(CannotFindBinaryPath)', /build/arm64-generic/usr/lib/cros_rust_registry/registry/tlsdate_dbus-0.24.52/build.rs:21:66
 * ERROR: chromeos-base/crosh-9999::chromiumos failed (compile phase):
```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CannotFindBinaryPath', /build/arm64-generic/usr/lib/cros_rust_registry/registry/vboot_reference-sys-1.0.0/build.rs:16:43
 * ERROR: chromeos-base/crosh-9999::chromiumos failed (compile phase):
```

When adding bindgen as a BDEPEND, we also need to add the virtual
into the DEPEND line.

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/crosh:9999

Change-Id: I0c774a5c395bdb1062aee3d49d7d379f57a7722b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692091
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>