drivers: flash: mark unused argument
Fixes:

```
.../zephyr/drivers/flash.h: In function 'flash_params_get_erase_cap':
.../flash.h:106:63: error: unused parameter 'p' [-Werror=unused-parameter]
  106 | int flash_params_get_erase_cap(const struct flash_parameters *p)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

(cherry picked from commit 272d52ff7ad47f43c4dac4976c9b90dc2099fb88)

Original-Signed-off-by: Nerijus Bendžiūnas <nerijus.bendziunas@astrolightspace.com>
GitOrigin-RevId: 272d52ff7ad47f43c4dac4976c9b90dc2099fb88
Change-Id: Id5a1437d1f341b9a869ba86398d9538bdaf3d8e4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5648161
Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>