drivers/wifi/winc1500: Fix build warnings with 64bit targets
Fix a set of warnings like:
drivers/wifi/winc1500/wifi_winc1500.c:332:25: error: cast from pointer
to integer of different size [-Werror=pointer-to-int-cast]
  332 |         SOCKET socket = (int)context->offload_context;

when int and void* do not have the same size, by casting the content
of context->offload_context to intptr_t which is whichever integer
size matches the pointer size.

(cherry picked from commit 9a50c10b346d64e330b09b6b1ac14fcee442c7f8)

Original-Original-Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
Original-GitOrigin-RevId: 9a50c10b346d64e330b09b6b1ac14fcee442c7f8
Original-Cr-Build-Id: 8732568629207591185
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8732568629207591185
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I726274e201a993f22d0bb9c49d68218affa6015d
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5980703
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Ting Shen <phoenixshen@chromium.org>
Original-Reviewed-by: Ting Shen <phoenixshen@chromium.org>
GitOrigin-RevId: ef6a5a0db420a632b1c7a8c1d9a17dcc268af415
Cr-Build-Id: 8692923083451228817
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692923083451228817
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I7160681d0b71f5f174cc5309c43a15a5c385d3c1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7446920
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>