UPSTREAM: freedreno/decode: Fix const correctness in get_tex_count
Fix compiler error:

../src/freedreno/decode/cffdec.c:580:7: error: assigning to 'char *'
from 'const char *' discards qualifiers
[-Werror,-Wincompatible-pointer-types-discards-qualifiers]
  580 |    p = strstr(name, "CONST");
      |      ^ ~~~~~~~~~~~~~~~~~~~~~

glibc now provides C23-style type-generic string functions. strstr
returns const char * when passed a const char * argument. Update p
declaration to const since it's only used for offset calculation.

Fixes: 1ea4ef0d3be ("freedreno: slurp in decode tools")
(cherry picked from commit bc34a122f3a1de1db14cbef2059c1228de58a89e)

Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/39828>

Backport Notes:
- resolve trivial .pick_status.json conflict

BUG=b:491765858
TEST=Local build on eve with glibc 2.43; CQ.

Change-Id: Ief9422583aa2d738fe2dc85b5a3772c95abba173
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/mesa/+/7849841
Reviewed-by: George Burgess <gbiv@chromium.org>
Reviewed-by: Sean Paul <sean@poorly.run>
Auto-Submit: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Commit-Queue: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: Yiwei Zhang <zzyiwei@google.com>
(cherry picked from commit 3efa69ead2cf1bcf68796189d34c8527e4bfc53c)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/mesa/+/7955943
Tested-by: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Commit-Queue: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Reviewed-by: Chia-I Wu <olv@google.com>
Auto-Submit: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Reviewed-by: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>