libchrome: Add unserialized_message_context.cc to libmojo
mojo/public/cpp/bindings/lib/unserialized_message_context.h
declares class UnserializedMessageContext. This class is used by
mojo/public/cpp/bindings/lib/message.cc, but the corresponding
implementation
mojo/public/cpp/bindings/lib/unserialized_message_context.cc
was not listed in the build target libmojo. This leads to errors
in some configurations. For example, building with -frtti would
build a libmojo.so that contains an undefined reference to the
typeinfo for UnserializedMessageContext.

This change adds unserialized_message_context.cc to the sources
for libmojo, fixing the problem.

BUG=b:422542836
TEST=build libchrome and chromeos-base/ml with USE=ubsan

Change-Id: I32fbd65386f81028a294eb0d791efd9a9b5831fc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/libchrome/+/6684906
Commit-Queue: Bob Haarman <inglorion@chromium.org>
Reviewed-by: Di Wu <diwux@google.com>
Tested-by: Bob Haarman <inglorion@chromium.org>