net: Fix build issues with arm-clang
The arm-clang compiler/linker does not optimize away unused function
symbols and thus will error if symbols that are referenced are not
defined.  To fix this add needed ifdef'ry.

Build various network samples that utilize ethernet but don't have
CONFIG_NET_PROMISCUOUS_MODE will get a link error for:

	Error: L6218E: Undefined symbol
	net_mgmt_NET_REQUEST_ETHERNET_SET_PROMISC_MODE
	(referred from ethernet.o).

Fix by adding ifdef protection around promisc code.

(cherry picked from commit 0090ad718a70af54a7a9d30cb02b1fe89ecf5e40)

Original-Original-Signed-off-by: Kumar Gala <kumar.gala@intel.com>
Original-GitOrigin-RevId: 0090ad718a70af54a7a9d30cb02b1fe89ecf5e40
Original-Change-Id: Id89d2dc78c66f4d91db0f92e951cf62bb2322759
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4479719
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: a801afe53dffe885b167532108621a234f0f588c
Cr-Build-Id: 8693283942708556769
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693283942708556769
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ic6883588102714489954125f284b01272b34d6df
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7413453
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>