UPSTREAM: soc/intel/xeon_sp/spr: Fix upd_display.c build error
Fix below build error after DISPLAY_UPD_DATA is selected:
src/soc/intel/xeon_sp/spr/upd_display.c:131:29: error: variable 'old' set but not used [-Werror=unused-but-set-variable]
  131 |         const FSP_S_CONFIG *old;
      |                             ^~~
src/soc/intel/xeon_sp/spr/upd_display.c:130:29: error: variable 'new' set but not used [-Werror=unused-but-set-variable]
  130 |         const FSP_S_CONFIG *new;

(cherry picked from commit 908be4f6edd27ef84ceb904912b92656258a88c0)

Original-Change-Id: I43ed5fadab58e0d4dc824457c7a1bdf48511198e
Original-Signed-off-by: Johnny Lin <johnny_lin@wiwynn.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/76342
Original-Reviewed-by: Sridhar Siricilla <sridhar.siricilla@intel.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: 908be4f6edd27ef84ceb904912b92656258a88c0
Change-Id: I49792a494d1ee8b39234f099143503c7c7008a8f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/4674233
Tested-by: Subrata Banik <subratabanik@chromium.org>
Reviewed-by: Subrata Banik <subratabanik@chromium.org>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Subrata Banik <subratabanik@chromium.org>