drivers: mdio: nxp_enet: Fix "expected statement" clangsa error
clangsa reports the error

mdio_nxp_enet.c:245:10: error: label at end of compound statement:
expected statement

(cherry picked from commit b4a059df75ab6c84f66c05bf9c2feb89c60d228e)

Original-Signed-off-by: Pieter De Gendt <pieter.degendt@basalte.be>
GitOrigin-RevId: b4a059df75ab6c84f66c05bf9c2feb89c60d228e
Change-Id: I38b06464536ee598a40f1e48d10e3fd19705583b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5180710
Tested-by: Tristan Honscheid <honscheid@google.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Tristan Honscheid <honscheid@google.com>