Autoupdate of 2 submodules
*chromite updated to bd91ee788ba7b0982f5ab9d4ad3b256c9b650270
Revert "lib: Annotate remaining types for cros_test_lib"

This reverts commit 4e216bf4dc2634308d0fdcd27d45709578f24bda.

Reason for revert: b:316067790 breaking unittests for firmware packages with `AttributeError: 'main' object has no attribute '_leaked_tempdir'`

Original change's description:
> lib: Annotate remaining types for cros_test_lib
>
> Also includes some type annotations for the osutils.TempDir class, as
> well as SetEnvironment and a few methods in lib/cache.py. I have not
> run mypy on either of these files.
>
> BUG=b:314695309
> TEST=cros format & cros lint
> TEST=scripts/mypy --strict --soft-error-limit=-1 --follow-imports=silent
> lib/cros_test_lib.py
> TEST=./run_tests
>
> Change-Id: Iabddde0ee70b1017d846d21dbe551c984f55c07b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/5109948
> Reviewed-by: Anuj Jamwal <anujjamwal@google.com>
> Tested-by: Lee Presland <zland@google.com>
> Auto-Submit: Lee Presland <zland@google.com>
> Commit-Queue: Lee Presland <zland@google.com>

BUG=b:314695309

Change-Id: Idb4972850d44634029382d19fd2ec5ab44151e08
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/5118581
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Pi-Hsun Shih <pihsun@chromium.org>
Commit-Queue: Pi-Hsun Shih <pihsun@chromium.org>

*infra/chromite-HEAD updated to bd91ee788ba7b0982f5ab9d4ad3b256c9b650270
Revert "lib: Annotate remaining types for cros_test_lib"

This reverts commit 4e216bf4dc2634308d0fdcd27d45709578f24bda.

Reason for revert: b:316067790 breaking unittests for firmware packages with `AttributeError: 'main' object has no attribute '_leaked_tempdir'`

Original change's description:
> lib: Annotate remaining types for cros_test_lib
>
> Also includes some type annotations for the osutils.TempDir class, as
> well as SetEnvironment and a few methods in lib/cache.py. I have not
> run mypy on either of these files.
>
> BUG=b:314695309
> TEST=cros format & cros lint
> TEST=scripts/mypy --strict --soft-error-limit=-1 --follow-imports=silent
> lib/cros_test_lib.py
> TEST=./run_tests
>
> Change-Id: Iabddde0ee70b1017d846d21dbe551c984f55c07b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/5109948
> Reviewed-by: Anuj Jamwal <anujjamwal@google.com>
> Tested-by: Lee Presland <zland@google.com>
> Auto-Submit: Lee Presland <zland@google.com>
> Commit-Queue: Lee Presland <zland@google.com>

BUG=b:314695309

Change-Id: Idb4972850d44634029382d19fd2ec5ab44151e08
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/5118581
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Pi-Hsun Shih <pihsun@chromium.org>
Commit-Queue: Pi-Hsun Shih <pihsun@chromium.org>