util.h: #include zephyr/toolchain.h, not zephyr/toolchain/common.h
Commit 9c5dafed95ee ("util: add type checking to CONTAINER_OF") made
`util.h` #include `toolchain/common.h` in order to get `BUILD_ASSERT()`
used by CONTAINER_OF_VALIDATE() when compiling C code.

However `toolchain/common.h` is not supposed to be included directly but
indirectly through `toolchain/<your_toolchain>.h` and in a very specific
order.

The direct inclusion caused the following warning when compiling C++:

```
toolchain/gcc.h:87: error: "ZRESTRICT" redefined [-Werror]
   87 | #define ZRESTRICT __restrict
      |
In file included from include/zephyr/sys/util.h:18:
include/zephyr/toolchain/common.h:33:
   33 | #define ZRESTRICT
```

Fix this issue #62464 by including `zephyr/toolchain.h` instead, as done
by 350 other files.

Fixes commit 9c5dafed95ee ("util: add type checking to CONTAINER_OF")

(cherry picked from commit a6540164d44d1f7d2715280cf1dc0bc40a6c423f)

Original-note: this is the location of the previous definition:
Original-Signed-off-by: Marc Herbert <marc.herbert@intel.com>
GitOrigin-RevId: a6540164d44d1f7d2715280cf1dc0bc40a6c423f
Change-Id: I00827de49e8e02d4e8040d4281e507b9e1d55ddf
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4866486
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Tested-by: Tristan Honscheid <honscheid@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Tristan Honscheid <honscheid@google.com>