usbc: fix shadowed declaration build error
/__w/zephyr/zephyr/subsys/usb/usb_c/usbc_tc_src_states.c:260:21: error:
declaration of 'ret' shadows a previous local [-Werror=shadow]

(cherry picked from commit 1c9be802bc090173fb308e1aaa76e3565cff9019)

Original-Fixes:
Original-Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-GitOrigin-RevId: 1c9be802bc090173fb308e1aaa76e3565cff9019
Original-Change-Id: I5236761b8ea71bacbadaa2617e1cd480b233d4a7
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5215322
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: e06977814692e6fdf76c954ee351586547f9b3ac
Cr-Build-Id: 8693090898819131345
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693090898819131345
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I72eb5dcde28dd9a6d12807801772b63835699625
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7430523
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>