Bluetooth: Classic: AVRCP: Fix Clang/LLVM build failures
Having variable declarations after labels causes build failures with
Clang/LLVM:

subsys/bluetooth/host/classic/avrcp.c:1269:2: error: label followed by a
declaration is a C23 extension [-Werror,-Wc23-extensions]
 1269 |         uint8_t failed_evt = 0;
      |         ^

/subsys/bluetooth/host/classic/avrcp.c:3809:3: error: label followed by a
declaration is a C23 extension [-Werror,-Wc23-extensions]
 3809 |              uint64_t identifier = sys_get_be64(data->identifier);
      |              ^

Fix these by moving the declarations to the top of the function in the
first case and add braces for the second.

(cherry picked from commit 445431c77922486b52e6df03c3f5c922dfbb1bd5)

Original-Original-Signed-off-by: Johan Hedberg <johan.hedberg@silabs.com>
Original-GitOrigin-RevId: 445431c77922486b52e6df03c3f5c922dfbb1bd5
Original-Cr-Build-Id: 8698228605132682497
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8698228605132682497
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ib5f5cd87ed5f054b7094c5bbc02a4d52a770647f
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7157513
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 283e0a52836f3f7427857657a5ee042bbac7f390
Cr-Build-Id: 8692642471503419777
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692642471503419777
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I4e9d36ca036fd23027abb9f4de8bacd460da1a98
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7475598
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>