drivers: i2c: stm32: don't manage cache aside DMA support
Fix STM32 I2C driver to not call cache management related functions
when DMA is not used. This change fixes an issue introduced by
commit 42c3a7814810 ("i2c: stm32: Add cache memory support"). The issue
makes boards embedding this driver with both CONFIG_I2C_STM32_V2_DMA
and CONFIG_ARCH_MPU disabled to fail to build with an error trace message
like the below:
   .../i2c_ll_stm32_v2.c:701: undefined reference to `mem_attr_check_buf'

(cherry picked from commit d0d8fa444fb308b3c8ba9daff1a58c26093e9f59)

Original-Fixes: 42c3a7814810a60cd23d719264695351ba5b8023
Original-Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
GitOrigin-RevId: d0d8fa444fb308b3c8ba9daff1a58c26093e9f59
Cr-Build-Id: 8719201802424120401
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8719201802424120401
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I22c9c71214cf947c2787c5f571d41ff2c6176494
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6406357
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>