net-wireless/floss: Add missing BDEPEND
```
  File "../../../../../../../tmp/portage/net-wireless/floss-9999/work/floss-9999/platform2/common-mk/file_generator_wrapper.py", line 19, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
Traceback (most recent call last):
  File "../../../../../../../tmp/portage/net-wireless/floss-9999/work/floss-9999/platform2/common-mk/file_generator_wrapper.py", line 19, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'flatc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/net-wireless/floss:9999

Change-Id: I29df21d0a3722b30034949cf3b949413d290b02b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692154
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>