Add -semihost mode to gcc command line
The semihost library provides basic console i/o and 'exit' calls
underneath libc. Adding this library to the linker is a bit tricky as
we need to pull put __iob before libc is scanned (to avoid using the
weak __iob there), but then the rest of libsemihost is scanned after
libc so that any undefined reference to _exit gets resolved.

Original-Signed-off-by: Keith Packard <keithp@keithp.com>
GitOrigin-RevId: 1329505ca187c33dfd5b890781b07a81df43312d
Cr-Build-Id: 8694321181936299617
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694321181936299617
Copybot-Job-Name: zephyr-project-picolibc-copybot-downstream
Change-Id: I5ce04d4ba431c875255adf3ca3788953277c1139
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7341493
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>