start-servod: Modify the nofile soft ulimit
Regarding to CL https://chromium-review.googlesource.com/c/chromiumos/third_party/hdctools/+/6032851
That CL adds in nofile ulimits. The smaller ulimit value here will cause an error.
================ error log ================
$ run-servod-tests
...
Exception in thread     retval = callback()
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ec3po/console.py", line 1143, in StartLoop
    with select.epoll() as poller:
         ^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files
...
===========================================

This change is to increase the nofile soft ulimit without generating an error.

BUG=b:378716023
TEST=Ran build-servod and run-servod-tests without generating an error

Change-Id: I45a5283cc6d7c1877877415f1ad1467786c3aa78
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/hdctools/+/6171781
Commit-Queue: Raymond Chung <raymondchung@ami.corp-partner.google.com>
Reviewed-by: Keith Haddow <haddowk@chromium.org>
Tested-by: Raymond Chung <raymondchung@ami.corp-partner.google.com>
Reviewed-by: Wai-Hong Tam <waihong@google.com>
Reviewed-by: 488603086791@cloudbuild.gserviceaccount.com <488603086791@cloudbuild.gserviceaccount.com>