sys-devel/llvm: Fix missing <cstdio>
```
/build/amd64-host/tmp/portage/sys-devel/llvm-17.0_pre496208_p20230501-r16/work/llvm-17.0_pre496208_p20230501/lldb/include/lldb/API/SBFile.h:28:10:
error: unknown type name 'FILE'
  SBFile(FILE *file, bool transfer_ownership);
           ^
```

BUG=b:295568460
TEST=BOARD=arm64-generic bazel run -k @portage//internal/packages/stage1/target/host/chromiumos/sys-devel/llvm:17.0_pre496208_p20230501-r16

Change-Id: I6af833dd378f959c2a718841db54318abbd8f807
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4775413
Reviewed-by: George Burgess <gbiv@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Auto-Submit: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Raul Rangel <rrangel@chromium.org>