Revert "FROMPULL: aarch32/mpu: Don't call function with empty data array"
This reverts commit 3ef5fe6031e4c674d5723c353decb327df645c4b.

Reason for revert: The Zephyr PR never merged. Our Zephyr EC builds
no longer needs this change. Also confirmed that the dynamic MPU functions are not part of the final link.

TEST=zmake build -a
TEST=twister

Original change's description:
> FROMPULL: aarch32/mpu: Don't call function with empty data array
>
> It's a no-op if there are no regions passed and gcc 11 complains
> that there might be an access to the array (which implies access to
> uninitialized memory because its size is 0) in the
> num_regions == 0 case.
>
> Error message without this change:
> error: 'arm_core_mpu_configure_dynamic_mpu_regions' reading 12 bytes from a region of size 0
>
> https://github.com/zephyrproject-rtos/zephyr/pull/39595
>
> BUG=b:201562004
> TEST=`emerge-herobrine chromeos-zephyr` gets past this error.
>
> Cq-Depend: chrome-internal:4198759
> Change-Id: Ie87985528b24bd6d04248386ed9029d44d38dac3
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3234420
> Commit-Queue: Patrick Georgi <pgeorgi@chromium.org>
> Commit-Queue: Raul E Rangel <rrangel@chromium.org>
> Tested-by: Patrick Georgi <pgeorgi@chromium.org>
> Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
> (cherry picked from commit 881db2524ba555584f626b7c6d1f9c3580f37513)
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3311518
> Reviewed-by: Denis Brockus <dbrockus@chromium.org>
> Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
> Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
> Commit-Queue: Jack Rosenthal <jrosenth@chromium.org>
> Tested-by: Jack Rosenthal <jrosenth@chromium.org>

Original-Bug: b:201562004
Original-Change-Id: I7a9cb266843d43365c319ecd7a41708d7cf43062
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3949623
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Original-Reviewed-by: Denis Brockus <dbrockus@chromium.org>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: 43a5d27ff23debc0a2a4e76ed2f65c82f2ff0abe
Cr-Build-Id: 8693437750037370881
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693437750037370881
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I19106b4acec4b45650dd674d9c054471223db8df
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7402105
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>