FROMGIT: mmc-utils: Fix build error MMC_BLOCK_MAJOR undeclared
The reported build error:
In function read_extcsd: mmc_cmds.c:72:18: error: MMC_BLOCK_MAJOR
undeclared (first use in this function)

In commit 118dc4a0909f ("mmc-utils: Remove unused MMC_BLOCK_MAJOR") the
define for MMC_BLOCK_MAJOR was dropped. In a way this commit is still
correct, but unfortunately it also introduced a dependency to a commit for
the Linux kernel (83fc5dd57f86 mmc: fix compilation of user API), which
fixes the mmc uapi header file.

Rather than relying on the commit in the kernel, let's include the missing
header for MMC_BLOCK_MAJOR.

Reported-by: Ming Liu <liu.ming50@gmail.com>
Fixes: 118dc4a0909f ("mmc-utils: Remove unused MMC_BLOCK_MAJOR")
Reviewed-by: Avri Altman <avri.altman@wdc.com>
Link: https://lore.kernel.org/r/20220426100605.36019-1-ulf.hansson@linaro.org
(cherry picked from commit 0d493fb091b592bde6004a618c28f1c3619af1a4
 https://git.kernel.org/pub/scm/utils/mmc/mmc-utils.git master)

BUG=None
TEST=compile

Change-Id: I826251e61c93b68f556ecfbcfef90c2500e77ad9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/mmc-utils/+/6193452
Reviewed-by: Alexis Savery <asavery@chromium.org>
Commit-Queue: Gwendal Grignou <gwendal@chromium.org>
Tested-by: Gwendal Grignou <gwendal@chromium.org>