chromeos-base/metrics: Add missing BDEPEND
```
FAILED: gen/include/metrics/structured/proto/storage.pb.cc gen/include/metrics/structured/proto/storage.pb.h gen/include/metrics/structured/proto/structured_data.pb.cc gen/include/metrics/structured/proto/structured_data.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
doins /build/arm64-generic/tmp/portage/chromeos-base/metrics-9999/work/metrics-9999/platform2/metrics/minijail/metrics_daemon.conf
into /usr
dobin /build/arm64-generic/var/cache/portage/chromeos-base/metrics/out/Default/update_reset_counter
chown: invalid user: ‘chronos:chronos-access’
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/metrics:9999

Change-Id: I15aa93ca4af9102f16c6a0d416b2525b54d3a986
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692111
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>