UPSTREAM: util/blob: Fix const correctness warning in blob_read_string
Fix compiler error:

  ../src/util/blob.c:344:8: error: assigning to 'uint8_t *' from
  'const void *' discards qualifiers
  [-Werror,-Wincompatible-pointer-types-discards-qualifiers]

glibc now provides C23-style type-generic string functions. memchr
returns const void * when passed a const void * argument. Update nul
declaration to const since it's only used to find the null terminator
position and calculate a size.

Fixes: 1c9877327ea ("glsl: Add blob.c---a simple interface for serializing data")
Reviewed-by: Tapani Pälli <tapani.palli@intel.com>
(cherry picked from commit b40850b24a09cd96c9de8c642fb8e4cd4ae587f6)
Link: https://gitlab.freedesktop.org/mesa/mesa/-/commit/b40850b24a09cd96c9de8c642fb8e4cd4ae587f6

Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/39462>

BUG=b:491765858
TEST=emerge-grunt media-libs/mesa-amd compiles cleanly

Change-Id: Iebda23d8f15eb83945f8d94dcdf2a98d73ff808b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/mesa/+/7993236
Tested-by: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Auto-Submit: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Commit-Queue: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>
Reviewed-by: Chia-I Wu <olv@google.com>