drivers: sensor: adi: max30210: Fix build with Clang/LLVM
drivers/sensor/adi/max30210/max30210_trigger.c:144:3: error: label followed
by a declaration is a C23 extension [-Werror,-Wc23-extensions]
  144 |                 uint8_t temp_hi_setup[2];
      |                 ^

drivers/sensor/adi/max30210/max30210_trigger.c:175:3: error: label followed
by a declaration is a C23 extension [-Werror,-Wc23-extensions]
  175 |                 uint8_t temp_inc_fast_thresh;
      |                 ^

drivers/sensor/adi/max30210/max30210_trigger.c:196:3: error: label followed
by a declaration is a C23 extension [-Werror,-Wc23-extensions]
  196 |                 uint8_t temp_dec_fast_thresh;
      |                 ^

(cherry picked from commit 0949f8a52ae981c7422b877e4fdce912b0666e3b)

Original-Original-Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>
Original-GitOrigin-RevId: 0949f8a52ae981c7422b877e4fdce912b0666e3b
Original-Cr-Build-Id: 8692838085574935745
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692838085574935745
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I9b782666c32dd5e872d13433c40da04f1fa16167
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7457820
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 2e5d4f633b27bcd892edfc1ba337626421765aff
Cr-Build-Id: 8692602135293398321
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692602135293398321
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I4ab1f65c754d7e8bb112d6ac9684b20453d02cf2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7486249
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>