Autoupdate of 2 submodules
*chromite updated to 5e2b763c7b3b005a1aec28dbb64e7d7e26091ab6
Revert "lib: Include resources/ in Lacros chrome copied paths"

This reverts commit 91a02d53981b427615dc0ef9f04982973d46ccd2.

Reason for revert: Seems to have broken chromite autoroll,
see https://autoroll.skia.org/r/chromite-chromium-autoroll/roll-history,
and example failure log looks related:
```
chromite.lib.chrome_util.MissingPathError: /b/s/w/ir/out/Release/lacros_clang/resources/accessibility/ does not exist and is required.
```

Will try again later, but reverting now to unblock autorolls.

Original change's description:
> lib: Include resources/ in Lacros chrome copied paths
>
> This will allow Lacros to find and load component extension
> resources used by a11y features in Ash to interact with
> Google Docs in Lacros.
>
> BUG=b:272150598
> TEST=Manual deploy_chrome --lacros with DUT
>
> Change-Id: I0a6a4d28fcbd0c498b9cc21f081b89405c71db1f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4619032
> Commit-Queue: Katie Dektar <katie@chromium.org>
> Tested-by: Katie Dektar <katie@chromium.org>
> Reviewed-by: Erik Chen <erikchen@chromium.org>
> Reviewed-by: Steven Bennetts <stevenjb@chromium.org>

BUG=b:272150598

Change-Id: Ida4d5385b4726777ea084c83470b24cfaef33b82
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4629999
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Fergus Dall <sidereal@google.com>
Reviewed-by: Erik Chen <erikchen@chromium.org>

*infra/chromite-HEAD updated to 5e2b763c7b3b005a1aec28dbb64e7d7e26091ab6
Revert "lib: Include resources/ in Lacros chrome copied paths"

This reverts commit 91a02d53981b427615dc0ef9f04982973d46ccd2.

Reason for revert: Seems to have broken chromite autoroll,
see https://autoroll.skia.org/r/chromite-chromium-autoroll/roll-history,
and example failure log looks related:
```
chromite.lib.chrome_util.MissingPathError: /b/s/w/ir/out/Release/lacros_clang/resources/accessibility/ does not exist and is required.
```

Will try again later, but reverting now to unblock autorolls.

Original change's description:
> lib: Include resources/ in Lacros chrome copied paths
>
> This will allow Lacros to find and load component extension
> resources used by a11y features in Ash to interact with
> Google Docs in Lacros.
>
> BUG=b:272150598
> TEST=Manual deploy_chrome --lacros with DUT
>
> Change-Id: I0a6a4d28fcbd0c498b9cc21f081b89405c71db1f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4619032
> Commit-Queue: Katie Dektar <katie@chromium.org>
> Tested-by: Katie Dektar <katie@chromium.org>
> Reviewed-by: Erik Chen <erikchen@chromium.org>
> Reviewed-by: Steven Bennetts <stevenjb@chromium.org>

BUG=b:272150598

Change-Id: Ida4d5385b4726777ea084c83470b24cfaef33b82
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4629999
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Fergus Dall <sidereal@google.com>
Reviewed-by: Erik Chen <erikchen@chromium.org>