UPSTREAM: acpi/sata.c: Fix Wunterminated-string-initialization error on port_name
src/acpi/sata.c: In function 'generate_sata_ssdt_ports':
src/acpi/sata.c:27:29: error: initializer-string for array of 'char' is too long [-Werror=unterminated-string-initialization]
   27 |         char port_name[4] = "PR00";
      |                             ^~~~~~

(cherry picked from commit 35ac087630d9355992c5355edb69ca6783d6fd97)

Original-Change-Id: Ie80c2329c4a2698bd9e72ba1b36c1c05e37b214b
Original-Signed-off-by: Elyes Haouas <ehaouas@noos.fr>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/84166
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Tim Wawrzynczak <inforichland@gmail.com>
Original-Reviewed-by: Sumeet Pawnikar <sumeet4linux@gmail.com>
GitOrigin-RevId: 35ac087630d9355992c5355edb69ca6783d6fd97
Cr-Build-Id: 8738004446171342033
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8738004446171342033
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I1efb866f951c596b43a47e90c5904b1c27b6fff7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5831085
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Nick Vaccaro <nvaccaro@google.com>
Commit-Queue: Nick Vaccaro <nvaccaro@google.com>