Revert "chameleon: Remove SendHIDReport redundant DBus route"
This reverts commit e4d12c6be67f50a7f7660dd3dcec3f646f635caa.

Reason for revert: not working code

We need to call the D-Bus method using the D-Bus connection so that call_async will invoke it. call_async accepts a reply_handler and an error_handler.

```
2024-10-30 21:51:20,752 ERROR Failed to run method bluetooth_mouse.LeftClick,  Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/chameleond-0.0.2-py3.7.egg/chameleond/drivers/fpga_tio.py", line 249, in _dispatch
    return func(*params)
  File "/usr/local/lib/python3.7/dist-packages/chameleond-0.0.2-py3.7.egg/chameleond/devices/raspi_bluetooth_flow.py", line 277, in LeftClick
    self._PressLeftButton()
  File "/usr/local/lib/python3.7/dist-packages/chameleond-0.0.2-py3.7.egg/chameleond/devices/raspi_bluetooth_flow.py", line 259, in _PressLeftButton
    self.MousePressButtons({PeripheralKit.MOUSE_BUTTON_LEFT})
  File "/usr/local/lib/python3.7/dist-packages/chameleond-0.0.2-py3.7.egg/chameleond/utils/bluetooth_raspi.py", line 1547, in MousePressButtons
    self.SendHIDReport(mouse_codes)
  File "/usr/local/lib/python3.7/dist-packages/chameleond-0.0.2-py3.7.egg/chameleond/utils/bluetooth_raspi.py", line 1398, in SendHIDReport
    error_handler=self.KeysErrorHandler,
TypeError: SendHIDReport() got an unexpected keyword argument 'reply_handler'
```

Original change's description:
> chameleon: Remove SendHIDReport redundant DBus route
>
> Calling SendHIDReport directly from raspi_bluez_service.py
>
> BUG=b:376110916
> TEST=test_that --args "btpeer_host_list=${RASPBERRY_IP} \
> router_addr=${AP_IP}" ${DUT_IP} \
> bluetooth_WiFiCoexPerformance.<test_name>.11n
>
> Change-Id: If316458f0d95a227360046b6dda461c08f291c85
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/chameleon/+/5972995
> Reviewed-by: Yun-hao Chung <howardchung@chromium.org>
> Commit-Queue: Mohammad Kh Sabri <mohammad.kh.sabri@exalt.ps>
> Tested-by: Mohammad Kh Sabri <mohammad.kh.sabri@exalt.ps>

BUG=b:376110916

Change-Id: I166c1a3d861e8b4c463f7956670d9063b8a87132
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/chameleon/+/5982228
Auto-Submit: John Lai <johnlai@google.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>