drivers: sensor: Remove unused function
Building with clang warns:

drivers/sensor/st/ism330dhcx/ism330dhcx.c:107:19: error: unused function
'ism330dhcx_reboot' [-Werror,-Wunused-function]
static inline int ism330dhcx_reboot(const struct device *dev)

(cherry picked from commit 337ca4e4780b9a8aacf081b935c7c15b68f52c13)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 337ca4e4780b9a8aacf081b935c7c15b68f52c13
Original-Cr-Build-Id: 8723052172249940737
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723052172249940737
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I962b57f71694adb754a79259111355c3b04eb0df
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6261364
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: e95ba66f3e46040b071a8871e4359589e4621bc7
Cr-Build-Id: 8692854981942345489
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692854981942345489
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I1568d5409bbfdfa7be257dc45c9aa9715c003988
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7454791
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>