drivers: gpio_pca95xx: add missing gpio_utils.h include
Include gpio_utils.h to fix a build failure:

gpio_pca95xx.c:490:20: warning: implicit declaration of
 function 'GPIO_PORT_PIN_MASK_FROM_NGPIOS'
 [-Wimplicit-function-declaration]
gpio_pca95xx.c:490:20: error: initializer element is not constant
   .port_pin_mask = GPIO_PORT_PIN_MASK_FROM_NGPIOS(
    DT_INST_##inst##_NXP_PCA95XX_NGPIOS), \

Original-Signed-off-by: Göran Weinholt <goran.weinholt@endian.se>
GitOrigin-RevId: d3ff59d383cb1bf8898b3fedefef2c390e84709e
Cr-Build-Id: 8694085109502099201
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694085109502099201
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: If2b9d76121d3c37077e5e7142b3595947063d46c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7356501
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>