pw_protobuf: Add restrict version in setup.cfg
pw_protobuf's setup.cfg previously restricted protobuf>=3.20.1, often
leading to newer much newer protobuf versions getting installed (e.g.
4.x).

Unfortunately, CIPD is currently shipping protoc 3.17.3, which is not
directly compatible with those newer protobuf versions. This commit
adds a restriction that protobuf<=3.20.3, the last protobuf version
compatible with protoc 3.17.3.

Once protoc is upgraded in CIPD this restriction may be able to be
lifted.

Error Message:
==============================
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of
date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible
workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use
    pure-Python parsing and will be much slower).

More information:
https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

==============================

Change-Id: I9394197555d45695b58e92894f0966151560db39
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/141370
Pigweed-Auto-Submit: Anthony DiGirolamo <tonymd@google.com>
Commit-Queue: Anthony DiGirolamo <tonymd@google.com>
Reviewed-by: Alexei Frolov <frolv@google.com>