twister: coverage: set gcov working directory
gcovr runs gcov to generate temporary coverage files into the gcov
working directory. The working directory defaults to gcovr's -r
argument.

When running twister with the --coverage-per-instance argument, multiple
gcovr instances may run in parallel. Since they all share the same gcov
working directory, they may interfere with each other, resulting in
errors like this:

	AssertionError: Sanity check failed, output file
	spinlock.h##4167b923a06cc9590c8eef372f016a6d.gcov doesn't exist
	but no error from GCOV detected.

To fix this, specify a separate gcov working directory for every test
through gcovr's --gcov-object-directory option.

(cherry picked from commit d45985347b47f608ad6cf731e5d679fe22913ae3)

Original-Signed-off-by: Marco Widmer <marco.widmer@bytesatwork.ch>
GitOrigin-RevId: d45985347b47f608ad6cf731e5d679fe22913ae3
Cr-Build-Id: 8706540875242396545
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8706540875242396545
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I45b59a58f543dfef7aa567721c72a93628b4c946
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6851660
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>