include: zephyr: arch: add missing stddef.h/stdbool.h in cache.h
Add missing inclusion of stddef.h and stdbool.h to respectively define
size_t and bool types used in some cache.h function declarations.

This change prevents build errors like:

.../include/zephyr/arch/cache.h:105:41: error: unknown type name 'size_t'
  105 | int arch_dcache_flush_range(void *addr, size_t size);
      |                                         ^~~~~~

(cherry picked from commit be62ee205adedb31b56f43d3fa5b9adee39b365a)

Original-Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
GitOrigin-RevId: be62ee205adedb31b56f43d3fa5b9adee39b365a
Cr-Build-Id: 8700425573583840625
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8700425573583840625
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I962923af1bd489f4fc6d0bb2461978d85c1a1ddf
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7066114
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>