dev-rust/system_api: Add missing BDEPEND
```
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MissingCodegen(CannotFindBinaryPath)', build.rs:151:66
  stack backtrace:
     0: rust_begin_unwind
     1: core::panicking::panic_fmt
     2: core::result::unwrap_failed
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
 * ERROR: dev-rust/system_api-9999::chromiumos failed (compile phase):
```

```
thread 'main' panicked at 'protoc binary not found: cannot find binary path', /build/arm64-generic/usr/lib/cros_rust_registry/registry/protobuf-parse-3.2.0/src/protoc/command.rs:174:17
 ```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/dev-rust/system_api:9999

Change-Id: Id27af369a00ba62f2ecdff81d982899abe226f02
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692148
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>