bluetooth: classic: shell: mitigate label followed by declaration
A recent change triggered a warning in LLVM that was promoted to error
when run with twister.

```shell
goep.c:102:3: error: label followed by a declaration is a C23 extension
  [-Werror,-Wc23-extensions]
  102 |                 int err;
```

Add a scope to the switch case so that the declaration has proper scope.

(cherry picked from commit 62f62dbb0bdedefb9dd4a6fef7da7f91bcf7b298)

Original-Signed-off-by: Chris Friedt <cfriedt@tenstorrent.com>
GitOrigin-RevId: 62f62dbb0bdedefb9dd4a6fef7da7f91bcf7b298
Cr-Build-Id: 8707016510567822897
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8707016510567822897
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ia8284cb598a04e47833b3298e727b79d2d3defcd
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6833026
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>