Add <stdlib.h> for free
Add stdlib.h includes to fix C++23 build errors because C++23 removed
certain transitive includes

Errors:
external/minijail/test_util.h:37:7: error: use of undeclared identifier
'free'
   37 |       free(entry);
external/minijail/test_util.h:46:7: error: use of undeclared identifier
'free'
   46 |       free(str);

Bug: 429048222
Test: m config_parser_unittest_gtest
Change-Id: I2d2041d55ea7b44362e0b757d9204dc98ab6bca7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/minijail/+/7374874
Reviewed-by: Jorge Lucangeli Obes <jorgelo@chromium.org>
Commit-Queue: Sharjeel Khan <sharjeelkhan@google.com>
Auto-Submit: Sharjeel Khan <sharjeelkhan@google.com>
Tested-by: Sharjeel Khan <sharjeelkhan@google.com>