chromeos-base/lorgnette: Add missing BDEPEND
```
FAILED: gen/include/lorgnette/dbus_adaptors/org.chromium.lorgnette.Manager.h

FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/lorgnette:9999

Change-Id: I99bc0ce4dca773a9a768d0427ebd96e1110e3bfb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692109
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>