tests: arch: arm: custom_interrupt: fix build issue
Fix build issue when multi level interrupts is enabled,
define new macro TEST_1ST_LEVEL_INTERRUPTS_MAX to support multi
level interrupts case.
  - core_cm33.h:2559:47: error: iteration 496 invokes undefined behavior
    [-Werror=aggressive-loop-optimizations]

(cherry picked from commit 0ea051a4331f9da5800b03909f7e5cff5309ad62)

Original-Original-Signed-off-by: Biwen Li <biwen.li@nxp.com>
Original-GitOrigin-RevId: 0ea051a4331f9da5800b03909f7e5cff5309ad62
Original-Cr-Build-Id: 8696212821870935201
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8696212821870935201
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I23a8f59c1192b2179f742d59f1c5c982feade999
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7235525
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
GitOrigin-RevId: 582c383ecb2ead3684948e846837b27d540338b4
Cr-Build-Id: 8692622784029784161
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692622784029784161
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I435c3506ff7b0325349df2bd2b4fbeaad0301eba
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7482460
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>