dts: arm: st: add stm32c071 dtsi files
- provide support for the STM32C071 serie
- add stm32g0-flash-controller compatible on flash node
to fix CI issue on undefined reference to
`flash_stm32_page_layout'

(cherry picked from commit 0ef33f3e7752e6c785957e79436148eefe57c54d)

Original-Signed-off-by: Fabrice DJIATSA <fabrice.djiatsa-ext@st.com>
GitOrigin-RevId: 0ef33f3e7752e6c785957e79436148eefe57c54d
Cr-Build-Id: 8727764308049365969
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8727764308049365969
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I778e7f3972c369e0c64f626ed75345ddaf6faf9f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6114347
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>