kernel: cmake: fix k_sleep compilation error for single thread
Fix k_sleep compilation error:
[build] ... syscalls/kernel.h:135: undefined reference to `z_impl_k_sleep'
for single thread applications (CONFIG_MULTITHREADING = n).
The shed.c contains source code which must be present also
in single thread applications.

(cherry picked from commit cc4ffb2a54bd136095100c899f1b875fd1ce6f9d)

Original-Signed-off-by: Andrej Butok <andrey.butok@nxp.com>
GitOrigin-RevId: cc4ffb2a54bd136095100c899f1b875fd1ce6f9d
Change-Id: I3f140cccc99e8bad0bd9586b1f7de6c37ee02e1a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5121990
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Yuval Peress <peress@google.com>
Tested-by: Yuval Peress <peress@google.com>
Commit-Queue: Yuval Peress <peress@google.com>