doc: dts: add help for undefined reference to __device_dts_ord_N
This is an FAQ and we don't have a satisfactory page that describes
the current state of the world for how to troubleshoot. This leads
to frustrated users and duplicated support efforts. Try to improve
this by at least writing down what people have to do today.

If we ever improve the situation by adding a machine-readable map
between drivers, Kconfig options, and DT compatibles, we can hopefully
do better than this, but at least it's a start.

(cherry picked from commit c625a0e7a820245cf1dbd18dceb7b8a2847ace67)

Original-Original-Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>
Original-GitOrigin-RevId: c625a0e7a820245cf1dbd18dceb7b8a2847ace67
Original-Change-Id: I0aa89d585aadd6f85711f7eeb72611b649108084
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4484081
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: fe5459bb7e009a6ab6c9997a00d81125f48db03c
Cr-Build-Id: 8693283942708556769
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693283942708556769
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I01f2533313dc271d90e0df1c30260d904933b052
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7413463
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>