drivers: net: initialize logging for the slip module
This fixes a regression introduced in:

16a0e314ea drivers: net: Move Ethernet device definition for SLIP to
	   ethernet

Where the module would fail to build with:

log_core.h:153:20: error: '__log_level' undeclared (first use in this
function)

Registering a module fixes the build.

(cherry picked from commit d4c8de514f8b223e8b76c16dbfad482a2ca92edf)

Original-Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-GitOrigin-RevId: d4c8de514f8b223e8b76c16dbfad482a2ca92edf
Original-Change-Id: If635be79a2e8cc7bd1420dc338d08156533ff54a
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4274659
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Original-Tested-by: Al Semjonovs <asemjonovs@google.com>
Original-Commit-Queue: Al Semjonovs <asemjonovs@google.com>
GitOrigin-RevId: 91e8f4fae43562beef3d99d12da0cb79deb6e5aa
Cr-Build-Id: 8693343704746485041
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693343704746485041
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I0658238afdb7f0858b78192b13e132b745733b86
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7408833
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>