sys: timeutil: check for 32-bit time_t to avoid warning (part 2)
Same error had to be fixed in the branch where optimizations were done.

This is probably a good example of where using `if (IS_ENABLED()) ...`
is a better choice than using `#ifdef`. Because the compiler would have
caught this error last time as well.

Anyway, same problem - different line(s)!

A warning was propogated to error when building for
native_sim/native.

```
timeutil.h:682:17: error: result of comparison of constant \
  -9223372036854775808 with expression of type '__time_t' (aka 'long') \
  is always false [-Werror,-Wtautological-constant-out-of-range-compare]
timeutil.h:680:17: error: result of comparison of constant \
  -9223372036854775808 with expression of type '__time_t' (aka 'long') \
  is always false [-Werror,-Wtautological-constant-out-of-range-compare]
```

This is due to the issue described in #90029.

Add workarounds for `timespec_to_timeout()` and `timespec_negate()`
until 90029 is resolved.

(cherry picked from commit d3ec91674a479f8c79ee51d75f6d01724475cfba)

Original-Original-Signed-off-by: Chris Friedt <cfriedt@tenstorrent.com>
Original-GitOrigin-RevId: d3ec91674a479f8c79ee51d75f6d01724475cfba
Original-Cr-Build-Id: 8713630084945030369
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8713630084945030369
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I81f3930132eb95abd5fb3198f0202c547a93f020
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6583327
Original-Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: Jeremy Bettis <jbettis@chromium.org>
GitOrigin-RevId: 1b476ff362dd2f10ed99a8e26ac2eb74bc7d1eb7
Cr-Build-Id: 8692785280656480161
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692785280656480161
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ic43973cb4f14ede4128125c1b7c8c06ddb15fd20
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7463794
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>