UPSTREAM: drivers/lenovo/hybrid_graphics: Add missing header Android Bringup: See http://go/android-fw-sync
Include the missing header stdbool.h

Fixes compilation error
hybrid_graphics.h:6:28: error: unknown type name 'bool'
while refactoring some code.

(cherry picked from commit 6a20caea01c5c72a4e57217990ac6aacdc6b7724)

(cherry picked from commit 63e5156c0bd2c16bbdafc8b1b9958335db771b49)

Original-Original-Change-Id: I96f7255049cd9e24d74838a173e920a00636b09e
Original-Original-Signed-off-by: Patrick Rudolph <patrick.rudolph@9elements.com>
Original-Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/88546
Original-Original-Reviewed-by: Paul Menzel <paulepanter@mailbox.org>
Original-Original-Reviewed-by: Angel Pons <th3fanbus@gmail.com>
Original-Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-GitOrigin-RevId: 6a20caea01c5c72a4e57217990ac6aacdc6b7724
Original-Cr-Build-Id: 8708345266036186753
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8708345266036186753
Original-Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I6787b26f2fb69af990981758910291bd894f5378
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6788470
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: Kshitij Shah <tij@google.com>
Original-Reviewed-by: Kshitij Shah <tij@google.com>
GitOrigin-RevId: 63e5156c0bd2c16bbdafc8b1b9958335db771b49
Cr-Build-Id: 8708092348870309825
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8708092348870309825
Copybot-Job-Name: android-main-coreboot-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6793110
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>