boards: beagle_bcf: Fix undefined references to pinctrl and gpio device
This patch fixes undefined references when compiling tests/drivers/flash
for beagleconnect_freedom board using following command:

west build -b beagleconnect_freedom tests/drivers/flash

Adding CONFIG_PINCTRL fixes undefined references to
'pinctrl_lookup_state' and 'pinctrl_configure_pins'.

Adding CONFIG_GPIO fixes undefined reference to '__device_dts_ord_13'
from spi_nor and spi_cc13xx_cc26xx drivers.

Fixes #56181

(cherry picked from commit 5ec4aaff5c676841dc1932096bd0606435fb0c26)

Original-Original-Signed-off-by: Patryk Duda <pdk@semihalf.com>
Original-GitOrigin-RevId: 5ec4aaff5c676841dc1932096bd0606435fb0c26
Original-Change-Id: I25a749b4cb7956cbcd652f58976d75f7844e97a2
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4377019
Original-Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Original-Tested-by: Al Semjonovs <asemjonovs@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Commit-Queue: Al Semjonovs <asemjonovs@google.com>
GitOrigin-RevId: a3a5dd2d696be00c7d6f5204978c5b9e3724e9a9
Cr-Build-Id: 8693314360975565745
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693314360975565745
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I5ef5f8187fdc720f63a4dd23040cca1872ee2a81
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7411224
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>