Bluetooth: controller: split: openisa: fix missing include
If CONFIG_BT_CTLR_CONN_RSSI is enabled, then lll_conn.h should
be included as well. Otherwise, struct lll_conn is unknown
at the compile unit level. This has been reproduced by
compiling the hci_uart sample, where the following error occurs:

lll_adv.c: In function 'isr_rx_pdu':
lll_adv.c:722:13: error: dereferencing pointer to incomplete
                         type 'struct lll_conn'
    lll->conn->rssi_latest =  radio_rssi_get();
             ^~

Original-Signed-off-by: Alex Porosanu <alexandru.porosanu@nxp.com>
GitOrigin-RevId: 03892c15716478ba4265b6e24a58416e0b0f9103
Cr-Build-Id: 8694091678110883265
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694091678110883265
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I31f4d741cc9052f8d95f90243b0d1dafcfeede92
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7357173
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>