ec-legacy: util: ecst: fix gcc 15 build breakage
GCC 15 has stricter checks when compiling, catching errors like
the following:

util/ecst.c: In function 'main':
util/ecst.c:360:49: error: '__builtin_strncpy' output may be truncated copying 100 bytes from a string of length 9999 [-Werror=stringop-truncation]
  360 |                                                 strncpy(hdr_args[arg_ind++],
      |                                                 ^

chromeos-ec-0.0.2-r3614: util/ecst.c: In function 'main':
chromeos-ec-0.0.2-r3614: util/ecst.c:242:48: error: the comparison will always evaluate as 'false' for the address of 'hdr_args' will never be NULL [-Werror=address]
chromeos-ec-0.0.2-r3614:   242 |                         if ((hdr_args[arg_ind] == NULL) ||
chromeos-ec-0.0.2-r3614:       |                                                ^~

In the first case we replace strncpy with snprintf to guarantee
that the dest buffer is NULL terminated and the max src/dest
sizes are known (that triggers another GCC 15.x warning).

In the second case, the check is a no-op because hdr_args is a
2D array and hdr_args[arg_ind] is never NULL, so we can just
drop the check since it does nothing, to silence the compiler.

BUG=b:493144630
TEST=cros-workon-$BOARD start chromeos-base/chromeos-ec; emerge-$BOARD chromeos-ec

Change-Id: I284fc8fd36acb35765606db211ac1c3187b1712a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/7725864
Reviewed-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: Keith Short <keithshort@chromium.org>