Bluetooth: Controller: Fix undefined reference in FEM support
Fix undefined reference to radio start time in FEM support
in ISO Synchronized Receiver implementation.

(cherry picked from commit 0813d09df968c75ab38aafd39818cb7129ca8e64)

Original-Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>
Original-GitOrigin-RevId: 0813d09df968c75ab38aafd39818cb7129ca8e64
Original-Change-Id: I5216495e5f33dd02e9d687f662b8ea7a818320ef
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3354337
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Aaron Massey <aaronmassey@google.com>
Original-Commit-Queue: Aaron Massey <aaronmassey@google.com>
GitOrigin-RevId: 9aa6aa754fe5f1a14951fac1507c04891c89f19f
Cr-Build-Id: 8693657076945471489
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693657076945471489
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I80f4febf1e1d775de2f57379caeba73681cc8c43
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7386809
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>