UPSTREAM: eventfs: Use ERR_CAST() in eventfs_create_events_dir()
When building with clang and CONFIG_RANDSTRUCT_FULL=y, there is an error
due to a cast in eventfs_create_events_dir():

  fs/tracefs/event_inode.c:734:10: error: casting from randomized structure pointer type 'struct dentry *' to 'struct eventfs_inode *'
    734 |                 return (struct eventfs_inode *)dentry;
        |                        ^
  1 error generated.

Use the ERR_CAST() function to resolve the error, as it was designed for
this exact situation (casting an error pointer to another type).

Link: https://lore.kernel.org/linux-trace-kernel/20231018-ftrace-fix-clang-randstruct-v1-1-338cb214abfb@kernel.org

BUG=b:360162015
TEST=find /sys/kernel/tracing

Closes: https://github.com/ClangBuiltLinux/linux/issues/1947
Fixes: 5790b1fb3d67 ("eventfs: Remove eventfs_file and just use eventfs_inode")
Reviewed-by: Kees Cook <keescook@chromium.org>
Change-Id: Ic9d0b0f08f58b324440cf4eaf711bc7840a7dbce
Signed-off-by: Nathan Chancellor <nathan@kernel.org>
Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>
(cherry picked from commit b8a555dc31e5aa18d976de0bc228006e398a2e7d)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/5792704
Commit-Queue: Steven Rostedt <rostedt@google.com>
Auto-Submit: Steven Rostedt <rostedt@google.com>
Reviewed-by: Sean Paul <sean@poorly.run>
Tested-by: Steven Rostedt <rostedt@google.com>
Reviewed-by: Masami Hiramatsu <mhiramat@google.com>