CHROMIUM: Revert "drm/mediatek: Fix backport issue in mtk_drm_gem_prime_vmap()"
This reverts commit d0952ce316d133fffc7a632c7ce0ab254702070a.

The build is broken with this change in place in a similar manner as the
one that this change is supposed to fix but with the opposite issue
(returning a pointer to a function with 'int' return type):

  drivers/gpu/drm/mediatek/mtk_drm_gem.c:262:10: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'int' [-Wint-conversion]
    262 |                 return NULL;
        |                        ^~~~
  include/linux/stddef.h:8:14: note: expanded from macro 'NULL'
      8 | #define NULL ((void *)0)
        |              ^~~~~~~~~~~
  1 error generated.

chromeos-5.10 contains upstream commit 7e542ff8b463 ("drm/mediatek: Use
struct dma_buf_map in GEM vmap ops") as commit cce2ecaf8112 ("UPSTREAM:
drm/mediatek: Use struct dma_buf_map in GEM vmap ops"), unlike upstream
linux-5.10.y, so the original linux-5.10.y backport of upstream
commit 379091e0f6d1 ("drm/mediatek: Fix potential memory leak if vmap()
fail") was correct for chromeos-5.10. Revert the backport fix up in
chromeos-5.10 to resolve the build breakage.

BUG=None
TEST=build chromiumos-arm64.flavour before and after change

Change-Id: I4f488a32dc1f06118cf2108410cc2a9bc02085e0
Signed-off-by: Nathan Chancellor <nathan@kernel.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4995831
Tested-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>