tests: mbedtls: Fix GCC warning about `test_snprintf`
Fix errors like:

inlined from ‘test_mbedtls’ at
zephyrproject/zephyr/tests/crypto/mbedtls/src/mbedtls.c:172:6:
zephyrproject/zephyr/tests/crypto/mbedtls/src/mbedtls.c:96:17: error:
‘test_snprintf’ reading 10 bytes from a region of size 1
[-Werror=stringop-overread]
   96 |                 test_snprintf(1, "", -1) != 0 ||
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~

In GCC >= 11 because `ret_buf` in some calls are shorter literals

Original-Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>
Original-GitOrigin-RevId: 890f6199367953e52f2ffcf10420c98d9ce3a320
Original-Change-Id: I23bf7337e3fcbbc9d22a65986f08dcded5ea4599
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3552855
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Yuval Peress <peress@google.com>
Original-Commit-Queue: Yuval Peress <peress@google.com>
Original-Tested-by: Yuval Peress <peress@google.com>
GitOrigin-RevId: 70eb3c4d360e373f2d3f81ebc2a2086c702b1762
Cr-Build-Id: 8693602491545629345
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693602491545629345
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I68ebd2f4df3f0f3acda0a2e63cee70c090d4f618
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7390540
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>