soc: intel_adsp: DCACHE_LINE_SIZE was not defined
The symbol DCACHE_LINE_SIZE was not being defined in Intel ADSP
targets.

It fixes the following problem:

/zephyr/soc/intel/intel_adsp/ace/power.c:30:29: error:
'CONFIG_DCACHE_LINE_SIZE' undeclared here (not in a function); did you
mean 'XCHAL_DCACHE_LINESIZE'?  30 | uint8_t
adsp_pending_buffer[CONFIG_DCACHE_LINE_SIZE]
__aligned(CONFIG_DCACHE_LINE_SIZE);

(cherry picked from commit 8fb592dfff6c0fb8f31102eb9fa8d41c6a5980d7)

Original-Original-Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>
Original-GitOrigin-RevId: 8fb592dfff6c0fb8f31102eb9fa8d41c6a5980d7
Original-Cr-Build-Id: 8739001010820476625
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8739001010820476625
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ie5dd7678f93580df66fbd2e55ff379a62b6c541f
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5803465
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Eric Yilun Lin <yllin@google.com>
Original-Commit-Queue: Eric Yilun Lin <yllin@google.com>
Original-Tested-by: Eric Yilun Lin <yllin@google.com>
GitOrigin-RevId: 48a86de7de2049bdb34ac043a9e55e3fe2c32d69
Cr-Build-Id: 8692970579647087041
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692970579647087041
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I709b23f66d35e64de1d5ecc8da08018ddadb213a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7442309
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>