bisect-kit: Separate switch_test_harness_cmd from switch_cmd
In the past, switch_tast_prebuilt.py and switch_autotest_prebuilt.py
are part of the swtich_cmd. However, they dont't fit in the "build"
and "deploy" model introduced in stateless bisection.
In stateless bisection, "build" requires no DUT and "deploy" requires
a DUT to push the built binary.

Bisections are failing because of they were not handled correctly:
Example:
https://crosperf.googleplex.com/b/368e5959-a1ec-4de6-b6a9-c1864800db8

"""
ExecutionFatalError: switch failed: ArgumentError:
switch_tast_prebuilt.py: error: argument --dut: should not be empty
(example value: foo)
"""

Adding "no_deploy" and "deploy_only" flags to the two scripts mentioned
above doesn't make good sense. As a result, I decided to handled them
separately from switch_cmd.

BUG=b:278200317
TEST=manual & ./run_formatters.sh && ./run_tests.sh

Change-Id: Ic2beb43606c8f032fc882f1e711fc793c66fd6d1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/bisect-kit/+/4773878
Commit-Queue: Cheng-Yu Lee <cylee@chromium.org>
Reviewed-by: MD Nayeem Jahan Rafi <njrafi@chromium.org>
Tested-by: Cheng-Yu Lee <cylee@chromium.org>