tests/amdgpu/amd_hotplug: add missing include file fcntl.h
Add missing include file to fix cross-compilation errors:

../tests/amdgpu/amd_hotplug.c: In function is_system_s2idle:
../tests/amdgpu/amd_hotplug.c:110:7: error: implicit declaration of function open; did you mean popen? [-Werror=implicit-function-declaration]
  fd = open(MEM_SLEEP_PATH, O_RDONLY);
       ^~~~
       popen
../tests/amdgpu/amd_hotplug.c:110:7: warning: nested extern declaration of open [-Wnested-externs]
../tests/amdgpu/amd_hotplug.c:110:28: error: O_RDONLY undeclared (first use in this function); did you mean STA_RONLY?
  fd = open(MEM_SLEEP_PATH, O_RDONLY);
                            ^~~~~~~~
                            STA_RONLY

Fixes: 6796e79abba2 ("tests/amdgpu/amd_hotplug: Check the suspend state after resume")
Signed-off-by: Alex Hung <alex.hung@amd.com>
Reviewed-by: Tom Chung <chiahsuan.chung@amd.com>