chromeos-base/u2fd-client: Add missing BDEPEND
```
FAILED: gen/include/u2fd/client/user_state.pb.cc gen/include/u2fd/client/user_state.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/u2fd-client:9999

Change-Id: I75e6949a581b02c61828b03faae95ef41224cf7a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692140
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>