UPSTREAM: pw_unit_test: Fix -Waddress warning when verifying RUN_ALL_TESTS
When Google Test back-end is used for pw_unit_test GCC reports warning
as follows:

pw_unit_test/public/pw_unit_test/framework.h:181:30: error: the address of 'int RUN_ALL_TESTS()' will never be NULL [-Werror=address]

This happens only with Google Test back-end, because pw_unit_test uses
"#define RUN_ALL_TESTS() ..." and in such case the static_assert is not
used.

(cherry picked from commit a4636bc83d6905cb252a65d19eab4ec2478af42b)

Original-Change-Id: Ia8918439bdc89e11a8a4dc416fe93f7e3daf51b5
Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/243133
Original-Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Original-Reviewed-by: Keir Mierle <keir@google.com>
Original-Commit-Queue: Keir Mierle <keir@google.com>
Original-Docs-Not-Needed: Arkadiusz Bokowy (Arkq) <arkadiusz.bokowy@gmail.com>
Original-Reviewed-by: Arkadiusz Bokowy (Arkq) <arkadiusz.bokowy@gmail.com>
Original-Reviewed-by: Andrei Litvin <andreilitvin@google.com>
GitOrigin-RevId: a4636bc83d6905cb252a65d19eab4ec2478af42b
Cr-Build-Id: 8730937883504950801
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730937883504950801
Copybot-Job-Name: pigweed-main-copybot-downstream
Change-Id: I4ccfa410b86e4afc7efb36d42007bbf7520192d4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/pigweed/pigweed/+/6006892
Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>