Autoupdate of 2 submodules
*chromite updated to 290f1d01a5d2c71d5f11205b594954f3777ea4ba
cli: Remove use of site_config and config_dump.json from cros_chrome_sdk

When building for a given board, the simple chrome CLI will first check
config_dump.json to ensure a cbuildbot release builder exists for that
board and is publishing needed SDKs.

In the new world, these cbuildbot builders will be replaced with a new
infra stack and the config_dump.json file subsequently abandoned. So
simple chrome needs to remove its dependence on config_dump.json.

This CL does that, and replaces the check with a series of GS calls
to gs://chromeos-build-release-console. This bucket contains config
files for the new release builders and lists the boards they build for.
By inspecting those files, we can determine if a release builder exists
for the given board.

However, these config files apply only to the internal release builders.
The public builders (aka the 'full' builders) aren't represented in
them. This means if we don't find the needed release builder in the
files, we need to fall back to assuming the appropriate public builder
exists. This is how one would build for 'amd64-generic' in simple chrome
since no internal release builder exists for 'amd64-generic'.

This means the failure message when trying to build for a non-existent
board has regressed a little with this CL. Before, cros_chrome_sdk
would throw the following error:
ValueError: Invalid board specified: notaboard.

Now, it attempts to look for that board's SDK and fails when it can't:
MissingSDK: Cannot find SDK for notaboard-full with version 14945.0.0 from its builder: https://dashboards.corp.google.com/chromeos_ci_release?f=cbb_config:in:notaboard-full

It still errors out, just with a slightly less clear message. This is
considered acceptable since there isn't an easy/available workaround.

BUG=chromium:1330762
TEST=unittest
TEST=ran this on chrome's bots: crrev.com/c/2967505/19

Change-Id: I22e2ecad74add647bc06a77105927696fa5ca771
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/3740864
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Reviewed-by: Jack Neus <jackneus@google.com>
Tested-by: Ben Pastene <bpastene@chromium.org>

*infra/chromite-HEAD updated to 290f1d01a5d2c71d5f11205b594954f3777ea4ba
cli: Remove use of site_config and config_dump.json from cros_chrome_sdk

When building for a given board, the simple chrome CLI will first check
config_dump.json to ensure a cbuildbot release builder exists for that
board and is publishing needed SDKs.

In the new world, these cbuildbot builders will be replaced with a new
infra stack and the config_dump.json file subsequently abandoned. So
simple chrome needs to remove its dependence on config_dump.json.

This CL does that, and replaces the check with a series of GS calls
to gs://chromeos-build-release-console. This bucket contains config
files for the new release builders and lists the boards they build for.
By inspecting those files, we can determine if a release builder exists
for the given board.

However, these config files apply only to the internal release builders.
The public builders (aka the 'full' builders) aren't represented in
them. This means if we don't find the needed release builder in the
files, we need to fall back to assuming the appropriate public builder
exists. This is how one would build for 'amd64-generic' in simple chrome
since no internal release builder exists for 'amd64-generic'.

This means the failure message when trying to build for a non-existent
board has regressed a little with this CL. Before, cros_chrome_sdk
would throw the following error:
ValueError: Invalid board specified: notaboard.

Now, it attempts to look for that board's SDK and fails when it can't:
MissingSDK: Cannot find SDK for notaboard-full with version 14945.0.0 from its builder: https://dashboards.corp.google.com/chromeos_ci_release?f=cbb_config:in:notaboard-full

It still errors out, just with a slightly less clear message. This is
considered acceptable since there isn't an easy/available workaround.

BUG=chromium:1330762
TEST=unittest
TEST=ran this on chrome's bots: crrev.com/c/2967505/19

Change-Id: I22e2ecad74add647bc06a77105927696fa5ca771
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/3740864
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Reviewed-by: Jack Neus <jackneus@google.com>
Tested-by: Ben Pastene <bpastene@chromium.org>