Bluetooth: Mesh: Fix compile warning when CID check is disabled
Since the entire cid checking function is conditionally included based
on KConfig, the usage site also needs to use #if instead of IS_ENABLED,
otherwise you get the following warning during compilation when the
option is disabled:

`error: implicit declaration of function
‘bt_mesh_vnd_mod_msg_cid_check’`

(cherry picked from commit 23d8ec360b7d51efb5c2ee37de1ad6709bbdbe45)

Original-Original-Signed-off-by: Ludvig Jordet <ludvig.jordet@nordicsemi.no>
Original-GitOrigin-RevId: 23d8ec360b7d51efb5c2ee37de1ad6709bbdbe45
Original-Cr-Build-Id: 8693381667133806833
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693381667133806833
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ia184f8935c0be54b3e0244aa56a9578d2aedde44
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7406142
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 824b118b99a302d40d7d548f27463f6caa390d5a
Cr-Build-Id: 8692607671867777489
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692607671867777489
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I5e71bd6e7243f6f11921edcab0b0375856431406
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7485345
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>