camera: fix glibc 2.41 memset warnings
Newer glibc >=2.41 fails the build with errors like the
following, due to memset usage on nontrivial structs:

../../../../../../../../../mnt/host/source/src/platform2/camera/hal_adapter/camera_device_adapter.cc:338:19: error: first argument in call to 'memset' is a pointer to non-trivially copyable type 'cros::internal::camera3_stream_aux_t' [-Werror,-Wnontrivial-memcall]
  338 |     memset(stream.get(), 0, sizeof(*stream.get()));
      |                   ^
../../../../../../../../../mnt/host/source/src/platform2/camera/hal_adapter/camera_device_adapter.cc:338:19: note: explicitly cast the pointer to silence this warning
  338 |     memset(stream.get(), 0, sizeof(*stream.get()));
      |                   ^
      |            (void*)
1 error generated.

In the first case (stream.get), the memset is redundant
because the memory is already value initialized.

In the second case (max_format), we just use value
initialization so we can remove the memset.

Both these solutions are better than the compiler
suggestion to cast to void* which just hides the type.

BUG=b:387993322
TEST=cros-workon start cros-camera-hal-usb; emerge cros-camera-hal-usb.

Change-Id: Icbafb6706279694f19d8c6b5c76943b8a6a6a7a1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/6643101
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>
Auto-Submit: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Commit-Queue: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: Ren-Pei Zeng <kamesan@chromium.org>