jay: fix clang building error with braces
Fixes the following clang building errors:

../src/intel/compiler/jay/jay_from_nir.c:2390:7: error: expected expression
      jay_def inv_idx_u16 =
      ^
../src/intel/compiler/jay/jay_from_nir.c:2392:37: error: use of undeclared identifier 'inv_idx_u16'
      jay_CVT(b, JAY_TYPE_U32, dst, inv_idx_u16, JAY_TYPE_U16, JAY_ROUND, 0);
                                    ^
../src/intel/compiler/jay/jay_from_nir.c:2392:37: error: use of undeclared identifier 'inv_idx_u16'
3 errors generated.

Fixes: 972a8fa6 ("jay: implement mesh/task shaders")
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/43206>