net: sockets_offload: Fix build error with NO_OPTIMIZATIONS
When CONFIG_NO_OPTIMIZATIONS the compiler will not inline
socket_offload_dns_is_enabled(), which means calls to
socket_offload* remain, and the linker will fail with

in function `zsock_getaddrinfo': undefined reference to
`socket_offload_getaddrinfo'
in function `zsock_freeaddrinfo': undefined reference to
`socket_offload_freeaddrinfo'

Instead of relaying on that function being inlined and the
if'ed code being removed, let's just use the preprocessor.

(cherry picked from commit dc24583858b68c1119d99e03c410db53a8b04335)

Original-Original-Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
Original-GitOrigin-RevId: dc24583858b68c1119d99e03c410db53a8b04335
Original-Cr-Build-Id: 8711863448051347393
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8711863448051347393
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ibc7e6ffd95fe29df4f03bc3d5b11e11cb9809eec
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6649870
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: Yuval Peress <peress@google.com>
Original-Reviewed-by: Yuval Peress <peress@google.com>
Original-Commit-Queue: Yuval Peress <peress@google.com>
GitOrigin-RevId: a30791c01a9b6ffcdfb257cbb2be7b0761ac6398
Cr-Build-Id: 8692767923838694785
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692767923838694785
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I4876be69b9516e7ecd1f95af771ff2311341e381
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7465660
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>