intel3a: fix an integer overflow bug
These checks were not properly detecting integer overflow, since
`int64(float(INT_MAX)) > int64(INT_MAX)`. Clang now warns about this:

Intel3AParameter.cpp:242:23: error: implicit conversion from 'int' to
'float' changes value from
2147483647 to 2147483648 [-Werror,-Wimplicit-const-int-float-conversion]

BUG=b:296451257
TEST=emerge-brya cros-camera-hal-intel-ipu6

Change-Id: I8b1fe09f01e245cd2f37f2ddf59fb13b35df073d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/camera/+/4849890
Reviewed-by: Ren-Pei Zeng <kamesan@chromium.org>
Reviewed-by: Juliana Chang <julianachang@chromium.org>
Tested-by: George Burgess <gbiv@chromium.org>
Commit-Queue: George Burgess <gbiv@chromium.org>