system_state_unittest: Unstub cras_feature_tier
It causes duplicate symbols errors.

| ld.lld: error: duplicate symbol: cras_feature_tier_init
| >>> defined at system_state_unittest.cc:827 (/proc/self/cwd/cras/src/tests/system_state_unittest.cc:827)
| >>>            bazel-out/amd64-opt/bin/cras/src/tests/_objs/system_state_unittest/system_state_unittest.o:(cras_feature_tier_init)
| >>> defined at feature_tier.rs:89 (cras/src/server/rust/src/feature_tier.rs:89)
| >>>            cras_rust-8ed1f897fe9488a8.cras-3e868393bc28696a.cras.b0c5eabf891c8e5-cgu.11.rcgu.o.rcgu.o:(.text.cras_feature_tier_init+0x0) in archive bazel-out/amd64-opt/bin/cras/src/server/rust/system_cras_rust/libcras_rust.a

BUG=b:328069910
BUG=b:268268938
TEST=buildozer 'set alwayslink True' //cras/src/server/rust/system_cras_rust
     cargo build && bazel test //cras/src/tests:system_state_unittest --//:system_cras_rust --linkopt=-L$PWD/target/debug -k --config=local-clang

Change-Id: I026bc8abfba9fab7e31d65f7ec007e1f49013c38
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/5341173
Tested-by: chromeos-cop-builder@chromeos-cop.iam.gserviceaccount.com <chromeos-cop-builder@chromeos-cop.iam.gserviceaccount.com>
Reviewed-by: Yu-Hsuan Hsu <yuhsuan@chromium.org>
Commit-Queue: Li-Yu Yu <aaronyu@google.com>