hostap: P2P needs EAPOL to select it
The P2P support needs EAPOL support in order to avoid a compilation
error about missing eap field in wpa_ssid struct.

modules/lib/hostap/wpa_supplicant/wpa_supplicant.c:5102:65:
 error: ‘struct wpa_ssid’ has no member named ‘eap’
 5102 |      eap_is_wps_pin_enrollee(&wpa_s->current_ssid->eap)) {

(cherry picked from commit 6827ec0d93d9bc6dd727ee61ca1941314db5f89b)

Original-Original-Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
Original-GitOrigin-RevId: 6827ec0d93d9bc6dd727ee61ca1941314db5f89b
Original-Cr-Build-Id: 8732659221460854369
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8732659221460854369
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ic4db8171917f9f144747a410c9ecdda67239e5e1
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5976029
Original-Commit-Queue: Ting Shen <phoenixshen@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Ting Shen <phoenixshen@chromium.org>
GitOrigin-RevId: fbbc975bb9880bd42d7fac11c44e58d4dab9d726
Cr-Build-Id: 8692928221032965233
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692928221032965233
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ifd90aad32cfba8963a064460365f6c8c64a6a1cc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7446453
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>