tests: subsys: usb: bos: Remove dummy_descriptor struct
When building with clang, it warns:

tests/subsys/usb/bos/src/test_bos.c:24:22: error: variable
'dummy_descriptor' is not needed and will not be emitted
[-Werror,-Wunneeded-internal-declaration]
static const uint8_t dummy_descriptor[] = {
                     ^

Only the size of dummy_descriptor is used, not the contents. Replace the
struct with a constant for the size.

(cherry picked from commit 785e36520fd3be5d8d9a2dd0fb569b889552b5b1)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: 785e36520fd3be5d8d9a2dd0fb569b889552b5b1
Cr-Build-Id: 8718794115469102209
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8718794115469102209
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I7e1e6ba7e42c7fec82153bfe09aa4170b1b050e1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6421713
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>