Revert "power: Receive Evicted Key Restored Signal"
This reverts commit 8db79520df03dd8595f8c434313b16f4fbebdaa3.

Reason for revert: post submit failures `error: no member named 'set_done' in 'user_data_auth::EvictedKeyRestored'` b/314155656

Original change's description:
> power: Receive Evicted Key Restored Signal
>
> The daemon needs to receive the evicated key restored signal.
>
> Further, Add ThawEssentialProcess which will be called when the
> system wakes up from suspend.
>
> BUG=b:293163215
> TEST=FEATURES=test emerge-dedede power_manager
>
> Change-Id: I87467dd2558add5a3b4cfbc6a9c512cb6feb7c80
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4952514
> Reviewed-by: Betul Soysal <betuls@google.com>
> Auto-Submit: Hardik Goyal <hardikgoyal@chromium.org>
> Commit-Queue: Hardik Goyal <hardikgoyal@chromium.org>
> Reviewed-by: Derek Basehore <dbasehore@chromium.org>
> Tested-by: Hardik Goyal <hardikgoyal@chromium.org>

BUG=b:293163215, b:314155656

Change-Id: I28920f7e4c4a1b8163003beaabfc7028a048dfae
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/5075777
Commit-Queue: Jonathon Murphy <jpmurphy@google.com>
Owners-Override: Jonathon Murphy <jpmurphy@google.com>
Reviewed-by: Thomas Cedeno <thomascedeno@google.com>
Auto-Submit: Jonathon Murphy <jpmurphy@google.com>
Tested-by: Jonathon Murphy <jpmurphy@google.com>