chromeos-base/hardware_verifier: Add missing BDEPEND
```
FAILED: gen/include/hardware_verifier/dbus_adaptors/org.chromium.HardwareVerifier.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

```
FAILED: gen/include/hardware_verifier/hardware_verifier.pb.cc gen/include/hardware_verifier/hardware_verifier.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/hardware_verifier:9999

Change-Id: I620d40be1071601476539eb56c2b16b5dcdf213f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692101
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>