drivers: display: gd7965: fix build break
gd7965 broke after 42bbb30ecf:

/zephyr/drivers/display/gd7965.c: In function 'gd7965_init':
/zephyr/drivers/display/gd7965.c:379:23: error: passing argument 1 of
'device_is_ready' from incompatible pointer type
[-Werror=incompatible-pointer-types]
  379 |  if (!device_is_ready(&config->reset_gpio.port)) {
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~
      |                       |
      |                       const struct device * const*

Fix all the occurrences.

(cherry picked from commit 1b370eead8541bd4c1808ad287456ef54d3aca35)

Original-Signed-off-by: Fabio Baltieri <fabio.baltieri@gmail.com>
Original-GitOrigin-RevId: 1b370eead8541bd4c1808ad287456ef54d3aca35
Original-Change-Id: If1bb4a99dcc5f51e4edaaf33fad104863c328e7b
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3490965
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Aaron Massey <aaronmassey@google.com>
Original-Commit-Queue: Aaron Massey <aaronmassey@google.com>
Original-Tested-by: Aaron Massey <aaronmassey@google.com>
GitOrigin-RevId: 0932b806db9c899f85a70a58b1104e33decff3a0
Cr-Build-Id: 8693623245984189217
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693623245984189217
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I8ae5f743a5fe1714a5b2aea4828650fb3e4ac39f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7389076
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>