Kconfig: Improve error messages for mismatched endchoice/endif/endmenu
Update Kconfiglib (and menuconfig, just to sync) to upstream revision
8087311cd91be to get the following fix in, for an issue reported by

    Give clearer errors for bad endchoice/endif/endmenu nesting

    An endchoice/endif/endmenu with no corresponding choice/if/menu
    generated a cryptic 'unrecognized construct' parse error. Improve
    the error message so that the problem is pointed out explicitly:

      kconfiglib.KconfigError: Kconfig:37: couldn't parse 'endmenu': no
      corresponding 'menu'

    Reported in https://github.com/ulfalizer/Kconfiglib/issues/56.

This update also adds support for user-defined preprocessor functions in
Python, which could potentially be handy for DTS/Kconfig integration.

Original-pfalcon:
Original-Signed-off-by: Ulf Magnusson <Ulf.Magnusson@nordicsemi.no>
GitOrigin-RevId: 905e65d694dc0e645b25954ed281023b2f73f2e4
Cr-Build-Id: 8694514491112723105
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694514491112723105
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Iad9cd062386658d46746e0577f0d54c27ac0e8a5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7328942
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>