libc: newlib: Fix declare a type conflict
Fix a variable declaration type conflict:

libc-hooks.c:92:16: error: conflicting types for '_heap_sentry'
   92 |   extern void *_heap_sentry;
soc.h:78:13: note: previous declaration of '_heap_sentry' was here

Fixes #44926

Original-Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>
Original-GitOrigin-RevId: bb98bd6d11a0d1f23b294e35776300bb9a8561e1
Original-Change-Id: Id1db20e7e22cb9eb04d8f25121a15e6f0fab361c
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3593636
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Original-Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Original-Tested-by: Al Semjonovs <asemjonovs@google.com>
GitOrigin-RevId: bedb97ef6626e2f38f975062fa6850cff2962c0d
Cr-Build-Id: 8693584727144037521
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693584727144037521
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I8a19900bb32dbc969a8cb75f63161639b956002e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7391718
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>