ec-legacy: util: ecst: fix gcc 15 strrchr const qualifier breakage
The GCC 15 host toolchain uprev surfaces another build error in the
ecst host utility, in addition to the ones already fixed in CL:7725864:

util/ecst.c: In function 'splice_into_path':
util/ecst.c:89:20: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
   89 |         last_delim = strrchr(path, '/');
      |                    ^
cc1: all warnings being treated as errors

The newer glibc <string.h> declares a const-correct strrchr() which
returns a 'const char *' when passed a 'const char *' argument. As
'path' is const, the result can no longer be assigned to the non-const
'char *last_delim' without discarding the qualifier.

last_delim is only ever read (NULL check, pointer-difference, and as a
read-only source for sprintf), so declare it 'const char *'.
result_last_delim stays non-const since it indexes into the writable
'result' output buffer.

BUG=b:493144630
TEST=cros-workon-brya start chromeos-base/chromeos-ec; emerge-brya chromeos-ec

Change-Id: I8fa08006c4564e958f19ec60b1e3c664e6f9af16
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/7903666
Tested-by: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Reviewed-by: Keith Short <keithshort@chromium.org>
Auto-Submit: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Reviewed-by: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Code-Coverage: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Reviewed-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: George Burgess <gbiv@chromium.org>
Commit-Queue: Keith Short <keithshort@chromium.org>