dev-rust/libchromeos: Add missing RDEPEND
```
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CannotFindBinaryPath', /build/arm64-generic/usr/lib/cros_rust_registry/registry/vboot_reference-sys-1.0.0/build.rs:16:43
  stack backtrace:
     0: rust_begin_unwind
     1: core::panicking::panic_fmt
     2: core::result::unwrap_failed
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::bindings_generation
     5: build_script_build::main
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
 * ERROR: dev-rust/libchromeos-9999::chromiumos failed (compile phase):
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/dev-rust/libchromeos:9999

Change-Id: If9fb7f2cd6d5a95a41a52b244ad9812a916db285
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692147
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>