dev-util/bazel: Add missing BDEPEND
```
scripts/bootstrap/buildenv.sh: line 25: hash: which: not found
ERROR: cannot find "which"; check your PATH.
       You may need to run the following command or similar:
         export PATH="/bin:/usr/bin:$PATH"
 * ERROR: dev-util/bazel-5.3.0-r2::chromiumos failed (compile phase):
```

```
/bin/bash: line 1: zip: command not found
Target //src:bazel_nojdk failed to build
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/dev-util/bazel:5.3.0-r3

Change-Id: I6029fd379ea74c883bd6190af57c577117194b4e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692247
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>