sci-libs/tensorflow: Add missing dep
Add a missing build-time dependency for the tensorflow
package, to fix the Bazel build error:

```
ERROR: /build/amd64-generic/tmp/portage/sci-libs/tensorflow-2.12.0/work/tensorflow-2.12.0/tensorflow/lite/experimental/acceleration/configuration/BUILD:36:8: Executing genrule //tensorflow/lite/experimental/acceleration/configuration:configuration_schema failed: (Exit 127): bash failed: error executing command
  (cd /build/amd64-generic/tmp/portage/sci-libs/tensorflow-2.12.0/work/tensorflow-2.12.0-bazel-base/execroot/org_tensorflow && \
  exec env - \
    HOME=/build/amd64-generic/tmp/portage/sci-libs/tensorflow-2.12.0/homedir \
    PATH=/build/amd64-generic/tmp/portage/sci-libs/tensorflow-2.12.0/temp/python3.8/bin:/build/amd64-generic/tmp/portage/sci-libs/tensorflow-2.12.0/temp/build-toolchain-wrappers:/build/amd64-generic/tmp/portage/sci-libs/tensorflow-2.12.0/temp/build-toolchain-wrappers/gnu_tools:/usr/lib/portage/python3.8/ebuild-helpers/xattr:/usr/lib/portage/python3.8/ebuild-helpers:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/build/amd64-generic/build/bin \
    PYTHON_BIN_PATH=/usr/bin/python3.8 \
    PYTHON_LIB_PATH=/usr/lib/python3.8/site-packages \
    SYSROOT=/build/amd64-generic/ \
    TF2_BEHAVIOR=1 \
    TF_SYSTEM_LIBS=absl_py,astor_archive,astunparse_archive,boringssl,com_github_googlecloudplatform_google_cloud_cpp,com_github_grpc_grpc,com_google_absl,com_google_protobuf,com_googlesource_code_re2,curl,cython,dill_archive,double_conversion,flatbuffers,functools32_archive,gast_archive,gif,hwloc,icu,jsoncpp_git,libjpeg_turbo,lmdb,nasm,nsync,opt_einsum_archive,org_sqlite,pasta,png,pybind11,six_archive,snappy,tblib_archive,termcolor_archive,typing_extensions_archive,wrapt,zlib \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
        bazel-out/host/bin/external/flatbuffers/flatc --proto -o bazel-out/k8-opt/bin/tensorflow/lite/experimental/acceleration/configuration tensorflow/lite/experimental/acceleration/configuration/configuration.proto
        perl -p -i -e '\''s/tflite.proto/tflite/'\'' bazel-out/k8-opt/bin/tensorflow/lite/experimental/acceleration/configuration/configuration.fbs
    ')
When you use --proto, that you should check for conformity yourself, using the existing --conform/bin/bash: line 3: perl: command not found
```

BUG=b:307282536,b:303060876
TEST=cros_sdk -- bash -c 'BOARD=amd64-generic /mnt/host/source/chromite/bin/bazel build @portage//target/sci-libs/tensorflow'

Change-Id: Idbb75c27e9f95f3708d8bd7ad4f202e80c1ea9bc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4966704
Reviewed-by: Allen Webb <allenwebb@google.com>
Tested-by: Maksim Ivanov <emaxx@chromium.org>
Reviewed-by: Andrew Moylan <amoylan@chromium.org>
Commit-Queue: Maksim Ivanov <emaxx@chromium.org>