sw_isr_table: Add spaces to fix compiler warning
When using clang to build a C++ file that includes this file, it warns:

include/zephyr/sw_isr_table.h:195:28: error: invalid suffix on literal;
C++11 requires a space between literal and identifier
[-Wreserved-user-defined-literal]
         "." Z_STRINGIFY(prefix)"."file"." Z_STRINGIFY(counter)

(cherry picked from commit db726c40a96a8475dc6422530cade3fd1256eb64)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: db726c40a96a8475dc6422530cade3fd1256eb64
Original-Cr-Build-Id: 8713358298138224881
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8713358298138224881
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ifcbdeef6d28741185a7f0c03deb0bd02e0eb2967
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6607899
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: f705568e3ecd91a322054a9471ed6402055a30d1
Cr-Build-Id: 8692780415494556961
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692780415494556961
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I4c04065db35df517dc30d9fd9b47a92b801919bd
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7464309
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>