chromeos-base/mist: Add missing BDEPEND
```
FAILED: gen/include/mist/proto_bindings/config.pb.cc gen/include/mist/proto_bindings/config.pb.h gen/include/mist/proto_bindings/usb_modem_info.pb.cc gen/include/mist/proto_bindings/usb_modem_info.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/mist:9999

Change-Id: I31986ffd2e18873a31c6dbad3db2f52b128bf1ec
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692115
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>