drivers: rtc: Fix failing RV8803 driver build when int-gpios not used
This PR fixes the issue that building the driver with either
CONFIG_RTC_CALIBRATION=y or CONFIG_RTC_ALARM=y and without
'int-gpios' used will cause
'undefined reference to `rv8803_write_reg8'' error.

(cherry picked from commit f0a70b03660cd5442cc463cf9ba7603973c1a0a6)

Original-Signed-off-by: Marcin Lyda <elektromarcin@gmail.com>
GitOrigin-RevId: f0a70b03660cd5442cc463cf9ba7603973c1a0a6
Cr-Build-Id: 8725724783141066929
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8725724783141066929
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I0f4b026c139e797ca1a515563cd75feba75a9cf9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6175305
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Keith Short <keithshort@chromium.org>
Reviewed-by: Keith Short <keithshort@chromium.org>
Tested-by: Keith Short <keithshort@chromium.org>