net: utils: Fix unused function warning
Building with clang warns:

subsys/net/ip/utils.c:600:24: error: unused function 'pkt_calc_chksum'
[-Werror,-Wunused-function]
static inline uint16_t pkt_calc_chksum(struct net_pkt *pkt, uint16_t sum)
                       ^

pkt_calc_chksum is called by net_calc_chksum, which only exists when
CONFIG_NET_NATIVE_IP is defined.

(cherry picked from commit 67e07b7a4116815b2b1379d1a8c9f38cd99e457a)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: 67e07b7a4116815b2b1379d1a8c9f38cd99e457a
Cr-Build-Id: 8723414561518963153
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723414561518963153
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ie9290977e6335d7ccfed3470eac8afac1c56e2f7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6247192
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>