irq: Add extern define to _isr_wrapper
When CONFIG_GEN_IRQ_VECTOR_TABLE and CONFIG_GEN_SW_ISR_TABLE are enabled
the generate IRQ table is trying to reference the _isr_wrapper function.

Add an extern to that to avoid a failure when compiling and remove the
previous arch-specific declarations.

arch/common/isr_tables.c:48:38: error: '_isr_wrapper' undeclared here
				(not in a function)

(cherry picked from commit b55e6dbfce6060decb778bdacb17f9016ff081e0)

Original-Original-Signed-off-by: Carlo Caione <ccaione@baylibre.com>
Original-GitOrigin-RevId: b55e6dbfce6060decb778bdacb17f9016ff081e0
Original-Change-Id: I83ae9490f70ddd993f2cf222653f11528fb7ab54
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3716554
Original-Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
Original-Commit-Queue: Jack Rosenthal <jrosenth@chromium.org>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
GitOrigin-RevId: d43b760f7c7608f7bbaa470fa1e0f4425a0934ca
Cr-Build-Id: 8693541697936693153
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693541697936693153
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I15504109191206adab0fecfe48dd41f530c30600
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7394345
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>