dev-libs/libtextclassifier: Add missing BDEPEND
```
FAILED: gen/libtextclassifier/annotator/experimental/experimental_generated.h
FileNotFoundError: [Errno 2] No such file or directory: 'flatc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/dev-libs/libtextclassifier:9999

Change-Id: I0beaabf3f0793d4b26d06c725efec84aa5be846b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692145
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>