Autoupdate of 2 submodules
*chromite updated to 84cae114fa4c43ce03c9b49e6328000d4e22f6a2
utils/timer: Fix UnboundLocalError for exception handling flow.

The `Timer t` is a local variable inside try...finally, it got pytype
error in google3 import:
  timer: Name 't' is not defined [name-error]
In runtime, it also triggers UnboundLocalError:
  UnboundLocalError: local variable 't' referenced before assignment
This change moves the definition of timer out to resolve issues.

BUG=none
TEST=./run_tests utils/timer_unittest.py

Change-Id: I541a5cfe9b6259b340436cff5b8f9f6e2c29b45c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/3892293
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Eric Lin <ericth@google.com>
Tested-by: Eric Lin <ericth@google.com>
Reviewed-by: Eric Lin <ericth@google.com>
Auto-Submit: Eric Lin <ericth@google.com>

*infra/chromite-HEAD updated to 84cae114fa4c43ce03c9b49e6328000d4e22f6a2
utils/timer: Fix UnboundLocalError for exception handling flow.

The `Timer t` is a local variable inside try...finally, it got pytype
error in google3 import:
  timer: Name 't' is not defined [name-error]
In runtime, it also triggers UnboundLocalError:
  UnboundLocalError: local variable 't' referenced before assignment
This change moves the definition of timer out to resolve issues.

BUG=none
TEST=./run_tests utils/timer_unittest.py

Change-Id: I541a5cfe9b6259b340436cff5b8f9f6e2c29b45c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/3892293
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Eric Lin <ericth@google.com>
Tested-by: Eric Lin <ericth@google.com>
Reviewed-by: Eric Lin <ericth@google.com>
Auto-Submit: Eric Lin <ericth@google.com>