chromeos-base/crash-reporter: Add missing BDEPEND
```
FAILED: gen/include/bindings/policy_common_definitions.pb.cc gen/include/bindings/policy_common_definitions.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/crash-reporter:9999

Change-Id: Ifeed979ca538d2e5c1ffa5fa89545ea89673d54a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692085
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>