tests: arch: arm: custom_interrupt: fix build issue
Fix build issue when multi level interrupts is enabled,
define new macro TEST_1ST_LEVEL_INTERRUPTS_MAX to support multi
level interrupts case.
  - core_cm33.h:2559:47: error: iteration 496 invokes undefined behavior
    [-Werror=aggressive-loop-optimizations]

(cherry picked from commit 0ea051a4331f9da5800b03909f7e5cff5309ad62)

Original-Signed-off-by: Biwen Li <biwen.li@nxp.com>
GitOrigin-RevId: 0ea051a4331f9da5800b03909f7e5cff5309ad62
Cr-Build-Id: 8696212821870935201
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8696212821870935201
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I23a8f59c1192b2179f742d59f1c5c982feade999
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7235525
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>