FROMGIT: mmc_cmds.c: fix build with gcc 4.9
Fix following error with gcc 4.9:

mmc_cmds.c:1918:9: error: missing braces around initializer [-Werror=missing-braces]
  struct rpmb_frame frame_status = {0};

Fixes:
 - http://autobuild.buildroot.org/results/bf3b6f9f6ef39b99842b3c92495b7bf359c68158

Link: https://lore.kernel.org/r/20190928185107.21125-1-fontaine.fabrice@gmail.com
(cherry picked from commit 520f54eb94845e597837ae908a03b91ae8c8758f
 https://git.kernel.org/pub/scm/utils/mmc/mmc-utils.git master)

BUG=None
TEST=compile

Change-Id: Ib6c8b94574078e7cbcf78e7d05128f7edf69f09e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/mmc-utils/+/6193438
Reviewed-by: Alexis Savery <asavery@chromium.org>
Commit-Queue: Gwendal Grignou <gwendal@chromium.org>
Tested-by: Gwendal Grignou <gwendal@chromium.org>