pw_rpc: Fix mimxrt595_evk target
A change(1) was merged that broke the mimxrt595_evk target. Adding
A pw_rpc_CONFIG GN variable to fix this target. Fixes the following
build error:

```
../pw_rpc/endpoint.cc:41:15: error: static assertion failed: PW_RPC_YIELD_MODE
   is PW_RPC_YIELD_MODE_SLEEP (pw::this_thread::sleep_for()), but no backend
   is set for pw_thread:sleep. Set a pw_thread:sleep backend or use a
   different PW_RPC_YIELD_MODE setting.
   41 | static_assert(false,
      |               ^~~~~
../pw_rpc/endpoint.cc: In function 'void pw::rpc::internal::YieldRpcLock()':
../pw_rpc/endpoint.cc:85:20: error: 'chrono' does not name a type
   85 |   static constexpr chrono::SystemClock::duration kSleepDuration =
      |                    ^~~~~~
../pw_rpc/endpoint.cc:87:3: error: 'this_thread' has not been declared
   87 |   this_thread::sleep_for(kSleepDuration);
      |   ^~~~~~~~~~~
../pw_rpc/endpoint.cc:87:26: error: 'kSleepDuration' was not declared in this scope
   87 |   this_thread::sleep_for(kSleepDuration);
      |                          ^~~~~~~~~~~~~~
[46/388] c++ mimxrt595_evk_debug/obj/pw_rpc/nanopb/codegen_test.lib.codegen_test.cc.o
```

(1) Breaking Change-Id: I94517d66e04b51b95a911adac560426ee3683388

Change-Id: I0e9269c5b4e361b86f3fd49ec3ab947b39f6b7d6
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/128910
Reviewed-by: Scott James Remnant <keybuk@google.com>
Commit-Queue: Chris Mumford <cmumford@google.com>