vulkan/runtime: Fix gnu-empty-initializer error in vk_pipeline.c
Fixes the following building error happening with clang:

FAILED: src/vulkan/runtime/libvulkan_runtime.a.p/vk_pipeline.c.o
...
../src/vulkan/runtime/vk_pipeline.c:3689:41: error: use of GNU empty initializer extension [-Werror,-Wgnu-empty-initializer]
         struct vk_shader *shaders[3] = {};
                                        ^
1 error generated.

Fixes: 51966cc4 ("vulkan: add vk_shader_ops::replay_at vfunc stub")
Reviewed-by: Lionel Landwerlin <lionel.g.landwerlin@intel.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/39642>