drivers: sensor: Fix unused function warning
Building with clang warns:

drivers/sensor/st/lsm9ds0_mfd/lsm9ds0_mfd.c:42:19: error: unused
function 'lsm9ds0_mfd_accel_set_odr_raw' [-Werror,-Wunused-function]
static inline int lsm9ds0_mfd_accel_set_odr_raw(const struct device *dev,
                  ^

lsm9ds0_mfd_accel_set_odr_raw is only used by code that was guarded by
defined(CONFIG_LSM9DS0_MFD_ACCEL_SAMPLING_RATE_RUNTIME) in addition to
!defined(LSM9DS0_MFD_ACCEL_DISABLED).

(cherry picked from commit 31be8696723f7c83e8ad98cf74ff8ebc4e311226)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: 31be8696723f7c83e8ad98cf74ff8ebc4e311226
Cr-Build-Id: 8723142769276654049
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723142769276654049
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I06187fe331ed916ddc00e1944863cb7ba4f536ee
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6257280
Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>