Bluetooth: audio: lc3: Fix build error
This fixes build error caused by redundant comma without expression
lc3.h:269:74: error: expected expression before ',' token
  269 |          (_max_frames_per_sdu)))),                         \
      |

(cherry picked from commit 0197d1154ae3b6833295e701e8297b42574bbe17)

Original-Original-Signed-off-by: Mariusz Skamra <mariusz.skamra@codecoup.pl>
Original-GitOrigin-RevId: 0197d1154ae3b6833295e701e8297b42574bbe17
Original-Change-Id: Id315dd42bf7131b7abdc86a945736d994cd3c026
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4836001
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: 4131b2e62a1c22f54414f75864b98672a23a62a9
Cr-Build-Id: 8693162543395197713
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693162543395197713
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I62bc946171b63d231ec5baf539810a5113320aa5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7417636
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>