scripts: test for imported ELFFile instead of setting it to None
mypy fails with:
Incompatible types in assignment
        (expression has type "None", variable has type "Type[ELFFile]")

this happens because of the code:
    try:
        from elftools.elf.elffile import ELFFile
    except ImportError:
        ELFFile = None

ELFFile is set to None to allow later code to check if ELFFile was
imported by checking against None. Instead of setting ELFFile to None,
then update testing code to check if the class has been loaded, as:
    if globals().get('ELFFile') is None:

Update the try-catch to `pass`.

Removed ELFFile cargo cult from intel_cyclonev.py and fix pylint
warnings.

Disable duplicate code check. The intel_cyclonev.py is already based
upon openocd.py, so although the duplication detection is correct then
this should not prevent other code changes / fixes to those files from
being applied.

(cherry picked from commit c531e4c2ac34a9eca268efb78834cf5245d745d0)

Original-Original-Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>
Original-GitOrigin-RevId: c531e4c2ac34a9eca268efb78834cf5245d745d0
Original-Change-Id: I8eefa69f03ff0590c9f4f76ee6143d58dea613a5
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5383299
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 2c258444a1ed4c0b9bcb33c8b5628324ebc7acd3
Cr-Build-Id: 8693060946518673009
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693060946518673009
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Iaf43e792b565e0cd2ff399d013067c76207e92ef
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7433427
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>