app-emulation/qemu Add missing BDEPEND
```
20:53:18.844 >>> Configuring source in /var/tmp/portage/app-emulation/qemu-6.2.0-r1/work/qemu-6.2.0 ...
 * Using python3.6 in global scope
../configure --prefix=/usr --sysconfdir=/etc ...

ERROR: Cannot find Ninja

 * ERROR: app-emulation/qemu-6.2.0-r1::portage-stable failed (configure phase):
 ```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/host/chromiumos/app-emulation/qemu:6.2.0-r1

Change-Id: I855e98b0a0bade79bd09a902760c99b1668af0cb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4690596
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>