net: Fix warning of `size_t` formatting with `%.*s`
This addresses the following warning building with `CONFIG_64BIT=y`:

    error: field precision specifier '.*' expects argument of type 'int',
    but argument X has type 'size_t' {aka 'long unsigned int'}

(cherry picked from commit 50f23500b8c62a7fca4d35f0b4ec9434ceab5fed)

Original-Signed-off-by: Chen Xingyu <hi@xingrz.me>
GitOrigin-RevId: 50f23500b8c62a7fca4d35f0b4ec9434ceab5fed
Cr-Build-Id: 8730286630880259329
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730286630880259329
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: If7f35e3e818da174223b1e4af3e96a4d352a95bb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6045626
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>