entropy: gd32: Fix build error
entropy_gd32_recover() had not return type defined causing the
following issue when building:

drivers/entropy/entropy_gd32.c:61:8: error: return type defaults to
'int' [-Werror=implicit-int]

Fix it and change the function to void since it was returning a
constant 0 that is never checked or used.

(cherry picked from commit 4690b7f966a58cb5c68c15442d11d17d22866026)

Original-Signed-off-by: Flavio Ceolin <flavio@hubblenetwork.com>
GitOrigin-RevId: 4690b7f966a58cb5c68c15442d11d17d22866026
Cr-Build-Id: 8692226556012859633
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692226556012859633
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I956f4a4fc04ed7cb4d8b93be9845aa3c2adc57be
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7494817
Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>