net: tcp2: Fix compile failure on native_posix_64
Need to use %zd in formatter string for net_pkt_get_len since it returns
a size_t otherwise we get something like:

	error: format ‘%d’ expects argument of type ‘int’, but argument
	3 has type ‘size_t’ {aka ‘long unsigned int’} [-Werror=format=]

Original-Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
GitOrigin-RevId: ff29d306c9bd50765317c4ee46a49acba64e2071
Cr-Build-Id: 8694026902685256417
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694026902685256417
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ia2751a974f2acaf525d086a96f1e05bf5b523916
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7363111
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>