ml-benchmark: Add missing deps
Add dependencies to the chromeos-base/ml-benchmark package to
reflect what this package really requires. The missing deps were
discovered when doing a Bazel build:

```
ERROR at //common-mk/pkg_config.gni:13:26: Script returned non-zero exit code.
    _pkg_config_result = exec_script("//common-mk/pkg-config_wrapper.py",
                         ^----------
Current dir: /build/amd64-generic/tmp/portage/chromeos-base/ml-benchmark-0.0.1-r402/work/build/out/Default/
Command: /usr/bin/env /build/amd64-generic/tmp/portage/chromeos-base/ml-benchmark-0.0.1-r402/work/ml-benchmark-0.0.1/platform2/common-mk/pkg-config_wrapper.py /build/amd64-generic/build/bin/pkg-config libbrillo libchrome libmetrics libminijail libmojo system_api zlib
Returned 1.
stderr:

Package system_api was not found in the pkg-config search path.
```

```
Command: /usr/bin/env /build/amd64-generic/tmp/portage/chromeos-base/ml-benchmark-0.0.1-r402/work/ml-benchmark-0.0.1/platform2/common-mk/pkg-config_wrapper.py /build/amd64-generic/build/bin/pkg-config libchrome libdlcservice-client protobuf system_api
Returned 1.
stderr:

Package libdlcservice-client was not found in the pkg-config search path.
```

```
FAILED: gen/include/ml/benchmark.pb.cc gen/include/ml/benchmark.pb.h
/usr/bin/env ../../../ml-benchmark-0.0.1/platform2/common-mk/file_generator_wrapper.py protoc benchmark.proto --proto_path /build/amd64-generic/tmp/portage/chromeos-base/ml-benchmark-0.0.1-r402/work/ml-benchmark-0.0.1/platform2/ml/proto/ --proto_path /build/amd64-generic/usr/share/proto --cpp_out=/build/amd64-generic/tmp/portage/chromeos-base/ml-benchmark-0.0.1-r402/work/build/out/Default/gen/include/ml
Traceback (most recent call last):
  File "../../../ml-benchmark-0.0.1/platform2/common-mk/file_generator_wrapper.py", line 19, in <module>
    subprocess.check_call(sys.argv[1:])
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:306661835
TEST=cros_sdk -- bash -c 'BOARD=amd64-generic /mnt/host/source/chromite/bin/bazel build @portage//target/chromeos-base/ml-benchmark'

Change-Id: I17a2209c1e1d590bb786cd3633ab61fce400f983
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4957018
Reviewed-by: Michael "Misha" Pishchagin <mblsha@google.com>
Commit-Queue: Michael "Misha" Pishchagin <mblsha@google.com>
Tested-by: Maksim Ivanov <emaxx@chromium.org>