lib: libc: arcmwdt: declare strsignal() in string.h wrapper
The MWDT toolchain's <string.h> does not declare strsignal(),
which is a POSIX XSI extension. Without a declaration the
compiler treats calls to strsignal() as implicit int-returning
functions, causing the return value to be passed as a pointer:

  error: incompatible integer to pointer conversion passing
  'int' to parameter of type 'const void *'

Add the declaration alongside the existing strnlen() declaration.
The implementation is already provided by Zephyr's POSIX
portability subsystem in subsys/portability/posix/options/signal.c.

Original-Signed-off-by: Mohamed Moawad <moawad@synopsys.com>
GitOrigin-RevId: 73cf2b8507ef9261481bf42e17c180c94626502b
Cr-Build-Id: 8680083166403963553
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8680083166403963553
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I192a389dd5a9c261066c771f0097a23a1468275f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7895253
Commit-Queue: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>