bluetooth: controller: Fix build with BT_HCI_VS_EXT disabled.
Fixing error: undefined reference to 'vs_set_min_used_chans'
when building with 'BT_HCI_VS_EXT' option disabled.

(cherry picked from commit 5ac063d79374183df756334c3302733c70237666)

Original-Original-Signed-off-by: Michał Grochala <michal.grochala@nordicsemi.no>
Original-GitOrigin-RevId: 5ac063d79374183df756334c3302733c70237666
Original-Change-Id: I548f81c91e3334733d04ceea9685dce36cc10b23
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4626695
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: bab04d0fab0dab6b78b658e413d53eec425fbc25
Cr-Build-Id: 8693202803307200209
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693202803307200209
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ied8d03a22d07878cf13ec33d0aa6f85898ebc55e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7418436
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>