chromeos-base/kerberos: Add missing BDEPEND
```
FAILED: gen/include/bindings/kerberos_containers.pb.cc gen/include/bindings/kerberos_containers.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'

FAILED: gen/include/kerberos/org.chromium.Kerberos.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

```
/build/arm64-generic/etc/portage/hooks/install/check-seccomp.sh: line 27: compile_seccomp_policy: command not found
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/kerberos:9999

Change-Id: I1182593cb683866bdbf1edc2c4876f0c42865fdf
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692105
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>