chromeos-base/crosvm: Fix Dependencies
```
thread 'main' panicked at 'missing wayland-scanner - please install libwayland-dev: CannotFindBinaryPath', gpu_display/build.rs:63:10
```

```
4: build_script_build::compile_policy
```

```
thread 'main' panicked at 'protoc binary not found: cannot find binary path', /build/amd64-generic/usr/lib/cros_rust_registry/registry/protobuf-parse-3.2.0/src/protoc/command.rs:174:17
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/crosvm:9999

Change-Id: Ia3d46c79e3eff087185b85708444bc1c6c774167
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4850429
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>