net: sockets: Fix compilation of getaddrinfo()
If the user call getaddrinfo() while K_HEAP_MEM_POOL_SIZE == 0 and
CONFIG_NET_IP=y, he get a link time failure:

  .../ld.bfd: ...: in function `zsock_getaddrinfo':
  ...(.text.zsock_getaddrinfo+0xe): undefined reference to `k_calloc'

In fact, k_calloc() is required if CONFIG_NET_IP or CONFIG_DNS_RESOLVER is
set (because of the definition of ANY_RESOLVER) but K_HEAP_MEM_POOL_SIZE is
guaranteed to be != 0 only if CONFIG_DNS_RESOLVER is set.

So, forward the dependency in Kconfig to fix the issue.

Original-Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>
GitOrigin-RevId: cb04840738f7d581d1940bb90c18c948300f6218
Cr-Build-Id: 8678116078484449153
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8678116078484449153
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ifdbbae36e02505bbbc2d01e3ec11f7cdc29621fa
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7990462
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>