media-sound/alsa-utils: add patch to fix glibc builds
This adds a patch (clean cherry-pick) to fix alsa-utils
builds against glibc >= 2.38.

The reason we backport the patch instead of upgrading
alsa-utils/alsa-lib is that upgrading causes a non
trivial regression in chromeos-base/midis as can be
seen in my attempt in CL 5682939.

This patch can be dropped when alsa-utils/lib are
finally upgraded.

Example failure:
alsa-utils-1.2.8-r1: ./init_sysdeps.c:21:15: error: static declaration of 'strlcpy' follows non-static declaration
alsa-utils-1.2.8-r1:    21 | static size_t strlcpy(char *dst, const char *src, size_t size)
alsa-utils-1.2.8-r1:       |               ^
alsa-utils-1.2.8-r1: /usr/include/string.h:506:15: note: previous declaration is here
alsa-utils-1.2.8-r1:   506 | extern size_t strlcpy (char *__restrict __dest,
alsa-utils-1.2.8-r1:       |               ^

BUG=b:324437695
TEST=Bootstrapped an SDK archive using glibc 2.39; emerge alsa-utils.

Change-Id: Ib2ee0fcdf3179753ffba61fac66370a0d118c82f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/5687791
Commit-Queue: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>
Reviewed-by: Terry Cheong <htcheong@chromium.org>
Auto-Submit: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>