cmake: toolchain: disable picolibc for armclang
`armclang` doesn't support picolibc right now so disable it and fix
few issues related to it as below:

```
zephyrproject/zephyr/lib/libc/validate_libc.c:17:14: error: static
assertion failed due to requirement 'sizeof(unsigned int) >= 8': time_t
cannot hold 64-bit values
   17 | BUILD_ASSERT(sizeof(time_t) >= 8, "time_t cannot hold 64-bit
   values");
```

Original-Signed-off-by: Sudan Landge <sudan.landge@arm.com>
GitOrigin-RevId: 4b635e18794e781157547962c89b713349923132
Cr-Build-Id: 8690324018689964961
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8690324018689964961
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I894a3f68425ac05a774e70cfcd9677a56e844cdb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7547613
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Rob Barnes <robbarnes@google.com>
Reviewed-by: Rob Barnes <robbarnes@google.com>