FROMGIT: Revert "perf test: Don't leak workload gopipe in PERF_RECORD_*"
This reverts commit b7e5c59f3b0971f56ebbceb9d42cc45e9ac1cd94 which is
commit 48918cacefd226af44373e914e63304927c0e7dc upstream.

Commit in question broke building perf followingly with v5.15.195:

  | ld: perf-in.o: in function `test__PERF_RECORD':
  | tools/perf/tests/perf-record.c:142: undefined reference to `evlist__cancel_workload'

The 'evlist__cancel_workload' seems to be introduced in
commit e880a70f8046 ("perf stat: Close cork_fd when create_perf_stat_counter() failed")
which is currently not included in the 5.15 stable series.

Fixes: b7e5c59f3b09 ("perf test: Don't leak workload gopipe in PERF_RECORD_*")
Cc: stable@vger.kernel.org # 5.15
Signed-off-by: Niko Mauno <niko.mauno@vaisala.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 3324e5e3ac97a2969de11f35bebea34921e7e502
 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
 linux-5.15.y)

BUG=b:491943494
TEST=cq

Change-Id: Idebc5af699aab2fe9ce17c1d5848b7771f1da291
Fixes: b7e5c59f3b09 ("perf test: Don't leak workload gopipe in PERF_RECORD_*", v5.15.195)
Disallow-Recycled-Builds: test-failures
Signed-off-by: Lina Versace <linyaa@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/7660014
Reviewed-by: Sean Paul <sean@poorly.run>
Reviewed-by: Sergey Senozhatsky <senozhatsky@chromium.org>
Reviewed-by: Jędrzej Ciupis <jciupis@google.com>