posix: syslog: Fix uninitialized variable error
Seen this in compiler

lib/posix/options/syslog.c: In function 'setlogmask':
lib/posix/options/syslog.c:66:16: error: 'oldpri' may be used uninitialized
   66 |         return oldpri;
      |                ^~~~~~
lib/posix/options/syslog.c:59:13: note: 'oldpri' was declared here
   59 |         int oldpri;
      |             ^~~~~~
lib/posix/options/syslog.c: In function 'vsyslog':
lib/posix/options/syslog.c:83:33: error: 'mask' may be used uninitialized
   83 |         if ((BIT(level) & mask) == 0) {
      |             ~~~~~~~~~~~~~~~~~~~~^~~~
lib/posix/options/syslog.c:71:17: note: 'mask' was declared here
   71 |         uint8_t mask;
      |                 ^~~~

(cherry picked from commit 71fd9b2e07a6fa9d7895759fc83685b6849aebb4)

Original-Original-Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
Original-GitOrigin-RevId: 71fd9b2e07a6fa9d7895759fc83685b6849aebb4
Original-Change-Id: Id260c25b46fa937adce3538756844924dfe26a1f
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5358342
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 6e71c4ceed8b7c44f4fc1d7c22f8688827d4f88c
Cr-Build-Id: 8693065741100219505
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693065741100219505
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Idc47544ca73f5df74ff05bdb956b9e7109309abb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7432786
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>