arch/arm: Fix gcc-9.2 warning with z_arch_syscall_invoke6
Fix the following warning from gcc-9.2:

arm/syscall.h:52:2: error: listing the stack pointer register 'sp'
 in a clobber list is deprecated [-Werror=deprecated]
   52 |  __asm__ volatile("svc %[svid]\n"
      |  ^~~~~~~

Original-Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
GitOrigin-RevId: e9d0f1812b71f4fbfd2bca3b94e4de5b14a65510
Cr-Build-Id: 8694126753657068705
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694126753657068705
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ida4fe0b569f908d09682aa20708e14e5f86f0684
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7354199
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>