media-libs/clvk: Add missing perfetto dep
media-libs/clvk uses the perfetto library, hence this should be
reflected in dependencies.

This was discovered in Bazel builds that are failing with errors
like:

```
FAILED: src/CMakeFiles/OpenCL-objects.dir/memory.cpp.o
/usr/bin/x86_64-cros-linux-gnu-clang++ --sysroot=/build/amd64-generic -DCLVK_PERFETTO_ENABLE -I/build/amd64-generic/tmp/portage/media-libs/clvk-0.0.1-r51/work/clvk-0.0.1/clvk/external/OpenCL-Headers -I/build/amd64-generic/tmp/portage/media-libs/clvk-0.0.1-r51/work/clvk-0.0.1/clspv/include -isystem /build/amd64-generic/usr/include/perfetto  -Os -pipe  -march=x86-64 -msse3 -g -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -fdiagnostics-color -std=gnu++17 -fPIC -DCLSPV_ONLINE_COMPILER -Wall -W -Wextra -Wno-ignored-attributes -DCOMPILER_AVAILABLE=1 -MD -MT src/CMakeFiles/OpenCL-objects.dir/memory.cpp.o -MF src/CMakeFiles/OpenCL-objects.dir/memory.cpp.o.d -o src/CMakeFiles/OpenCL-objects.dir/memory.cpp.o -c /build/amd64-generic/tmp/portage/media-libs/clvk-0.0.1-r51/work/clvk-0.0.1/clvk/src/memory.cpp
In file included from /build/amd64-generic/tmp/portage/media-libs/clvk-0.0.1-r51/work/clvk-0.0.1/clvk/src/memory.cpp:17:
In file included from /build/amd64-generic/tmp/portage/media-libs/clvk-0.0.1-r51/work/clvk-0.0.1/clvk/src/image_format.hpp:18:
In file included from /build/amd64-generic/tmp/portage/media-libs/clvk-0.0.1-r51/work/clvk-0.0.1/clvk/src/device.hpp:32:
In file included from /build/amd64-generic/tmp/portage/media-libs/clvk-0.0.1-r51/work/clvk-0.0.1/clvk/src/vkutils.hpp:22:
/build/amd64-generic/tmp/portage/media-libs/clvk-0.0.1-r51/work/clvk-0.0.1/clvk/src/tracing.hpp:21:10: fatal error: 'perfetto.h' file not found
         ^~~~~~~~~~~~
1 error generated.
```

BUG=b:307392616
TEST=cros_sdk -- bash -c 'BOARD=amd64-generic /mnt/host/source/chromite/bin/bazel build @portage//target/media-libs/clvk'

Change-Id: Ic8e9dfc4252cd0531e386f1289a7c5a56ffa494b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4970152
Reviewed-by: Romaric Jodin <rjodin@chromium.org>
Commit-Queue: Romaric Jodin <rjodin@chromium.org>
Auto-Submit: Maksim Ivanov <emaxx@chromium.org>
Tested-by: Maksim Ivanov <emaxx@chromium.org>