dfu: Fix build issue with gcc8
We get the following warning when buiding with gcc8:

	error: 'packed' attribute ignored for type 'u32_t *'
	{aka 'unsigned int *'} [-Werror=attributes]

Use UNALIGNED_GET() to access the data since we don't know the
alignment.

Original-Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
GitOrigin-RevId: 93d0f8c58dbe973f95f7e8b4f7a23dd4e97dd45b
Cr-Build-Id: 8694370982197094753
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694370982197094753
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I1497f2c214a19546204c3b0d93d108a27d6ff09d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7336171
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>