FROMGIT: ASoC: ops: dynamically allocate struct snd_ctl_elem_value
[ Upstream commit 7e10d7242ea8a5947878880b912ffa5806520705 ]

This structure is really too larget to be allocated on the stack:

sound/soc/soc-ops.c:435:5: error: stack frame size (1296) exceeds limit (1280) in 'snd_soc_limit_volume' [-Werror,-Wframe-larger-than]

Change the function to dynamically allocate it instead.

There is probably a better way to do it since only two integer fields
inside of that structure are actually used, but this is the simplest
rework for the moment.

Fixes: 783db6851c18 ("ASoC: ops: Enforce platform maximum on initial value")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://patch.msgid.link/20250610093057.2643233-1-arnd@kernel.org
Signed-off-by: Mark Brown <broonie@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit cfb5e5582f69b5f34f6499a31c3c9658625ad052
 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
 branch linux-5.15.y)

BUG=b:428154606
TEST=CQ

Change-Id: If82b54997ecdca1c8d49a88c02d72348ef2c937c
Disallow-Recycled-Builds: test-failures
Signed-off-by: Lina Versace <linyaa@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/6937387
Reviewed-by: Masami Hiramatsu <mhiramat@google.com>