libqmi: explicitly build without MBIM support
We don't want to introduce built-in QMI support for Qualcomm based
MBIM modems yet, because this may change some interactions we
currently do in ModemManager using MBIM (e.g. multiple slot
management).

Therefore, for now we will enable QMI support unconditionally, but
without enabling QMI-over-MBIM operations in ModemManager.

BUG=b:309142127
TEST=Check if qmicli allows opening port in MBIM mode
  gimble-rev3 ~ # qmicli -d /dev/cdc-wdm0 --device-open-mbim --dms-noop
  [20 Nov 2023, 04:15:45] -Warning ** [/dev/cdc-wdm0] requested MBIM mode but no MBIM QMUX support available
  error: couldn't open the QmiDevice: Could not create endpoint

Cq-Depend: chromium:5005300
Change-Id: I4a3c1c2b47d5aa19b5100bff13a0136c609092b6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/5040559
Tested-by: Aleksander Morgado <aleksandermj@google.com>
Commit-Queue: Aleksander Morgado <aleksandermj@google.com>
Reviewed-by: Madhav <madhavadas@google.com>