fromupstream: remove patchwork.kernel.org
patchwork.kernel.org has disabled xmlrpc [1]:

  raise ProtocolError(
  xmlrpc.client.ProtocolError: <ProtocolError for patchwork.kernel.org/xmlrpc/: 404 Not Found>

so it's not possible at the moment to pickup patches fromlist
(by msgid.)  Remove patchwork.kernel.org from the pw list.

[1] https://patchwork.kernel.org/about/

BUG=none
TEST=tested that the following works
     fromupstream.py msgid://${MY_MESSAGE_ID}

Change-Id: I021743651c38ffd8f95a8f40f6f76bbc622af121
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/dev-util/+/6627459
Commit-Queue: Sergey Senozhatsky <senozhatsky@chromium.org>
Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
Tested-by: Sergey Senozhatsky <senozhatsky@chromium.org>