Revert "eclass: make test dependencies on Python and coreutils explicit."
This reverts commit cbf6b271b60bfee50a154761ea12a8fd5e20f6b3.

Reason for revert: breaks some slim-cq builders (b:302025470).

Original change's description:
> eclass: make test dependencies on Python and coreutils explicit.
>
> Missing dependency is exposed by running tests under Bazel.
>
> BUG=b:298920283
> TEST=BOARD=amd64-generic bazel test @portage//chromeos-base/fusebox:test
> (with crrev.com/c/4855140)
>
> Without the dependencies we see the following failure:
>
> 07:32:24.400 >>> Test phase: chromeos-base/fusebox-9999
> /mnt/host/source/src/platform2/common-mk/platform2_test.py --action=pre_test --sysroot=/build/amd64-generic --strategy=unprivileged --user=root --bind-mount-dev --
> /mnt/host/source/src/platform2/common-mk/platform2_test.py --action=run --sysroot=/build/amd64-generic --strategy=unprivileged --user=root --bind-mount-dev --jobs=32 -- /build/amd64-generic/var/cache/portag
> e/chromeos-base/fusebox/out/Default/fusebox_test
> chroot: /build/amd64-generic
> cwd: /mnt/host/source/src/platform2/fusebox
> cmd: {/mnt/host/source/src/third_party/gtest-parallel/gtest-parallel} '/mnt/host/source/src/third_party/gtest-parallel/gtest-parallel' '/var/cache/portage/chromeos-base/fusebox/out/Default/fusebox_test' '--
> workers=32'
> error: execing /mnt/host/source/src/third_party/gtest-parallel/gtest-parallel failed: [Errno 2] No such file or directory
> Error: /mnt/host/source/src/third_party/gtest-parallel/gtest-parallel: failed with exit code 127
>  * ERROR: chromeos-base/fusebox-9999::chromiumos failed (test phase):
>  *   (no error message)
>  *
>  * Call stack:
>  *               ebuild.sh, line  125:  Called src_test
>  *             environment, line 4410:  Called platform_src_test
>  *             environment, line 4112:  Called platform_pkg_test
>  *             environment, line 4079:  Called platform_test 'run' '/build/amd64-generic/var/cache/portage/chromeos-base/fusebox/out/Default/fusebox_test'
>  *             environment, line 4154:  Called die
>  * The specific snippet of code:
>  *       "${cmd[@]}" || die
>
> Change-Id: Ia72d1dada1e29b075475d083bb7a7aab29ee5d33
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4840797
> Reviewed-by: Shuhei Takahashi <nya@chromium.org>
> Reviewed-by: Sergey Frolov <sfrolov@google.com>
> Tested-by: Tomasz Tylenda <ttylenda@chromium.org>
> Commit-Queue: Tomasz Tylenda <ttylenda@chromium.org>

BUG=b:298920283,b:302025470

Change-Id: Id398740ed2f68511fbf90b7e8a96e19072a62466
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4897183
Owners-Override: Andres Calderon Jaramillo <andrescj@google.com>
Reviewed-by: Jim Pollock <jmpollock@chromium.org>
Tested-by: Andres Calderon Jaramillo <andrescj@google.com>