tests: mcumgr: Re-enable clang warning by using variables
When removing TOOLCHAIN_DISABLE_CLANG_WARNING, building the
settings.mgmt test with clang fails with:

tests/subsys/mgmt/mcumgr/settings_mgmt/src/main.c:87:22: error:
variable 'test_response_read_data_start' is not needed and will not be
emitted [-Werror,-Wunneeded-internal-declaration]
   87 | static const uint8_t test_response_read_data_start[5] = {
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests/subsys/mgmt/mcumgr/settings_mgmt/src/main.c:91:22: error:
variable 'test_response_read_data_end' is not needed and will not be
emitted [-Werror,-Wunneeded-internal-declaration]
   91 | static const uint8_t test_response_read_data_end[1] = {

Add additional asserts to use these variables in the test.

(cherry picked from commit 2d6aa4739886a923d650cb4403e623d89422aa28)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: 2d6aa4739886a923d650cb4403e623d89422aa28
Cr-Build-Id: 8692022711654242305
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692022711654242305
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I873d9413b9e0614dece2ebaeced2c9b4665b288e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7508427
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
Tested-by: Dawid Niedźwiecki <dawidn@google.com>