mm_drv: tlb: Fix compile time warning
This fixes the following compile time warning;

drivers/mm/mm_drv_intel_adsp_mtl_tlb.c: In function 'sys_mm_drv_mm_init':
include/zephyr/sys/__assert.h:44:52: error: format '%p' expects argument
of type 'void *', but argument 2 has type
'long unsigned int' [-Werror=format=]
__ASSERT_PRINT("\t" fmt "\n", ##__VA_ARGS__)

(cherry picked from commit b4998c357e43ff99714dc9f33ea5721e397557b1)

Original-Original-Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
Original-GitOrigin-RevId: b4998c357e43ff99714dc9f33ea5721e397557b1
Original-Change-Id: I200869ff689651a13a66a333d1b04ae383611e33
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4887358
Original-Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Original-Tested-by: Al Semjonovs <asemjonovs@google.com>
GitOrigin-RevId: f08f564ec9d71fcfc373764980cddee9249f4edd
Cr-Build-Id: 8693153334652043185
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693153334652043185
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I6fd4b0306a82690d4e6a6a35c6f37194c208a1ea
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7423518
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>