tests: lib: cmsis_nn: Initialise bias dimensions for depthwise convolve
This commit adds an initialisation for the `bias_dims` variable, which
is given as an input to the `arm_depthwise_conv_s8` function.

Note that the `bias_dims` parameter is currently unused by the function
implementation.

This fixes the following warning reported by the GCC 12:

  error: 'bias_dims' may be used uninitialized
  Werror=maybe-uninitialized]

(cherry picked from commit 8355341c66fb1cbe5466e47ef31ed26613d2f59b)

Original-Original-Signed-off-by: Stephanos Ioannidis <root@stephanos.io>
Original-GitOrigin-RevId: 8355341c66fb1cbe5466e47ef31ed26613d2f59b
Original-Change-Id: Idf6b7c419b792e3ae7bf57c155d7016800fd9283
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3823367
Original-Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Commit-Queue: Jack Rosenthal <jrosenth@chromium.org>
GitOrigin-RevId: 3e920371ec85347a4113ebf0ee06d9b8eb8c4b4d
Cr-Build-Id: 8693488060366067793
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693488060366067793
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I6e2202c86e35651f740b29a09a00d5dc6e3a2038
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7398498
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>