net: sockets_offload: Fix build error with NO_OPTIMIZATIONS
When CONFIG_NO_OPTIMIZATIONS the compiler will not inline
socket_offload_dns_is_enabled(), which means calls to
socket_offload* remain, and the linker will fail with

in function `zsock_getaddrinfo': undefined reference to
`socket_offload_getaddrinfo'
in function `zsock_freeaddrinfo': undefined reference to
`socket_offload_freeaddrinfo'

Instead of relaying on that function being inlined and the
if'ed code being removed, let's just use the preprocessor.

(cherry picked from commit dc24583858b68c1119d99e03c410db53a8b04335)

Original-Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
GitOrigin-RevId: dc24583858b68c1119d99e03c410db53a8b04335
Cr-Build-Id: 8711863448051347393
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8711863448051347393
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ibc7e6ffd95fe29df4f03bc3d5b11e11cb9809eec
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6649870
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: Yuval Peress <peress@google.com>
Reviewed-by: Yuval Peress <peress@google.com>
Commit-Queue: Yuval Peress <peress@google.com>