Autoupdate of 2 submodules
*chromite updated to 749632e0f5f4b75e1a1a915548aaedd42b76f759
third_party: opentelemetry: dump swallowed exception traceback in log

If our telemetry collectors crash, we only get a short one-liner, and
this makes it difficult to understand where the crash is actually.
Expand the log to include the traceback.

Before:
$ ./run_tests
16:14:35.243: WARNING: Exception Invalid isoformat string: '2025-01-08T20:04:31Z' in detector <chromite.lib.telemetry.cros_detector.SDKSourceDetector object at 0x7f2496d00130>, ignoring
16:14:35: NOTICE: Caching tools from network (cipd/vpython/etc...)
.........

After:
$ ./run_tests
16:14:35.243: WARNING: Exception Invalid isoformat string: '2025-01-08T20:04:31Z' in detector <chromite.lib.telemetry.cros_detector.SDKSourceDetector object at 0x7f2496d00130>, ignoring
Traceback (most recent call last):
  File "~/chromiumos/chromite/third_party/opentelemetry/sdk/resources/__init__.py", line 365, in get_aggregated_resources
    detected_resource = future.result(timeout=timeout)
  File "~/.cache/vpython-root.145691/store/cpython+tkj8tpr2n0oj8m0t270p0m71s0/contents/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "~/.cache/vpython-root.145691/store/cpython+tkj8tpr2n0oj8m0t270p0m71s0/contents/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "~/.cache/vpython-root.145691/store/cpython+tkj8tpr2n0oj8m0t270p0m71s0/contents/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "~/chromiumos/chromite/lib/telemetry/cros_detector.py", line 41, in detect
    commit = git.GetLastCommit(manifest_repo)
  File "~/chromiumos/chromite/lib/git.py", line 2161, in GetLastCommit
    return next(CommitEntry.ParseFuller(stdout), None)
  File "~/chromiumos/chromite/lib/git.py", line 2146, in ParseFuller
    yield _build_entry(data, tags)
  File "~/chromiumos/chromite/lib/git.py", line 2100, in _build_entry
    datetime.datetime.fromisoformat(data["AuthorDate"])
ValueError: Invalid isoformat string: '2025-01-08T20:04:31Z'
16:14:35: NOTICE: Caching tools from network (cipd/vpython/etc...)
.........

BUG=None
TEST=`./run_tests` passes

Change-Id: I905c05c15b78d9030f66c4577211ce29a17e7b32
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/6190872
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Auto-Submit: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Alex Klein <saklein@chromium.org>

*infra/chromite-HEAD updated to 749632e0f5f4b75e1a1a915548aaedd42b76f759
third_party: opentelemetry: dump swallowed exception traceback in log

If our telemetry collectors crash, we only get a short one-liner, and
this makes it difficult to understand where the crash is actually.
Expand the log to include the traceback.

Before:
$ ./run_tests
16:14:35.243: WARNING: Exception Invalid isoformat string: '2025-01-08T20:04:31Z' in detector <chromite.lib.telemetry.cros_detector.SDKSourceDetector object at 0x7f2496d00130>, ignoring
16:14:35: NOTICE: Caching tools from network (cipd/vpython/etc...)
.........

After:
$ ./run_tests
16:14:35.243: WARNING: Exception Invalid isoformat string: '2025-01-08T20:04:31Z' in detector <chromite.lib.telemetry.cros_detector.SDKSourceDetector object at 0x7f2496d00130>, ignoring
Traceback (most recent call last):
  File "~/chromiumos/chromite/third_party/opentelemetry/sdk/resources/__init__.py", line 365, in get_aggregated_resources
    detected_resource = future.result(timeout=timeout)
  File "~/.cache/vpython-root.145691/store/cpython+tkj8tpr2n0oj8m0t270p0m71s0/contents/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "~/.cache/vpython-root.145691/store/cpython+tkj8tpr2n0oj8m0t270p0m71s0/contents/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "~/.cache/vpython-root.145691/store/cpython+tkj8tpr2n0oj8m0t270p0m71s0/contents/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "~/chromiumos/chromite/lib/telemetry/cros_detector.py", line 41, in detect
    commit = git.GetLastCommit(manifest_repo)
  File "~/chromiumos/chromite/lib/git.py", line 2161, in GetLastCommit
    return next(CommitEntry.ParseFuller(stdout), None)
  File "~/chromiumos/chromite/lib/git.py", line 2146, in ParseFuller
    yield _build_entry(data, tags)
  File "~/chromiumos/chromite/lib/git.py", line 2100, in _build_entry
    datetime.datetime.fromisoformat(data["AuthorDate"])
ValueError: Invalid isoformat string: '2025-01-08T20:04:31Z'
16:14:35: NOTICE: Caching tools from network (cipd/vpython/etc...)
.........

BUG=None
TEST=`./run_tests` passes

Change-Id: I905c05c15b78d9030f66c4577211ce29a17e7b32
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/6190872
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Auto-Submit: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Alex Klein <saklein@chromium.org>