chromeos-base/chaps: Add missing BDEPEND
```
FAILED: gen/include/chaps/proto_bindings/attributes.pb.cc gen/include/chaps/proto_bindings/attributes.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/chaps:9999

Change-Id: Ic2da4a62cacf6a1c989af26aaa3201e64112b5e9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4690601
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>