tests: subsys: usb: bos: Remove dummy_descriptor struct
When building with clang, it warns:

tests/subsys/usb/bos/src/test_bos.c:24:22: error: variable
'dummy_descriptor' is not needed and will not be emitted
[-Werror,-Wunneeded-internal-declaration]
static const uint8_t dummy_descriptor[] = {
                     ^

Only the size of dummy_descriptor is used, not the contents. Replace the
struct with a constant for the size.

(cherry picked from commit 785e36520fd3be5d8d9a2dd0fb569b889552b5b1)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 785e36520fd3be5d8d9a2dd0fb569b889552b5b1
Original-Cr-Build-Id: 8718794115469102209
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8718794115469102209
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I7e1e6ba7e42c7fec82153bfe09aa4170b1b050e1
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6421713
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 8f7f85b7bd63ba581e0d6ecd15b4466f41acc5ed
Cr-Build-Id: 8692823396573113169
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692823396573113169
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ie6c3ae18e29e2566ffb709e90b383af1d2bcecc7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7460100
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>