dev-util/bazel: Pin the JDK version to 11
When building bazel with JDK 21, we see a crash. Therefore,
pin the JDK version to 11 to avoid it.
```
java.lang.NoClassDefFoundError: Could not initialize class com.google.devtools.build.lib.unsafe.StringUnsafe
```

BUG=b:445049386
TEST=CQ

Change-Id: I53acc6e02d1db1728195f1768b8cb1929b71659d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/7197119
Tested-by: Tommy Chiang <ototot@google.com>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Tommy Chiang <ototot@google.com>