tests: i2c_emul: Remove unused variable
Building with clang warns:

tests/drivers/i2c/i2c_emul/src/test_forwarding_pio.cpp:19:32: error:
unused variable 'targets' [-Werror,-Wunused-const-variable]
constexpr const struct device *targets[FORWARD_COUNT] = {
                               ^

(cherry picked from commit bae8e34a3814acc6b64a7f23b5836f9cd1cde1e9)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: bae8e34a3814acc6b64a7f23b5836f9cd1cde1e9
Original-Cr-Build-Id: 8723052172249940737
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723052172249940737
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Id31aa4ad1d46ce8cc9627c0785d2e48c463db943
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6261361
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: d211f9b187994d246e0ef35575d0ae2b6461dfa5
Cr-Build-Id: 8692854981942345489
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692854981942345489
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Iecd5d2787bdc7bad8f4a9ef31fb0e2f68717a02c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7454788
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>