target-chromium-os-sdk: add app-text/docbook-xsl-ns-stylesheets
This is required when cross-compiling the new version
of pam >= 1.7.0 because it expects to pick up these
stylesheets from the host sysroot.

There is no option to disable the pam documentation
(I sent an PR for that, however it's a separate issue)
and the build will attempt to fetch the xsl from the
internet if they are missing, causing failures like:

pam-1.7.0_p20241230-r3: FAILED: doc/man/misc_conv.3
pam-1.7.0_p20241230-r3: /usr/bin/xsltproc -o doc/man/misc_conv.3 --nonet --xinclude --path /build/asurada/tmp/portage/sys-libs/pam-1.7.0_p20241230-r3/work/linux-pam-e634a3a9be9484ada6e93970dfaf0f055ca17332/doc/man --stringparam profile.condition 'without_vendordir;no_openssl_hmac'
doc/custom-man.xsl ../linux-pam-e634a3a9be9484ada6e93970dfaf0f055ca17332/doc/man/misc_conv.3.xml
pam-1.7.0_p20241230-r3: error : Resource temporarily unavailable: getaddrinfo failed
pam-1.7.0_p20241230-r3: warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl-ns/current/manpages/profile-docbook.xsl"
pam-1.7.0_p20241230-r3: compilation error: file doc/custom-man.xsl line 3 element import
pam-1.7.0_p20241230-r3: xsl:import : unable to load http://docbook.sourceforge.net/release/xsl-ns/current/manpages/profile-docbook.xsl
pam-1.7.0_p20241230-r3: ninja: build stopped: subcommand failed.

When testing with emerge-$BOARD pam, it will silently
fetch the xls from the internet and the build passes.

BUG=b:417103947
TEST=Local builds and boot on amd64, arm64; CQ.

Change-Id: I986adea6d2db2912a94a86b236204f56ed31a42b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/6596946
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: George Burgess <gbiv@chromium.org>