UPSTREAM: soc/intel/baytrail: Add acpi_get_sleep_type() to bootblock
Add a Baytrail implementation of acpi_get_sleep_type() and build
pmutil.c in the bootblock.

This resolves the undefined reference to acpi_get_sleep_type() when
USE_OPTION_TABLE and HAVE_ACPI_RESUME are enabled together on Baytrail
platforms.

(cherry picked from commit 7635fd4d82e8423fde06e7551c7cade1b4e03266)

BUG=https://ticket.coreboot.org/issues/614
Original-Change-Id: I3d9c53e805d03f2aa70ca419fb5b83691680a6ce
Original-Signed-off-by: Bhargav Rathod <bhargav.rathod1905@gmail.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/94522
Original-Reviewed-by: Matt DeVillier <matt.devillier@gmail.com>
Original-Reviewed-by: Angel Pons <th3fanbus@gmail.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Kyösti Mälkki <kyosti.malkki@gmail.com>
GitOrigin-RevId: 7635fd4d82e8423fde06e7551c7cade1b4e03266
Cr-Build-Id: 8672650061180888641
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8672650061180888641
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I8b0fd66a5b53e9059a2da466e52d885fcc58915e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/8282782
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Reka Norman <rekanorman@chromium.org>
Commit-Queue: Reka Norman <rekanorman@chromium.org>