cr50: util: ecst: fix gcc 15 strrchr const qualifier breakage
The GCC 15 host toolchain uprev surfaces a build error in the
ecst host utility, similar to the one fixed in ec-legacy CL:7903666:

util/ecst.c: In function 'splice_into_path':
util/ecst.c:89:20: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
   89 |         last_delim = strrchr(path, '/');
      |                    ^
cc1: all warnings being treated as errors

The newer glibc <string.h> declares a const-correct strrchr() which
returns a 'const char *' when passed a 'const char *' argument. As
'path' is const, the result can no longer be assigned to the non-const
'char *last_delim' without discarding the qualifier.

last_delim is only ever read (NULL check, pointer-difference, and as a
read-only source for sprintf), so declare it 'const char *'.
result_last_delim stays non-const since it indexes into the writable
'result' output buffer.

This fixes the build failure that was already observed during
emerge-brya chromeos-base/chromeos-ec.

BUG=b:493144630
TEST=cros-workon-brya start chromeos-base/chromeos-ec; emerge-brya chromeos-ec

Change-Id: Ic8ef4eba9636b1f657549f98c98e9f1909df29f5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/7909754
Reviewed-by: Mary Ruthven <mruthven@chromium.org>
Commit-Queue: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Code-Coverage: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Reviewed-by: Vadím Sukhomlínov <sukhomlinov@google.com>
Auto-Submit: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Reviewed-by: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Tested-by: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>