Make sure to have full configuration info in sys/_types.h.
The following testcase:

  $ cat > test.c <<EOF
  #include <sys/select.h>
  #include <sys/time.h>
  EOF
  $ gcc -c test.c

emits the following error:

  /usr/include/sys/reent.h:276:3: error: expected specifier-qualifier-list befor
e ‘_fpos64_t’
     _fpos64_t _EXFNPTR(_seek64, (struct _reent *, _PTR, _fpos64_t, int));
     ^

The reason is that the load order from sys/select.h includes sys/_types.h
before sys/config.h has been included from anywhere else.  sys/_types.h
defines _fpos64_t only if __LARGE64_FILES is defined, but it never is in
this scenario.  So sys/_types.h has to make sure to get the configuration
info by itself.

Original-Signed-off-by: Corinna Vinschen <corinna@vinschen.de>
GitOrigin-RevId: 72ded594471affbad3950f7a7a622304605be98f
Cr-Build-Id: 8694340433404800353
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694340433404800353
Copybot-Job-Name: zephyr-project-picolibc-copybot-downstream
Change-Id: Ie83e5000789cd2d2a2d0419a5f2566c0cd4a2261
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7339864
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>