FROMGIT: mmc-utils: mmc_cmds: fix type-punned warning on &ext_csd[] casting
When building with -Werror=strict-aliasing error is thrown:

mmc_cmds.c: In function 'do_ffu':
mmc_cmds.c:2972:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  sect_done = htole32(*((__u32 *)&ext_csd[EXT_CSD_NUM_OF_FW_SEC_PROG_0]));
  ^
cc1: all warnings being treated as errors

Let's fix type-punned breaking strict-aliasing by implementing local
per_byte_htole32(__u8 *) and use it for the 2 present occurences of
htole32(). Let's also change sect_done type to __u32 for consistency.

Suggested-by: Avri Altman <Avri.Altman@wdc.com>
Fixes: a1b594ca735e ("mmc-utils: ffu: Simplify ext_csd bytes parsing")
Reviewed-by: Avri Altman <avri.altman@wdc.com>
Link: https://lore.kernel.org/r/20240305184513.400364-1-giulio.benetti@benettiengineering.com
(cherry picked from commit e1281d4de9166b7254ba30bb58f9191fc2c9e7fb
 https://git.kernel.org/pub/scm/utils/mmc/mmc-utils.git master)

BUG=None
TEST=compile

Change-Id: I1d378df16b07fb61147bc5128547e68f3cc7fa3e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/mmc-utils/+/6193483
Reviewed-by: Alexis Savery <asavery@chromium.org>
Commit-Queue: Gwendal Grignou <gwendal@chromium.org>
Tested-by: Gwendal Grignou <gwendal@chromium.org>