stepper: shell: fix uninitialized variable compiler warning
/__w/zephyr/zephyr/include/zephyr/drivers/stepper.h:429:16: error:
'direction' may be used uninitialized [-Werror=maybe-uninitialized]

found with:

west build -p -b esp32s3_touch_lcd_1_28/esp32s3/appcpu -T
tests/drivers/stepper/shell/drivers.stepper.shell

(cherry picked from commit 5e2203a6cdd0daf395bb3825d416843ecdc40629)

Original-Fixes:
Original-Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-GitOrigin-RevId: 5e2203a6cdd0daf395bb3825d416843ecdc40629
Original-Cr-Build-Id: 8735286451693989857
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8735286451693989857
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I57e6c71c1618fb324690e55620e1c8b8d497d7aa
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5901729
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Original-Tested-by: Al Semjonovs <asemjonovs@google.com>
Original-Reviewed-by: Al Semjonovs <asemjonovs@google.com>
GitOrigin-RevId: 808d3f8a8d1f4eb6d8cf8a1d3290e4ec0026ea71
Cr-Build-Id: 8692943743589236977
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692943743589236977
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ib33744c2bba79fcf767a72b63182e4f469826497
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7444878
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>