tests: net: lwm2m: Fix zsock_fcntl impl name
The syscall name has _impl postfix so adjusting the stub
name.

zephyr-sdk-0.16.5-1/x86_64-zephyr-elf/bin/../lib/gcc/
  x86_64-zephyr-elf/12.2.0/../../../../x86_64-zephyr-elf/bin/ld.bfd:
  app/libapp.a(lwm2m_engine.c.obj): in function `zsock_fcntl_impl':
.../syscalls/socket.h:363: undefined reference to `z_impl_zsock_fcntl_impl'

(cherry picked from commit 66bc15d89d5449a0dedd44892d636d3130f3c425)

Original-Original-Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
Original-GitOrigin-RevId: 66bc15d89d5449a0dedd44892d636d3130f3c425
Original-Change-Id: I83c422e20d6ed4b3292f5605f07740c379f60d1f
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5407487
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 9a02769fc4448fd1d58aeb6d00ff666d130c1bd9
Cr-Build-Id: 8693054043427284545
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693054043427284545
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I051f4ea4a1c83cf3232bb2aba1fd287312154875
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7434187
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>