android_stub: fix missing prototypes issues
When the compiler is configured to complain about missing
prototypes, the lack of prototypes can cause issues:

src/android_stub/cutils_stub.cpp:13:1:
   error: no previous prototype for function 'atrace_begin_body' [-Werror,-Wmissing-prototypes]
   13 | atrace_begin_body(const char * /*name*/)

Update cutils/trace.h to the version in android-16.0.0_r3 [1], and
add proper header includes to fix this.

[1] https://android.googlesource.com/platform/system/core.git/+/refs/tags/android-16.0.0_r3/libcutils/include/cutils/trace.h

Acked-by: Yonggang Luo <luoyonggang@gmail.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/38644>