drivers: flash: Fix stm32 ospi and xpsi reset gpios handling
Fix compilation error when reset-gpios is enabled.
Undefined reference to dev_cfg variable.
Reset gpio duration needs to be defined, but is not in binding file.

(cherry picked from commit 04e56f72c71f5e05a2bf5666c67f6f1be13e13ed)

Original-Signed-off-by: Joakim Andersson <joerchan@gmail.com>
GitOrigin-RevId: 04e56f72c71f5e05a2bf5666c67f6f1be13e13ed
Change-Id: I8153369acac95d4e08c29d4913f4c79bef7ba7b7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5629319
Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Tested-by: Jeremy Bettis <jbettis@chromium.org>
Commit-Queue: Jeremy Bettis <jbettis@chromium.org>