xtensa: gdbstub: fix compilation
Building gdbstub for xtensa is failing currently with multiple
failures like

arch/xtensa/core/gdbstub.c:432:24: error: invalid operands to \
binary - (have 'int *' and 'const struct arch_esf *')
  432 |         if ((int *)bsa - stack > 4) {

Fix them by using appropriate pointer types.

(cherry picked from commit 5769c4d5652e295bbcbeb72e76b370985aaab18b)

Original-Original-Signed-off-by: Guennadi Liakhovetski <guennadi.liakhovetski@linux.intel.com>
Original-GitOrigin-RevId: 5769c4d5652e295bbcbeb72e76b370985aaab18b
Original-Cr-Build-Id: 8714943743272990721
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8714943743272990721
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I11573596b7cf54360cde2dd6f063beb0cf44a31a
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6545075
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 746a4a3b1ae180ce8a76baa4c02ae2aa3657c610
Cr-Build-Id: 8692795375977693793
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692795375977693793
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Id4f0a7dd310c2715f4c3b97311a07ce58facdf02
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7462934
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>