pinweaver/ti50: workaround to build with Clang-15 in Ti50 SDK
LIBCLANG_PATH cause weird issues that types from stdint.h not found:
  pinweaver_types.h:100:2: error: unknown type name 'uint8_t'
  pinweaver_types.h:105:2: error: unknown type name 'uint8_t'
  pinweaver_types.h:110:2: error: unknown type name 'uint8_t'
  ...

Commenting out LIBCLANG_PATH helps, but in general this is not a correct
behavior. Updating bindgen to 0.62 also didn't make a difference.

BUG=b:259282140
TEST=make, manually check that RISC-V target is correctly handled

Cq-Depend: chrome-internal:5146615
Change-Id: I9778afa3fb0f6c134e9f599f0bdb594ab6f36aea
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/pinweaver/+/4049022
Reviewed-by: Vadim Sukhomlinov <sukhomlinov@chromium.org>
Owners-Override: Brad McKee <bradmckee@google.com>
Reviewed-by: Alyssa Haroldsen <kupiakos@google.com>
Auto-Submit: Vadim Sukhomlinov <sukhomlinov@chromium.org>
Commit-Queue: Vadim Sukhomlinov <sukhomlinov@chromium.org>
Tested-by: Vadim Sukhomlinov <sukhomlinov@chromium.org>