runners: jlink: Fix NoneType object error
The commit 221199e15b85a070b3d81709eee3d533c9f99967 presents a bug that
makes west flash failed with error.

In function is_tunnel(), tunnel may contain None and has no attribute
"startswith". Fix it.

(cherry picked from commit 829c03bcdca378fa2fa55484d16a190d379f754c)

Original-Original-AttributeError: 'NoneType' object has no attribute 'startswith'
Original-Original-Signed-off-by: Phi Bang Nguyen <phibang.nguyen@nxp.com>
Original-GitOrigin-RevId: 829c03bcdca378fa2fa55484d16a190d379f754c
Original-Cr-Build-Id: 8733565196572304993
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8733565196572304993
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I6a6ed29d28c2dd114921af945b1efb7a5e7daf3a
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5940417
Original-Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Commit-Queue: Eric Yilun Lin <yllin@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
GitOrigin-RevId: 2981913979f7451c06775dd190cfb058e46f55a4
Cr-Build-Id: 8692934434195585665
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692934434195585665
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I79945d285919ed1931cb7d04b484c024e45676eb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7445841
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>