chromeos-base/attestation: Add missing BDEPEND
```
FAILED: gen/include/attestation/pca-agent/dbus_adaptors/org.chromium.PcaAgent.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

```
FAILED: gen/include/attestation/common/database.pb.cc gen/include/attestation/common/database.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
/build/arm64-generic/etc/portage/hooks/install/check-seccomp.sh: line 27: compile_seccomp_policy: command not found
 * ERROR: chromeos-base/attestation-9999::chromiumos failed:
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/attestation:9999

Change-Id: I579ae35a12d97f434ef89eb1a963f9219f89896c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4690598
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>