samples: nrf: onoff_level_lighting_vnd_app: fix build with mcumgr
There is an optional mcumgr enabled prj_smp_svr.conf configuration
file. Using it results in following errors:

  .../src/smp_svr.c:12:10: fatal error: mgmt/buf.h: No such file or \
  directory
     12 | #include <mgmt/buf.h>
        |

Fix include paths to keep sample buildable with mcumgr enabled.

Original-Fixes: c200b1c5e634 ("mgmt: Move mcumgr into its own folder")
Original-Signed-off-by: Marcin Niestroj <m.niestroj@grinn-global.com>
GitOrigin-RevId: d7d1c4a58f19b773b4f1f36e01a5ee2d1248e969
Cr-Build-Id: 8693996574547804577
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693996574547804577
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I3d6066ddd268892f69903f99465a20a3051dc611
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7365706
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>