cros-sanitizers: Use same flags for ubsan with/without fuzzing
This resolves an old TODO, and also causes us to consistently
apply -fsanitize=vptr, which should avoid link errors such as
error: undefined symbol: __ubsan_vptr_type_cache.

BUG=b:422542836
TEST=cros try

Change-Id: I226a9504f789af75d983da39f72cdd66f699ad10
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/6653095
Commit-Queue: Bob Haarman <inglorion@chromium.org>
Reviewed-by: Jordan Abrahams-Whitehead <ajordanr@google.com>
Tested-by: Bob Haarman <inglorion@chromium.org>
Reviewed-by: Lina Versace <linyaa@google.com>