drivers: sensor: maxim,ds3231: avoid compilation error
As the C language treats 'cases' similar to 'labels' the following
error can also occur when using switch statements when it encounters
a declaration immediately after a label:

drivers/sensor/maxim/ds3231/ds3231.c:77:3: error: a label can only
        be part of a statement and a declaration is not a statement
   77 |   const uint16_t raw_temp = data->raw_temp;
      |   ^~~~~

(cherry picked from commit 98cf437d7a988d12d3fc295b3d4ce6df82c57f1a)

Original-Signed-off-by: Stephan Linz <linz@li-pro.net>
GitOrigin-RevId: 98cf437d7a988d12d3fc295b3d4ce6df82c57f1a
Cr-Build-Id: 8723776949373603889
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723776949373603889
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I983bc4f6c2b2c96fcbfd38a0cb6bdbded532ff7f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6234544
Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>