drivers: dma: Remove unused function
Building with clang warns:

drivers/dma/dma_emul.c:73:20: error: unused function
'dma_emul_xfer_is_error_status' [-Werror,-Wunused-function]
static inline bool dma_emul_xfer_is_error_status(int status)
                   ^

(cherry picked from commit 538b525ef15a5689372cbdffbac86e35df8460e1)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 538b525ef15a5689372cbdffbac86e35df8460e1
Original-Cr-Build-Id: 8723052172249940737
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723052172249940737
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I0bfe6a2cbe544f17df8223710726f24b222c8d29
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6261363
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 2cdd79a7976fa9df6b83652dedbcb5ba0fc4d9ab
Cr-Build-Id: 8692854981942345489
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692854981942345489
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ifee91a900e0871fe0d84abcd873228ea56ba371d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7454790
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>