chromeos-base/oobe_config: Add missing BDEPEND
```
FAILED: gen/include/oobe_config/rollback_data.pb.cc gen/include/oobe_config/rollback_data.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
FAILED: gen/include/dbus_adaptors/org.chromium.OobeConfigRestore.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

```
/build/arm64-generic/etc/portage/hooks/install/check-seccomp.sh: line 27: compile_seccomp_policy: command not found
 * ERROR: chromeos-base/oobe_config-9999::chromiumos failed:
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/oobe_config:9999

Change-Id: I1b5529ecdbf7d1a39f4dec93bff98f9c701287ed
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692119
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>