media-sound/cras-client: add missing alsa-lib dep
While fixing the sysroot path for the bindgen builds,
we have noticed that the generic bazel builds fail due
to the following error:

./../include/cras_audio_format.h:45:10: fatal error:
'alsa/asoundlib.h' file not found

This is due to a missing media-libs/alsa-lib dependency
which, due to sysroot misconfiguration, gets picked up
from the host /usr/include dir.

By adding the dep we ensure the alsa-lib headers exist
in the board sysroots, from where bindgen will correctly
pick them up.

BUG=b:335699866
TEST=Local builds on amd64/arm64; CQ.

Change-Id: Iec5e13cfa8cfacf88ab294922a7483091552366d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/6438811
Reviewed-by: Jordan Abrahams-Whitehead <ajordanr@google.com>
Commit-Queue: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>
Auto-Submit: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>