Revert "scripts: devicetree: Handle mixed case node names"
This reverts commit 1c060659411e5fd23ec299f49bd98e0744632c07.
Breaks cc3200_launchxl really bad:

 CC      drivers/serial/uart_cc32xx.o
/projects/zephyr4/drivers/serial/uart_cc32xx.c:39:18: error: ‘TI_CC32XX_UART_4000C000_BASE_ADDRESS’ undeclared here (not in a function)
  .base = (void *)TI_CC32XX_UART_4000C000_BASE_ADDRESS,
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/projects/zephyr4/drivers/serial/uart_cc32xx.c: In function ‘uart_cc32xx_init’:
/projects/zephyr4/drivers/serial/uart_cc32xx.c:65:5: error: ‘TI_CC32XX_UART_4000C000_BAUD_RATE’ undeclared (first use in this function)
     TI_CC32XX_UART_4000C000_BAUD_RATE,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Original-Change-Id: If46c239bc8d6b4296494f638e900f6044a92ce26
Original-Signed-off-by: Anas Nashif <anas.nashif@intel.com>
GitOrigin-RevId: 670268697614bd804ed6a96865ab03a5538c0e5f
Cr-Build-Id: 8694645158408960481
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694645158408960481
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I82eb26abdf3463e9c9187fc41de980e14ac4a5fd
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7316058
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>