chromeos-base/libsegmentation: Add missing BDEPEND
```
FAILED: gen/include/proto/feature_management.pb.cc gen/include/proto/feature_management.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/libsegmentation:9999

Change-Id: Iad38210f804f44b1258a0f8a33854aaaff66d8f3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692108
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>