mgmt: smp: add missing kernel.h include statement
There is following error when compiling applications using smp:

  /zephyr/include/mgmt/smp.h:77:16: error: field 'zst_work' has \
  incomplete type
     77 |  struct k_work zst_work;
        |                ^~~~~~~~
  /zephyr/include/mgmt/smp.h:80:16: error: field 'zst_fifo' has \
  incomplete type
     80 |  struct k_fifo zst_fifo;
        |                ^~~~~~~~

Fix that by adding missing kernel.h include statement in mgmt/smp.h.

Original-Signed-off-by: Marcin Niestroj <m.niestroj@grinn-global.com>
GitOrigin-RevId: aec0b5ae84395858974943a339e8280df7355c89
Cr-Build-Id: 8694007797326777681
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694007797326777681
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I97deb1beaf16a06b266290a98594438d9a61a36e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7364920
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>