chromeos-base/runtime_probe: Add missing BDEPEND
```
ninja: error: '../../../../../../../../../usr/bin/compile_seccomp_policy', needed by 'gen/runtime_probe/init/seccomp/runtime_probe-seccomp.bpf', missing and no known rule to make it
```

```
FAILED: gen/include/runtime_probe/dbus_adaptors/org.chromium.RuntimeProbe.h 
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/runtime_probe:9999

Change-Id: I02d8eb907a752ea1b7c87cce1185a23e525677db
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692129
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>