net: Fix alignment error with net_ipaddr_copy()
As struct sockaddr have now alignment of 4 bytes, net_ipaddr_copy()
gives the following error if used for sockaddr:

  error: alignment 1 of ‘struct <anonymous>’ is less than 4
  [-Werror=packed-not-aligned]

Just use memcpy() instead, net_ipaddr_copy() was intended to use with IP
addresses, not socket related structs.

(cherry picked from commit 62a5260e0182f3327982b382922e52deb4fed1d0)

Original-Original-Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>
Original-GitOrigin-RevId: 62a5260e0182f3327982b382922e52deb4fed1d0
Original-Cr-Build-Id: 8710232702044463633
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8710232702044463633
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ia080cc7724d156e0211b64ff88840660ec652a71
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6706040
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 3712274e94fdede56e13d3103a3ed990a9b5cf7b
Cr-Build-Id: 8692750170886086881
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692750170886086881
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ia2335dc4c30d6fc16a3b562a86cf57c6e4233b38
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7467769
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>