UPSTREAM: kernfs: add stub helper for kernfs_generic_poll()
In some randconfig builds, kernfs ends up being disabled, so there is no prototype
for kernfs_generic_poll()

In file included from kernel/sched/build_utility.c:97:
kernel/sched/psi.c:1479:3: error: implicit declaration of function 'kernfs_generic_poll' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                kernfs_generic_poll(t->of, wait);
                ^

Add a stub helper for it, as we have it for other kernfs functions.

Fixes: aff037078ecae ("sched/psi: use kernfs polling functions for PSI trigger polling")
Fixes: 147e1a97c4a0b ("fs: kernfs: add poll file operation")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Chengming Zhou <zhouchengming@bytedance.com>
Link: https://lore.kernel.org/r/20230724121823.1357562-1-arnd@kernel.org
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 79038a99445f69c5d28494dd4f8c6f0509f65b2e)

BUG=chromium:1028527
TEST=run the monitor example from PSI kernel documentation

Signed-off-by: Linux Patches Robot <linux-patches-robot@chromeos-missing-patches.google.com.iam.gserviceaccount.com>
Change-Id: I0e7b7e3f3a3688439fa9be0a9bc439e12ad10a6a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4837078
Commit-Queue: Vovo Yang <vovoy@chromium.org>
Reviewed-by: Sean Paul <sean@poorly.run>
Reviewed-by: Vovo Yang <vovoy@chromium.org>
Tested-by: Vovo Yang <vovoy@chromium.org>