dev-python/pytest: update for compatibility with Python 3.11
This CL updates dev-python/pytest to the latest version.

This CL should fix the host-packages-cq failures in
https://crrev.com/c/5995371. Specifically, the tests for
chromeos-base/zephyr-build-tools fail with the following message:

    TypeError: required field "lineno" missing from alias

This discussion suggests our version of pytest might be too old:
https://github.com/pytest-dev/pytest/discussions/9195. So I tried
updating pytest to the latest version and that fixed our test failures.

BUG=b:318531403 b:362791652
TEST=sudo emerge -jv dev-python/pytest
TEST=sudo FEATURES=test emerge chromeos-base/zephyr-build-tools

Change-Id: I141b3d5d7892b962969ec7214d29f8ddb932ad6e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/portage-stable/+/5996250
Reviewed-by: Tim Bain <tbain@google.com>
Commit-Queue: Leandro Lovisolo <lovisolo@google.com>
Tested-by: Leandro Lovisolo <lovisolo@google.com>