samples: tfm_integration: replace nrf5340dk with nrf9161dk
Building for nrf5340dk cause link time failure as:

undefined reference to `tfm_platform_gpio_pin_mcu_select'

It only happens with this platform, not with other ones in the allow
list, therefore we pick another Nordic one as integration platform and
disable nrf5340dk.

Original-Signed-off-by: Valerio Setti <vsetti@baylibre.com>
GitOrigin-RevId: ccfd5efa09f9fed814c1947edba2739544b3c901
Cr-Build-Id: 8684605994025143249
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8684605994025143249
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I4d76b9cf4a91a3b41271ec1f0e6f66b20571d423
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7758607
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>