kconf: Fix build with gcc 5.1.1
Building zconf.hash.c fails with gcc 5.1.1 from Fedora 22:

In file included from zconf.tab.c:159:0:
zconf.hash.c:233:55: error: ‘kconf_id_strings_contents’ is static but used in inline function ‘kconf_id_lookup’ which is not static [-Werror]
zconf.hash.c:226:23: error: ‘kconf_id_hash’ is static but used in inline function ‘kconf_id_lookup’ which is not static [-Werror]
    register int key = kconf_id_hash (str, len);
                       ^
zconf.hash.c:177:26: error: ‘wordlist’ is static but declared in inline function ‘kconf_id_lookup’ which is not static [-Werror]
   static struct kconf_id wordlist[] =
                          ^
Import the necessary change from the latest Linux source tree.

Change-Id: Ib6297b5cc3da161bd99c2e92c366206e6c08b4e5
Original-Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>
GitOrigin-RevId: 15bf447614e0fcd86007145ed9df75f5fbb3b4cc
Cr-Build-Id: 8697639724041279665
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8697639724041279665
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7182734
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>