modem_shell: fix compilation error.
fix error: 'struct modem_shell_user_data' has no member named 'shell'

(cherry picked from commit a0418f18219750138f1a4497bcbed9e51cf75069)

Original-Original-Signed-off-by: Mark Kettner <mark@kettner.io>
Original-GitOrigin-RevId: a0418f18219750138f1a4497bcbed9e51cf75069
Original-Change-Id: Id31efff44bd11ef0dd7d3dbbc1272e0c1480baca
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4645593
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: bca24d5e67e248602deb156f71cb0e350bfc356d
Cr-Build-Id: 8693193308765882737
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693193308765882737
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ibbdbea550128d2aeff8db2952c438df02132da1b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7419029
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>