chameleon: fix grpcio package on Buster
There's an issue with pip installing grpcio on
Buster. An import error occurs when using the
grpc library:
```
ImportError: /lib/arm-linux-gnueabihf/libm.so.6:
version `GLIBC_2.29' not found (required by
/usr/local/lib/python3.7/dist-packages/grpc/_cytho
n/cygrpc.cpython-37m-arm-linux-gnueabihf.so)
```
To address the issue, build the package from
source instead of using the pre-built binary.

BUG=b:369954585
TEST=manually

Change-Id: I3ef4a994c327a3bec3414881e15c7ab447f512cd
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/chameleon/+/5904230
Reviewed-by: Yun-hao Chung <howardchung@chromium.org>
Commit-Queue: John Lai <johnlai@google.com>
Tested-by: John Lai <johnlai@google.com>