soc: stm32: common: gpioport_mgr: always provide GPIO driver API
There are some (many?) applications and drivers which use the GPIO API
without making sure to enable it first. Unfortunately, it is common for
boards to enable CONFIG_GPIO=y in their defconfig, which allows these
applications/drivers to work fine even though they don't explicitly
enable the GPIO drivers they depend on... except when the target does
not enable CONFIG_GPIO=y as expected, which is now the case on STM32
platforms.

Unfortunately, due to a combination of several factors, such misuses
will currently result in runtime failures on STM32 platforms that are
not immediately obvious to diagnose:
- the GPIO API is implemented entirely in headers and not gated behind
  any symbol - as a result, consumers of the API will build fine and
  there will be no link error due to missing subsystem code when the
  GPIO subsystem is disabled

- the GPIOport manager instantiates devices regardless of CONFIG_GPIO;
  as such, the `undefined reference to __device_dts_ord_NNN` link error
  that would be expected to occur doesn't and images build just fine

- when CONFIG_GPIO=n, the GPIOport devices have NULL as `api` pointer

The GPIO API functions expect `dev->api` to be valid - as do functions
in every other Zephyr API - so they don't check that `dev->api != NULL`
and blindly dereference `api` which is NULL in this case. If the MPU is
enabled, this should fault immediately and could be easy to diagnose;
however, if the MPU is not enabled, the NULL dereference will (usually)
not fault and the resulting behavior is unpredictable.

Provide a dummy implementation of the GPIO API when CONFIG_GPIO=n such
that calls to the API will fail gracefully and log a clear error message
instead of causing unpredictable behavior, which should help users to
diagnose the issue and fix their configuration.

A broader rework of the GPIOport manager organization could solve this
issue by bringing back the link-time errors, but this is a much larger
effort and I'm not sure the result will be satisfactory, so let's start
with this first even though it is a bit hacky.

Original-Signed-off-by: Mathieu Choplain <mathieu.choplain-ext@st.com>
GitOrigin-RevId: 15b11930255950fe2a4f220d0f795cd9c54775a9
Cr-Build-Id: 8680083166403963553
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8680083166403963553
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ic75c770028100f8bf907498af88a7e083eb9706c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7897111
Bot-Commit: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>