chromeos-base/system_api: Add missing BDEPEND
```
[1/296] ACTION //system_api:system_api-anomaly_detector-protos_gen(//common-mk/toolchain:toolchain)
FAILED: gen/include/anomaly_detector/proto_bindings/anomaly_detector.pb.cc gen/include/anomaly_detector/proto_bindings/anomaly_detector.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
FAILED: gen/go/src/attestation_ca.pb.go gen/go/src/interface.pb.go gen/go/src/keystore.pb.go
protoc-gen-go: program not found or is not executable
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/system_api:9999

Change-Id: I8ac63d07df067fb6481cd30392c9f097da789022
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692138
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>