ext/hal/st/stm32cube/stm32l1xx: rename SVC_IRQn -> SVCall_IRQn
SVCall_IRQn is used as enum value for SV Call Interrupt for Cortex-M
based SoCs for which CPU_CORTEX_M_HAS_BASEPRI=y. However stm32cube
for stm32l1xx uses SVC_IRQn enum value for this purpose.
This leads to this error:

  arch/arm/include/cortex_m/exc.h:101:19: error: 'SVCall_IRQn'
    undeclared (first use in this function); did you mean 'SVC_IRQn'?

    NVIC_SetPriority(SVCall_IRQn, _EXC_SVC_PRIO);
                     ^~~~~~~~~~~
                     SVC_IRQn

fixed in 9f8260457b86 ('ext: hal: st: stm32cube: Add HAL for
the STM32L1x series').

Original-NB: ext/hal/st/stm32cube/stm32l1xx/soc/stm32l151xb.h file was already
Original-Signed-off-by: Antony Pavlov <antonynpavlov@gmail.com>
GitOrigin-RevId: 43c4c9c50731e0507f54f6d99485795aedff0236
Cr-Build-Id: 8694283657752380497
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694283657752380497
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I2599f1fc7eb897f7f5b1843c33675169b5d527d4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7347418
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>