chromeos-base/quipper: Add missing BDEPEND
```
FAILED: gen/include/perf_stat.pb.cc gen/include/perf_stat.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/quipper:9999

Change-Id: Ic3bb277ac8e9e0c316d5cf4eaa2655a8c0006d2a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692125
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>