mm_drv: tlb: Fix compile time warning
This fixes the following compile time warning;

drivers/mm/mm_drv_intel_adsp_mtl_tlb.c: In function 'sys_mm_drv_mm_init':
include/zephyr/sys/__assert.h:44:52: error: format '%p' expects argument
of type 'void *', but argument 2 has type
'long unsigned int' [-Werror=format=]
__ASSERT_PRINT("\t" fmt "\n", ##__VA_ARGS__)

(cherry picked from commit b4998c357e43ff99714dc9f33ea5721e397557b1)

Original-Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
GitOrigin-RevId: b4998c357e43ff99714dc9f33ea5721e397557b1
Change-Id: I200869ff689651a13a66a333d1b04ae383611e33
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4887358
Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Tested-by: Al Semjonovs <asemjonovs@google.com>