Bluetooth: Fix compiler warning when VS HCI is unset
subsys/bluetooth/host/hci_core.c: In function ‘set_static_addr’:
subsys/bluetooth/host/hci_core.c:4043:1: error: label ‘generate’ defined
but not used [-Werror=unused-label]
 generate:
 ^~~~~~~~

Original-Fixes:
Original-Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>
GitOrigin-RevId: ea68c3aa2240232a644155ec6e4bd4884e535ee8
Cr-Build-Id: 8694597838787381201
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694597838787381201
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ifaba7d624cca65bc733af68d3215e60ec6683868
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7322097
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>