tests: arch: arm_custom_interrupt: exclude imx943
Exclude imx943,
  - multi level interrupts feature is enabled defaultly,
    so irqsteer1 driver is enabled, then the test case
    report the build issue:
    multiple definition of z_soc_irq_enable,
    tests/arch/arm/arm_custom_interrupt/src/arm_custom_interrupt.c:47
    first defined here.

(cherry picked from commit 9dcf76c6700ff38f433067e256303a788f7a6b02)

Original-Original-Signed-off-by: Biwen Li <biwen.li@nxp.com>
Original-GitOrigin-RevId: 9dcf76c6700ff38f433067e256303a788f7a6b02
Original-Cr-Build-Id: 8694559427236376193
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694559427236376193
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Iaf26c819c09ec25dcffc70ee64c4045aaa1a49e0
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7325288
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: 68b464a5d79b51a0728a0e7116a92e2c574e058a
Cr-Build-Id: 8692610755496680913
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692610755496680913
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I437fab2ab3519feb96631f671330ed0f082ab63e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7484537
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>