drivers/storage: Fix pointer truncation warning for x86_64 build Android Bringup: See http://go/android-fw-sync
The `pci_read_config32()` function returns a `uint32_t`, which is then
bitwise ANDed with `~0xf` and cast to a `void *`. This can result in
pointer truncation on platforms where pointers are wider than 32 bits.

Compilation Error:

```
src/drivers/storage/ufs_intel.c: In function 'intel_ufs_update':
src/drivers/storage/ufs_intel.c:46:29: error: cast to pointer from
 integer of different size [-Werror=int-to-pointer-cast]
 46 |   intel_ufs->ufs.hci_base = (void *)(pci_read_config32(dev,
         REG_BAR0) & ~0xf);
                                   ^
```

Fix this by casting the result of `pci_read_config32()` to `uintptr_t`
before the bitwise AND and the cast to `void *`.

(cherry picked from commit f7c82e816cb849ea84f9b8171d11fe88f1768c82)

Original-cc1: all warnings being treated as errors
Change-Id: I44551d681c9528dfd732a3d765281ca822a9e540
Original-Signed-off-by: Subrata Banik <subratabanik@google.com>
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/6075648
Original-Tested-by: Subrata Banik <subratabanik@chromium.org>
Original-Commit-Queue: Subrata Banik <subratabanik@chromium.org>
Original-Auto-Submit: Subrata Banik <subratabanik@chromium.org>
Original-Reviewed-by: Kapil Porwal <kapilporwal@chromium.org>
GitOrigin-RevId: f7c82e816cb849ea84f9b8171d11fe88f1768c82
Cr-Build-Id: 8729035347046430481
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8729035347046430481
Copybot-Job-Name: android-main-depthcharge-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/6079504
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Jonathon Murphy <jpmurphy@google.com>