chromeos-base/smbfs: Add missing BDEPEND
```
FAILED: gen/include/smbfs/dbus-proxies.h gen/include/smbfs/dbus-proxy-mocks.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/smbfs:9999

Change-Id: I1afb1bc3e562717f00a707615bb0a1c4c17bc96a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692133
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>