chromeos-base/mtpd: Add missing BDEPEND
```
FAILED: gen/include/mtpd/dbus_adaptors/org.chromium.Mtpd.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

```
/build/arm64-generic/etc/portage/hooks/install/check-seccomp.sh: line 27: compile_seccomp_policy: command not found
 * ERROR: chromeos-base/mtpd-9999::chromiumos failed:
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/mtpd:9999

Change-Id: I736c59ae2552008bcb29e1845936ef50a9e87b1f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692118
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>