Bluetooth: mesh: Fix uninitialized variable error
This fixes the error below:

main.c: In function ‘bt_mesh_provision’:
main.c:173:17: error: ‘node’ may be used uninitialized in
	       this function [-Werror=maybe-uninitialized]
  173 |                 bt_mesh_cdb_node_del(node, true);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(cherry picked from commit c563e7a1b84bd324f47c75e4adf7eee0b1c54153)

Original-Original-cc1: all warnings being treated as errors
Original-Original-Signed-off-by: Mariusz Skamra <mariusz.skamra@codecoup.pl>
Original-GitOrigin-RevId: c563e7a1b84bd324f47c75e4adf7eee0b1c54153
Original-Change-Id: I6c10dc8654cfcc32ef3c2e8e459f3e4160e8a50e
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4808545
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 13da020ac4ad1953616c9b3127dd836c18affa9a
Cr-Build-Id: 8693169872617377201
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693169872617377201
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ic193daaee3d25f667d75ec10005886166a6b9d96
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7421799
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>