net-wireless/floss: Add missing BDEPEND
```
  File "../../../../../../tmp/portage/net-wireless/floss-9999/work/floss-9999/platform2/common-mk/file_generator_wrapper.py", line 19, in <module>
    subprocess.check_call(sys.argv[1:])
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cxxbridge'
```

```
error: failed to run custom build command for `grpcio-sys v0.9.1+1.38.0`

Caused by:
  process didn't exit successfully: `/var/cache/portage/net-wireless/floss/cros-rust/release/build/grpcio-sys-9e3c08991086af4e/build-script-build` (exit status: 101)

failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/host/chromiumos/net-wireless/floss:9999

Change-Id: Idb0e2d76ca8ec69b5d9f66bbfdcf28701f53a8a9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4655489
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>