UPSTREAM: ASoC: qcom: Select missing common Soundwire module code on SDM845
SDM845 sound card driver uses qcom_snd_sdw_startup() from the common
Soundwire module, so select it to fix build failures:

  ERROR: modpost: "qcom_snd_sdw_startup" [sound/soc/qcom/snd-soc-sdm845.ko] undefined!

Fixes: d0e806b0cc62 ("ASoC: qcom: sdm845: add missing soundwire runtime stream alloc")
Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Link: https://patch.msgid.link/20241012100957.129103-1-krzysztof.kozlowski@linaro.org
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit b930d8647869802a0d430aae6b1b05c3acb24a41)

BUG=b:326869955
TEST=Test Audio use cases.

Signed-off-by: Linux Patches Robot <linux-patches-robot@chromeos-missing-patches.google.com.iam.gserviceaccount.com>
Change-Id: If7eb4e0f7fea6c47186b92154a518cefb9a2d8a9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/6043118
Reviewed-by: Sean Paul <sean@poorly.run>
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>
Reviewed-by: Terry Cheong <htcheong@chromium.org>
Commit-Queue: Curtis Malainey <cujomalainey@chromium.org>