drivers: watchdog_shell: fix compiler error
Fix wdt_shell.c:54:13: error: implicit declaration of function 'strtoul'

Tested with west build -p -b nrf52dk_nrf52832 samples/drivers/watchdog
-DCONFIG_SHELL=y.

(cherry picked from commit 420d9563a4801905d255a4103e5654cd70928fb7)

Original-Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-GitOrigin-RevId: 420d9563a4801905d255a4103e5654cd70928fb7
Original-Change-Id: I790142ecb9b05a71cb0c554e84e40a126417f53a
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4801964
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 67bc0df234fbe035d97e0596c96d5d271e33829c
Cr-Build-Id: 8693169872617377201
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693169872617377201
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I05daabd037ec89a0bea3a7bbbc92e92cebcffeeb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7421749
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>