CHROMIUM: media: camx: cam_isp: Fix misleading indentation
cam_irq_controller.c: In function ‘cam_irq_controller_handle_irq’:
irq_controller/cam_irq_controller.c:763:25: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
  763 |                         if (irq_register->top_half_enable_mask[j] &
      |                         ^~

BUG=none
TEST=make C=1 W=1
UPSTREAM-TASK=b:274966069

Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
Change-Id: I917c2937acfabf766be5716d5e359923cfc407b5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4921750
Reviewed-by: Sergey Senozhatsky <senozhatsky@chromium.org>
(cherry picked from commit 24e6a86573671506aba52f907a1909398f42f748)
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4926208