net: ptp: do not use a reserved id in global scope
Generally, we should avoid using reserved names in global
contexts.

subsys/net/lib/ptp/clock.c:58:25: \
  error: 'clock' redeclared as different kind of symbol
   58 | static struct ptp_clock clock = { 0 };

/opt/toolchains/zephyr-sdk-0.16.8/arm-zephyr-eabi/picolibc/ \
  include/time.h:100:12: \
  note: previous declaration of 'clock' with type 'clock_t(void)' \
  {aka 'long unsigned int(void)'}
  100 | clock_t    clock (void);

subsys/net/lib/ptp/clock.c:58:25: \
  error: 'clock' defined but not used [-Werror=unused-variable]
   58 | static struct ptp_clock clock = { 0 };

(cherry picked from commit 72bd951ac40f88d534afd18b71c97005d6f257e2)

Original-Original-Signed-off-by: Chris Friedt <cfriedt@tenstorrent.com>
Original-GitOrigin-RevId: 72bd951ac40f88d534afd18b71c97005d6f257e2
Original-Change-Id: I0d633e5fc2d1fb1a56c631d6915e0f16f5a445d9
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5642868
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
Original-Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: c1a3e98bd4e0ffe7a61f637744a989f3dce2afe8
Cr-Build-Id: 8693000327137950161
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693000327137950161
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I345c93c76ffe1a1e1200169f739f27fa3a283795
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7439407
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>