board/goroh: Fix duplicate initialization
When building with clang, it warns:

board/goroh/sensors.c:86:20: error: initializer overrides prior
initialization of this subobject [-Werror,-Winitializer-overrides]
   86 |                 .min_frequency = BMA255_ACCEL_MIN_FREQ,
      |                                  ^~~~~~~~~~~~~~~~~~~~~
include/driver/accel_bma2x2_public.h:50:31: note: expanded from macro
'BMA255_ACCEL_MIN_FREQ'
   50 | #define BMA255_ACCEL_MIN_FREQ 7810
      |                               ^~~~
board/goroh/sensors.c:85:20: note: previous initialization is here
   85 |                 .min_frequency = BMI_GYRO_MIN_FREQ,
      |                                  ^~~~~~~~~~~~~~~~~
include/driver/accelgyro_bmi_common.h:57:27: note: expanded from macro
'BMI_GYRO_MIN_FREQ'
   57 | #define BMI_GYRO_MIN_FREQ 25000
      |                           ^~~~~

It looks like min_frequency was accidentally duplicated. The first
initialization was using the gyro frequency, while the second one was
using the correct acceleration frequency. There is no functional change
with this since the last initialization wins.

BUG=b:407560601, b:172020503
TEST=./util/compare_build.sh -b all

Change-Id: I706d5cd2239339e1e191e6d6c340da9bbfca79be
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/6441496
Tested-by: Tom Hughes <tomhughes@chromium.org>
Reviewed-by: Eric Yilun Lin <yllin@google.com>
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
Commit-Queue: Tom Hughes <tomhughes@chromium.org>