main: Simplify variable assignment
Error: RESOURCE_LEAK (CWE-772): [#def39] [important]
src/main.c:425:2: alloc_fn: Storage is returned from allocation function "g_key_file_get_string".
src/main.c:425:2: var_assign: Assigning: "tmp" = storage returned from "g_key_file_get_string(config, group, key, &err)".
src/main.c:433:2: noescape: Assuming resource "tmp" is not freed or pointed-to as ellipsis argument to "btd_debug".
src/main.c:440:2: leaked_storage: Variable "tmp" going out of scope leaks the storage it points to.
438|	}
439|
440|->	return true;
441|   }
442|