UPSTREAM: util/blob: Fix const correctness warning in blob_read_string
Fix compiler error:

  ../src/util/blob.c:344:8: error: assigning to 'uint8_t *' from
  'const void *' discards qualifiers
  [-Werror,-Wincompatible-pointer-types-discards-qualifiers]

glibc now provides C23-style type-generic string functions. memchr
returns const void * when passed a const void * argument. Update nul
declaration to const since it's only used to find the null terminator
position and calculate a size.

Fixes: 1c9877327ea ("glsl: Add blob.c---a simple interface for serializing data")
Reviewed-by: Tapani Pälli <tapani.palli@intel.com>
(cherry picked from commit b40850b24a09cd96c9de8c642fb8e4cd4ae587f6)

Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/39462>

Backport Notes:
- resolve trivial .pick_status.json conflict

BUG=b:491765858
TEST=emerge-reven media-libs/mesa-reven

Change-Id: Iafb8580ae28e45399f86b432cf7bde7773745ca9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/mesa/+/8138758
Auto-Submit: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: Allen Ballway <ballway@google.com>
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Commit-Queue: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>