sys-devel/llvm: Add missing dep
    /build/amd64-host/tmp/portage/sys-devel/llvm-16.0_pre484197_p20230405-r1/work/llvm-16.0_pre484197_p20230405/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp:180:10: fatal error: 'crypt.h' file not found
    #include <crypt.h>
             ^~~~~~~~~
    1 error generated.

BUG=b:278728702
TEST=BOARD=amd64-host bazel run --//bazel/sdk:new-sdk @portage//sys-devel/llvm:debug -- --login=after

Change-Id: I80fc18ede446666738a8a274956dae8332f2fdf3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4509371
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>