Fix compile error due to new strnstr()
Remove local strnstr() implementation to fix compile error:

newlib/libc/iconv/lib/aliasesi.c:53:8: error: conflicting types for 'strnstr'
 _DEFUN(strnstr, (haystack, needle, length),
        ^
In file included from newlib/libc/iconv/lib/aliasesi.c:29:0:
newlib/libc/include/string.h:125:10:
 char    *strnstr(const char *, const char *, size_t) __pure;
          ^~~~~~~

Original-note: previous declaration of 'strnstr' was here
Original-Signed-off-by: Sebastian Huber <sebastian.huber@embedded-brains.de>
GitOrigin-RevId: f1863582eda80694f77a90ad21d5b2eb2be9b881
Cr-Build-Id: 8694333425744650289
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694333425744650289
Copybot-Job-Name: zephyr-project-picolibc-copybot-downstream
Change-Id: I9eac2dbc73279fddc7050458d76c6b3de260385f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7340562
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>