installer: Disallow chromeos-install.sh with args
The script no longer does any argument parsing, so to save folks
potential confusion: print a message if any args are passed.

BUG=b:356344778
TEST=(host)$ cros deploy vm chromeos-install
     (vm)$ /usr/sbin/chromeos-install
     > Running: FLAGS_debug="1" [...] "/usr/sbin/chromeos-install.sh"
     > Error: can not determine destination device. Specify --dst yourself.
     (vm)$ /usr/sbin/chromeos-install.sh
     > chromeos-install.sh shouldn't be called directly. Use chromeos-install.
     (vm)$ /usr/sbin/chromeos-install.sh --help
     > chromeos-install.sh shouldn't be called directly. Use chromeos-install.

Change-Id: Ie098de707a4eb8145460e8ac86c1a15667d17040
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/5830991
Reviewed-by: Nicholas Bishop <nicholasbishop@google.com>
Tested-by: Ted Brandston <tbrandston@google.com>
Commit-Queue: Ted Brandston <tbrandston@google.com>