debug: coredump: Fix build issue with armclang
Building tests/drivers/coredump/coredump_api with armclang gets:

include/zephyr/debug/coredump.h:98:2: error: unknown type name 'uint8_t'
        uint8_t *buffer;
        ^

Fix simply be including <stdint.h> to get uint8_t typedef.

(cherry picked from commit b0ea0c8ec6135aa5cb8d0e70ca72af2abe1f38fa)

Original-Original-Signed-off-by: Kumar Gala <kumar.gala@intel.com>
Original-GitOrigin-RevId: b0ea0c8ec6135aa5cb8d0e70ca72af2abe1f38fa
Original-Change-Id: I066acc930369e4d86eaad004249f2a893b88b6a9
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4350068
Original-Reviewed-by: Aaron Massey <aaronmassey@google.com>
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: 41243ae4487999925ee8ef13cb49b111a5a1da85
Cr-Build-Id: 8693323063598468129
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693323063598468129
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Id6ed446394de6026b914275cf024e573519aba52
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7410459
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>