chromeos-base/cros-config-api: Add missing protobuf dep
```
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/cros_config_host/cros_config_proto_converter.py", line 25, in <module>
    from chromiumos.build.api import firmware_config_pb2
  File "/usr/lib/python3.8/site-packages/chromiumos/build/api/firmware_config_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
```

```
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/cros_config_host/cros_config_proto_converter.py", line 38, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```

BUG=b:389666580
TEST=none

Change-Id: I5f65819e7812e29f9f56dd879fb2a0875d866fd9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/6180189
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Chao Gui <chaogui@google.com>
Auto-Submit: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Chao Gui <chaogui@google.com>
Tested-by: Chao Gui <chaogui@google.com>