virtual/bindgen: Have packages explicitly depend on bindgen
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CannotFindBinaryPath', build.rs:16:43
  stack backtrace:
     0: rust_begin_unwind
     1: core::panicking::panic_fmt
     2: core::result::unwrap_failed
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::bindings_generation
     5: build_script_build::main
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 * ERROR: dev-rust/vboot_reference-sys-9999::chromiumos failed (compile phase):
```

We need an explicit BDEPEND on bindgen so that the host tool gets pulled
in. Using a virtual with a BDEPEND doesn't work since the virtual could
be installed as a binpkg. We keep the virtual so we can revbump it and
cause the packages that depend on bindgen to rebuild.

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/dev-rust/vboot_reference-sys:9999

Change-Id: Idfc0f00f363316cdbf22923e629d19d0748d7cc1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4681914
Reviewed-by: Allen Webb <allenwebb@google.com>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Auto-Submit: Raul Rangel <rrangel@chromium.org>