chromeos-base/spaced: Add missing BDEPEND
```
FAILED: gen/include/spaced/dbus_adaptors/org.chromium.Spaced.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
[11/28] ACTION //spaced:spaced_proxy(//common-mk/toolchain:toolchain)
```
```
/build/arm64-generic/tmp/portage/chromeos-base/spaced-9999/temp/environment: line 4385: compile_seccomp_policy: command not found
* ERROR: chromeos-base/spaced-9999::chromiumos failed (install phase):
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/spaced:9999

Change-Id: I9450f7b756609108dbdfa95fb639346374439774
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692135
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>