configure.ac: fix sixaxis build without tools
Fix the following build failure with --enable-sixaxis --enable-udev
--disable-tools raised since version 5.73 and
9f71892b63f6b65dab874a633d88ae2dcad93a16:

sixaxis.c:(.text.sixaxis_init+0x23): undefined reference to `udev_new'

Fixes: http://autobuild.buildroot.org/results/c337d0f473c5fbb3e6cda1317ba06f5e2b16a43e