drivers: sai: Fix compile time error with clang
After commit 524b72ce40530 ("toolchain: llvm: Provide working
BUILD_ASSERT macro") when compiling with clang we have actual
checks and a real assert check using _Static_assert.

Now, when compiling with clang (used by Xtensa internal toolchain)
we get the following error.

$ zephyr/drivers/dai/nxp/sai/sai.c:968:29: error: static_assert expression
 is not an integral constant expression

We get this in asserts like this:

BUILD_ASSERT(SAI_DLINE_COUNT(inst) != -1, "...").

This expands to (reduced the macro to easier understand the context):

_Static_assert(((((((I2S_Type *)(uintptr_t)(1493499904U))) ==
((I2S_Type *)(0x59040000u)))

... and clang complains that this is not a constant expression.

So, in order to fix the compile time error remove the compile time
asserts and replace them with runtime checks.

BUILD_ASSERT macro")
(cherry picked from commit 54545430e467abee5d1442a330c2729a3a3dde98)

Original-Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
Original-Fixes: commit 524b72ce40530 ("toolchain: llvm: Provide working
GitOrigin-RevId: 54545430e467abee5d1442a330c2729a3a3dde98
Cr-Build-Id: 8701965728260108737
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8701965728260108737
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I0be84493ae0b808fc04ce00580b33da8c210cbed
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7009653
Reviewed-by: Keith Short <keithshort@chromium.org>
Commit-Queue: Keith Short <keithshort@chromium.org>
Tested-by: Keith Short <keithshort@chromium.org>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>