sw_isr_table: Add spaces to fix compiler warning
When using clang to build a C++ file that includes this file, it warns:

include/zephyr/sw_isr_table.h:195:28: error: invalid suffix on literal;
C++11 requires a space between literal and identifier
[-Wreserved-user-defined-literal]
         "." Z_STRINGIFY(prefix)"."file"." Z_STRINGIFY(counter)

(cherry picked from commit db726c40a96a8475dc6422530cade3fd1256eb64)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: db726c40a96a8475dc6422530cade3fd1256eb64
Cr-Build-Id: 8713358298138224881
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8713358298138224881
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ifcbdeef6d28741185a7f0c03deb0bd02e0eb2967
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6607899
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>