dev-util/bazel: Add missing BDEPEND
```
scripts/bootstrap/buildenv.sh: line 25: hash: which: not found
ERROR: cannot find "which"; check your PATH.
       You may need to run the following command or similar:
         export PATH="/bin:/usr/bin:$PATH"
 * ERROR: dev-util/bazel-6.2.0-r1::chromiumos failed (compile phase):
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/dev-util/bazel:6.2.0-r2

Change-Id: Ic6570cb38b9dc207564bf83616a66a03defb9261
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692248
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>