tests: work_queue: initialize msg
Make sure msg is initialized before being used, fixes compiler warning:

  main.c:735:9: error: 'msg' may be used uninitialized

(cherry picked from commit 7c231e3e271ab0525bbbf938dbab739b5a3bd274)

Original-Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-GitOrigin-RevId: 7c231e3e271ab0525bbbf938dbab739b5a3bd274
Original-Change-Id: I35bbf534defe070dfb3b3573265006b6edb54844
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3907809
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
GitOrigin-RevId: c330b4eb4ab9d689732e837b63233602481c62b1
Cr-Build-Id: 8693449691947151729
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693449691947151729
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I094fd7e787c0aaf433810b2324cb8fc6b415a22a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7401225
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>