chromeos-base/factory: Fix Dependencies
```
ERROR: python_setup: none of the enabled implementation matched the patterns.
```

Turns out that using `python-r1` is incorrect. `factory` can't use
multiple versions of python. i.e., it doesn't use `python_foreach_impl`.

Instead it only uses a single version of python, so switch to
`python-single-r1`. I'm honestly now sure how the factory scripts find
the correct python version since I don't see any calls to
`python_doexe`. See https://projects.gentoo.org/python/guide/helper.html

I'm also not sure if we really need `${PYTHON_DEPS}` in `DEPEND`. Does
the factory build package the python in the ROOT?

Anyway, this fixes a build failure with the bazel builds.

BUG=b:300087305
TEST=BOARD=amd64-generic ~/chromiumos/depot_tools/bazel build -k @portage//internal/packages/stage1/target/board/chromiumos/chromeos-base/factory_installer:0.0.1-r280_deps

Change-Id: I0b02c66bd74030f538d28d37f0b57263e93dd595
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4860987
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Auto-Submit: Raul Rangel <rrangel@chromium.org>