chromeos-base/cryptohome-dev-utils: Add missing BDEPENDs
```
FileNotFoundError: [Errno 2] No such file or directory: 'flatc'
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'

Traceback (most recent call last):
  File "gen/python/flatbuffer_cpp_binding_generator.py", line 87, in <module>
    from jinja2 import Template
ModuleNotFoundError: No module named 'jinja2'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/cryptohome-dev-utils:9999

Change-Id: I171279a2eb6f98088915a753fb18e8ae6a87104c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4787230
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>