modules: trusted-firmware-a: Disable AArch32 context for ARMv9-A
ARMv9-A is AArch64-only and does not support AArch32 execution states
at EL1/EL2/EL3. Configure TF-A build to disable AArch32 register
context (CTX_INCLUDE_AARCH32_REGS=0) when building for ARMv9-A platforms.

This fixes TF-A boot failures on ARMv9-A non-secure variants where
TF-A would panic with:
  ERROR: EL1 supports AArch64-only. Please set build flag
         CTX_INCLUDE_AARCH32_REGS = 0

(cherry picked from commit a479606c338360922e6cebfbefed0a30215b8682)

Original-Original-Signed-off-by: Nicolas Pitre <npitre@baylibre.com>
Original-GitOrigin-RevId: a479606c338360922e6cebfbefed0a30215b8682
Original-Cr-Build-Id: 8697820917959855649
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8697820917959855649
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I33cba9ce156d98900a312114105ac0a997c3ae62
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7171045
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 0f5339663fddbe925e7cd21daeba9832203a3088
Cr-Build-Id: 8692637872112448129
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692637872112448129
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Idc5f83adc2ebd4314fbd2e494afbed5cd0f4359e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7480719
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>