samples: modules: lvgl: transparency: Fix supported pixel format check
Found while building with clang and -Wtautological-compare:

samples/modules/lvgl/screen_transparency/src/main.c:47:45: error:
bitwise or with non-zero value always evaluates to true
[-Werror,-Wtautological-bitwise-compare]

if (!(display_caps.supported_pixel_formats | PIXEL_FORMAT_ARGB_8888)) {
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~

(cherry picked from commit 37deb317c5637aa917a4ed75317e80f89d4931dc)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: 37deb317c5637aa917a4ed75317e80f89d4931dc
Cr-Build-Id: 8725588887340772977
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8725588887340772977
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I74185d8f312c0b26e1e39b13292ae3e1105edc91
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6179518
Commit-Queue: Keith Short <keithshort@chromium.org>
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
Tested-by: Keith Short <keithshort@chromium.org>