init: adjust the SYS_INIT dev field init to play nice with older compilers
Fix a build error with certain older Cadence XCC toolchains. These
are used e.g. for Intel Tiger Lake products for the audio DSP (thhe oldest
platform supported in Zephyr upstream for the audio DSP).

To keep all compilers happy, use C89 style initializers.

lib/os/p4wq.c:216: error: unknown field ‘dev’ specified in initializer
lib/os/p4wq.c:216: warning: missing braces around initializer
lib/os/p4wq.c:216: warning: (near initialization for
  ‘__init_static_init.<anonymous>’)

Compiler version XCC RG-2017.8-linux (xt-xcc version 12.0.8)

in SYS_INIT macro")
(cherry picked from commit 19a33c7884134070ab9a13cf8112f5c8f81c5b94)

Original-Error:
Original-Original-Fixes: 2438dbb613731f ("init: add missing initialization of dev pointer
Original-Original-Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>
Original-GitOrigin-RevId: 19a33c7884134070ab9a13cf8112f5c8f81c5b94
Original-Change-Id: If82445c1f3c6f2e291623def5180793697fd42e2
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5240593
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Al Semjonovs <asemjonovs@google.com>
Original-Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
Original-Reviewed-by: Al Semjonovs <asemjonovs@google.com>
GitOrigin-RevId: 739f009a256d2f5c55fc83c3bf52f9d6460f4444
Cr-Build-Id: 8693086764068568289
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693086764068568289
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I6e0912b872673cdc3061c20589078c7d869defd4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7430926
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>