dome: Prevent some syntax error
Make some changes to avoid this error message:

```
export default red;
^^^^^^

SyntaxError: Unexpected token 'export'
```

BUG=None
TEST=make test

Change-Id: Ie7e89cb70219706157a6f3ca1408f69d182dd808
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/factory/+/6844458
Commit-Queue: Ruei-fong Lyu <rueifong@google.com>
Reviewed-by: Wen-Ting Tseng <wdzeng@chromium.org>
Tested-by: Ruei-fong Lyu <rueifong@google.com>