UPSTREAM: pw_toolchain/rust: Introduce support for alloc
There's support for stdlibs_none and stdlibs_core_only
essentially.  We need to support alloc too.  This
fixes a compile with the ARMv8 MCU target when it requires
alloc support.

error[E0463]: can't find crate for `alloc`
 --> external/rules_rust++crate+crates_no_std__allocator-api2-0.2.21/src/lib.rs:7:1
  |
7 | extern crate alloc as alloc_crate;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

BUG=453730584
TEST=compile library for ARMv8 MCU

(cherry picked from commit 4207a70b8f96867e7fed1803a079e9349f851ed1)

Original-Change-Id: I9fc9d0c022ed865bfea059e084cce8edc0b9f834
Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/354593
Original-Docs-Not-Needed: Armando Montanez <amontanez@google.com>
Original-Copybara-Verified: Copybara Prod <copybara-worker-blackhole@google.com>
Original-Reviewed-by: Erik Gilling <konkers@google.com>
Original-Pigweed-Auto-Submit: Gurchetan Singh <gurchetansingh@google.com>
Original-Docs-Not-Needed: Erik Gilling <konkers@google.com>
Original-Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Original-Commit-Queue: Gurchetan Singh <gurchetansingh@google.com>
GitOrigin-RevId: 4207a70b8f96867e7fed1803a079e9349f851ed1
Cr-Build-Id: 8695280428704307345
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8695280428704307345
Copybot-Job-Name: pigweed-main-copybot-downstream
Change-Id: Ib9bff789bb78feff2188097b9715d9b8981327db
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/pigweed/pigweed/+/7266057
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Commit-Queue: Jon Murphy <jpmurphy@google.com>
Reviewed-by: 488603086791@cloudbuild.gserviceaccount.com <488603086791@cloudbuild.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>