net: ethernet: Fix build without -fpermissive
Fix ethernet_hw_caps initialization in ethernet.h for
strict type checking.

g++-12: include/zephyr/net/ethernet.h:957:38: error: invalid \
 conversion from 'int' to 'ethernet_hw_caps' [-fpermissive]

(cherry picked from commit b4f940d654a223e8aaa283d74dddb4bdb554cf92)

Original-Signed-off-by: Daniel Nicoletti <dantti12@gmail.com>
GitOrigin-RevId: b4f940d654a223e8aaa283d74dddb4bdb554cf92
Cr-Build-Id: 8716039703355817313
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8716039703355817313
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I0a02fcea1a4c7831977ce08643a70fd054603780
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6507528
Reviewed-by: Keith Short <keithshort@chromium.org>
Tested-by: Keith Short <keithshort@chromium.org>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Keith Short <keithshort@chromium.org>