dev-util/intel_clc: fix build with glibc 2.43 / C23
intel_clc builds from the mesa release tarballs, so unlike the
cros-workon media-libs/mesa-* packages it does not pick up the
glibc 2.43 / C23 fixes that already landed on the chromeos-*
third_party/mesa branches.

Both SDK slots (:24.1 and :24.2), both required by
virtual/target-chromium-os-sdk) fail to compile:

  src/c11/threads.h:121:25: error: typedef redefinition with
    different types ("pthread_once_t" (aka "int") vs "__once_flag")
  src/util/blob.c:344:8: error: assigning to "uint8_t *" from
    "const void *" discards qualifiers

Add the four relevant upstream fixes as FILESDIR patches to both
versioned ebuilds. All four apply unmodified to the 24.1.1 and
24.2.3 tarballss.

BUG=b:491765858
TEST=emerge =dev-util/intel_clc-24.1.1-r2 =dev-util/intel_clc-24.2.3-r1

Change-Id: Ieeb953b9de1e9abadf20c266d9526c9234003d88
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/8355304
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Commit-Queue: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>
Reviewed-by: Juston Li <justonli@google.com>