lib/igt_aux: since procps-ng 4.0.5, PIDS_VAL() takes 3 arguments, not 4
Unfortunately, the API of procps-ng has changed between procps-ng
4.0.4 and procps-ng 4.0.5, with the PIDS_VAL() macro changing in
upstream commit
https://gitlab.com/procps-ng/procps/-/commit/967fdcfb06e20aad0f31073474cb94545c9bdea5
"library: expunge that 'info' parameter in 'VAL' macros"

This API breakage has been reported upstream as of
https://gitlab.com/procps-ng/procps/-/issues/366
but in the mean time, the build of igt-gpu-tools breaks with:

../lib/igt_aux.c:1358:78: error: macro "PIDS_VAL" passed 4 arguments, but takes just 3

We fix this by detecting the version of the libproc2 library, and
adjusting accordingly how PIDS_VAL() gets used.

Cc: DeX77 <dex@dragonslave.de>
Cc: Jim Warner <james.warner@comcast.net>
Closes: https://gitlab.freedesktop.org/drm/igt-gpu-tools/-/issues/164
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
Reviewed-by: Jonathan Cavitt <jonathan.cavitt@intel.com>