power_telemetry_utils.py: fix IndexError under NumpPy 1.24.4
Under NumPy 1.24.4, some tests in power_telemetry_utils_unittest.py fail due to
IndexError exceptions in power_telemetry_utils.py. For example:

ERROR: test_AcceptableNaNRatio (autotest_lib.client.cros.power.power_telemetry_utils_unittest.TestInterpolateData)
Validation succeeds if the ratio of NaN is below the threshold.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "[...]/autotest_lib/client/cros/power/power_telemetry_utils_unittest.py", line 66, in test_AcceptableNaNRatio
    interp_data = power_telemetry_utils.interpolate_missing_data(
  File "[...]/autotest_lib/client/cros/power/power_telemetry_utils.py", line 97, in interpolate_missing_data
    sample_idx = numpy.arange(len(data))[[~nan_data]]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

I hypothesize this is due to a difference in the new NumPy version, but I
haven't verified this.

In any case, the changes in this CL appear to prevent the aforementioned
errors.

BUG=b:362791706 b:318531403
TEST=First, run ebuild-amd64-generic /mnt/host/source/src/third_party/chromiumos-overlay/chromeos-base/autotest/autotest-0.0.2-r19435.ebuild test
TEST=Then, edit power_telemetry_utils.py in $S and repeat. Tests should pass.

Cq-Depend: chromium:5824154, chromium:5828104, chromium:5824664
Change-Id: Ib51f01ec3637382b8f5d7ba772f1eab9540ce7a8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/5829566
Reviewed-by: Derek Beckett <dbeckett@chromium.org>
Commit-Queue: Jack Rosenthal <jrosenth@chromium.org>
Tested-by: Leandro Lovisolo <lovisolo@google.com>
Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>