perror: fix POSIX compliance and work with recent newlib change
* cygtls.h (strerror_r_buf): New buffer.
* errno.cc (strerror): Move guts...
(_strerror_r): ...to new function demanded by newlib.
(strerror_r): Don't clobber strerror buffer.
(_user_strerror): Drop unused declaration.
* tlsoffsets.h: Regenerate.

GitOrigin-RevId: 154fa4d7ef23ee85e937ab6d1f1fab49dfb1872a
Cr-Build-Id: 8694380884400408737
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694380884400408737
Copybot-Job-Name: zephyr-project-picolibc-copybot-downstream
Change-Id: I5a4c7014b157ba4e2c0f04995b46f4eb95f1de17
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7334537
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>