libchrome.eclass: add perfetto to its DEPEND
Perfetto needs to be in the DEPEND of packages that use its function via
libchrome to avoid seeing different implementations from header includes
and using libbase-core. This is even worse when there is an API change
in the SDK like in https://github.com/google/perfetto/pull/1446.

Sample breakage:
https://ci.chromium.org/ui/p/chromeos/builders/zork/zork-cq/b8693188201492824337/overview
In step test_images/call_chromite.api.ImageService_Test:

AssertionError: ["File dir-ROOT-A/usr/bin/powerd contains unsatisfied
symbols:
{b'_ZN8perfetto8internal18TrackEventInternal13EnableTracingERKNS0_26TrackEventCategoryRegistryERKNS_6protos3gen16TrackEventConfigERKNS_14DataSourceBase9SetupArgsE',
...

Where the unsatisfied symbol
perfetto::internal::TrackEventInternal::EnableTracing(perfetto::internal::TrackEventCategoryRegistry
const&, perfetto::protos::gen::TrackEventConfig const&,
perfetto::DataSourceBase::SetupArgs const&) was removed and is missing in
libbase-core.so, but powerd that includes perfetto.h isn't rebuilt still
requires it.

BUG=b:429236971,b:465761228,b:471065324
TEST=CQ dry run

Change-Id: Ica87f3c0c2df60dabf2e9c4a8764fcd9e1bfb200
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/7414723
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Chinglin Yu <chinglinyu@chromium.org>
Tested-by: Chinglin Yu <chinglinyu@chromium.org>
Reviewed-by: Hanlin Chen <hanlinchen@google.com>