xtensa: gdbstub: fix compilation
Building gdbstub for xtensa is failing currently with multiple
failures like

arch/xtensa/core/gdbstub.c:432:24: error: invalid operands to \
binary - (have 'int *' and 'const struct arch_esf *')
  432 |         if ((int *)bsa - stack > 4) {

Fix them by using appropriate pointer types.

(cherry picked from commit 5769c4d5652e295bbcbeb72e76b370985aaab18b)

Original-Signed-off-by: Guennadi Liakhovetski <guennadi.liakhovetski@linux.intel.com>
GitOrigin-RevId: 5769c4d5652e295bbcbeb72e76b370985aaab18b
Cr-Build-Id: 8714943743272990721
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8714943743272990721
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I11573596b7cf54360cde2dd6f063beb0cf44a31a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6545075
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>