libec: fix test not compiling under bazel
Error before:

FAILED: obj/libec/libec_tests.ec_usb_device_monitor_test.o
x86_64-cros-linux-gnu-clang++ -MMD -MF obj/libec/libec_tests.ec_usb_device_monitor_test.o.d -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Igen/inclu
de -I../../../../../../../../../../mnt/host/source/src/platform2 -I/build/amd64-generic/usr/include -Wall -Wunused -Wbool-operation -Wfree-nonheap-object -Wint-in-bool-
context -Wstring-compare -Wstring-plus-int -Wxor-used-as-pow -Wdeprecated-declarations -Wno-c99-designator -Wno-unused-parameter -Wunreachable-code -Wunreachable-code-r
eturn -ggdb3 -fstack-protector-strong -Wformat=2 -fvisibility=internal -Wa,--noexecstack -Wimplicit-fallthrough -Werror -Wno-error=deprecated-enum-enum-conversion -Wno-
error=deprecated-this-capture -ftrivial-auto-var-init=pattern --sysroot=/build/amd64-generic -fPIE -DUSE_RTTI_FOR_TYPE_TAGS=1 -Wno-unused-local-typedefs -DBASE_VER=1193
442 -DBASE_USE_PERFETTO_CLIENT_LIBRARY -DPERFETTO_ENABLE_LEGACY_TRACE_EVENTS=1 -I/build/amd64-generic/usr/include/chromeos -I/build/amd64-generic/usr/include/libchrome
-I/build/amd64-generic/usr/include/glib-2.0 -I/build/amd64-generic/usr/lib64/glib-2.0/include -I/build/amd64-generic/usr/include/perfetto -I/build/amd64-generic/usr/inc
lude/nss -I/build/amd64-generic/usr/include/nspr -I/build/amd64-generic/usr/include/dbus-1.0 -I/build/amd64-generic/usr/lib64/dbus-1.0/include -I/build/amd64-generic/us
r/include/power_manager-client -I/build/amd64-generic/usr/include/libusb-1.0 -Wno-unused-local-typedefs -DBASE_VER=1193442 -DBASE_USE_PERFETTO_CLIENT_LIBRARY -DPERFETTO
_ENABLE_LEGACY_TRACE_EVENTS=1 -I/build/amd64-generic/usr/include/libchrome -I/build/amd64-generic/usr/include/dbus-1.0 -I/build/amd64-generic/usr/lib64/dbus-1.0/include
 -std=gnu++20 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -Os -pipe -march=x86-64 -msse3 -g -ffunction-sections -fdata-sections -march=corei7 -fno-
exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -c ../../../../../../../../../../mnt/host/source/src/platform2/libec/ec_usb_device_monitor_test.cc -o obj/
libec/libec_tests.ec_usb_device_monitor_test.o
../../../../../../../../../../mnt/host/source/src/platform2/libec/ec_usb_device_monitor_test.cc:5:10: fatal error: 'chromeos/dbus/service_constants.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Error after:

platform2_test.py: Unhandled exception:
Traceback (most recent call last):
  File "/mnt/host/source/src/platform2/common-mk/platform2_test.py", line 1167, in <module>
    commandline.ScriptWrapperMain(lambda _: main)
  File "/mnt/host/source/chromite/lib/commandline.py", line 1461, in ScriptWrapperMain
    ret = target(argv[1:])
  File "/mnt/host/source/src/platform2/common-mk/platform2_test.py", line 1163, in main
    getattr(p2test, options.action)()
  File "/mnt/host/source/src/platform2/common-mk/platform2_test.py", line 715, in run
    self._setup_sysroot()
  File "/mnt/host/source/src/platform2/common-mk/platform2_test.py", line 681, in _setup_sysroot
    self._setup_dev(new_sysroot)
  File "/mnt/host/source/src/platform2/common-mk/platform2_test.py", line 532, in _setup_dev
    os.mknod(
PermissionError: [Errno 1] Operation not permitted
platform2.py: Unhandled exception:
Traceback (most recent call last):
  File "/mnt/host/source/src/platform2/common-mk/platform2.py", line 892, in <module>
    commandline.ScriptWrapperMain(lambda _: main)
  File "/mnt/host/source/chromite/lib/commandline.py", line 1461, in ScriptWrapperMain
    ret = target(argv[1:])
  File "/mnt/host/source/src/platform2/common-mk/platform2.py", line 888, in main
    getattr(p2, options.action)(options.args)
  File "/mnt/host/source/src/platform2/common-mk/platform2.py", line 663, in test_all
    cros_build_lib.run(test_options, encoding="utf-8")
  File "/mnt/host/source/chromite/lib/cros_build_lib.py", line 952, in run
    raise RunCommandError(msg, cmd_result)
chromite.lib.cros_build_lib.RunCommandError: return code: 1; command: /mnt/host/source/src/platform2/common-mk/platform2_test.py '--action=run' '--sysroot=/build/amd64-
generic' '--strategy=sudo' '--jobs=32' -- /build/amd64-generic/tmp/portage/chromeos-base/libec-9999/work/build/out/Default/libec_tests
cmd=['/mnt/host/source/src/platform2/common-mk/platform2_test.py', '--action=run', '--sysroot=/build/amd64-generic', '--strategy=sudo', '--jobs=32', '--', '/build/amd64
-generic/tmp/portage/chromeos-base/libec-9999/work/build/out/Default/libec_tests']
 * ERROR: chromeos-base/libec-9999::chromiumos failed (test phase):

BUG=none
TEST=BOARD=amd64-generic bazel test @portage//chromeos-base/libec:test

Change-Id: I3a990a6e906b08c0651c1db3cc9003f6d445a875
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4851490
Reviewed-by: Bobby Casey <bobbycasey@google.com>
Commit-Queue: Tomasz Tylenda <ttylenda@chromium.org>
Reviewed-by: Firas Sammoura <fsammoura@google.com>
Tested-by: Tomasz Tylenda <ttylenda@chromium.org>
Reviewed-by: Shuhei Takahashi <nya@chromium.org>