chromeos-base/minijail: Add missing RDEPEND
Setuptools also needs to be an RDEPEND.

```
FAILED: gen/mojo_service_manager/init/seccomp/mojo_service_manager.bpf
/usr/bin/env /usr/bin/compile_seccomp_policy --arch-json /build/arm64-generic/build/share/constants.json ../../../../../../../../../../mnt/host/source/src/platform2/mojo_service_manager/init/seccomp/arm64/mojo_service_manager.policy /build/arm64-generic/tmp/portage/chromeos-base/mojo_service_manager-9999/work/build/out/Default/gen/mojo_service_manager/init/seccomp/mojo_service_manager.bpf
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/compile_seccomp_policy", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/minijail:9999

Change-Id: Ia8fa5fef232871768ca969f449b74b3cd0500560
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692113
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>