soc: silabs_exx32: define an empty pm_state_exit_post_ops
Some EFR32 build broke after 3d2194f11e with:

pm.c:152: undefined reference to `pm_state_exit_post_ops'

Add an extra empty function to make this one build again.

(cherry picked from commit e065e5c600e4e9416cf51a5aa023727b0c6253e2)

Original-Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-GitOrigin-RevId: e065e5c600e4e9416cf51a5aa023727b0c6253e2
Original-Change-Id: I63c68ad1d8c9d97ba4440006b30cd956e96d878a
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4715065
Original-Reviewed-by: Yuval Peress <peress@google.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Yuval Peress <peress@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 9f802df5e25c0e544621c0426ca8c2239c47a16e
Cr-Build-Id: 8693182501767684353
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693182501767684353
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I67ac45db0570d4ba57d2a2dc9e4152ef4da4725a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7420422
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>