scripts: west_commands: patch: capture subprocess output in apply() method
Pass 'capture_output=True' to the 'subprocess.run()' call in the 'apply()'
method.
This ensures that stdout and stderr are captured, so 'proc.stderr'
is not 'None' when 'self.err()' is called on a failed process.

Example without this patch:
west patch apply --roll-back
FATAL ERROR: failed to apply patch libcsp/test.patch

Example with this patch:
west patch apply --roll-back
FATAL ERROR: failed to apply patch libcsp/test.patch

(cherry picked from commit 634b45edddd55a923a74f923cf2d3c0540a5bfb0)

Original-Original-error: patch failed: examples/csp_server_client.py:32
Original-Original-error: examples/csp_server_client.py: patch does not apply
Original-Original-ERROR: None
Original-Original-ERROR: b'error: patch failed: examples/csp_server_client.py:32\n
Original-Original-error: examples/csp_server_client.py: patch does not apply\n'
Original-Original-Signed-off-by: Mirai SHINJO <oss@mshinjo.com>
Original-GitOrigin-RevId: 634b45edddd55a923a74f923cf2d3c0540a5bfb0
Original-Cr-Build-Id: 8697956813069601489
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8697956813069601489
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I8686ec9b052d644de880c3828077bc8e9e6f815f
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7159640
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: a61da242173e5a44308bc6c2c234f8d8f8366f3d
Cr-Build-Id: 8692642471503419777
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692642471503419777
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ibb27abefa55241747ce14428da4fa7f35566bb76
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7480344
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>