chromeos-base/missive: Add missing BDEPEND
```
FAILED: gen/include/dbus_adaptors/org.chromium.Missived.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'

FAILED: gen/include/missive/proto/status.pb.cc gen/include/missive/proto/status.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/missive:9999

Change-Id: Iba91a8ed74af346096e1f90e386309f40f80baab
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692114
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>