pinmux: Fix using wrong variable name
In the pinmux_dev driver for the Quark SE development board in
pinmux_dev_set() the variable 'mode' was used, but it should have been
'func'. This was causing a compilation error:

/home/vinicius/work/zephyr/boards/quark_se_devboard/pinmux.c:
In function 'pinmux_dev_set':
/home/vinicius/work/zephyr/boards/quark_se_devboard/pinmux.c:245:23:
  uint32_t mode_mask = mode << (pin_no << 1);

Original-error: 'mode' undeclared (first use in this function)
Original-Change-Id: I5b9df7c6b488dc5b8819fcf59bb3b994d9d4820b
Original-Signed-off-by: Vinicius Costa Gomes <vinicius.gomes@intel.com>
GitOrigin-RevId: 0efdb22ae5eb3770ec9381994aa6122d15acf014
Cr-Build-Id: 8694799605735196641
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694799605735196641
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I0890caaec9ca23d658906daa19ef9ae18eae2a9c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7298675
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>