drivers: crypto_mbedtls_shim: Fix build with Clang/LLVM
drivers/crypto/crypto_mbedtls_shim.c:310:3: error: label followed by a
declaration is a C23 extension [-Werror,-Wc23-extensions]
                 uint16_t tag_len = ctx->mode_params.ccm_info.tag_len;
                 ^

(cherry picked from commit 69946a1253db1326a06e73303d79b8ec652a90f4)

Original-Signed-off-by: Johan Hedberg <johan.hedberg@silabs.com>
GitOrigin-RevId: 69946a1253db1326a06e73303d79b8ec652a90f4
Cr-Build-Id: 8696326068362242273
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8696326068362242273
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ic0ba30b81c531ccddb9b18a6ae3d4b929d8a2c0f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7231820
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>