chromeos-base/chromeos-chrome: Add missing BDEPEND
```
FAILED: gen/third_party/blink/renderer/platform/color_data.cc
FileNotFoundError: [Errno 2] No such file or directory: 'gperf': 'gperf'
```

```
  File "/home/root/chrome_root/src/third_party/mako/mako/mako/compat.py", line 68, in <module>
    import importlib_metadata  # noqa
ModuleNotFoundError: No module named 'importlib_metadata'
```

```
FAILED: nacl_helper_arm32/obj/base/third_party/double_conversion/double_conversion/string-to-double.o
armv7a-cros-linux-gnueabihf-clang++ -MMD -MF nacl_helper_arm32/obj/base/third_party/double_conversion/double_conversion/string-to-double.o.d
../../../../../../../home/root/chrome_root/src/buildtools/third_party/libc++/trunk/include/__config:283:14: fatal error: 'features.h' file not found
```

```
../../../../../../../home/root/chrome_root/src/third_party/skia/src/ports/SkFontConfigInterface_direct.h:14:10: fatal error: 'fontconfig/fontconfig.h' file not found
```

```
../../../../../../../home/root/chrome_root/src/net/http/http_auth_gssapi_posix.h:26:10: fatal error: 'gssapi.h' file not found
```

```
  File "/build/arm64-generic/tmp/portage/chromeos-base/chromeos-chrome-117.0.5859.0_rc-r1/work/autotest-work/autotest_lib/client/bin/utils.py", line 16, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'
```

```
/build/arm64-generic/tmp/portage/chromeos-base/chromeos-chrome-117.0.5859.0_rc-r1/temp/environment: line 1885: git: command not found
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/chromeos-chrome:117.0.5859.0_rc-r1

Change-Id: Idcce4742889f84738c9c761b6d93ac2d94df699b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692258
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>