modem_shell: fix compilation error.
fix error: 'struct modem_shell_user_data' has no member named 'shell'

(cherry picked from commit a0418f18219750138f1a4497bcbed9e51cf75069)

Original-Signed-off-by: Mark Kettner <mark@kettner.io>
GitOrigin-RevId: a0418f18219750138f1a4497bcbed9e51cf75069
Change-Id: Id31efff44bd11ef0dd7d3dbbc1272e0c1480baca
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4645593
Tested-by: Keith Short <keithshort@chromium.org>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Keith Short <keithshort@chromium.org>
Commit-Queue: Keith Short <keithshort@chromium.org>