Autoupdate of 2 submodules
*chromite updated to 7ceb0fec850a7a1d96492f369cc079698ee884f6
cli: device_imager: Fix {pid} reference

If we terminate (_ShouldExit()) the previous loop, we won't have |pid|
set, and we'll fail the next formatting line with:

  NameError: name 'pid' is not defined.

Exit early like intended.

BUG=none
TEST=none

Change-Id: I3a8cca2e73e188f9e859cfc1bdccdaffdcb46015
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4283088
Reviewed-by: Jae Hoon Kim <kimjae@chromium.org>
Commit-Queue: Brian Norris <briannorris@chromium.org>
Tested-by: Brian Norris <briannorris@chromium.org>

*infra/chromite-HEAD updated to 7ceb0fec850a7a1d96492f369cc079698ee884f6
cli: device_imager: Fix {pid} reference

If we terminate (_ShouldExit()) the previous loop, we won't have |pid|
set, and we'll fail the next formatting line with:

  NameError: name 'pid' is not defined.

Exit early like intended.

BUG=none
TEST=none

Change-Id: I3a8cca2e73e188f9e859cfc1bdccdaffdcb46015
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4283088
Reviewed-by: Jae Hoon Kim <kimjae@chromium.org>
Commit-Queue: Brian Norris <briannorris@chromium.org>
Tested-by: Brian Norris <briannorris@chromium.org>