UPSTREAM: util/cbmem/sysfs_drv: Fix incompatible pointer type for 'size'
Fix the following error for armv7a-cros-linux-gnueabihf-clang.

sysfs_drv.c:247:49: error: incompatible pointer types passing 'uint64_t *' (aka
      'unsigned long long *') to parameter of type 'size_t *'
      (aka 'unsigned int *') [-Werror,-Wincompatible-pointer-types]
  247 |                 if (!cbmem_sysfs_probe_cbmem_entry(id, &addr, &size))
      |                                                               ^~~~~
sysfs_drv.c:99:84: note: passing argument to parameter 'size_out' here
   99 |   ...id, uint64_t *addr_out, size_t *size_out)
      |                                      ^
1 error generated.

BUG=b:434971585
TEST=none
BRANCH=none

(cherry picked from commit 54016e273e2edeb186490a403b7be5d443e6bd3b)

Original-Change-Id: I5e2be25d57c5e69501564b6e8b6d880ec046bc3b
Original-Signed-off-by: Yu-Ping Wu <yupingso@chromium.org>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/88605
Original-Reviewed-by: Paul Menzel <paulepanter@mailbox.org>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: 54016e273e2edeb186490a403b7be5d443e6bd3b
Cr-Build-Id: 8707866718850028913
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8707866718850028913
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I8c3b9ca46eec6e259f4fe45612d3657f2c111e1d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6804747
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>