chromeos-base/dns-proxy: Add missing DEPEND
```
FAILED: gen/include/dns-proxy/ipc.pb.cc gen/include/dns-proxy/ipc.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
/build/arm64-generic/etc/portage/hooks/install/check-seccomp.sh: line 27: compile_seccomp_policy: command not found
 * ERROR: chromeos-base/dns-proxy-9999::chromiumos failed:
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/dns-proxy:9999

Change-Id: I0cc2ce634d1c296abe7f10accfe090bada480ae3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692098
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>