UPSTREAM: pw_span: Cast (end - begin) to size_t
This avoids the following error under some conditions:

implicit conversion changes signedness: 'long' to 'size_t'

pw_span/internal/span_impl.h:265:63: error: implicit conversion changes signedness: 'long' to 'size_t' (aka 'unsigned long') [-Werror,-Wsign-conversion]
  265 |   constexpr span(T* begin, T* end) noexcept : span(begin, end - begin) {
      |                                               ~~~~        ~~~~^~~~~~~

(cherry picked from commit fa3b9d9ba6c3642dbafca9d78c14813f15677b76)

Original-Bug: 448746326
Original-Change-Id: I5344d9aa80449c8a44b858f8aa9a4ea4f81925c1
Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/328272
Original-Reviewed-by: Wyatt Hepler <hepler@google.com>
Original-Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Original-Tests-Not-Needed: Jonathon Reinhart <jrreinhart@google.com>
Original-Commit-Queue: Jonathon Reinhart <jrreinhart@google.com>
Original-Docs-Not-Needed: Jonathon Reinhart <jrreinhart@google.com>
GitOrigin-RevId: fa3b9d9ba6c3642dbafca9d78c14813f15677b76
Cr-Build-Id: 8702075199003587457
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8702075199003587457
Copybot-Job-Name: pigweed-main-copybot-downstream
Change-Id: I71c6ad6c2f824986b93bb7b8ecc6bd166dee8597
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/pigweed/pigweed/+/7003290
Tested-by: Rob Barnes <robbarnes@google.com>
Reviewed-by: Rob Barnes <robbarnes@google.com>
Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Tested-by: Al Semjonovs <asemjonovs@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>