media-libs/virglrenderer: Add a missing dependency
virglrenderer needs EGL/elgplatform.h, which is provided by
x11-drivers/opengles-headers.

In file included from ../virglrenderer-0.8.2/src/vrend_renderer.c:50:
In file included from ../virglrenderer-0.8.2/src/vrend_winsys.h:32:
In file included from ../virglrenderer-0.8.2/src/vrend_winsys_egl.h:30:
In file included from /build/amd64-generic/usr/include/epoxy/egl.h:46:
/build/amd64-generic/usr/include/epoxy/egl_generated.h:11:10:
fatal error: 'EGL/eglplatform.h' file not found
         ^~~~~~~~~~~~~~~~~~~

  1 error generated.

Cherry-picked from http://tg/1773184

BUG=b:263139238
BUG=b:262460834
TEST=BOARD=amd64-generic bazel build @portage//media-libs/virglrenderer

Change-Id: I32d7c7015d1c270e4adf53984a853dc90f0d4b13
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4495889
Auto-Submit: Shuhei Takahashi <nya@chromium.org>
Commit-Queue: Shuhei Takahashi <nya@chromium.org>
Reviewed-by: Yiwei Zhang <zzyiwei@chromium.org>
Reviewed-by: Raul Rangel <rrangel@chromium.org>
Tested-by: Shuhei Takahashi <nya@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>