chromeos-base/libhwsec: Add missing BDEPEND
```
FAILED: gen/python/reflection_generated.h
FileNotFoundError: [Errno 2] No such file or directory: 'flatc'
```

```
FAILED: gen/include/libhwsec/frontend/oobe_config/encrypted_data.pb.cc gen/include/libhwsec/frontend/oobe_config/encrypted_data.pb.h 
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
FAILED: gen/include/libhwsec/structures/signature_sealed_data.h gen/include/libhwsec/structures/signature_sealed_data_flatbuffer.h gen/include/libhwsec/structures/signature_sealed_data.cc gen/include/libhwsec/structures/signature_sealed_data_test_utils.h
ModuleNotFoundError: No module named 'jinja2'
```

```
FAILED: gen/include/libhwsec/structures/signature_sealed_data.h gen/include/libhwsec/structures/signature_sealed_data_flatbuffer.h gen/include/libhwsec/structures/signature_sealed_data.cc gen/include/libhwsec/structures/signature_sealed_data_test_utils.h 
ModuleNotFoundError: No module named 'flatbuffers'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/libhwsec:9999

Change-Id: I359b329a7edfa1f690111ffa0adbb53b0cfd6342
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692107
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>