drivers: sensor: bmp581: ifdef static function
So it is only built when needed, and we avoid a compiler warning:
bmp581.c:59:19: error: unused function 'bmp581_pm_busy_check'

The issue was there since c68a25e4d531462505eaf4e9f45c1d31a311088b
but only became apparent in CI when its test was added in
f0802b645b6ad215af05adbde72ab35333834191

Original-Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
GitOrigin-RevId: 8994f40014c9977a8fcacccd1c34adc2ebce1a4b
Cr-Build-Id: 8675647309988525249
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8675647309988525249
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I95e827f8a86a15fddbacd069586bb9aea5335442
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/8131579
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Rob Barnes <robbarnes@google.com>
Tested-by: Rob Barnes <robbarnes@google.com>
Reviewed-by: Rob Barnes <robbarnes@google.com>