incremental-cargo-update: run cargo-update
New versions of this no longer build

```
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/gbiv/.cargo/[...]/proc-macro2-1.0.49/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
```

Update everything while I'm at it.

BUG=b:264463632
TEST=cargo build --release

Change-Id: Iecfa5671229a4f1534be82cb2b0ee207696257d5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/rust_crates/+/5232186
Auto-Submit: George Burgess <gbiv@chromium.org>
Tested-by: George Burgess <gbiv@chromium.org>
Reviewed-by: Allen Webb <allenwebb@google.com>
Commit-Queue: George Burgess <gbiv@chromium.org>