tests/msm/msm_perfcntrs: Fix compilation break
I used checkpatch script for fixes and forgot to check compilation
after, it added 'void' to igt_main and it caused fail with:

../tests/msm/msm_perfcntrs.c:64:18: error: macro "igt_main" passed 1 arguments, but takes just 0
   64 | int igt_main(void)

Fix it by removing unneeded 'void'.

Signed-off-by: Kamil Konieczny <kamil.konieczny@linux.intel.com>
Reviewed-by: Zbigniew Kempczyński <zbigniew.kempczynski@intel.com>