tests: mgmt: mcumgr: Disable clang warning
When building with clang it reports:

tests/subsys/mgmt/mcumgr/settings_mgmt/src/main.c:69:22: error: variable
'test_response_read_data_start' is not needed and will not be emitted
[-Werror,-Wunneeded-internal-declaration]
static const uint8_t test_response_read_data_start[5] = {
                     ^
tests/subsys/mgmt/mcumgr/settings_mgmt/src/main.c:73:22: error: variable
'test_response_read_data_end' is not needed and will not be emitted
[-Werror,-Wunneeded-internal-declaration]
static const uint8_t test_response_read_data_end[1] = {
                     ^

The values of test_response_read_data_start and
test_response_read_data_end are not actually used anywhere in the tests.

(cherry picked from commit 11e3aa89521c7d59b3929b8381c7ab395f743ccc)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 11e3aa89521c7d59b3929b8381c7ab395f743ccc
Original-Cr-Build-Id: 8718567623776601377
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8718567623776601377
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I5fecb8c8907ed2787bbbcf981e3e22414a8e6721
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6432110
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: d70046e6e66c9498324ee2eb87f6e302b5ccb8bc
Cr-Build-Id: 8692820791692617393
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692820791692617393
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ie8707ae74ab8156402b23101216d7397b49dcae2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7460491
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>