trunks: Add missing BDEPEND for go bindings
Fix the error in Bazel builds:

/usr/bin/env ../../../../../../../tmp/portage/chromeos-base/trunks-0.0.1-r3725/work/trunks-0.0.1/common-mk/file_generator_wrapper.py go-generate-chromeos-dbus-bindings -adaptor=/build/amd64-generic/var/cache/portage/chromeos-base/trunks/out/Default/gen/include/trunks/dbus_adaptors/org.chromium.Trunks.h -service-config=/build/amd64-generic/tmp/portage/chromeos-base/trunks-0.0.1-r3725/work/trunks-0.0.1/trunks/dbus_bindings/dbus-service-config.json ../../../../../../../tmp/portage/chromeos-base/trunks-0.0.1-r3725/work/trunks-0.0.1/trunks/dbus_bindings/org.chromium.Trunks.xml
Traceback (most recent call last):
  File "../../../../../../../tmp/portage/chromeos-base/trunks-0.0.1-r3725/work/trunks-0.0.1/common-mk/file_generator_wrapper.py", line 19, in <module>
    subprocess.check_call(sys.argv[1:])
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'

This seems to appear after crrev.com/c/5171634.

BUG=b:319618238,b:235569085
TEST=none

Change-Id: I0f509bf9291dc6cf21b944a310f2724591e254aa
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/5189386
Tested-by: Maksim Ivanov <emaxx@chromium.org>
Commit-Queue: Maksim Ivanov <emaxx@chromium.org>
Reviewed-by: Yi Chou <yich@google.com>
Auto-Submit: Maksim Ivanov <emaxx@chromium.org>
Commit-Queue: Yi Chou <yich@google.com>