WebSQL: Update policy expiration
Fix of reverted CL https://crbug.com/326228129
which broke the build. This change adds required changes
to configuration_policy_handler_list_factory.cc

Error: chrome/browser/policy/configuration_policy_handler_list_factory.cc:2020:5: error: no member named 'kWebSQLAccess' in namespace 'policy::key'

Bug: 326228129
Change-Id: I62c854b68f8f6ff7cc128b9afa1a34df1a6652c8
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5314242
Reviewed-by: Anqing Zhao <anqing@chromium.org>
Commit-Queue: Ayu Ishii <ayui@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1263588}
NOKEYCHECK=True
GitOrigin-RevId: ca80ca4a7cefa496d2495153b5a152eefc93b4f8