sci-libs/tensorflow: Add missing BDEPEND
```
/build/arm64-generic/tmp/portage/sci-libs/tensorflow-2.8.0-r23/temp/environment: line 1801: envsubst: command not found
```

```
Error in fail: Repository command failed
src/main/tools/process-wrapper-legacy.cc:80: "execvp(which, ...)": No such file or directory
```

```
Error in fail: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
```

```
which: no flatc in (/build/arm64-generic/tmp/portage/sci-libs/tensorflow-2.8.0-r24/temp/python3.6/bin:...
```

dev-libs/gcc is required because cros-bazel passes the `gconv` command
into the bazel config.

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/sci-libs/tensorflow:2.8.0-r24

Change-Id: Ia486de06de27919ca43a35ad965a813d97e97118
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692254
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>