soc: npcx: Add __packed to flags struct in npcx_pinctrl
When building with clang and CONFIG_LTO, clang warns:

soc/nuvoton/npcx/common/pinctrl_soc.h:141:4: error: field flags within
'struct npcx_pinctrl' is less aligned than 'struct (unnamed struct at
soc/nuvoton/npcx/common/./pinctrl_soc.h:128:2)' and is usually due to
'struct npcx_pinctrl' being packed, which can lead to unaligned accesses
[-Werror,-Wunaligned-access]
         } flags;
           ^

(cherry picked from commit 94edd9723318779e490501811a30938437a0b34d)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: 94edd9723318779e490501811a30938437a0b34d
Cr-Build-Id: 8713109155270078145
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8713109155270078145
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I724b4358a84a79ed6a6430b0e9228fe8e6da5224
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6615540
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>