chromeos-base/regions: Add missing BDEPEND and die calls
```
17:54:47.445 >>> Compiling source in /mnt/host/source/src/platform2/regions ...
Traceback (most recent call last):
  File "./regions.py", line 20, in <module>
    import yaml  # pylint: disable=import-error
ModuleNotFoundError: No module named 'yaml'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/regions:9999

Change-Id: I17e47e5222b62604fffac090e4152ebfdd657eb7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692126
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>