manifest: Update hostap to fix build error
Fix build error of undefined reference to 'inet_aton' in
hostap/src/utils/ip_addr.c

(cherry picked from commit 244958c9f482ab0980da07d7565bd86cca377ed7)

Original-Signed-off-by: Maochen Wang <maochen.wang@nxp.com>
GitOrigin-RevId: 244958c9f482ab0980da07d7565bd86cca377ed7
Cr-Build-Id: 8733565196572304993
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8733565196572304993
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I5a77f61d19bb9ab951d309c936cdc9486d628a51
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5937727
Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Commit-Queue: Eric Yilun Lin <yllin@google.com>