lib: libc: arcmwdt: fix typedef redefinitions with MWDT toolchain
The MWDT toolchain defines clockid_t as int in its <time.h>, pid_t
as long and uid_t as long in its <sys/types.h>. Zephyr's POSIX
headers redefine these with different underlying types, causing:

  error: typedef redefinition with different types

Fix by including <sys/types.h> early in the arcmwdt <time.h> and
<signal.h> wrappers so that the MWDT type guard macros are set
before posix_time.h and posix_signal.h attempt to define those
types. Also set _PID_T_DECLARED in the arcmwdt <sys/types.h>
wrapper to suppress the conflicting Zephyr pid_t definition.

Original-Signed-off-by: Mohamed Moawad <moawad@synopsys.com>
GitOrigin-RevId: 865124768bf8c6be2f1dbddaa55dddf918f6589e
Cr-Build-Id: 8680083166403963553
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8680083166403963553
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I34aaf4a1f6b81d63f729815104a2465aecc02fbe
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7895252
Bot-Commit: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>