chromeos-base/chromeos-machine-id-regen: Add missing BDEPEND
```
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
 * ERROR: chromeos-base/chromeos-machine-id-regen-9999::chromiumos failed (compile phase)
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/chromeos-machine-id-regen:9999

Change-Id: I7df69e739a78859bfc3fa2e1ddf824e34e76f52f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4836961
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>