chromeos-base/usb_bouncer: Add missing BDEPEND
```
FAILED: gen/include/usb_bouncer/usb_bouncer.pb.cc gen/include/usb_bouncer/usb_bouncer.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
/build/arm64-generic/etc/portage/hooks/install/check-seccomp.sh: line 27: compile_seccomp_policy: command not found
 * ERROR: chromeos-base/usb_bouncer-9999::chromiumos failed:
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/usb_bouncer:9999

Change-Id: Ib5b4e62c73150951b21961b38e9060114e890c42
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692143
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>