zbus: fix error on ZBUS_CHAN_DEFINE
There appear error on `ZBUS_CHAN_DEFINE` when `CONFIG_CPP`
is enabled. Error: `zephyr/zbus/zbus.h:352:9: error: designator
order for field 'zbus_channel_data::highest_observer_priority'
does not match declaration order in `zbus_channel_data`.

to zbus_channel_data structure.

(cherry picked from commit b7bf2091f8e9db5ba1692387ded2cb47b3720aeb)

Original-Solution: change order in `ZBUS_CHAN_DEFINE` macro according
Original-Signed-off-by: Mariusz Dziębowski <mdziebowski@meden.com.pl>
GitOrigin-RevId: b7bf2091f8e9db5ba1692387ded2cb47b3720aeb
Cr-Build-Id: 8738366835818535617
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8738366835818535617
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I450150ab0c5eeac248b64cb17057c36f8057c03c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5822405
Commit-Queue: Ting Shen <phoenixshen@chromium.org>
Tested-by: Ting Shen <phoenixshen@chromium.org>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Ting Shen <phoenixshen@chromium.org>