sys-devel/llvm: Add missing dep
    /build/amd64-host/tmp/portage/sys-devel/llvm-16.0_pre484197_p20230405-r1/work/llvm-16.0_pre484197_p20230405/llvm/lib/Support/Compression.cpp:24:10: fatal error: 'zstd.h' file not found
    #include <zstd.h>
             ^~~~~~~~
    1 error generated.

BUG=b:278728702
TEST=BOARD=amd64-host bazel run --//bazel/sdk:new-sdk @portage//sys-devel/llvm:debug -- --login=after

Change-Id: Icecd2f141edbd0e58d1edd0a2819ea82f41cd179
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4509370
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>