CHROMIUM: media: camx: cam_isp: Fix conflicting type
BUG=none
TEST=make C=1 W=1
UPSTREAM-TASK=b:274966069

error: conflicting types for ‘cam_ife_csid_enable_soc_resources’ due to enum/integer mismatch; have ‘int(struct cam_hw_soc_info *, enum cam_vote_level)’ [-Werror=enum-int-mismatch]
  110 | int cam_ife_csid_enable_soc_resources(

Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
Change-Id: I1ba84556586448c203830e6e7b8dfc715138a586
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4921751
Reviewed-by: Sergey Senozhatsky <senozhatsky@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>
(cherry picked from commit f43c159b59bd26a719e18860c349667f653898e4)
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4926209