trace_event: trace_arguments: fix risky memcpy
Glibc 2.41 improved its headers fortify checks and one
of the checks added is for memcpy on complex structs,
which are considered inherently risky, and should be
avoided (in this case it's a class).

Therefore replace the top-level memcpy of the entire
struct with memcpy of its members (trivial types) and
a move of its TraceValue struct.

The error is:
/build/asurada/usr/include/libchrome/base/trace_event/trace_arguments.h:656:14: error: first argument in call to 'memcpy' is a pointer to non-trivially copyable type 'base::trace_event::TraceArguments' [-Werror,-Wnontrivial-memcall]
  656 |     ::memcpy(this, &other, sizeof(*this));
      |              ^
/build/asurada/usr/include/libchrome/base/trace_event/trace_arguments.h:656:14: note: explicitly cast the pointer to silence this warning
  656 |     ::memcpy(this, &other, sizeof(*this));
      |              ^
      |              (void*)
1 error generated.

BUG=b:387993322
TEST=cros-workon-asurada start libchrome; emerge libvda-gpu-tests.

Change-Id: I3e48c500171c851a59ad111a20bef40ab34af24b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/libchrome/+/6632927
Reviewed-by: Jae Hoon Kim <kimjae@chromium.org>
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>
Commit-Queue: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>