Revert "Remove backward-compatibility-3300-Restore-base-JsonReader-default-params.patch"
This reverts commit 8956a1d149c214dbcca3f2ffeec228459c3c89f0.

Reason for revert: Some tests still use default params
Example Error
```
../../../../../../../../../mnt/host/source/src/platform2/runtime_probe/functions/ec_component_test.cc:424:9: error: too few arguments to function call, expected at least 2, have 1
  419 |   auto arguments = base::JSONReader::Read(R"JSON(

```
Example failure:
https://ci.chromium.org/ui/p/chromeos/builders/postsubmit/amd64-generic-asan-snapshot/62030/overview

Original change's description:
> Remove backward-compatibility-3300-Restore-base-JsonReader-default-params.patch
>
> BUG=b:448525509
> TEST=CQ
>
> Cq-Depend: chromium:6999136, chromium:7005905
> Change-Id: I432affc1279c42d8a5f57fb8a29c4adc6f43c8eb
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/libchrome/+/7005407
> Tested-by: Ryo Hashimoto <hashimoto@chromium.org>
> Commit-Queue: Ryo Hashimoto <hashimoto@chromium.org>
> Reviewed-by: Di Wu <diwux@google.com>

BUG=b:448525509
No-Presubmit: true
No-Tree-Checks: true
No-Try: true

Change-Id: I66afdc8c2efc3ed886b80dc72af8a61bedcd7eb7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/libchrome/+/7021936
Owners-Override: Fahad Mansoor <fahadmansoor@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Fahad Mansoor <fahadmansoor@google.com>