chromeos-base/tpm_manager: Add missing BDEPEND
```
FAILED: gen/include/tpm_manager/server/legacy_local_data.pb.cc gen/include/tpm_manager/server/legacy_local_data.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
/build/arm64-generic/etc/portage/hooks/install/check-seccomp.sh: line 27: compile_seccomp_policy: command not found
 * ERROR: chromeos-base/tpm_manager-9999::chromiumos failed:
```

I didn't save the dbus binding error, but it needs it :)

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/tpm_manager:9999

Change-Id: I2cd607874d7aaf8cab7719d43e648dcd6eb372a4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692139
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>