UPSTREAM: mb/ocp/tiogapass: Fix build failure
Add console.c to SMM stage as well. Fixes the build failure:
"undefined reference to `get_uart_baudrate'" when CONFIG_DEBUG_SMI
is set.

(cherry picked from commit 50905e7cdc9f0030cdeec6ab0eb70128bacc15e0)

Original-Change-Id: I2587287b0074a56c49b7434553c69cae97aaa1b4
Original-Signed-off-by: Patrick Rudolph <patrick.rudolph@9elements.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/85135
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Alicja Michalska <ahplka19@gmail.com>
Original-Reviewed-by: Lean Sheng Tan <sheng.tan@9elements.com>
GitOrigin-RevId: 50905e7cdc9f0030cdeec6ab0eb70128bacc15e0
Cr-Build-Id: 8731028479029462145
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8731028479029462145
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: Ib83c5d04fd04aceed3401b96e380fe4c0f5003f1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6028911
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Kangheui Won <khwon@chromium.org>
Commit-Queue: Kangheui Won <khwon@chromium.org>