chromeos-base/libchrome: Add missing BDEPEND
```
FAILED: gen/include/base/tracing/protos/chrome_track_event.pbzero.h
/usr/bin/env ../../../libchrome-0.0.1/platform2/common-mk/file_generator_wrapper.py protoc --proto_path /build/amd64-generic/tmp/portage/chromeos-base/libchrome-0.0.1-r841/work/libchrome-0.0.1/platform2/libchrome/base/tracing/protos --proto_path /usr/include/proto --plugin protoc-gen-plugin=/usr/libexec/protozero_plugin --plugin_out=wrapper_namespace=pbzero:/build/amd64-generic/tmp/portage/chromeos-base/libchrome-0.0.1-r841/work/build/out/Default/gen/include/base/tracing/protos /build/amd64-generic/tmp/portage/chromeos-base/libchrome-0.0.1-r841/work/libchrome-0.0.1/platform2/libchrome/base/tracing/protos/chrome_track_event.proto
Traceback (most recent call last):
  File "../../../libchrome-0.0.1/platform2/common-mk/file_generator_wrapper.py", line 19, in <module>
    subprocess.check_call(sys.argv[1:])
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:298923683
TEST=none

Change-Id: Ic8d51c138d11e1ba41eecab5bf8cbcd42270079e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4894875
Reviewed-by: Sami Kyöstilä <skyostil@chromium.org>
Auto-Submit: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Sami Kyöstilä <skyostil@chromium.org>
Reviewed-by: Tim Bain <tbain@google.com>
Tested-by: Raul Rangel <rrangel@chromium.org>