drivers: i2c: stm32: fix compilation with DMA
- implicit declaration of function 'stm32_buf_in_nocache'
- undefined reference to 'stm32_buf_in_nocache'

(cherry picked from commit 6e018bbf04eccad1c67229a247f4f1ddb123c494)

Original-Original-fixes:
Original-Original-Signed-off-by: Mickael Bosch <mickael.bosch@linux.com>
Original-GitOrigin-RevId: 6e018bbf04eccad1c67229a247f4f1ddb123c494
Original-Cr-Build-Id: 8703913562775995409
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8703913562775995409
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I16e1e0a5cf89eec260af3a029ae61cc5b7e91812
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6944946
Original-Tested-by: Al Semjonovs <asemjonovs@google.com>
Original-Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Reviewed-by: Al Semjonovs <asemjonovs@google.com>
GitOrigin-RevId: 54cc8d9476e8f47210f68c1a5eaade6af8b28164
Cr-Build-Id: 8692705559657760673
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692705559657760673
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ifdb03871d4fe44ab1227967669aa366605459ad4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7472598
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>