tests: add missing END_TEST for virgl_test_set_viewport_state
The virgl_test_set_viewport_state test was missing END_TEST,
leaving the following START_TEST() macros nested inside it.
This breaks compilation when tests are enabled (-Dtests=true),
e.g.:
  error: invalid storage class for function 'virgl_decode_set_scissor_state'

Signed-off-by: Weishi Li <liweishi@kylinos.cn>
Part-of: <https://gitlab.freedesktop.org/virgl/virglrenderer/-/merge_requests/1647>