samples: net: lwm2m: depend on xsi single process for gettimeofday()
15014534061/job/42189411225

We were seeing a linker error of the form

```
picolibc/x86_64-zephyr-elf/lib/32/libc.a(libc_time_time.c.o): \
  in function `time':
time.c:(.text.time+0x11): undefined reference to `gettimeofday'
```

Update the dependency from CONFIG_POSIX_TIMERS to
CONFIG_XSI_SINGLE_PROCESS for gettimeofday().

be to have libc functions not depend on POSIX functions.

Specifically, here

51a8b32857e75345c37652a80b5cda98b28d69e5/newlib/libc/time/\
time.c#L54

and here

3a4e12899c2ae5962a64055f4739f774fb7262e5/lib/libc/common/\
source/time/time.c#L17

Also mentioned in #89068

(cherry picked from commit 393446108e9ed6bfaf905b8916e626811f6727ad)

Original-Original-https: //github.com/zephyrproject-rtos/zephyr/actions/runs/\
Original-Original-Note: this is really only a workaround. The proper solution would
Original-Original-https: //github.com/zephyrproject-rtos/picolibc/blob/\
Original-Original-https: //github.com/zephyrproject-rtos/zephyr/blob/\
Original-Original-Signed-off-by: Chris Friedt <cfriedt@tenstorrent.com>
Original-GitOrigin-RevId: 393446108e9ed6bfaf905b8916e626811f6727ad
Original-Cr-Build-Id: 8714785199454382401
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8714785199454382401
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Icd5afbb0078ba54b222400ccb6632f73788cd755
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6553674
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 8a00bacbb1a81f1810a6e3131d9c578aecb90797
Cr-Build-Id: 8692792910433217201
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692792910433217201
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I700a3a02ff65e7bf7f0e7142bc57afed59aa56e8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7463096
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>