virtual_usb_device: op_commands: fix memcpy argument
Glibc 2.41 added new fortify checks which fail builds
with errors like the one below, if for eg memcpy is
used to copy complex structures.

In this case, I think we just need to copy the header,
which is the first element of the structure, so we can
pass it directly to memcpy to fix the warning, instead
of the entire OpRevDevlist.

I think this is the correct aproach because the Pack*
counterparts actually use list.header, for example:
SmartBuffer packed_header = PackOpRepDevlistHeader(list.header);

The error we get with glibc 2.41:
virtual-usb-printer/virtual_usb_device/op_commands.cc:179:10: error: first argument in call to 'memcpy' is a pointer to non-trivially copyable type 'OpRepDevlist' [-Werror,-Wnontrivial-memcall]
  179 |   memcpy(&list, buf->data(), sizeof(OpRepDevlistHeader));
      |          ^
../../../../../../../tmp/portage/chromeos-base/virtual-usb-printer-9999/work/virtual-usb-printer-9999/platform2/virtual-usb-printer/virtual_usb_device/op_commands.cc:179:10: note: explicitly cast the pointer to silence this warning
  179 |   memcpy(&list, buf->data(), sizeof(OpRepDevlistHeader));
      |          ^
      |          (void*)
1 error generated.

BUG=b:387993322
TEST=emerge-amd64-generic libvda-gpu-tests.

Change-Id: I3e48c500171c851a56ad1113aafef40ab34af15f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/virtual-usb-printer/+/6633594
Reviewed-by: George Burgess <gbiv@chromium.org>
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: Santosh Mahto <santosh.mahto@collabora.corp-partner.google.com>
Reviewed-by: Nathan Muggli <nmuggli@google.com>
Auto-Submit: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Commit-Queue: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>