dev-rust/tlsdate_dbus: Add missing BDEPEND
```
process didn't exit successfully: `/build/arm64-generic/tmp/portage/dev-rust/tlsdate_dbus-9999/work/build/cros-rust/release/build/tlsdate_dbus-d805db761b496ebb/build-script-build` (exit status: 101)

Change-Id: Ide0854b77b604581444923e1c336ba7d2dfc7708
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MissingCodegen(CannotFindBinaryPath)', build.rs:21:66
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/dev-rust/tlsdate_dbus:9999

Change-Id: I6666bb7b666eb3060ebee37bc3668e51bc25f714
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692149
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>