dev-util/cros-test: add missing build dep on dev-go/luci-go-common
While testing CrOS in Go modules mode, a build race was
noticed due to cros-test missing a dependency on
dev-go/luci-go-common.

This went uncaught because in GOPATH mode the ebuilds
just dump the files in $GOPATH from where the Go runtime
will eventually find them, but in modules mode the deps
are actually verified when a module is installed.

Example error:
execution/cmd/cros-test/testexecserver_rpc.go:14:2: cannot find module providing package go.chromium.org/luci/common/errors: module go.chromium.org/luci/common/errors

BUG=b:187795288
TEST=Local builds in GOPATH and modules mode.

Change-Id: I7aaddecca41679415044c0471cca3e9453558834
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4828322
Reviewed-by: Azizur Rahman <azrahman@google.com>
Commit-Queue: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: Andrew Lamb <andrewlamb@chromium.org>
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>