nano_init.c: STACK_CANARY_INIT fix for ARC
An updated version of ARC GCC reports this error:
nano_init.c:340: Error: inappropriate arguments for opcode 'mov'

The offending in-line assembly code tried to move register value into a
memory location.

Use store "st" instruction instead of "mov" istruction to store
a value in memory.

Original-Change-Id: I91ebd20495612da4d5639a3ef848379705f6dedd
Original-Signed-off-by: Juro Bystricky <juro.bystricky@intel.com>
GitOrigin-RevId: 19d84d8e00300774432050e76762028dbc50a180
Cr-Build-Id: 8694737397606750881
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694737397606750881
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: If1fb6e826ce0500b7014d80f7dfb13cbba79217f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7305092
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>