Revert "toolchain: gcc: Simplify `GEN_ABSOLUTE_SYM` and `GEN_ABSOLUTE_SYM_KCONFIG`"
This reverts commit 87779e73f87739afdeb2b595b397b831f5fc3518.

Commit 87779e73f877 ("toolchain: gcc: Simplify GEN_ABSOLUTE_SYM and
GEN_ABSOLUTE_SYM_KCONFIG") "unified the variants from using a
target-specific dialects to a target-agnostic solution". While reducing
duplication is always desired, this "unification" got rid of some
differences between architectures. Among others, this commit generalized
the use of the `c` constant operand modifier in the `GEN_ABSOLUTE_SYM()`
macro. Before this commit, the `c` modifier was NOT in use in a number
of architectures!

Generally speaking, reducing copy/paste/diverge must always be performed
in _two_ distinct phases with ample testing time between the two phases:

1. First, perform functional changes that remove the divergence.

   < give plenty enough time for testing >

2. Finally, remove the identical copies.

More specifically, I understand the `c` modifier may be required by some
architectures, but it's causing problems on other(s). Notably, it broke
the build with one pre-C11, gcc-based Xtensa toolchain:

```
                                first unrecognized character is `c'
                                first unrecognized character is `c'
...
```

While newer Xtensa toolchains accept `c`, they also ignore it. `c` makes
no difference whatsoever with all the (working) Xtensa toolchains I
tested. So for `Xtensa`, `c` is a best useless and at worse breaking the
build.

Up to gcc version 12 (2022), the `c` constant modifier was documented as
X86-specific!

Only starting with gcc version 13 (2023), the `c` modifier was
officially supported as "generic":

`c` was very likely working with other architectures before 2023, but
not officially and we don't know which architectures and we don't know
when.

Note toolchain/gcc.h is included by toolchain/llvm.h and also used by
clang. The status of `c` across clang versions is unknown.

While I personally hate copy/paste/diverge with a passion, these macros
GEN_ABSOLUTE_SYM() and GEN_ABSOLUTE_SYM_KCONFIG() are very small so that
particular duplication is very reasonable. Architecture-specific code is
tricky and portability across toolchain and toolchain versions even
more. Testing low-level changes like this across different architectures
would also require demanding and unlikely coordination across different
architectures/companies.

(cherry picked from commit 89493ee56b6cbd51b1117796b5dc2a2666bc22e8)

Original-14: 03:17 kernel_offsets.h: Assembler messages:
Original-14: 03:17 kernel_offsets.h:28: Error: bad expression
Original-14: 03:17 kernel_offsets.h:28: Error: junk at end of line,
Original-14: 03:17 kernel_offsets.h:29: Error: bad expression
Original-14: 03:17 kernel_offsets.h:29: Error: junk at end of line,
Original-https: //gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Extended-Asm.html#x86Operandmodifiers
Original-https: //gcc.gnu.org/onlinedocs/gcc-13.1.0/gcc/Extended-Asm.html#Generic-Operand-Modifiers
Original-Original-Signed-off-by: Marc Herbert <marc.herbert@intel.com>
Original-GitOrigin-RevId: 89493ee56b6cbd51b1117796b5dc2a2666bc22e8
Original-Change-Id: I4cde729bf289ed69a9c066cd080ce6b5a5f9b4e9
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5451475
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: Jeremy Bettis <jbettis@chromium.org>
GitOrigin-RevId: 51e3a89d4bd9497c55cd3550b07e824454998223
Cr-Build-Id: 8693045275188255777
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693045275188255777
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: If848a13ab3c2fa288b1fe6c1f7d196c325e64d9b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7434862
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>