UPSTREAM: soc/intel/alderlake: Fix uninitialized usb_cfg pointer
This patch addresses uninitialized usb_cfg pointer warning which is also
an error - src/soc/intel/alderlake/fsp_params.c:936:48: error: 'usb_cfg'
may be used uninitialized in this function [-Werror=maybe-uninitialized]

BUG=None
TEST=./util/abuild/abuild

(cherry picked from commit 1d9bddf1632ccbb7ffd5d92c4608c3065df72c0f)

Original-Change-Id: I764fed561dfe2a571f3404fe505997edd7aa5ff7
Original-Signed-off-by: Karthikeyan Ramasubramanian <kramasub@google.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/84939
Original-Reviewed-by: Jayvik Desai <jayvik@google.com>
Original-Reviewed-by: Subrata Banik <subratabanik@google.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: 1d9bddf1632ccbb7ffd5d92c4608c3065df72c0f
Cr-Build-Id: 8731898458657424529
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8731898458657424529
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I934e6f5ae2bf654211658553cba32e704341570f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6003387
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
Commit-Queue: Jonathon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>