samples/net/mqtt_publisher: undefined reference to z_impl_sys_rand32_get
Add missing random options to prj.conf file.

Fixes #31414

Original-Signed-off-by: Vitaliy Gribko <vitaliy69@gmail.com>
GitOrigin-RevId: 75847b7a5e2c7db4268f2ee977c093bcb7c50640
Cr-Build-Id: 8693905240056402833
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693905240056402833
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I9ef35e6646d4eec59fa40ab5e71c277afdc398ee
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7372268
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>