tests: lib: cmsis_dsp: Fix -Wsometimes-uninitialized warning
Building with clang warns:

tests/lib/cmsis_dsp/distance/src/u32.c:82:3: error: variable 'val' is
used uninitialized whenever switch default is taken
[-Werror,-Wsometimes-uninitialized]
                default:
                ^~~~~~~
tests/lib/cmsis_dsp/distance/src/u32.c:87:19: note: uninitialized use
occurs here
                output[index] = val;
                                ^~~
tests/lib/cmsis_dsp/distance/src/u32.c:47:16: note: initialize the
variable 'val' to silence this warning
                float32_t val;
                             ^
                              = 0.0

Hitting the default switch will assert, so this won't cause any problems
as written, but it doesn't hurt to initialize the variable.

(cherry picked from commit 481a3c77c9e7e90cbbfa00886ab6feec45f686cf)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: 481a3c77c9e7e90cbbfa00886ab6feec45f686cf
Cr-Build-Id: 8720062473382680481
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8720062473382680481
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ib27ba943ce3e7e2f5113baef661babc04c47a92d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6367339
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>