Revert "toolchain/zephyr: invoke ar with -D for deterministic .a files"
This reverts commit b4078c557ddc / zephyrproject-rtos/zephyr#17495

This revert is needed for two reasons:

1. As reported by Lawrence King at
   https://lists.zephyrproject.org/g/users/message/1566
this breaks incremental builds with ninja:

  cd sample/hello_world
  west build -b qemu_x86
  touch src/main.c
  west build -b qemu_x86

  hello_world/build/../src/main.c:11: multiple definition of main';
  app/libapp.a(main.c.obj):samples/hello_world/build/../src/main.c:11:
  first defined here
  collect2: error: ld returned 1 exit status

  ar tf build/app/libapp.a
   main.c.obj
   main.c.obj

This does NOT break incremental builds with GNU Make, not sure why not.

2. Less urgently, I finally got someone from the CMake team to help me
and point me at an alternative solution that doesn't rely on CMake
I was about to try it when Lawrence reported the regression above.

Original-internals: https://gitlab.kitware.com/cmake/cmake/issues/19474
Original-Signed-off-by: Marc Herbert <marc.herbert@intel.com>
GitOrigin-RevId: 2371679528f85e5a93285f34b10e7cd7d4fd465b
Cr-Build-Id: 8694180980391195425
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694180980391195425
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I22cb1742031de0bca433e1dd9637186900179ac8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7350210
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>