chromeos-base/bootlockbox-client: Add missing BDEPEND
```
FAILED: gen/include/bootlockbox/key_value_map.pb.cc gen/include/bootlockbox/key_value_map.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```
```
FAILED: gen/include/bootlockbox/dbus-proxies.h gen/include/bootlockbox/dbus-proxy-mocks.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/bootlockbox-client:9999

Change-Id: I8850df8b1a74ec33ed854286109c972925027ce4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4690599
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>