vrend: fix returning bool instead of pointer
virgl_egl_get_device is supposed to return EGLDeviceEXT which is
basically a void* but one of the error branches was returning a boolean
value and this gives an error when building for the C23 standard.

Return a value of the correct type to fix the following error:

-----------------------------------------------------------------------
../src/vrend/vrend_winsys_egl.c: In function ‘virgl_egl_get_device’:
../src/vrend/vrend_winsys_egl.c:250:21: error: incompatible types when returning type ‘_Bool’ but ‘EGLDeviceEXT’ {aka ‘void *’} was expected
  250 |              return false;
      |                     ^~~~~
-----------------------------------------------------------------------

Part-of: <https://gitlab.freedesktop.org/virgl/virglrenderer/-/merge_requests/1542>