zephyr: sw_isr_table: Fix compilation error
The IRQ_DIRECT_CONNECT macro eventually uses _Z_ISR_DIRECT_TABLE_ENTRY,
which defines a function. IRQ_DIRECT_CONNECT is meant to be used
inside functions. While nested functions are supported as an extension
in GNU C, the nested function cannot have static storage.

> A nested function always has no linkage. Declaring one with extern or
> static is erroneous.

./scripts/twister -c -s arch.interrupt.gen_isr_table_local.riscv --all

tests/kernel/gen_isr_table/src/main.c: In function
'gen_isr_table_test_build_time_direct_interrupt':
include/zephyr/sw_isr_table.h:197:41: error: invalid storage class for
function '__isr_table_entry_isr1_irq_2'
#define __MK_ISR_ELEMENT_NAME(func, id) __isr_table_entry_ ## func ## _irq_ ## id
                                        ^~~~~~~~~~~~~~~~~~

Issue #92194

(cherry picked from commit 9fd547f94d7d08b4e0e946af43b78e6a9f893558)

Original-https: //gcc.gnu.org/onlinedocs/gcc/Nested-Functions.html:
Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: 9fd547f94d7d08b4e0e946af43b78e6a9f893558
Cr-Build-Id: 8709349381864786321
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8709349381864786321
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ib231fd847f7a9ec133b6cc095be7d3634e24bd6d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6732794
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>