lib: posix: Fix undefined reference to clock_gettime()
timespec_to_timeoutms calls clock_gettime that requires
CONFIG_POSIX_CLOCK. ifdef this function to avoid undefined reference.

Fixes #20137

Original-Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>
GitOrigin-RevId: 9e45c67679759108b0cf594aec29ce3c3647b61e
Cr-Build-Id: 8694081801241614193
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694081801241614193
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I83bea5037117b3d05cc767daba15a86e495d6f3c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7358013
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>