dev-python/more-itertools: Update to EAPI 7
```
ModuleNotFoundError: No module named 'setuptools'
 * ERROR: dev-python/more-itertools-4.2.0-r1::portage-stable failed
   (compile phase):
```

Updating to EAPI7 will cause distutils-r1.eclass to set the setuptools
BDEPEND.

This package is way out of date compared to upstream, so not pushing
this upstream.

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/portage-stable/dev-python/more-itertools:4.2.0-r2

Change-Id: Ib1a87384643698e9bd5cdd7b3976a24e1a819161
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/portage-stable/+/4787067
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>