UPSTREAM: pw_clock_tree: Provide initializer for DeferredInit::storage_
Without this change, DeferredInit and classes derived from
ElementBlocking cannot be use to define constinit-specified objects:

  example.cc:123: error: variable does not have a constant initializer
  example.cc:123: note: required by 'constinit' specifier here
  example.cc:123: note: subobject '__elems_' is not initialized
  external/pigweed++_repo_rules6+llvm_toolchain/bin/../include/c++/v1/array:203:7: note: subobject declared here
    203 |   _Tp __elems_[_Size];
        |       ^

(cherry picked from commit 0f717f2c0e7fa94dc79ea8d280fb41c6a2fb9914)

Original-Change-Id: If3fc5bafbe24cfd55d00d662578493139a2e8411
Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/345352
Original-Commit-Queue: Jonathon Reinhart <jrreinhart@google.com>
Original-Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Original-Reviewed-by: Austin Foxley <afoxley@google.com>
Original-Docs-Not-Needed: Jonathon Reinhart <jrreinhart@google.com>
Original-Presubmit-Verified: CQ Bot Account <pigweed-scoped@luci-project-accounts.iam.gserviceaccount.com>
Original-Tests-Not-Needed: Jonathon Reinhart <jrreinhart@google.com>
GitOrigin-RevId: 0f717f2c0e7fa94dc79ea8d280fb41c6a2fb9914
Cr-Build-Id: 8696299644465094513
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8696299644465094513
Copybot-Job-Name: pigweed-main-copybot-downstream
Change-Id: I7d537356638123d2bedb0b763476648989881819
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/pigweed/pigweed/+/7164616
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Commit-Queue: Jon Murphy <jpmurphy@google.com>