net: lib: shell: dns: Fix field precission specifier type
Explicitly cast down the string width to int, as otherwise it is
size_t which may have a bigger size.

Avoids the following build error:

subsys/net/lib/shell/dns.c:496:67: error: field precision specifier
‘.*’ expects argument of type ‘int’, but argument 4 has type ‘size_t’
{aka ‘long unsigned int’}

(cherry picked from commit 499aa995f6d8e16a3110447bec719f9a2d2bc4fd)

Original-Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
GitOrigin-RevId: 499aa995f6d8e16a3110447bec719f9a2d2bc4fd
Cr-Build-Id: 8700380283100427425
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8700380283100427425
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I2a2d930ef36e730dfd13371dafb1d93d6fe0957c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7069662
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>