mtkcam: suppress Clang diagnostic
Clang complains that the `MSize` fields here can't be packed, since it's
not a POD type:

```
error: not packing field 'bin_size' as it is non-POD for the purposes of
layout
```

There's no point in packing MSize, since it's just a pair of ints.
Packing is beneficial to make this `struct` take 25 bytes instead of 28.

BUG=b:307936642
TEST=emerge-kukui cros-camera-hal-mtk

Change-Id: Ie4ff5b2587947d0b19a6e864a28d888fb52acfd8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/camera/+/4980525
Commit-Queue: George Burgess <gbiv@chromium.org>
Reviewed-by: becker hsieh <beckerh@chromium.org>
Tested-by: George Burgess <gbiv@chromium.org>