UPSTREAM: Makefile.mk: Suppress stack-usage LTO link warning
Suppress the following warning during linking with gcc:
src/drivers/spi/spi_flash.c: In function 'spi_flash_cmd_write':
src/drivers/spi/spi_flash.c:138:5: error: stack usage might be unbounded [-Werror=stack-usage=]
  138 | int spi_flash_cmd_write(const struct spi_slave *spi, const u8 *cmd,

(cherry picked from commit 01dfc9b18730189445353422a5569e9d9865f5e3)

Original-Change-Id: If08d6d543a4fcff07003af8d1f8dd59ab79f42f8
Original-Signed-off-by: Arthur Heymans <arthur@aheymans.xyz>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/84044
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Angel Pons <th3fanbus@gmail.com>
GitOrigin-RevId: 01dfc9b18730189445353422a5569e9d9865f5e3
Cr-Build-Id: 8732025048093146161
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8732025048093146161
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I5b8e1e967c020742ab492f79ca1403021eca9c3e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5997327
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Nick Vaccaro <nvaccaro@google.com>
Commit-Queue: Nick Vaccaro <nvaccaro@google.com>