Autoupdate of 2 submodules
*chromite updated to 8277ef50a227d9b9f1b23ac91883c3ebf1568242
utils: Skirt around a pylint quirk in detector_unittest.py

detector_unittest mocks Path.read_text, but pylint has special
handling for it at https://github.com/pylint-dev/pylint/blob/v2.15.10/pylint/checkers/stdlib.py#L666

Currently, attempting to lint this file causes pylint to crash:
```
  Exception on node <> in file '..chromite/utils/telemetry/detector_unittest.py'
  ...
  File "/usr/lib/python3/dist-packages/pylint/checkers/stdlib.py", line 666, in _check_open_call
    if node.func.attrname == "read_text":
AttributeError: 'Name' object has no attribute 'attrname'
```

Supporting mocks seems a bit out of scope for a linter, so just
skirt around the problem by renaming the local variable
read_text -> real_read_text.

BUG=b:236161656
TEST=`cros lint` no longer crashes on this file. detector_unittest.py passes.

Change-Id: I18e9a6ed74dbb79e1c4ae7ed3a98483438b0abb0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4542023
Tested-by: Trent Apted <tapted@chromium.org>
Reviewed-by: Anuj Jamwal <anujjamwal@google.com>
Commit-Queue: Trent Apted <tapted@chromium.org>

*infra/chromite-HEAD updated to 8277ef50a227d9b9f1b23ac91883c3ebf1568242
utils: Skirt around a pylint quirk in detector_unittest.py

detector_unittest mocks Path.read_text, but pylint has special
handling for it at https://github.com/pylint-dev/pylint/blob/v2.15.10/pylint/checkers/stdlib.py#L666

Currently, attempting to lint this file causes pylint to crash:
```
  Exception on node <> in file '..chromite/utils/telemetry/detector_unittest.py'
  ...
  File "/usr/lib/python3/dist-packages/pylint/checkers/stdlib.py", line 666, in _check_open_call
    if node.func.attrname == "read_text":
AttributeError: 'Name' object has no attribute 'attrname'
```

Supporting mocks seems a bit out of scope for a linter, so just
skirt around the problem by renaming the local variable
read_text -> real_read_text.

BUG=b:236161656
TEST=`cros lint` no longer crashes on this file. detector_unittest.py passes.

Change-Id: I18e9a6ed74dbb79e1c4ae7ed3a98483438b0abb0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4542023
Tested-by: Trent Apted <tapted@chromium.org>
Reviewed-by: Anuj Jamwal <anujjamwal@google.com>
Commit-Queue: Trent Apted <tapted@chromium.org>