installer: Move argument parsing from shell to rust
Tips #1 and #2 from the deshell playbook are about moving arg parsing:
https://github.com/google/deshell/blob/main/playbook.md

Parse args with Clap, and pass them as environment variables to the
script, taking care to use the same format that shflags previously
provided.

Two significant things here:
* Handling of the `lvm_stateful_partition` USE flag was done by running
  sed on chromeos-install to replace the default value. That's not going
  to work with rust. Instead we toggle a `const` default value via a new
  crate feature `lvm_default`. That feature can be controlled from the
  ebuild.

* The 'no' variants of args (like `--noskip_rootfs`) are annoying to
  provide in Clap, and I don't see evidence of them being used. See this
  code search:
  https://source.chromium.org/search?q=%5B-%5D%7B2%7D(noskip_dst_removable%7Cnoskip_rootfs%7Cnoyes%7Cnopreserve_stateful%7Cnodebug%7Cnoskip_postinstall%7Cnostorage_diags%7Cnolvm_stateful%7Cnominimal_copy%7Cnoskip_gpt_creation)&sq=
  Drop all the 'no' variants, except for the one that allows turning off
  lvm when the default is 'on'.

BUG=b:356344778
TEST=$ cros_sdk USE=-lvm_stateful_partition -- emerge-reven \
                                               chromeos-installer
     $ cros deploy vm chromeos-installer
     $ ssh vm chromeos-install
     > Running: [...] FLAGS_lvm_stateful="1" [...] chromeos-install.sh"
     > Error: can not determine destination device. Specify --dst yourself.
     $ ssh vm chromeos-install --lvm_stateful
     > Running: [...] FLAGS_lvm_stateful="0" [...] chromeos-install.sh"
     > Error: can not determine destination device. Specify --dst yourself.

     $ cros_sdk USE=lvm_stateful_partition -- emerge-reven \
                                              chromeos-installer
     $ cros deploy vm chromeos-installer
     $ ssh vm chromeos-install
     > Running: [...] FLAGS_lvm_stateful="0" [...] chromeos-install.sh"
     > Error: can not determine destination device. Specify --dst yourself.
     $ ssh vm chromeos-install --nolvm_stateful
     > Running: [...] FLAGS_lvm_stateful="1" [...] chromeos-install.sh"
     > Error: can not determine destination device. Specify --dst yourself.
     $ ssh vm chromeos-install --lvm_stateful --nolvm_stateful
     > error: the argument '--nolvm_stateful' cannot be used with
     > '--lvm_stateful'
     >
     > Usage: chromeos-install --nolvm_stateful
     >
     > For more information, try '--help'.
TEST=cros_sdk FEATURES=test -- emerge-reven chromeos-installer

Cq-Depend: chromium:5837237, chromium:5835576
Change-Id: Id525a2764a261e4e00e2b9129bbd7cc2a3755ba0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/5830990
Reviewed-by: Nicholas Bishop <nicholasbishop@google.com>
Commit-Queue: Ted Brandston <tbrandston@google.com>
Tested-by: Ted Brandston <tbrandston@google.com>