compiler_wrapper: Fix findings from staticcheck
This CL fixes the following staticcheck findings:

clang_tidy_flag.go:235:6: func hasAtLeastOneSuffix is unused (U1000)
command.go:96:13: error strings should not be capitalized (ST1005)
compiler_wrapper.go:97:22: should use time.Since instead of time.Now().Sub (S1012)
compiler_wrapper.go:154:3: this value of cSrcFile is never used (SA4006)
compiler_wrapper.go:187:12: unnecessary use of fmt.Sprintf (S1039)
env.go:148:5: var _env is unused (U1000)
env_test.go:228:2: this value of err is never used (SA4006)
iwyu_flag.go:18:7: const iwyuCrashSubstring is unused (U1000)

BUG=b:295930281
TEST=go test

Change-Id: I3d365243192f9041d12b9c8385d4bd8ff1bd5669
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/4779192
Reviewed-by: George Burgess <gbiv@chromium.org>
Commit-Queue: Ryan Beltran <ryanbeltran@chromium.org>
Tested-by: Ryan Beltran <ryanbeltran@chromium.org>