net: http_client: add missing kernel.h include statement
There is following error when compiling applications using http_client:

  /zephyr/include/net/http_client.h:157:24: error: field 'work' has \
  incomplete type
    157 |  struct k_delayed_work work;
        |                        ^~~~
  /zephyr/include/net/http_client.h:177:2: error: unknown type name \
  'k_timeout_t'
    177 |  k_timeout_t timeout;
        |  ^~~~~~~~~~~

Fix that by adding missing kernel.h include statement in http_client.h.

Original-Signed-off-by: Marcin Niestroj <m.niestroj@grinn-global.com>
GitOrigin-RevId: e2e2a2bd94c48c3854e6bb7ec6928b339bd433dd
Cr-Build-Id: 8694011412242336305
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694011412242336305
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ia5f8fd4bcb7aa882252370c0d9d2f6bedbe19175
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7364533
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>