Patch and bump freeimage to use libjpeg_turbo from BCR instead of internal version (#7074)
FreeImage ships with its internal copy of libjpeg (jpeg-9d), which can
conflict with later versions of libjpeg_turbo when transitively pulled
into the same build. For example, I see the following ODR violation
flagged by the linker for a downstream target that depends on both
FreeImage and libjpeg_turbo transitively.
```
ld.lld: error: duplicate symbol: jpeg_abort
>>> defined at jcomapi.c
>>>            bazel-out/haswell-opt/bin/external/libjpeg_turbo+/_objs/jpeg/jcomapi.o:(jpeg_abort)
>>> defined at jcomapi.c
>>>            bazel-out/haswell-opt/bin/external/freeimage+/_objs/libjpeg/jcomapi.o:(.text.jpeg_abort+0x0)
```

This PR patches FreeImage to depend on libjpeg_turbo for jpeg support
instead of its internal copy.

Since FreeImage requires jpeg transform support, a separate `transform`
target is added to libjpeg_turbo to expose transupp.h and transupp.c
which were previously omitted from the bazel build. As a result,
libjpeg_turbo is bumped to version 3.1.3.bcr.2 and FreeImage is bumped
to version 3.19.10.bcr.5.

I verified that this PR addresses the linker errors mentioned above.

---------

Signed-off-by: Shameek Ganguly <shameek@intrinsic.ai>