bluetooth: Fix cast in bt_buf_get_type
The function returns an enum, not a u8_t, so we should cast
appropriately to avoid an implicit conversion.

This construct was triggering this compilation error when compiling
with CXX:

/home/sebo/zephyr/include/bluetooth/buf.h:85:9: error: invalid
  conversion from ‘u8_t {aka unsigned char}’ to ‘bt_buf_type’
  [-fpermissive] return *(u8_t *)net_buf_user_data(buf);

Original-Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
GitOrigin-RevId: d3304dc50863ffe5dbc89daa2793c557cf9edd25
Cr-Build-Id: 8694589597225911713
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694589597225911713
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I192662e1ee143867f4b4f6c1da4e3b20fc5bc789
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7322852
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>