dev-python/setuptools_scm: Upgrade to EAPI 7
```
ModuleNotFoundError: No module named 'setuptools'
 * ERROR: dev-python/setuptools_scm-3.2.0::portage-stable failed
   (compile phase):
```

This will add the setuptools BDEPEND.

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/portage-stable/dev-python/setuptools_scm:3.2.0-r1

Change-Id: I532cf6dd472c65f1ca98d5aae3c041ee0ac01579
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/portage-stable/+/4787068
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>