chromeos-base/secagentd: Add missing deps
```
Package libsession_manager-client was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsession_manager-client.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsession_manager-client' found

See //secagentd/BUILD.gn:63:1: whence it was called.
```

```
FAILED: gen/include/bindings/policy_common_definitions.pb.cc gen/include/bindings/policy_common_definitions.pb.h 
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/secagentd:9999

Change-Id: Ie96951cacc8581243df2333e6478f54c4ccab891
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692130
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>