Add compile-time error message for when PB_FIELD_32BIT is needed (#680, #827)
Messages that are larger than 64 kB need a compilation option to use 32-bit type
for pb_size_t. Previously this would be indicated by FIELDINFO_DOES_NOT_FIT error
which is not clear to the actual cause.

This commit adds a new check with more clear error message:
test.pb.c:14:2: error: #error Enable PB_FIELD_32BIT to support messages exceeding 64kB in size: Message1

Also clarified some comments.

(cherry picked from commit 2da421befe1b91a3645807f5e8a7a99be0f323a7)

GitOrigin-RevId: 2da421befe1b91a3645807f5e8a7a99be0f323a7
Change-Id: I499f5c13aa5e59613fae992a4866b8750e6763f6