media-sound/adhd: Add DEPEND on gtest
adhd includes libchrome's headers that, transitively,
include gtest headers. Given the lack of a better
approach (see b/274791539), we have to make adhd explicitly
depend on gtest.

This fixes the error in Bazel builds:

```
In file included from external/webrtc_apm/webrtc_apm/webrtc_apm.cc:16:
In file included from /build/amd64-generic/usr/include/metrics/metrics_library.h:22:
In file included from /build/amd64-generic/usr/include/metrics/metrics_writer.h:14:
In file included from external/pkg_config__libmetrics/sysroot/build/amd64-generic/usr/include/libchrome/base/task/sequenced_task_runner.h:13:
In file included from external/pkg_config__libmetrics/sysroot/build/amd64-generic/usr/include/libchrome/base/gtest_prod_util.h:9:
external/pkg_config__libmetrics/sysroot/build/amd64-generic/usr/include/libchrome/testing/gtest/include/gtest/gtest_prod.h:1:10: fatal error: 'gtest/gtest_prod.h' file not found
    1 | #include <gtest/gtest_prod.h>
```

BUG=b:322996926
TEST=cros_sdk BOARD=amd64-generic /mnt/host/source/chromite/bin/bazel build @portage//target/media-sound/adhd

Change-Id: Ia946c20b62c85683a73e08fbb996adf7a8311780
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/5255537
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Li-Yu Yu <aaronyu@google.com>
Auto-Submit: Maksim Ivanov <emaxx@chromium.org>
Tested-by: Maksim Ivanov <emaxx@chromium.org>