chromeos-base/puffin: Add missing BDEPEND
```
FAILED: gen/include/puffin/src/puffin.pb.cc gen/include/puffin/src/puffin.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/puffin:9999

Change-Id: I1e56c1f4a54888c945cfac91a7466a1267fce2fb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692244
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>