tests: fix build errors with USE_FLASHROM=0
Test `vb2_host_flashrom_tests` uses libflashrom, thus it fails to build
with `USE_FLASHROM=0`:

```
.../tests/vb2_host_flashrom_tests.o: in function `test_read_whole_chip':
.../tests/vb2_host_flashrom_tests.c:152:(.text.startup.main+0x48): undefined reference to `flashrom_read'
.../tests/vb2_host_flashrom_tests.o: in function `test_read_region':
.../tests/vb2_host_flashrom_tests.c:175:(.text.startup.main+0x195): undefined reference to `flashrom_read'
.../tests/vb2_host_flashrom_tests.o: in function `test_read_failure':
.../tests/vb2_host_flashrom_tests.c:200:(.text.startup.main+0x2e9): undefined reference to `flashrom_read'
.../tests/vb2_host_flashrom_tests.o: in function `test_write_whole_chip':
.../tests/vb2_host_flashrom_tests.c:216:(.text.startup.main+0x33c): undefined reference to `flashrom_write'
.../tests/vb2_host_flashrom_tests.o: in function `test_write_region':
.../tests/vb2_host_flashrom_tests.c:243:(.text.startup.main+0x49e): undefined reference to `flashrom_write'
.../tests/vb2_host_flashrom_tests.o: in function `test_write_failure':
.../tests/vb2_host_flashrom_tests.c:270:(.text.startup.main+0x614): undefined reference to `flashrom_write'
collect2: error: ld returned 1 exit status
```

Build it conditionally on this variable to fix that.

BRANCH=None
BUG=None
TEST=`make clean; make USE_FLASHROM=0 -j$(nproc) tests`

Change-Id: I17ad4843e8db024b554ca7386e68103c99d1619a
Signed-off-by: Mauricio Faria de Oliveira <mfo@igalia.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/vboot_reference/+/6309491
Commit-Queue: Julius Werner <jwerner@chromium.org>
Tested-by: Julius Werner <jwerner@chromium.org>
Reviewed-by: Yu-Ping Wu <yupingso@chromium.org>
Reviewed-by: Julius Werner <jwerner@chromium.org>