chromeos-base/system-proxy: Add missing DEPEND
```
FAILED: gen/include/bindings/worker_common.pb.cc gen/include/bindings/worker_common.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
FAILED: gen/include/system_proxy/org.chromium.SystemProxy.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

```
/build/arm64-generic/etc/portage/hooks/install/check-seccomp.sh: line 27: compile_seccomp_policy: command not found
 * ERROR: chromeos-base/system-proxy-9999::chromiumos failed:
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/system-proxy:9999

Change-Id: I206a9937f0aecf213010eea6b3765c2610a0e402
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692137
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>