intel/common: remove fallthrough annotation in unreachable code
Fixes the following building errors happening with with clang:

FAILED: [code=1] src/intel/common/libintel_common.a.p/xe_intel_gem.c.o
...
./src/intel/common/xe/intel_gem.c
error: fallthrough annotation in unreachable code [-Werror,-Wimplicit-fallthrough]
error: fallthrough annotation in unreachable code [-Werror,-Wimplicit-fallthrough]
error: fallthrough annotation in unreachable code [-Werror,-Wimplicit-fallthrough]
3 errors generated.

Fixes: 39a0d76f ("intel: Add common utils for page fault reporting")
Reviewed-by: Calder Young <calder.young@intel.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/42366>