zink: avoid designated initializers as they are not supported in C++ < 20
    error C7555: use of designated initializers requires at least '/std:c++20'

Fixes: 7bdaf6e95f79d3c159ae ("zink: use zink_shader_key_optimal unions for pipeline state asserts")
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/29139>