Autoupdate of 2 submodules
*chromite updated to da5efe9975b1ca12e248ffe7a375069be4f10034
lib: toolchain_util: Fix log message

Fixed error:
"AttributeError: 'GSNoSuchKey' object has no attribute 'stdout'".

BUG=b:249144473
TEST=unittest + http://ci.chromium.org/b/8800824073223177905

Change-Id: I76ab0c6aeb5bbf51bf1f0031698c3cf60b090c66
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/3940509
Tested-by: Denis Nikitin <denik@chromium.org>
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
Commit-Queue: Denis Nikitin <denik@chromium.org>

*infra/chromite-HEAD updated to da5efe9975b1ca12e248ffe7a375069be4f10034
lib: toolchain_util: Fix log message

Fixed error:
"AttributeError: 'GSNoSuchKey' object has no attribute 'stdout'".

BUG=b:249144473
TEST=unittest + http://ci.chromium.org/b/8800824073223177905

Change-Id: I76ab0c6aeb5bbf51bf1f0031698c3cf60b090c66
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/3940509
Tested-by: Denis Nikitin <denik@chromium.org>
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
Commit-Queue: Denis Nikitin <denik@chromium.org>