va: Use { 0 } initialize struct
../src/gallium/frontends/va/config.c(574): error C2059: syntax error: '}'

MSVC 2019 doesn't support for it yet

Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>
Reviewed-by: David Rosca <david.rosca@amd.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/36843>