chromeos-base/chromeos-config: Add missing BDEPEND
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/build/arm64-generic/tmp/portage/chromeos-base/chromeos-config-9999/work/chromeos-config-9999/chromeos-config/cros_config_host/cros_config_schema.py", line 27, in <module>
    import libcros_schema
  File "/build/arm64-generic/tmp/portage/chromeos-base/chromeos-config-9999/work/chromeos-config-9999/chromeos-config/cros_config_host/libcros_schema.py", line 18, in <module>
    from jsonschema import validate  # pylint: disable=import-error
ModuleNotFoundError: No module named 'jsonschema'
 * ERROR: chromeos-base/chromeos-config-9999::chromiumos failed (compile phase):
```

```
 Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/build/arm64-generic/tmp/portage/chromeos-base/chromeos-config-9999/work/chromeos-config-9999/chromeos-config/cros_config_host/cros_config_schema.py", line 27, in <module>
    import libcros_schema
  File "/build/arm64-generic/tmp/portage/chromeos-base/chromeos-config-9999/work/chromeos-config-9999/chromeos-config/cros_config_host/libcros_schema.py", line 19, in <module>
    import yaml  # pylint: disable=import-error
ModuleNotFoundError: No module named 'yaml'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/chromeos-config:9999

Change-Id: I142f30a7170570722c6ab848caf17c8a5f4c0384
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4738848
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>