chromeos-base/crosh-extension: Add missing BDEPEND
```
/build/arm64-generic/tmp/portage/chromeos-base/crosh-extension-9999/work/crosh-extension-9999/node_modules/.bin/node: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

```
FileNotFoundError: [Errno 2] No such file or directory: 'zip'
```

```
/build/arm64-generic/tmp/portage/chromeos-base/crosh-extension-9999/temp/environment: line 3390: unzip: command not found
 * ERROR: chromeos-base/crosh-extension-9999::chromiumos failed (install phase):
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/crosh-extension:9999

Change-Id: I61dc6e978198e80f77f3072563281f4922d9ac50
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692090
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>