chromeos-base/net-base: Drop unused "ipv4" variables
With llvm-r547379-1, the following warning is issued:

    .../net-base/ip_address.cc:107:18: error: variable 'ipv4' set but not used [-Werror,-Wunused-but-set-variable]
      107 |   if (const auto ipv4 = std::get_if<IPv4Address>(&address_)) {
          |                  ^
    .../net-base/ip_address.cc:287:18: error: variable 'ipv4' set but not used [-Werror,-Wunused-but-set-variable]
      287 |   if (const auto ipv4 = std::get_if<IPv4CIDR>(&cidr_)) {
          |                  ^
    2 errors generated.

BUG=b:368393962
TEST=emerge-jacuzzi net-base

Change-Id: I02c11c7ae26b6971e1a6875cf9a6d691f9e85c80
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/6070207
Reviewed-by: Jordan Abrahams-Whitehead <ajordanr@google.com>
Reviewed-by: Jie Jiang <jiejiang@chromium.org>
Reviewed-by: Chih-Yu Huang <akahuang@chromium.org>
Reviewed-by: Hugo Benichi <hugobenichi@google.com>
Commit-Queue: Andrej Shadura <andrew.shadura@collabora.com>
Tested-by: Andrej Shadura <andrew.shadura@collabora.com>