tests: net: socket: Fix -Wsometimes-uninitialized warning
Building with clang warns:

tests/net/socket/tcp/src/main.c:377:13: error: variable 'c_sock' is used
uninitialized whenever 'if' condition is false
[-Werror,-Wsometimes-uninitialized]
        } else if (family == AF_INET6) {
                   ^~~~~~~~~~~~~~~~~~
tests/net/socket/tcp/src/main.c:396:15: note: uninitialized use occurs here
        test_connect(c_sock, s_saddr, addrlen);
                     ^~~~~~
tests/net/socket/tcp/src/main.c:377:9: note: remove the 'if' if its
condition is always true
        } else if (family == AF_INET6) {
               ^~~~~~~~~~~~~~~~~~~~~~~~
tests/net/socket/tcp/src/main.c:360:12: note: initialize the variable
'c_sock' to silence this warning
        int c_sock;
                  ^
                   = 0
tests/net/socket/tcp/src/main.c:377:13: error: variable 's_sock' is used
uninitialized whenever 'if' condition is false
[-Werror,-Wsometimes-uninitialized]
        } else if (family == AF_INET6) {
                   ^~~~~~~~~~~~~~~~~~
tests/net/socket/tcp/src/main.c:387:12: note: uninitialized use occurs here
        test_bind(s_sock, s_saddr, addrlen);
                  ^~~~~~
tests/net/socket/tcp/src/main.c:377:9: note: remove the 'if' if its
condition is always true
        } else if (family == AF_INET6) {
               ^~~~~~~~~~~~~~~~~~~~~~~~
tests/net/socket/tcp/src/main.c:361:12: note: initialize the variable
's_sock' to silence this warning
        int s_sock;
                  ^
                   = 0

Not really needed since we have zassert_unreachable(), but doesn't hurt
to initialize the variables.

(cherry picked from commit 9e856694826cf42fa3702ec06bbb1ca04a3ca9d3)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 9e856694826cf42fa3702ec06bbb1ca04a3ca9d3
Original-Cr-Build-Id: 8723550454920298305
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723550454920298305
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ie32165b8505185bca92b7bee82e79852d92b0cda
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6243000
Original-Commit-Queue: Jonathon Murphy <jpmurphy@google.com>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Jeremy Bettis <jbettis@chromium.org>
Original-Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
GitOrigin-RevId: c893b637d567d740fc817dc3536e5ec4a880bdb3
Cr-Build-Id: 8692862747512897393
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692862747512897393
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I1e208150be70d0194384558cff38ded8368d75c1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7455299
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>