drivers/storage: Fix pointer truncation warning for x86_64 build
The `pci_read_config32()` function returns a `uint32_t`, which is then
bitwise ANDed with `~0xf` and cast to a `void *`. This can result in
pointer truncation on platforms where pointers are wider than 32 bits.

Compilation Error:

```
src/drivers/storage/ufs_intel.c: In function 'intel_ufs_update':
src/drivers/storage/ufs_intel.c:46:29: error: cast to pointer from
 integer of different size [-Werror=int-to-pointer-cast]
 46 |   intel_ufs->ufs.hci_base = (void *)(pci_read_config32(dev,
         REG_BAR0) & ~0xf);
                                   ^
cc1: all warnings being treated as errors
```

Fix this by casting the result of `pci_read_config32()` to `uintptr_t`
before the bitwise AND and the cast to `void *`.

Change-Id: I44551d681c9528dfd732a3d765281ca822a9e540
Signed-off-by: Subrata Banik <subratabanik@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/6075648
Tested-by: Subrata Banik <subratabanik@chromium.org>
Commit-Queue: Subrata Banik <subratabanik@chromium.org>
Auto-Submit: Subrata Banik <subratabanik@chromium.org>
Reviewed-by: Kapil Porwal <kapilporwal@chromium.org>