UPSTREAM: treewide: Const-correct all __cfr_form definition
Although macro "__cfr_form" contains an attribute to link it into a
readonly section, not all __cfr_form definition used to be
const-corrected, which makes gcc confused when CONFIG_LTO=y:

src/console/cfr.c:101:44: error: 'console' causes a section type
conflict with 'cfr_sm_management_engine' in section
'.rodata.cfr_forms'
  101 | static const __cfr_form struct sm_obj_form console = {
      |                                            ^
src/southbridge/intel/bd82x6x/cfr.c:90:38: note:
'cfr_sm_management_engine' was declared here
   90 | __cfr_form static struct sm_obj_form
   cfr_sm_management_engine = {
      |                                      ^
Assembler messages:
{standard input}:43744: Warning: setting incorrect section attributes
for .rodata.cfr_forms

Const-correcting all existing __cfr_form definition could satisfy
gcc.

The other option might be to embed a "const" into the definition of
macro "__cfr_form", thus automatically making every __cfr_form object
const-corrected, but checkpatch will false-positively complain
"ERROR: Macros with complex values should be enclosed in parentheses".

(cherry picked from commit 61428842dca35dbcef96dcf4b115f23f5ae525e4)

Original-Signed-off-by: Ivan Kuzneczov <ivan.kuzneczov@hardenedvault.net>
Original-Change-Id: I7801dbfd4750be72f0b5b3118fe10649b4908326
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/95704
Original-Reviewed-by: Arthur Heymans <arthur@aheymans.xyz>
Original-Reviewed-by: Angel Pons <th3fanbus@gmail.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: 61428842dca35dbcef96dcf4b115f23f5ae525e4
Cr-Build-Id: 8669125357443457393
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8669125357443457393
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I790e46787069fc07d332467127d9f63fa3041022
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/8479280
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Jon Murphy <jpmurphy@google.com>