dai: intel: dmic: fix shadow variable
Fix a shadow variable build error:

dmic_nhlt.c: In function 'dai_dmic_write_coeff':
dmic_nhlt.c:57:78: error: declaration of 'base' shadows a global
declaration [-Werror=shadow]

(cherry picked from commit 1ddabfa8d8a6d807717dcd4ce0d6a5ee723a89fb)

Original-Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-GitOrigin-RevId: 1ddabfa8d8a6d807717dcd4ce0d6a5ee723a89fb
Original-Change-Id: Ia32a8014fd1795f51f6b0c00750a85f8a3ccf9d2
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4841984
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: ec401041884d04a0b68dc9577ef16edb2ef8db6b
Cr-Build-Id: 8693162543395197713
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693162543395197713
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I73b3f3f7d0048a889487725eff1aba69bf086133
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7422462
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>