zbus: fix error on ZBUS_CHAN_DEFINE
There appear error on `ZBUS_CHAN_DEFINE` when `CONFIG_CPP`
is enabled. Error: `zephyr/zbus/zbus.h:352:9: error: designator
order for field 'zbus_channel_data::highest_observer_priority'
does not match declaration order in `zbus_channel_data`.

to zbus_channel_data structure.

(cherry picked from commit b7bf2091f8e9db5ba1692387ded2cb47b3720aeb)

Original-Original-Solution: change order in `ZBUS_CHAN_DEFINE` macro according
Original-Original-Signed-off-by: Mariusz Dziębowski <mdziebowski@meden.com.pl>
Original-GitOrigin-RevId: b7bf2091f8e9db5ba1692387ded2cb47b3720aeb
Original-Cr-Build-Id: 8738366835818535617
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8738366835818535617
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I450150ab0c5eeac248b64cb17057c36f8057c03c
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5822405
Original-Commit-Queue: Ting Shen <phoenixshen@chromium.org>
Original-Tested-by: Ting Shen <phoenixshen@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Ting Shen <phoenixshen@chromium.org>
GitOrigin-RevId: 4e3335f53b30856b0536a1bc5799d5f5202ffc1b
Cr-Build-Id: 8692966415129288577
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692966415129288577
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Iacb784b3492856d28be1ab90ab0a8621bbe75e71
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7442790
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>