modules: mbedtls: fix pk ecc functions undefined references
Fix undefined reference to mbedtls_pk_ecc_xxx functions following update
to latest mbedtls version.

(cherry picked from commit b876bd26fd7aacbca07041451408425b338e50f2)

Original-Original-Signed-off-by: Joel Guittet <joelguittet@gmail.com>
Original-GitOrigin-RevId: b876bd26fd7aacbca07041451408425b338e50f2
Original-Change-Id: I50100f1af9a96d3f41c81d9bab2d3e2fbd065d6e
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5554681
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: f74a390d3a4a2bae2aee0592c54ceebd9393e1f2
Cr-Build-Id: 8693025198997176577
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693025198997176577
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I9de357eb6dc513b67a0c9c2d8a701d1387dcd6ca
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7436788
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>