chromeos-base/ml: Add missing BDEPEND
```
FAILED: gen/include/ml/benchmark.pb.cc gen/include/ml/benchmark.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
FAILED: gen/include/dbus_adaptors/org.chromium.MachineLearning.AdaptiveCharging.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/ml:9999

Change-Id: I03c34a728a6a21860ad6fa9c33aa8769d87b1669
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692116
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>