net: mqtt: Fix error of `size_t` formatting with `PRIu16`
This addresses the following warning building with `CONFIG_64BIT=y`:

    error: format '%hu' expects argument of type 'int', but argument X has
    type 'size_t' {aka 'long unsigned int'}

(cherry picked from commit de1643d8fb0725b457098e2558a4902980e0284f)

Original-Signed-off-by: Chen Xingyu <hi@xingrz.me>
GitOrigin-RevId: de1643d8fb0725b457098e2558a4902980e0284f
Cr-Build-Id: 8730213107226609921
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730213107226609921
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I6a0367f4c2be4c0c2c4bf2a4aa66efd89cc55170
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6052087
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>