mgmt/mcumgr: add missing designator to ZCBOR_MAP_DECODE_KEY_DECODER
Add missing `.key` designator.

This also fixes a compile error:
> error: either all initializer clauses should be designated or none of
them should be

(cherry picked from commit 6e7268d21bcec208a82bd014cb0281b9adc1b9bf)

Original-Signed-off-by: Jeppe Odgaard <jeppe.odgaard@prevas.dk>
GitOrigin-RevId: 6e7268d21bcec208a82bd014cb0281b9adc1b9bf
Cr-Build-Id: 8703279383919101409
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8703279383919101409
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I6f6988a2b5337c7bcbdc9d4c9d9087cffb7a9b7c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6969599
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Reviewed-by: Jeremy Bettis <jbettis@chromium.org>