linker: ld: lld: do not do RELRO when using llvm/clang
GNU ld and LLVM lld both complain under C++:
  error: section: init_array is not contiguous with other relro sections

So do not create RELRO program header.

(cherry picked from commit 5d9079ba6d2758f3f48ac4adc9d3cfd0b1aa97fa)

Original-Original-Signed-off-by: Daniel Leung <daniel.leung@intel.com>
Original-GitOrigin-RevId: 5d9079ba6d2758f3f48ac4adc9d3cfd0b1aa97fa
Original-Change-Id: Id7fb28dd0607a2a0976941080beef72dd83cf427
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4384640
Original-Tested-by: Al Semjonovs <asemjonovs@google.com>
Original-Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Original-Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
GitOrigin-RevId: 4cdb6e2ced5b07b8ce667e53a250b5b6481b5e16
Cr-Build-Id: 8693310284456022353
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693310284456022353
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I3b58d84bd59f0ba89948aeca9ccb178fe0a77e05
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7411526
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>