Bluetooth: Controller: Add device tree dependency to selection
This commit makes the device tree configuration decide
which link layer is compiled in. We do this to avoid
hard-to-understand linker errors referencing device tree nodes.

The following configuration creates a difficult to parse
linker error:
* BT_LL_CHOICE contains multiple entries, BT_LL_SW_SPLIT
  is selected.
* Each BT_LL_CHOICE has its own unique device tree node with its
  own "compatible".
* Only one of the link layer device tree nodes has status "okay",
  but not the one corresponding to BT_LL_SW_SPLIT.

The linker error indicates that code using the HCI driver fails
to link with the controller. This because the HCI driver device
tree node references the link layer selected in devicetree which
is not compiled in.

By adding a dependendency to the device tree node, this can no longer
happen. Instead, if BT_LL_SW_SPLIT is now selected in a configuration
file, a Kconfig warning will be issued:

```
(defined at subsys/bluetooth/controller/Kconfig:129) was
selected (set =y), but BT_LL_SOFTDEVICE (defined at
/home/ruge/ncs/nrf/subsys/bluetooth/controller/Kconfig:11)
ended up as the choice selection.
```

This should be easier to understand than:

```
...(hci_core.c.obj):(.data.bt_dev+0x16c):
undefined reference to `__device_dts_ord_132'
```

After this commit we should consider getting rid of link layer
selection from Kconfig completely as the link layer is in practice
selected through device tree.

Unit tests have been updated to satisfy the dts dependency.

(cherry picked from commit 417a9e81eca20b85a6f26e417156815cfe2c932a)

Original-Original-warning: The choice symbol BT_LL_SW_SPLIT
Original-Original-Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>
Original-GitOrigin-RevId: 417a9e81eca20b85a6f26e417156815cfe2c932a
Original-Cr-Build-Id: 8735739522938636033
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8735739522938636033
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I86518b0f942bbd5bb24f85b235911955c3b231b9
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5893403
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 3b0bf299d7b7d9ec4e0876edb456c3d629ec08db
Cr-Build-Id: 8692945862648109841
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692945862648109841
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I108f0a8e15f5f6c30c03bde1ec68a963f0f82776
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7444678
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>