Autoupdate of 2 submodules
*chromite updated to 0be30fc68c29e8659d58ec845c953d5169f09fe8
lib: Catch overlooked exception

.. an exception raised from an import class is not the same as the class
defined within the paygen. This caused exceptions to be missed.

chromite.lib.cgpt.Error: Unable to find header in cgpt output
^ cgpt.Error is not the same as <other py file>.Error

BUG=b:287158901
TEST=./run_tests

Change-Id: Ic76571b926e5869fc6ffae888c95a38e03b12189
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4618016
Auto-Submit: Jae Hoon Kim <kimjae@chromium.org>
Tested-by: Jae Hoon Kim <kimjae@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Yuanpeng Ni‎ <yuanpengni@chromium.org>

*infra/chromite-HEAD updated to 0be30fc68c29e8659d58ec845c953d5169f09fe8
lib: Catch overlooked exception

.. an exception raised from an import class is not the same as the class
defined within the paygen. This caused exceptions to be missed.

chromite.lib.cgpt.Error: Unable to find header in cgpt output
^ cgpt.Error is not the same as <other py file>.Error

BUG=b:287158901
TEST=./run_tests

Change-Id: Ic76571b926e5869fc6ffae888c95a38e03b12189
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4618016
Auto-Submit: Jae Hoon Kim <kimjae@chromium.org>
Tested-by: Jae Hoon Kim <kimjae@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Yuanpeng Ni‎ <yuanpengni@chromium.org>