BACKPORT: Bluetooth: btmtk: Fix btmtk.c undefined reference build error
MediaTek moved some usb interface related function to btmtk.c which
may cause build failed if BT USB Kconfig wasn't enabled.
Fix undefined reference by adding config check.

btmtk.c:(.text+0x89c): undefined reference to `usb_alloc_urb'
btmtk.c:(.text+0x8e3): undefined reference to `usb_free_urb'
btmtk.c:(.text+0x956): undefined reference to `usb_free_urb'
btmtk.c:(.text+0xa0e): undefined reference to `usb_anchor_urb'
btmtk.c:(.text+0xb43): undefined reference to `usb_autopm_get_interface'
btmtk.c:(.text+0xb7e): undefined reference to `usb_autopm_put_interface'
btmtk.c:(.text+0xf70): undefined reference to `usb_disable_autosuspend'
btmtk.c:(.text+0x133a): undefined reference to `usb_control_msg'

Fixes: d019930b0049 ("Bluetooth: btmtk: move btusb_mtk_hci_wmt_sync to btmtk.c")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202407091928.AH0aGZnx-lkp@intel.com/
Signed-off-by: Chris Lu <chris.lu@mediatek.com>
Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
(cherry picked from commit f0c83a23fcbb424fdff5b38fbcdda3c04003a210
 https://git.kernel.org/pub/scm/linux/kernel/git/bluetooth/bluetooth-next.git master)

BUG=b:308395932
TEST=build pass bluetooth basic function pass on Brya

Backport Notes:
MediaTek BT reset flow refactor in the latest Kerenl.

Fix Conflict:
drivers/bluetooth/btmtk.c
drivers/bluetooth/btmtk.h

Change-Id: I0989794c451b6a673238d4b43c99326bf16d188e
Signed-off-by: Chris Lu <chris.lu@mediatek.corp-partner.google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/5792844
Reviewed-by: Yun-hao Chung <howardchung@chromium.org>
Commit-Queue: Yun-hao Chung <howardchung@chromium.org>
Tested-by: Yun-hao Chung <howardchung@chromium.org>