tests: subsys: mgmt: Fix warning of `size_t` formatting with `%.*s`
This addresses the following warning building with `CONFIG_64BIT=y`:

    error: field precision specifier '.*' expects argument of type 'int',
    but argument X has type 'size_t' {aka 'long unsigned int'}

(cherry picked from commit 1dd6d0db6785626b143d53e559d708725075ac9c)

Original-Signed-off-by: Chen Xingyu <hi@xingrz.me>
GitOrigin-RevId: 1dd6d0db6785626b143d53e559d708725075ac9c
Cr-Build-Id: 8730286630880259329
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730286630880259329
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I9c5b1bab890c2f0291ab0e500336703f54fb29c0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6045628
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>