twister: coverage: set gcov working directory
gcovr runs gcov to generate temporary coverage files into the gcov
working directory. The working directory defaults to gcovr's -r
argument.

When running twister with the --coverage-per-instance argument, multiple
gcovr instances may run in parallel. Since they all share the same gcov
working directory, they may interfere with each other, resulting in
errors like this:

	AssertionError: Sanity check failed, output file
	spinlock.h##4167b923a06cc9590c8eef372f016a6d.gcov doesn't exist
	but no error from GCOV detected.

To fix this, specify a separate gcov working directory for every test
through gcovr's --gcov-object-directory option.

(cherry picked from commit d45985347b47f608ad6cf731e5d679fe22913ae3)

Original-Original-Signed-off-by: Marco Widmer <marco.widmer@bytesatwork.ch>
Original-GitOrigin-RevId: d45985347b47f608ad6cf731e5d679fe22913ae3
Original-Cr-Build-Id: 8706540875242396545
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8706540875242396545
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I45b59a58f543dfef7aa567721c72a93628b4c946
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6851660
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 9758e976d19df32b296e49c716fb087e40c59beb
Cr-Build-Id: 8692725257821836673
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692725257821836673
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: If054b105fdb26b7dab3972bbbac5bc329412de4c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7470208
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>