Bluetooth: Classic: Fix invalid comparison with int8_t
We can't use 0xff to compare with an int8_t since it'll trigger compiler
warnings/errors:

subsys/bluetooth/host/classic/br.c:397:11: error: result of comparison of
constant 255 with expression of type 'int8_t' (aka 'signed char') is
always false [-Werror,-Wtautological-constant-out-of-range-compare]
        if (rssi == 0xff) {
            ~~ ^  ~~
1 error generated.

Use 127 instead for situations where we don't know the RSSI value, like
when processing remote name events. This is fine since from a spec
perspective only -127 - +20 are valid values for the parameter.

(cherry picked from commit c9647a55fee87d42a198c35c48a0d154ce14d823)

Original-Original-Signed-off-by: Johan Hedberg <johan.hedberg@silabs.com>
Original-GitOrigin-RevId: c9647a55fee87d42a198c35c48a0d154ce14d823
Original-Cr-Build-Id: 8725543589450806177
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8725543589450806177
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I179aab52d00f613318d362e787bb6f9632e558bf
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6181108
Original-Commit-Queue: Jonathon Murphy <jpmurphy@google.com>
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
GitOrigin-RevId: f496b5e79bce09541b0662e8d0e63d2d2abdf303
Cr-Build-Id: 8692876761902365697
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692876761902365697
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I5b6960902eb047e08f552b32c7f7604318b0b1c4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7453197
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>