llext: hotfix: fix function pointer logging
Some function pointers were being passed via `%p` to LOG_DBG, and this
was causing the following issues in SOF CI with the `sparse` checker:

   subsys/llext/llext.c: error: arithmetics on pointers to functions
   subsys/llext/llext.c: error: incompatible types for operation (+)

This patch fixes the issue by casting the function pointers to void*.
Also fix a misleading error message in `llext_get_fn_table()`.

(cherry picked from commit e6b32ab68145df10ee2029e2e462e60adc3d8cf4)

Original-Original-Signed-off-by: Luca Burelli <l.burelli@arduino.cc>
Original-GitOrigin-RevId: e6b32ab68145df10ee2029e2e462e60adc3d8cf4
Original-Cr-Build-Id: 8736917283475341809
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8736917283475341809
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I9145adce289b3f99106daf6c0301c8d73ad108ce
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5856256
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: fbaa81156b9b20be97abccf32d55a1cf0a361d23
Cr-Build-Id: 8692957049763707889
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692957049763707889
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I3256908a9fa1e6ea2379ba7e117ba1f6afa91031
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7443606
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>