cros-rust.eclass: fix bindgen cross-* sysroot
Starting with glibc 2.41 we are finally enabling
float128 support. Its implementation is different
between x86 and arm architectures.

For example the x86 headers provide __float128 while
arm provides _Float128, therefore it's important to
include the proper headers for each architecture.

The vboot_reference-sys crate started failing with:

BOARD: arm64-generic (aarch64-cros-linux-gnu)
ERROR:
  /usr/include/bits/floatn.h:97:9: error: __float128 is not supported on this target
  Error: unable to generate bindings for vboot_host.h

Thus, with float128 we have uncovered an existing bug:
bindgen was including headers from the host instead of
the relevant sysroots.

This is because bingden bypasses the compiler wrapper
and uses libclang, ignoring the --syroot arg.

Ensure the --sysroot arg gets passed to bindgen by
exporting BINDGEN_EXTRA_CLANG_ARGS.

BUG=b:335699866
TEST=Local builds on host, amd64 (eve), arm; CQ;

Cq-Depend: chromium:6438811
Change-Id: Iec5e03cfa8cfacf88ab294922a7483090552216e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/6415856
Commit-Queue: ChromeOS Auto Retry <chromeos-auto-retry@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: George Burgess <gbiv@chromium.org>
Reviewed-by: Jordan Abrahams-Whitehead <ajordanr@google.com>
Reviewed-by: Alex Klein <saklein@chromium.org>
Auto-Submit: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>