dome: Prevent some console error with factory_drive_list.tsx file
Make some changes to avoid these error messages:

```
● Test suite failed to run

Jest encountered an unexpected token

Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
```
and details about the error:

```
Details:

/usr/local/google/home/rueifong/chromiumos/src/platform/factory/py/dome/frontend/node_modules/@mui/material/colors/grey.js:17
export default grey;
^^^^^^

SyntaxError: Unexpected token 'export'
```

BUG=None
TEST=make test

Change-Id: I8fc44cd126c0995c98ca113331c8c74505f920b4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/factory/+/7149382
Tested-by: Ruei-fong Lyu <rueifong@google.com>
Reviewed-by: Wen-Ting Tseng <wdzeng@chromium.org>
Commit-Queue: Ruei-fong Lyu <rueifong@google.com>