modules: lvgl: fix multiple LVGL inputs
The LVGL input callback does not use an instance specific name, so we
can only ever have one instance of this type. This issue was evident by
a build error, e.g., when using "zephyr,lvgl-keypad-input" nodes twice:

  error: redefinition of '_input_callback__lvgl_keypad_process_event'

(cherry picked from commit 5bcb5242ed352f05b870d290c97c4388586064d1)

Original-Original-Signed-off-by: Gero Schwäricke <gero.schwaericke@posteo.de>
Original-GitOrigin-RevId: 5bcb5242ed352f05b870d290c97c4388586064d1
Original-Cr-Build-Id: 8735286451693989857
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8735286451693989857
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I5fc5727f3a4749bfd6858477c71b1f869fe5b413
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5901538
Original-Tested-by: Al Semjonovs <asemjonovs@google.com>
Original-Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Al Semjonovs <asemjonovs@google.com>
GitOrigin-RevId: 207fb7d87488dac0f70674d840aa2dda885c103d
Cr-Build-Id: 8692945862648109841
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692945862648109841
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I2e9285b4ae1a8373638813ff15a5ce3fa073793d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7444807
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>