Bluetooth: Classic: AVRCP: Fix Clang/LLVM build failures
Having variable declarations after labels causes build failures with
Clang/LLVM:

subsys/bluetooth/host/classic/avrcp.c:1269:2: error: label followed by a
declaration is a C23 extension [-Werror,-Wc23-extensions]
 1269 |         uint8_t failed_evt = 0;
      |         ^

/subsys/bluetooth/host/classic/avrcp.c:3809:3: error: label followed by a
declaration is a C23 extension [-Werror,-Wc23-extensions]
 3809 |              uint64_t identifier = sys_get_be64(data->identifier);
      |              ^

Fix these by moving the declarations to the top of the function in the
first case and add braces for the second.

(cherry picked from commit 445431c77922486b52e6df03c3f5c922dfbb1bd5)

Original-Signed-off-by: Johan Hedberg <johan.hedberg@silabs.com>
GitOrigin-RevId: 445431c77922486b52e6df03c3f5c922dfbb1bd5
Cr-Build-Id: 8698228605132682497
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8698228605132682497
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ib5f5cd87ed5f054b7094c5bbc02a4d52a770647f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7157513
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>