dev-util/cros-test-ready: Add missing dependency
```
  File "/build/arm64-generic/tmp/portage/dev-util/cros-test-ready-9999/work/cros-test-ready-9999/src/chromiumos/test/check/python/cros_test_ready_config_generator.py", line 13, in <module>
    from chromiumos.test.api import cros_test_ready_cli_pb2 as test_ready_pb
ModuleNotFoundError: No module named 'chromiumos'
 * ERROR: dev-util/cros-test-ready-9999::chromiumos failed (install phase):
```

```
  File "/usr/lib/python3.8/site-packages/chromiumos/test/api/cros_test_ready_cli_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
```

```
Traceback (most recent call last):
  File "/build/arm64-generic/tmp/portage/dev-util/cros-test-ready-9999/work/cros-test-ready-9999/src/chromiumos/test/check/python/cros_test_ready_config_generator.py", line 15, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

Also added python-any-r1 since the build executes python.

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/dev-util/cros-test-ready:9999

Change-Id: If2423c8be727a2d520e047ef9eb967757524ef3f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4836962
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>