uart_qmsi: Remove uart_qmsi_pm_save_config
One remaining reference to uart_qmsi_pm_save_config
was missed by patch bc60506d3e5d1cb2c46fda3bebe35467d084699b.

This reference is removed.

This fixes the following error:
...
drivers/built-in.o: In function `uart_qmsi_line_ctrl_set':
/drivers/serial/uart_qmsi.c:439:
undefined reference to `uart_qmsi_pm_save_config'
...

Original-collect2: error: ld returned 1 exit status
Original-Change-Id: I1ceda0e152db5a1c7f70d67c04b931416687031a
Original-Signed-off-by: Julien Delayen <julien.delayen@intel.com>
GitOrigin-RevId: 54b5085e8aa47994d995925dd84c8da25a58b2d2
Cr-Build-Id: 8694734771194294641
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694734771194294641
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I7e5e09df4967c7fd27307f25314aff4ee39e54e9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7305531
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>