Reland "chromeos-base/chromeos-chrome: Add missing BDEPEND"
This reverts commit ee88d6d2dbc3ef77baa8af5ed217a8ef1faf8a10.

Reason for revert: The create_sysroot script no longer tries to pull
in BDEPEND. See https://chromium-review.googlesource.com/4730216.

Original change's description:
> Revert "chromeos-base/chromeos-chrome: Add missing BDEPEND"
>
> This reverts commit 85d484a54ac8eaae2826d3f3b0c9b113f8aff41b.
>
> Reason for revert: Breaking Chrome sysroot generation.
>
> Original change's description:
> > chromeos-base/chromeos-chrome: Add missing BDEPEND
> >
> > ```
> > FAILED: gen/third_party/blink/renderer/platform/color_data.cc
> > FileNotFoundError: [Errno 2] No such file or directory: 'gperf': 'gperf'
> > ```
> >
> > ```
> >   File "/home/root/chrome_root/src/third_party/mako/mako/mako/compat.py", line 68, in <module>
> >     import importlib_metadata  # noqa
> > ModuleNotFoundError: No module named 'importlib_metadata'
> > ```
> >
> > ```
> > FAILED: nacl_helper_arm32/obj/base/third_party/double_conversion/double_conversion/string-to-double.o
> > armv7a-cros-linux-gnueabihf-clang++ -MMD -MF nacl_helper_arm32/obj/base/third_party/double_conversion/double_conversion/string-to-double.o.d
> > ../../../../../../../home/root/chrome_root/src/buildtools/third_party/libc++/trunk/include/__config:283:14: fatal error: 'features.h' file not found
> > ```
> >
> > ```
> > ../../../../../../../home/root/chrome_root/src/third_party/skia/src/ports/SkFontConfigInterface_direct.h:14:10: fatal error: 'fontconfig/fontconfig.h' file not found
> > ```
> >
> > ```
> > ../../../../../../../home/root/chrome_root/src/net/http/http_auth_gssapi_posix.h:26:10: fatal error: 'gssapi.h' file not found
> > ```
> >
> > ```
> >   File "/build/arm64-generic/tmp/portage/chromeos-base/chromeos-chrome-117.0.5859.0_rc-r1/work/autotest-work/autotest_lib/client/bin/utils.py", line 16, in <module>
> >     import chardet
> > ModuleNotFoundError: No module named 'chardet'
> > ```
> >
> > ```
> > /build/arm64-generic/tmp/portage/chromeos-base/chromeos-chrome-117.0.5859.0_rc-r1/temp/environment: line 1885: git: command not found
> > ```
> >
> > BUG=b:278728702
> > TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/chromeos-chrome:117.0.5859.0_rc-r1
> >
> > Change-Id: Idcce4742889f84738c9c761b6d93ac2d94df699b
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692258
> > Commit-Queue: Raul Rangel <rrangel@chromium.org>
> > Reviewed-by: Alex Klein <saklein@chromium.org>
> > Tested-by: Raul Rangel <rrangel@chromium.org>
>
> BUG=b:278728702, b:291914996
>
> Change-Id: I68db9a55381f838438c7bf95a416621e9053457b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4702267
> Auto-Submit: Mike Frysinger <vapier@chromium.org>
> Commit-Queue: Alex Klein <saklein@chromium.org>
> Tested-by: Mike Frysinger <vapier@chromium.org>
> Reviewed-by: Pilar Molina Lopez <pmolinalopez@google.com>
> Reviewed-by: Alex Klein <saklein@chromium.org>
> Reviewed-by: Jonathon Murphy <jpmurphy@google.com>

BUG=b:278728702, b:291914996
TEST=CQ

Cq-Depend: chromium:4730216
Change-Id: I600e643b10c7c1ffc3aad591c485b7550da0d7bc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4727823
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
Reviewed-by: Mike Frysinger <vapier@chromium.org>