chromeos-base/chromeos-imageburner: Add missing BDEPEND
```
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
ninja: build stopped: subcommand failed.
18:01:15.429: ERROR: Ninja failed
 * ERROR: chromeos-base/chromeos-imageburner-9999::chromiumos failed (compile phase):
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/chromeos-imageburner:9999

Change-Id: I9450f7b756609108dbdfa95fb639346374439772
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692082
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>