FROMGIT: Bluetooth: coredump: fix building with coredump disabled
The btmtk driver uses an IS_ENABLED() check to conditionally compile
the coredump support, but this fails to build because the hdev->dump
member is in an #ifdef:

drivers/bluetooth/btmtk.c: In function 'btmtk_process_coredump':
drivers/bluetooth/btmtk.c:386:30: error: 'struct hci_dev' has no member named 'dump'
  386 |   schedule_delayed_work(&hdev->dump.dump_timeout,
      |                              ^~

The struct member doesn't really make a huge difference in the total size,
so just remove the #ifdef around it to avoid adding similar checks
around each user.

Fixes: 872f8c253cb9e ("Bluetooth: btusb: mediatek: add MediaTek devcoredump support")
Fixes: 9695ef876fd12 ("Bluetooth: Add support for hci devcoredump")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
(cherry picked from commit 45018a3caf9b3c65c2fbb1e00216b212734f74dc
 https://kernel.googlesource.com/pub/scm/linux/kernel/git/next/linux-next master)

BUG=b:227610040
TEST=CQ

Change-Id: Icbf4dbb97bf0ff3f305793666a7d81cee8a4f169
Signed-off-by: Aashish Sharma <shraash@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4741212
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Sean Paul <sean@poorly.run>
(cherry picked from commit 4a6e958bbf247929b0fec46c8de8860d2f4e0774)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4740255
Commit-Queue: Guenter Roeck <groeck@chromium.org>