net: capture: enable capturing of IPv6/v4 only
Net capturing would not link when either IPv6 or IPv4 was switched off
due to missing symbols. This change allows for capturing a single IP
protocol only.

To reproduce:

samples/net/sockets/http_client/prj.conf
```
-CONFIG_NET_IPV4=y
+CONFIG_NET_IPV4=n
-CONFIG_NET_CONFIG_NEED_IPV4=y
+CONFIG_NET_CONFIG_NEED_IPV4=n
+
+CONFIG_NET_CAPTURE=y
```

This will cause the following linker error:
```
.../subsys/net/lib/capture/capture.c:648:
    undefined reference to `net_if_ipv4_get_ttl'
```

(cherry picked from commit 9d1874f7f91be79d9dddd15d407a1cb7f9d8ee9d)

Original-Original-Signed-off-by: Florian Grandel <fgrandel@code-for-humans.de>
Original-GitOrigin-RevId: 9d1874f7f91be79d9dddd15d407a1cb7f9d8ee9d
Original-Cr-Build-Id: 8738508474594683537
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8738508474594683537
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ic64d1e336a7886da6817167e6cb0a03e2ef37873
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5814313
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 9214defb62c987983bfddc86322f948ba8b7a68a
Cr-Build-Id: 8692968494524072993
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692968494524072993
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I1a423b23747ef8a9bc3d648b0b04f914cabf7025
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7442607
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>