modules: hal_nordic: nrfx: Compile NRFX_GPPI modules for 54lbsim
We should use CONFIG_SOC_COMPATIBLE_NRF54L15 whenever possible.
With the current bsim model of 54L these files do not yet compile,
but that can be added separately.

Compilation warning:
```
/nrfx_interconnect_dppic_ppib.c:158:36:
[-Wimplicit-function-declaration]
  158 |         uint8_t bus_address_area =
	nrf_address_bus_get(addr, p_dppic->apb_size);
      |                                    ^~~~~~~~~~~~~~~~~~~
```

(cherry picked from commit 81ed3432129307ef67f3b970bc654d7acb03244a)

Original-Original-warning: implicit declaration of function ‘nrf_address_bus_get’
Original-Original-Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>
Original-GitOrigin-RevId: 81ed3432129307ef67f3b970bc654d7acb03244a
Original-Cr-Build-Id: 8726362737952124785
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8726362737952124785
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ib969716062d4cd407211160acdcc0f93986ea7c8
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6154022
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: f59f6cca555b5fbced2b97050738524bc2628e9d
Cr-Build-Id: 8692883578826147009
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692883578826147009
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I792effd85b3eb9f4a59f75679aab6c0eaab64de8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7452183
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>