eclass/autotest{,-deponly}: Add missing BDEPEND
```
Performing autotest_lib import
Traceback (most recent call last):
  File "/build/arm64-generic/tmp/portage/chromeos-base/autotest-deps-graphics-9999/work/autotest-work/autotest_lib/client/common_lib/hosts/__init__.py", line 11, in <module>
    from autotest_lib.client.common_lib.hosts.base_classes import Host
  File "/build/arm64-generic/tmp/portage/chromeos-base/autotest-deps-graphics-9999/work/autotest-work/autotest_lib/client/common_lib/hosts/base_classes.py", line 27, in <module>
    from autotest_lib.client.common_lib.cros import path_utils
  File "/build/arm64-generic/tmp/portage/chromeos-base/autotest-deps-graphics-9999/work/autotest-work/autotest_lib/client/common_lib/cros/path_utils.py", line 8, in <module>
    from autotest_lib.client.bin import utils
  File "/build/arm64-generic/tmp/portage/chromeos-base/autotest-deps-graphics-9999/work/autotest-work/autotest_lib/client/bin/utils.py", line 16, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/autotest-all:0.0.1-r59_package_set

Change-Id: I72dbf09cd88933dba1a42c2846d6a9d688c6141d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4844758
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>