net: dns: Check query index in dns_read
This commit adds a check, in the `dns_read` function, before
dereferencing the query index returned by the `dns_validate_msg`
function.

This fixes the warnings generated by the GCC 12 such as:

  error: array subscript -1 is below array bounds of
  'struct dns_pending_query[5]' [-Werror=array-bounds]

(cherry picked from commit 8fe855f166baf73083fd905474d3f5bd6e2e7de1)

Original-Original-Signed-off-by: Stephanos Ioannidis <root@stephanos.io>
Original-GitOrigin-RevId: 8fe855f166baf73083fd905474d3f5bd6e2e7de1
Original-Change-Id: Id332717bc49826d8b58de95aa786c59ee5ca05c9
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3822993
Original-Commit-Queue: Jack Rosenthal <jrosenth@chromium.org>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
GitOrigin-RevId: 3aeab31ed78458b5dc370c420b87885ebbc09f5c
Cr-Build-Id: 8693488060366067793
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693488060366067793
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I1075338a50e27264f466061839ff2b60f490b559
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7398404
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>