kernel: events: Depend on multithreading
Kernel events depend on multithreading being enabled, and mixing them
with a non-multithreaded build gives linker failures internal to
events.c. To avoid this, make events depend on multithreading.

```
libkernel.a(events.c.obj): in function `k_event_post_internal':
events.c:183: undefined reference to `z_sched_wake_thread'
events.c:191: undefined reference to `z_reschedule'
libkernel.a(events.c.obj): in function `k_sched_current_thread_query':
kernel.h:216: undefined reference to `z_impl_k_sched_current_thread_query'
libkernel.a(events.c.obj): in function `k_event_wait_internal':
events.c:312: undefined reference to `z_pend_curr'
```

(cherry picked from commit cd8e773b325722e5d7b67427f3ebb88bd971b2f5)

Original-175: undefined reference to `z_sched_waitq_walk'
Original-Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>
GitOrigin-RevId: cd8e773b325722e5d7b67427f3ebb88bd971b2f5
Cr-Build-Id: 8699564905169231937
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8699564905169231937
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ia4ebf43735e78b8188757417ba069fafebc5e8f5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7100968
Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Tested-by: Dawid Niedźwiecki <dawidn@google.com>