pm: use braces for .pm_base inside anonymous union initializer
Fixes commit 25173f71cda6 ("pm: device_runtime: Extend with synchronous
runtime PM")

Fixes compilation with gcc 4.2-based toolchain used by SOF for TGL
generation products. As seen in the error message below, that gcc
version requires braces for initialization of anonymous unions:

```
zephyr/soc/xtensa/intel_adsp/common/mem_window.c:62:
   error: unknown field ‘pm_base’ specified in initializer
   warning: missing braces around initializer
   warning: (near initialization for ‘__device_dts_ord_66.<anonymous>’)
```

This is a well-known and recurring issue, see past example(s) in #68118

As the Zephyr build is deterministic, I could easily verify that this
commit makes zero .obj difference (when using the Zephyr SDK).

(cherry picked from commit f91d4731af4e4edfa5c316a02c14ac145f027c52)

Original-Original-Signed-off-by: Marc Herbert <marc.herbert@intel.com>
Original-GitOrigin-RevId: f91d4731af4e4edfa5c316a02c14ac145f027c52
Original-Change-Id: I5b4af6516720a66037cc01aee398e456444aa4e9
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5315064
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: f30bc91cb89832df3b593db2846d0d781758b58e
Cr-Build-Id: 8693074504754244897
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693074504754244897
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I7198d8a9cd6812adf55952213ee0a0fa1e84a661
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7432037
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>