chromeos-base/factory-mini: Add missing rsync BDEPEND
```
Building PAR build/par/factory-mini.par...
Traceback (most recent call last):
  File "/build/amd64-generic/tmp/portage/chromeos-base/factory-mini-0.0.1-r3805/work/factory-mini-0.0.1/build/tmp/par/py/cli/make_par.py", line 308, in <module>
    sys.exit(0 if main() else 1)
  File "/build/amd64-generic/tmp/portage/chromeos-base/factory-mini-0.0.1-r3805/work/factory-mini-0.0.1/build/tmp/par/py/cli/make_par.py", line 162, in main
    Spawn([
  File "/build/amd64-generic/tmp/portage/chromeos-base/factory-mini-0.0.1-r3805/work/factory-mini-0.0.1/build/tmp/par/py_pkg/cros/factory/utils/process_utils.py", line 425, in Spawn
    process = ExtendedPopen(args, encoding=encoding, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'rsync'
make: *** [Makefile:342: par] Error 1
 * ERROR: chromeos-base/factory-mini-0.0.1-r3805::chromiumos failed (compile phase):
 ```

BUG=b:317413089
TEST=bazel CQ

Change-Id: I044f6b21638034bc86d9d28c860f3a6df6334127
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/5233984
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>