tests: i2c_emul: Remove unused variable
Building with clang warns:

tests/drivers/i2c/i2c_emul/src/test_forwarding_buf.cpp:20:32: error:
unused variable 'targets' [-Werror,-Wunused-const-variable]
constexpr const struct device *targets[FORWARD_COUNT] = {
                               ^

(cherry picked from commit 782152f404b9dfd96f9922f62c466b8e4e06c953)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: 782152f404b9dfd96f9922f62c466b8e4e06c953
Cr-Build-Id: 8723052172249940737
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723052172249940737
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Iafa99afc81c6bde3184a52e65aea36a59a2f48d7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6261362
Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>