Restore original ifdef in limits.h for the include_next of system's limits.h
Commit 2f5f8439bd61e93e0f42d8009324d8c5227153c1 made changes to the
preprocessor guard that gated the include_next directive for limits.h

Currently the guard looks something like this:

```
ifdef __GNUC__
 include_next<limits.h>
endif
```

The original guard, on the other hand, also checked for _GCC_LIMITS_H_.
This extra condition is necessary to build with Clang. This error
message is shown:

> fatal error: 'limits.h' file not found

Because include_next is run when it shouldn't.

(cherry picked from commit 59843b2e121129ad5fafaa615dbfa4e1c472fd48)

GitOrigin-RevId: 59843b2e121129ad5fafaa615dbfa4e1c472fd48
Cr-Build-Id: 8731843854058218129
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8731843854058218129
Copybot-Job-Name: zephyr-picolibc-copybot-downstream
Change-Id: I739a3881c527fbc675ecda87079b625a96c7d8c0