UPSTREAM: pw_build_info: Use correct variable type for git tree dirty var
Fixes clang-tidy finding:

bazel-out/k8-fastbuild/bin/external/pigweed+/pw_build_info/git_build_info.h:23:32: error: converting integer literal to bool, use bool literal instead [modernize-use-bool-literals,-warnings-as-errors]
   23 | constexpr bool kGitTreeDirty = 1;
      |                                ^
      |                                true

(cherry picked from commit d2b2644598a297cc7d6b2fec16225ea5348e0a31)

Original-Change-Id: I1171fe3b66e1e39b7df57ad7a02d598b1d2af19b
Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/317392
Original-Docs-Not-Needed: Austin Foxley <afoxley@google.com>
Original-Presubmit-Verified: CQ Bot Account <pigweed-scoped@luci-project-accounts.iam.gserviceaccount.com>
Original-Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Original-Pigweed-Auto-Submit: Austin Foxley <afoxley@google.com>
Original-Reviewed-by: Armando Montanez <amontanez@google.com>
Original-Commit-Queue: Austin Foxley <afoxley@google.com>
GitOrigin-RevId: d2b2644598a297cc7d6b2fec16225ea5348e0a31
Cr-Build-Id: 8705155496287882065
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8705155496287882065
Copybot-Job-Name: pigweed-main-copybot-downstream
Change-Id: Ic0bfbfe1b68c0a3e9715409d94deaf8b06e4be1c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/pigweed/pigweed/+/6902163
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>