armclang: fix compiler warnings with isprint()
We get compile warnings of the form:

drivers/console/uart_console.c:508:8: error: converting the result of
'<<' to a boolean; did you mean
'((__aeabi_ctype_table_ + 1)[(byte)] << 28) != 0'?
 [-Werror,-Wint-in-bool-context]
                if (!isprint(byte)) {
                     ^

Since isprint returns an int, change check to an explicit test against
the return value.

(cherry picked from commit 831bd2f841faa49008c4acd471bb019f44de1c9d)

Original-Original-Signed-off-by: Kumar Gala <kumar.gala@intel.com>
Original-GitOrigin-RevId: 831bd2f841faa49008c4acd471bb019f44de1c9d
Original-Change-Id: I13ecd0e0c79e61012b348c5f88055f3d456a0873
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4350077
Original-Reviewed-by: Aaron Massey <aaronmassey@google.com>
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: 5c1a7dafcbcaa90abf37b5b718e119aaba53e75a
Cr-Build-Id: 8693323063598468129
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693323063598468129
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I7946d418abe53b9e14b8d15751223af67614c13e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7410468
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>