tests: bluetooth: classic: Remove self assignment
When building with clang it warns about self-assignment in the
bluetooth.classic.sdp_s test:

tests/bluetooth/classic/sdp_s/src/sdp_server.c:258:5: error: explicitly
assigning value of variable of type 'const struct shell *' to itself
[-Werror,-Wself-assign]
  258 |         sh = sh;
      |         ~~ ^ ~~
tests/bluetooth/classic/sdp_s/src/sdp_server.c:277:5: error: explicitly
assigning value of variable of type 'const struct shell *' to itself
[-Werror,-Wself-assign]
  277 |         sh = sh;
      |         ~~ ^ ~~
tests/bluetooth/classic/sdp_s/src/sdp_server.c:290:5: error: explicitly
assigning value of variable of type 'const struct shell *' to itself
[-Werror,-Wself-assign]
  290 |         sh = sh;
      |         ~~ ^ ~~
tests/bluetooth/classic/sdp_s/src/sdp_server.c:368:5: error: explicitly
assigning value of variable of type 'const struct shell *' to itself
[-Werror,-Wself-assign]
  368 |         sh = sh;
      |         ~~ ^ ~~
4 errors generated.

The "sh" variable is used later in the functions.

(cherry picked from commit 32b63c63edc82324c4d10b18e79858ad8fa8e56d)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: 32b63c63edc82324c4d10b18e79858ad8fa8e56d
Cr-Build-Id: 8692611591669624993
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692611591669624993
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I567c4f39e08465de41855417836080c971d52ce7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7484460
Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: Jeremy Bettis <jbettis@chromium.org>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jeremy Bettis <jbettis@chromium.org>