chromeos-base/cryptohome: Add missing BDEPEND
```
FAILED: gen/include/cryptohome/flatbuffer_schemas/user_secret_stash.h
Traceback (most recent call last):
  File "gen/python/flatbuffer_cpp_binding_generator.py", line 89, in <module>
    from reflection.Schema import Schema
  File "/build/arm64-generic/var/cache/portage/chromeos-base/cryptohome/out/Default/gen/python/reflection/Schema.py", line 5, in <module>
    import flatbuffers
ModuleNotFoundError: No module named 'flatbuffers'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/cryptohome:9999

Change-Id: I1dbfed5a85d6e43fea73cc30465bc648e4a96d35
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692093
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>