test: timer: Fix symbol conflict
Timer test fail to build with the error below:

    .../tick_timer_train.c:12: error: "TIMERS" redefined [-Werror]
       12 | #define TIMERS 4
          |
    In file included from .../zephyr/soc/.../siwg917/soc.h:8,
                     from .../modules/cmsis_6/cmsis_core_m.h:24,
                     from .../modules/cmsis_6/cmsis_core.h:10,
                     from .../zephyr/include/.../asm_inline_gcc.h:24,
                     from .../zephyr/include/.../asm_inline.h:18,
                     from .../zephyr/include/.../arch.h:30,
                     from .../zephyr/include/.../cpu.h:19,
                     from .../zephyr/include/.../kernel_includes.h:36,
                     from .../zephyr/include/.../kernel.h:17,
                     from .../zephyr/tests/.../tick_timer_train.c:7:
    .../modules/hal/silabs/wiseconnect/components/.../si91x_device.h:15930:
                     note: this is the location of the previous definition

Indeed, the CMSIS interface of Silabs siwx91x also defines "TIMERS" symbol.
"TIMERS" is a common names in the CMSIS interfaces. So, it makes sense to
avoid to redefine it in the applications.

Original-Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>
GitOrigin-RevId: 5353e4db6c582e3d8a6e2c57673120c5794e7d73
Cr-Build-Id: 8690188123194777697
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8690188123194777697
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I6c53ebf2930cf7314090f23efedd99848798e564
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7565883
Commit-Queue: Keith Short <keithshort@chromium.org>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>