scripts: west_commands: patch: capture subprocess output in apply() method
Pass 'capture_output=True' to the 'subprocess.run()' call in the 'apply()'
method.
This ensures that stdout and stderr are captured, so 'proc.stderr'
is not 'None' when 'self.err()' is called on a failed process.

Example without this patch:
west patch apply --roll-back
FATAL ERROR: failed to apply patch libcsp/test.patch

Example with this patch:
west patch apply --roll-back
FATAL ERROR: failed to apply patch libcsp/test.patch

(cherry picked from commit 634b45edddd55a923a74f923cf2d3c0540a5bfb0)

Original-error: patch failed: examples/csp_server_client.py:32
Original-error: examples/csp_server_client.py: patch does not apply
Original-ERROR: None
Original-ERROR: b'error: patch failed: examples/csp_server_client.py:32\n
Original-error: examples/csp_server_client.py: patch does not apply\n'
Original-Signed-off-by: Mirai SHINJO <oss@mshinjo.com>
GitOrigin-RevId: 634b45edddd55a923a74f923cf2d3c0540a5bfb0
Cr-Build-Id: 8697956813069601489
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8697956813069601489
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I8686ec9b052d644de880c3828077bc8e9e6f815f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7159640
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>