net: lib: shell: dns: Fix field precission specifier type
Explicitly cast down the string width to int, as otherwise it is
size_t which may have a bigger size.

Avoids the following build error:

subsys/net/lib/shell/dns.c:496:67: error: field precision specifier
‘.*’ expects argument of type ‘int’, but argument 4 has type ‘size_t’
{aka ‘long unsigned int’}

(cherry picked from commit 499aa995f6d8e16a3110447bec719f9a2d2bc4fd)

Original-Original-Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
Original-GitOrigin-RevId: 499aa995f6d8e16a3110447bec719f9a2d2bc4fd
Original-Cr-Build-Id: 8700380283100427425
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8700380283100427425
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I2a2d930ef36e730dfd13371dafb1d93d6fe0957c
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7069662
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: d4580e01582e72041003bc4f4f48cabc4aaf3f5a
Cr-Build-Id: 8692663046855492273
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692663046855492273
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I35d3536c411ddb5d57e1a0daba38db3c7e4cbc44
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7477737
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>