Revert "bisect-kit: Add dut_state:ready filter"
This reverts commit d4f843d0bf5a35b363d69a848d504e74999ebf65.

Reason for revert:
This CL appears to be causing the following error
```
    Allocating a DUT from the lab: end
{"result": "failed", "exception": "NameError", "text": "name 'x' is not defined"}
-----
log file = bisect.sessions/f6980f46-c023-41d3-a23e-c0a071f7686c/bisect-kit.log
06:45:59 INFO boards with prebuilt: ['skyrim']
06:46:01 ERROR cmd_allocate_dut failed
Traceback (most recent call last):
  File "/usr/local/google/home/cros-bisect-service/chromiumos/src/platform/bisect-kit/./cros_helper.py", line 459, in cmd_allocate_dut
    todo, host, board = do_allocate_dut(opts)
  File "/usr/local/google/home/cros-bisect-service/chromiumos/src/platform/bisect-kit/./cros_helper.py", line 393, in do_allocate_dut
    x,
NameError: name 'x' is not defined
```

Original change's description:
> bisect-kit: Add dut_state:ready filter
>
> BUG=b:270265822
> TEST=./run_tests.sh
>
> Change-Id: I27bcacd0eb0245c48c56d0d617bb5e1fed153992
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/bisect-kit/+/4279506
> Commit-Queue: Zheng-Jie Chang <zjchang@chromium.org>
> Auto-Submit: Zheng-Jie Chang <zjchang@chromium.org>
> Reviewed-by: MD Nayeem Jahan Rafi <njrafi@chromium.org>
> Reviewed-by: Ace Wu <acewu@chromium.org>
> Tested-by: Zheng-Jie Chang <zjchang@chromium.org>

Bug: b:270265822
Change-Id: I8ba877e95e48c9c37be14609dc0dbb8054290114
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/bisect-kit/+/4277898
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Ace Wu <acewu@chromium.org>
Commit-Queue: Ace Wu <acewu@chromium.org>