UPSTREAM: ec/lenovo/pmh7: Include stdbool.h
When moving headers compilation can fail as pmh7.h is missing
the include for type bool. Add the missing include to make sure
future code refactoring works.

Fixed the error:
src/ec/lenovo/pmh7/pmh7.h:27:1: error: unknown type name 'bool'

(cherry picked from commit b44c0ab25b256edea6b376abe79ae22878adc416)

Original-Change-Id: Ib0a2489a0c461bf021168e98737ecb6062caa696
Original-Signed-off-by: Patrick Rudolph <patrick.rudolph@9elements.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/88542
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Paul Menzel <paulepanter@mailbox.org>
Original-Reviewed-by: Angel Pons <th3fanbus@gmail.com>
GitOrigin-RevId: b44c0ab25b256edea6b376abe79ae22878adc416
Cr-Build-Id: 8708345266036186753
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8708345266036186753
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: Ie9b726e6bc6274c785ae979556ed01e74bd863bb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6788468
Reviewed-by: Kshitij Shah <tij@google.com>
Commit-Queue: Kshitij Shah <tij@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>