chromeos-base/factory-mini: Fix dependencies
This change also upgrades PYTHON_COMPAT to 8..11 since 6 is being phased
out of the SDK. I also changed over to using python-any-r1 since it
looks like python is only a BDEPEND.

```
tar: /opt//closure-library-20211107.tar.gz: Cannot open: No such file or directory
/build/arm64-generic/tmp/portage/chromeos-base/factory-mini-9999/work/factory-mini-9999/devtools/mk/closure-compiler-host.sh: line 14: /usr/share/java-config-2/launcher/launcher.bash: No such file or directory
```

```
/bin/sh: line 1: msgcat: command not found
/bin/sh: line 1: msgfmt: command not found
```

```
ModuleNotFoundError: No module named 'jsonrpclib'
```

```
ModuleNotFoundError: No module named 'google.protobuf'
```

```
cp: cannot stat '/usr/bin/makeself': No such file or directory
```

```
ModuleNotFoundError: No module named 'jsonschema'
```

I also added a missing RDEPEND on chromeos-base/factory-deps

BUG=b:278728702, b:296444880
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/factory-mini:9999
TEST=BOARD=arm64-generic bazel run @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/factory-mini:9999_debug
TEST=/build/arm64-generic/tmp/portage/chromeos-base/factory-mini-9999/image/usr/local/bin/hwid --help
TEST=/build/arm64-generic/tmp/portage/chromeos-base/factory-mini-9999/image/usr/local/factory-toolkit/install_factory_toolkit.run  -- --non-cros

Change-Id: I7edb397f2d150be7a62ddb292ab5158dce345c80
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4795516
Tested-by: Raul Rangel <rrangel@chromium.org>
Auto-Submit: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Cheng Yueh <cyueh@chromium.org>
Commit-Queue: Cheng Yueh <cyueh@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>