net: mdns: Fix compile error when using clang
No issues with gcc but clang gives this error for
the *v4 variable few lines below.

.../lib/dns/mdns_responder.c:712:2: error: expected expression
        struct net_context *v4;

(cherry picked from commit 5209666539bcd4dea30faaf39f700339e075d14d)

Original-Original-Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
Original-GitOrigin-RevId: 5209666539bcd4dea30faaf39f700339e075d14d
Original-Change-Id: Ib9becdcf10ac9c312440fde74e195ad65a9b4fe8
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5041401
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: 6c84baa26cd7f34e91607d6c191be143ce6bc4c5
Cr-Build-Id: 8693119361452865953
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693119361452865953
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ib2fde5658c39a83f398b132331be5b630105a488
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7427352
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>