tests: mcumgr: exclude lpcxpresso51u68
The test is failing for lpcxpresso51u68 with:

soc_flash_lpc.c:25:2: error: #error No matching compatible for
soc_flash_lpc.c
   25 | #error No matching compatible for soc_flash_lpc.c
      |  ^~~~~

Add the board to the exclude list, sort the list as well.

(cherry picked from commit e7781626e7c7a483b69e32fe43c2c19ee7ab1c46)

Original-Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-GitOrigin-RevId: e7781626e7c7a483b69e32fe43c2c19ee7ab1c46
Original-Change-Id: I8f4d739094d48901652e6a471ac9f778d1b2017e
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4715051
Original-Tested-by: Yuval Peress <peress@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Yuval Peress <peress@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 528654c17bc1580a10da81db4a8b3da0ebcd8dc8
Cr-Build-Id: 8693182501767684353
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693182501767684353
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I01b650e53bddd40b2f87c7f2e49386c25b3217ab
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7420408
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>