drivers: sensor: fix possible unaligned access bmi08x
bmi08x_accel_frame is defined as packed struct,
while the nested structures are not. It causes an issue of
potential unaligned access to accel member.
The issue was detected by clang compiling with
-Wunaligned-access flag:

```
bmi08x.h:605:2: error: field  within 'struct bmi08x_accel_frame'
is less aligned than 'union bmi08x.h:605:2)' and is usually due
to 'struct bmi08x_accel_frame' being packed,
which can lead to unaligned accesses [-Werror,-Wunaligned-access]
```

This commit resolves the following Zephyr issue:
by adding `packed` attribute to accel member.

(cherry picked from commit bd6a228911059f39cfb83fd9d68cffc93a187119)

Original-Original-https: //github.com/zephyrproject-rtos/zephyr/issues/101142
Original-Original-Signed-off-by: Ivan Iushkov <ivan.iushkov@nordicsemi.no>
Original-GitOrigin-RevId: bd6a228911059f39cfb83fd9d68cffc93a187119
Original-Cr-Build-Id: 8693834649729444993
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693834649729444993
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I4748e0e676d2197dff1d7b03d8975b61a7f23a3b
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7376011
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 93dabd700b9125a7ddf59de111b4b94dd40eaafb
Cr-Build-Id: 8692610755496680913
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692610755496680913
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: If815687614990d1e5e84d2dea3f4e429e7b55ee4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7484647
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>