net: Fix macro for XCC
NET_SOCKET_GET_NAME macro adds some extra parenthesis that, on XCC (based
on GCC 4.2) ends up in the generated assembly, thus causing `as` to error

  Error: junk at end of line, first unrecognized character is `('

It appears that the parenthesis are actually concatenated to the
generated name for identifier. This patch just removes them.

(cherry picked from commit 827d07abbcd56b27eef89ac4921fadcbb1fcbd35)

Original-with:
Original-Signed-off-by: Ederson de Souza <ederson.desouza@intel.com>
Original-GitOrigin-RevId: 827d07abbcd56b27eef89ac4921fadcbb1fcbd35
Original-Change-Id: Ic05c48e652b311696ef4ae1fef7d66394e61d6dc
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3480399
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
Original-Reviewed-by: Aaron Massey <aaronmassey@google.com>
Original-Tested-by: Aaron Massey <aaronmassey@google.com>
Original-Commit-Queue: Aaron Massey <aaronmassey@google.com>
GitOrigin-RevId: 17d08ab13fa0d4a193ea6e5e8876bfcc71d13e69
Cr-Build-Id: 8693626578181626849
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693626578181626849
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I853897425ae53b74266b9918376151a21b847756
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7388886
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>