Autoupdate of 2 submodules
*chromite updated to 5bf5156143db1f4c7e7b20a10bc54bd32d8036bd
lib: toolchain_util: Fix regex word boundary

https://ci.chromium.org/ui/p/chromeos/builders/toolchain/kernel-5.15-release-afdo-verify-toolchain/4/overview
failed with:

KeyError: (re.compile('(?P<bef>AFDO_PROFILE_VERSION=)(?P<name>("[^"]*"|.*))
(?P<aft>.*)'), '\\g<bef>"R112-15350.0-1676889429"\\g<aft>')

Fix the word boundary in regex so it patches "AFDO_PROFILE_VERSION" but
not "ARM_AFDO_PROFILE_VERSION".

BUG=b:270225672
TEST=unit tests

Change-Id: If9bbab3178228fd3a3b6638ece93b83b3693bd0c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4288742
Reviewed-by: George Burgess <gbiv@chromium.org>
Tested-by: Denis Nikitin <denik@chromium.org>
Commit-Queue: Denis Nikitin <denik@chromium.org>

*infra/chromite-HEAD updated to 5bf5156143db1f4c7e7b20a10bc54bd32d8036bd
lib: toolchain_util: Fix regex word boundary

https://ci.chromium.org/ui/p/chromeos/builders/toolchain/kernel-5.15-release-afdo-verify-toolchain/4/overview
failed with:

KeyError: (re.compile('(?P<bef>AFDO_PROFILE_VERSION=)(?P<name>("[^"]*"|.*))
(?P<aft>.*)'), '\\g<bef>"R112-15350.0-1676889429"\\g<aft>')

Fix the word boundary in regex so it patches "AFDO_PROFILE_VERSION" but
not "ARM_AFDO_PROFILE_VERSION".

BUG=b:270225672
TEST=unit tests

Change-Id: If9bbab3178228fd3a3b6638ece93b83b3693bd0c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4288742
Reviewed-by: George Burgess <gbiv@chromium.org>
Tested-by: Denis Nikitin <denik@chromium.org>
Commit-Queue: Denis Nikitin <denik@chromium.org>