drivers: sensor: fix possible unaligned access icm45686
icm45686_encoded_fifo_payload is defined as packed struct,
while the nested structures are not. It causes an issue of
potential unaligned access to accel and gyro members.
The issue was detected by clang compiling with
-Wunaligned-access flag:

```
icm45686.h:52:6: error: field accel within 'struct icm45686.h:46:3)'
is less aligned than 'struct icm45686.h:48:4)' and is usually due
to 'struct icm45686.h:46:3)' being packed,
which can lead to unaligned accesses [-Werror,-Wunaligned-access]

icm45686.h:57:6: error: field gyro within 'struct icm45686.h:46:3)'
is less aligned than 'struct icm45686.h:53:4)' and is usually due
to 'struct icm45686.h:46:3)' being packed,
which can lead to unaligned accesses [-Werror,-Wunaligned-access]
```

Small C code snippet to demonstrate the reported issue:
```
struct icm45686_encoded_fifo_payload icm45686;
// prints 1:
printf("%lu\n", __alignof__(icm45686));
// prints 1:
printf("%lu\n", __alignof__(icm45686.accel));
// prints 2:
printf("%lu\n", __alignof__(typeof(icm45686.accel)));
```

This commit resolves the following Zephyr issue:
by adding `packed` attribute to accel and gyro members.

(cherry picked from commit 0436b8abd8310cb20abbaf0f2fb3432b3ee71f72)

Original-Original-https: //github.com/zephyrproject-rtos/zephyr/issues/101142
Original-Original-Signed-off-by: Ivan Iushkov <ivan.iushkov@nordicsemi.no>
Original-GitOrigin-RevId: 0436b8abd8310cb20abbaf0f2fb3432b3ee71f72
Original-Cr-Build-Id: 8693834649729444993
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693834649729444993
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I8c318dc7907b0595872a01d3f8155e267909101e
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7376012
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 1e72b4e961352c8b3a0eb46156d7e54cb00cad2d
Cr-Build-Id: 8692610755496680913
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692610755496680913
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ic670e4e9fdb79b78c65437411f93dce3efb11a5a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7484648
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>