net: stats: fix duplicate Prometheus metric variable names for multi-NIC
The NET_STATS_GET_VAR() macro was defined as:

  #define NET_STATS_GET_VAR(dev_id, sfx, var) zephyr_net_##var

This ignores the dev_id and sfx arguments, so every network interface
that calls NET_STATS_PROMETHEUS() (via NET_IF_INIT()) expands to the
same static variable names (e.g. zephyr_net_processing_error,
zephyr_net_ipv6_sent, etc.).

On platforms with multiple network interfaces, such as the i.MX943 EVK
which has three ENETC instances (enetc_psi0/psi1/psi2), the linker
sees duplicate definitions of every Prometheus metric variable and
fails with:

  error: redefinition of 'zephyr_net_processing_error'

Fix by including dev_id and sfx in the generated variable name, making
it unique per interface, consistent with how NET_STATS_GET_COLLECTOR_NAME
already works. The new expansion is:

  zephyr_net_##dev_id##_##sfx##_##var

Original-Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/118981
Original-Signed-off-by: Jiafei Pan <jiafei.pan@nxp.com>
GitOrigin-RevId: f0bdf59a0b7d1b4dadbec339662d764cba78138a
Cr-Build-Id: 8668943134226092113
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8668943134226092113
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I11dae41c992f1b487820564cbefc9bb518bab0a5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/8510492
Tested-by: Keith Short <keithshort@chromium.org>
Commit-Queue: Keith Short <keithshort@chromium.org>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Keith Short <keithshort@chromium.org>