Revert "drivers: gpio_cc13xx_cc26xx: Update for latest sdk"
This reverts commit 99e7223a1ce73e7b52f614e0feda0b52a884c804.

Breaks CI with the following compilation error in SPI.c:52:

Failing tests (cc3220sf_launchxl/cc3220sf)
- sample.net.sockets.echo.offload.simplelink
- sample.net.sockets.http_get.offload.simplelink
- sample.net.wifi

(cherry picked from commit 06e86e95da1c168f1578bb2c20da37a8c078fec0)

Original-Original-error: 'SPI_MASTER' undeclared here (not in a function)
Original-Original-Signed-off-by: Benjamin Cabé <benjamin@zephyrproject.org>
Original-GitOrigin-RevId: 06e86e95da1c168f1578bb2c20da37a8c078fec0
Original-Cr-Build-Id: 8720130420530112897
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8720130420530112897
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I616ba714a244715c790f300389b9e71e3af36fc6
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6362575
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 1095eb961296bac0e83abbab9dbbe862d512691a
Cr-Build-Id: 8692836905459451233
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692836905459451233
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I4d1032e4c1761695fc02cf025281a1d9ff603359
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7458693
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>