tests/intel/kms_ccs: add missed include
seems <fcntl.h> is needed for O_RDONLY flag on some platforms/libc.
Example from https://gitlab.freedesktop.org/drm/igt-gpu-tools/-/jobs/70719166

	../tests/intel/kms_ccs.c: In function ‘check_hibernation_support’:
	../tests/intel/kms_ccs.c:289:7: error: implicit declaration of function ‘open’; did you mean ‘popen’? [-Werror=implicit-function-declaration]
	  fd = open("/sys/power/state", O_RDONLY);
	       ^~~~
	       popen
	../tests/intel/kms_ccs.c:289:7: warning: nested extern declaration of ‘open’ [-Wnested-externs]
	../tests/intel/kms_ccs.c:289:32: error: ‘O_RDONLY’ undeclared (first use in this function); did you mean ‘STA_RONLY’?
	  fd = open("/sys/power/state", O_RDONLY);
					^~~~~~~~
					STA_RONLY

Fixes: d3602c12b73f ("tests/intel/kms_ccs: add hiberbate test")
Signed-off-by: Juha-Pekka Heikkila <juhapekka.heikkila@gmail.com>
Link: https://lore.kernel.org/r/20250207155152.2506970-1-juhapekka.heikkila@gmail.com