chromeos-base/update_engine: Add missing BDEPEND
```
FAILED: gen/include/dbus_bindings/org.chromium.UpdateEngineInterface.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'

FAILED: gen/include/update_engine/update_metadata.pb.cc gen/include/update_engine/update_metadata.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/update_engine:9999

Change-Id: Ifa89efc59ea9c559e8196e9f5450e3ec84377a27
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692142
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>