CHROMIUM: Merge tag 'v5.15.202' into chromeos-5.15
drivers/gpu/drm/amd/amdgpu/amdgpu_gmc.c
Due to chromeos-5.15 picked but linux-5.15.y didn't:
- 3f543552846b ("drm/amdgpu: Merge get_reserved_allocation to get_vbios_allocations.") in upstream.
- 8680d68e84d9 ("UPSTREAM: drm/amdgpu: Merge get_reserved_allocation to get_vbios_allocations.") in chromeos-5.15.

drivers/media/platform/mediatek/mdp/mtk_mdp_core.c
This is a big mess as mdp is a downstream series basis in chromeos-5.15.
Due to downstream patches in chromeos-5.15:
- b7ddac3dcf90 ("CHROMIUM: mtk-mdp: add driver to probe mdp components") in chromeos-5.15.
- mtk_mdp_register_m2m_device() isn't in mtk_mdp_probe() but mtk_mdp_master_bind() in chromeos-5.15.
Due to chromeos-5.15 picked but linux-5.15.y didn't:
- 2023a9981111 ("media: platform: rename mediatek/mtk-jpeg/ to mediatek/jpeg/") in upstream.
- 12c068a3d1e2 ("BACKPORT: UPSTREAM: media: platform: rename mediatek/mtk-jpeg/ to mediatek/jpeg/") in chromeos-5.15.
As a result, the paths are different:
- drivers/media/platform/mtk-mdp/mtk_mdp_core.c in linux-5.15.y.
- drivers/media/platform/mediatek/mdp/mtk_mdp_core.c in upstream and chromeos-5.15.

drivers/pinctrl/qcom/pinctrl-sm8250-lpass-lpi.c
Due to chromeos-5.15 already picked:
- 5241a682422f ("pinctrl: qcom: Extract chip specific LPASS LPI code") in v5.15.202.
- 6b40dad0f4c9 ("FROMGIT: pinctrl: qcom: Extract chip specific LPASS LPI code") in chromeos-5.15.
But chromeos-5.15 lacks of:
- eabf273c8466 ("pinctrl: qcom: sm8250-lpass-lpi: Fix i2s2_data_groups definition") in upstream.
- 1658bb88b443 ("pinctrl: qcom: sm8250-lpass-lpi: Fix i2s2_data_groups definition") in v5.15.202.

drivers/i3c/master.c
Encountered a compilation error: "variable 'i2cdev' is uninitialized when used here"
Pick the following fix:
- 6cbf8b38dfe3 ("i3c: fix uninitialized variable use in i2c setup") in upstream.

BUG=b:514868568
TEST=cq

Change-Id: Ie70708de95f0fea5b2e45b09ae793bbaf240af1b
Disallow-Recycled-Builds: test-failures
Signed-off-by: Tzung-Bi Shih <tzungbi@chromium.org>