samples: net: Disable native_sim net USB driver in samples
The native_sim USB driver gives this error currently if one
enables CONFIG_POSIX_API.

drivers/usb/device/usb_dc_native_posix_adapt.c:22:10: \
 fatal error: sys/un.h: No such file or directory
   22 | #include <sys/un.h>
      |          ^~~~~~~~~~
compilation terminated.

Disable the netusb support from networking shells for native_sim
board for now so that CI can pass.

(cherry picked from commit a613e2427a30e07da1683369726b9292f7ccd9d6)

Original-Original-Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
Original-GitOrigin-RevId: a613e2427a30e07da1683369726b9292f7ccd9d6
Original-Change-Id: I681ca4b3ad35db4fffdff8bd6557ecaa6eef08b3
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5407491
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: f8d068b62f2d004000501b6b4b18d6f58a52f101
Cr-Build-Id: 8693054043427284545
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693054043427284545
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I99255c90cb4759e801f4b4c4189254e0b491601a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7434191
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>