drivers: sensor: Fix unused function warning
Building with clang warns:

drivers/sensor/st/lis2dw12/lis2dw12.c:194:23: error: unused
function 'sensor_ms2_to_mg' [-Werror,-Wunused-function]
static inline int32_t sensor_ms2_to_mg(const struct sensor_value *ms2)
                      ^

Move the function to include/zephyr/drivers/sensor.h with the other
sensor_ms2_to* functions.

(cherry picked from commit a887fe16079c3c5fc37db7bd666e5f491e27132c)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: a887fe16079c3c5fc37db7bd666e5f491e27132c
Original-Cr-Build-Id: 8723142769276654049
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723142769276654049
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: If8d6d8ecde2f65231a6bf8961a6f49b8d323be94
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6257384
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: cd73fe679c3247e401f55d789301177e09b8593b
Cr-Build-Id: 8692857091111002929
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692857091111002929
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I80779daefc5583656cc8e457f42af1ee979472d5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7455924
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>