drivers/timer: Fix build error when run by twister
Fix undefined reference to z_sys_timer_irq_for_test

(cherry picked from commit a75d6a40b6fd3aea2620eb82c684876339926b1e)

Original-Signed-off-by: Andrew Perepech <andrew.perepech@mediatek.com>
GitOrigin-RevId: a75d6a40b6fd3aea2620eb82c684876339926b1e
Cr-Build-Id: 8702282817499087745
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8702282817499087745
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ice4035db29d859b1e5c08a9211435dc909dea8ba
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7001243
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: Keith Short <keithshort@chromium.org>
Commit-Queue: Keith Short <keithshort@chromium.org>
Reviewed-by: Keith Short <keithshort@chromium.org>