chromeos-base/diagnostics: Add missing BDEPEND
```
ninja: error: '../../../../../../../../../usr/bin/compile_seccomp_policy', needed by 'obj/diagnostics/cros_healthd/seccomp/_diagnostics_seccomp_install-check_seccomp.inputdeps.stamp', missing and no known rule to make it
```

```
FAILED: gen/include/diagnostics/dbus_bindings/bluetooth/dbus-proxies.h gen/include/diagnostics/dbus_bindings/bluetooth/dbus-proxy-mocks.h 
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

```
FAILED: gen/include/wilco_dtc.grpc.pb.cc gen/include/wilco_dtc.grpc.pb.h gen/include/wilco_dtc.pb.cc gen/include/wilco_dtc.pb.h gen/include/wilco_dtc_supportd.grpc.pb.cc gen/include/wilco_dtc_supportd.grpc.pb.h gen/include/wilco_dtc_supportd.pb.cc gen/include/wilco_dtc_supportd.pb.h 
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
/usr/bin/grpc_cpp_plugin: program not found or is not executable
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/diagnostics:9999

Change-Id: I7f93985f48ee839789530aface594b23f5691bd0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692095
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>