Bluetooth: Fix GATT client build without SMP
If GATT client is enabled but SMP is disabled NULL SMP backend
needs to provide bt_smp_sign stub.

  LD      zephyr.elf
net/built-in.o: In function `bt_att_send':
net/bluetooth/att.c:1747: undefined reference to `bt_smp_sign'
make[2]: *** [zephyr] Error 1

Original-Makefile: 757: recipe for target 'zephyr' failed
Change-Id: Ia740d6c7ca7d65b78f7ecb781275d1f4d635baf7
Original-Signed-off-by: Szymon Janc <ext.szymon.janc@tieto.com>
GitOrigin-RevId: b6221d4a5c379b2f2b034d91dbd35735421faf14
Cr-Build-Id: 8697415573219248001
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8697415573219248001
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7195933
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>