UPSTREAM: soc/qualcomm/sc7280/socinfo: Add missing <console/console.h>
This to fix Wimplicit-function-declaration error:
src/soc/qualcomm/sc7280/socinfo.c:67:2: error: call to undeclared function 'die'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   67 |         die("could not match jtagid\n");
      |         ^
src/soc/qualcomm/sc7280/socinfo.c:81:2: error: call to undeclared function 'die'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   81 |         die("could not match jtagid\n");
      |         ^

(cherry picked from commit 1e0ce7a9d8d67e83c67e22dd51d5b8e8f6e7cb8d)

Original-Change-Id: If930e39d0c7231975c1a11179fa7dbd9fcc0d1d1
Original-Signed-off-by: Elyes Haouas <ehaouas@noos.fr>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/85166
Original-Reviewed-by: Felix Singer <service+coreboot-gerrit@felixsinger.de>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: 1e0ce7a9d8d67e83c67e22dd51d5b8e8f6e7cb8d
Cr-Build-Id: 8730870591242854033
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730870591242854033
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: Ic25dcb6bbc93eb251ffbac8051429651654683d5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6034556
Tested-by: Kangheui Won <khwon@chromium.org>
Commit-Queue: Kangheui Won <khwon@chromium.org>
Reviewed-by: Kangheui Won <khwon@chromium.org>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>