chromeos-base/swap_management: Add missing BDEPEND
```
FAILED: gen/include/swap_management/dbus_adaptors/org.chromium.SwapManagement.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/swap_management:9999

Change-Id: I643034be4d0fbc9a67582ce6f3f279a17b87b258
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692136
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>