tests: app_dev: ram_context_for_isr: fix irq_num
This commit fixes build issue when multi level interrupts is enabled,
define TEST_IRQ_NUM as (CONFIG_2ND_LVL_ISR_TBL_OFFSET - 1)
  - CMSIS/Core/Include/core_cm33.h:2438:15: error: array subscript 24
    is above array bounds of volatile uint32_t[16]

(cherry picked from commit e6c9feabef87634e1852bd1882f9fad0bf3678d9)

Original-Original-Signed-off-by: Biwen Li <biwen.li@nxp.com>
Original-GitOrigin-RevId: e6c9feabef87634e1852bd1882f9fad0bf3678d9
Original-Cr-Build-Id: 8696507262808549057
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8696507262808549057
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ib18e9d49ab7a9286a9e9c4930a1265cc4194c8ec
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7222133
Original-Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 965330da24470d6b8820e51006356d7b2f40e4c9
Cr-Build-Id: 8692627694996055329
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692627694996055329
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ic5beb732f6e32d2d28cb154bcde14260940fcc47
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7482195
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>