Bluetooth: Controller: Fix build for hci_uart sample with new LLCP
ull_tx_queue.h needs to be included before ll_sw/ull_conn_types.h

zephyr/zephyr/subsys/bluetooth/controller/hci/hci.c
In file included from zephyr/zephyr/subsys/bluetooth/controller/
    hci/hci.c:52:
../../subsys/bluetooth/controller/./ll_sw/ull_conn_types.h:453:18:
     error: field 'tx_q' has incomplete type
  453 |  struct ull_tx_q tx_q;
      |                  ^~~~

(cherry picked from commit 1f5417988939d6ed80775b46b550c4a79b84aca2)

Original-Signed-off-by: Szymon Janc <szymon.janc@codecoup.pl>
Original-GitOrigin-RevId: 1f5417988939d6ed80775b46b550c4a79b84aca2
Original-Change-Id: Id3ee2cd1fdf4aa04b83ad9950f05d8da53d60a20
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3308756
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
Original-Reviewed-by: Yuval Peress <peress@google.com>
Original-Commit-Queue: Jack Rosenthal <jrosenth@chromium.org>
GitOrigin-RevId: dce4214d7d3d528d48840ac1eabbf0d83fbada19
Cr-Build-Id: 8693670570659424833
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693670570659424833
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I31f1a6b8654522aac80050a8dcbeca28067d0cc2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7385924
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>