UPSTREAM: 3rdparty/cmocka/fix(cmocka): Don't mix uint/int functions, causing -Wsign-conversion
GCC showed the following when activating wide warning
sets and -Werror:

    error: conversion to ‘uintmax_t’ {aka ‘const long unsigned int’} from ‘long int’ may change the sign of the result [-Werror=sign-conversion]

Add the warning to the PICKY_DEVELOPER=ON mode.
Fix similar errors in tests found by combining that mode
with UNIT_TESTS=ON.

Original-Reviewed-by: Andreas Schneider <asn@cryptomilk.org>
GitOrigin-RevId: 13863cfa6a1a49777b79c0a8a8be302401387e64
Cr-Build-Id: 8686171652459199537
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8686171652459199537
Copybot-Job-Name: coreboot-cmocka-copybot-downstream
Change-Id: Ib48e0f534ee80e7a4b0e251ff2f6a11b041979b1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/7704745
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>