CHROMIUM: media: camx: Fix misleading identation
cam_sensor_dev.c:69:17: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]

BUG=none
TEST=make C=1 W=1
UPSTREAM-TASK=b:274966069

Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
Change-Id: Ibc2c77360d6a3cc05724e1d1230173c764372340
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4921754
Reviewed-by: Sergey Senozhatsky <senozhatsky@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>
(cherry picked from commit a6a2d872405e2de416d51240ac7802beb37daf43)
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4926212