CHROMIUM: media: camx: cam_icp: Fix printf format error
error: format ‘%zu’ expects argument of type ‘size_t’, but argument 6 has type ‘uint32_t’ {aka ‘unsigned int’} [-Werror=format=]

BUG=none
TEST=make C=1 W=1
UPSTREAM-TASK=b:274966069

Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
Change-Id: Ic28b865c6faf97c1293c61996409688fd84e7bda
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4921753
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Sergey Senozhatsky <senozhatsky@chromium.org>
(cherry picked from commit a14bd56c47774e3f4ae2cc3445e8eab2ab03fa1a)
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4926211