soc: silabs: siwx91x: Fix corrupted firmware
Since, commit 2f7d13840f6 ("kconfig: Fix CONFIG_FLASH_LOAD_OFFSET for non-0
starting addresses"), the way to compute offsets in the flash memory has
changed.

With this change, the arguments passed to siwx91x_isp_prepare.py were not
correct anymore and "west flash" ended up with:

   ERROR: Waiting for flashloader failed: 108 - Checksum error

Original-Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>
GitOrigin-RevId: 1ac564bc4f6af511235e1a2369b5b2a116a6d7a0
Cr-Build-Id: 8688942407325083793
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8688942407325083793
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I76a3425d5209665805c2c209201d4135a4f3216a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7605162
Tested-by: Tristan Honscheid <honscheid@google.com>
Commit-Queue: Tristan Honscheid <honscheid@google.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>