scripts: twisterlib: Fix --short-build-path argument handling
When `--short-build-path` argument is specified to the twister, the
following error message is displayed because the Python argparse module
does not allow specifying a mutually exclusive argument as required:

  ValueError: mutually exclusive arguments must be optional

This commit removes the `required` parameter when adding the `--ninja`
argument, which is a mutually exclusive argument, and adds a manual
check to validate this condition instead.

(cherry picked from commit 1f81d2cd978ccdb6161412b3f16bc6e47bef49b8)

Original-Original-Signed-off-by: Stephanos Ioannidis <root@stephanos.io>
Original-GitOrigin-RevId: 1f81d2cd978ccdb6161412b3f16bc6e47bef49b8
Original-Change-Id: I1c14c05a8369f4b9229d9aa354859b28fe0bf5ee
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3788476
Original-Tested-by: Al Semjonovs <asemjonovs@google.com>
Original-Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Original-Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
GitOrigin-RevId: d376c69a47aba0d9fdd4b2e8638620368fb1dbf3
Cr-Build-Id: 8693500042307236321
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693500042307236321
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I8173588298dae827c26b249b8e953caa67cfc469
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7397331
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>