runners: trace32: mypy fixes
Fixes for the following issues that a new version of mypy started
reporting recently:

runners/trace32.py:34: error: Incompatible default for argument
"startup_args" (default has type "None", argument has type
"List[str]") [assignment]

runners/trace32.py:137: error: Incompatible default for argument
"cfg" (default has type "None", argument has type "Path") [assignment]

runners/trace32.py:34: note: PEP 484 prohibits implicit Optional.
Accordingly, mypy has changed its default to no_implicit_optional=True

(cherry picked from commit b907f74326fc24a55b8fabdc8afe05e98f867b16)

Original-Original-Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>
Original-GitOrigin-RevId: b907f74326fc24a55b8fabdc8afe05e98f867b16
Original-Change-Id: I6cd7a0f1013f1f24aeea8254e792558cc553a713
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4016905
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 541fbc65885eb9e8e13c7d0446241b94fd08ac1e
Cr-Build-Id: 8693413929763416033
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693413929763416033
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I6eea1d786488eff24ee928bd4431054fa2ee40fe
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7403717
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>