scripts: intel_adsp: don't invoke west sign with --tool-path None
When there is no rimage found in the path, don't invoke west sign with
"-tool-path None". This enhances the error message from the somewhat

  ERROR: --tool-path None: not an executable

... to the user friendlier:

  FATAL ERROR: rimage not found; either install it or provide --tool-path

Also log the complete west sign command at the "info" level before
running it to show that no signed firmware was found, to show which
rimage is used and in case other rimage problems arise. Invoking an
external command is an important "checkpoint".

(cherry picked from commit 739aa951cdbe011ff907aa4249ec013867c2e32d)

Original-cryptic:
Original-Original-Signed-off-by: Marc Herbert <marc.herbert@intel.com>
Original-GitOrigin-RevId: 739aa951cdbe011ff907aa4249ec013867c2e32d
Original-Change-Id: Iff719daf50330da8fc4e01132fe159ea2adf75f9
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3737865
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: b7539f89962155a13a3ce7d60134a243ce0f9270
Cr-Build-Id: 8693530804400003137
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693530804400003137
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I9b6215bfd07da495b9bfa9ba77e3fce2292e732f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7395156
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>