tests: bluetooth: classic: Remove self assignment
When building with clang it warns about self-assignment in the
bluetooth.classic.sdp_s test:

tests/bluetooth/classic/sdp_s/src/sdp_server.c:258:5: error: explicitly
assigning value of variable of type 'const struct shell *' to itself
[-Werror,-Wself-assign]
  258 |         sh = sh;
      |         ~~ ^ ~~
tests/bluetooth/classic/sdp_s/src/sdp_server.c:277:5: error: explicitly
assigning value of variable of type 'const struct shell *' to itself
[-Werror,-Wself-assign]
  277 |         sh = sh;
      |         ~~ ^ ~~
tests/bluetooth/classic/sdp_s/src/sdp_server.c:290:5: error: explicitly
assigning value of variable of type 'const struct shell *' to itself
[-Werror,-Wself-assign]
  290 |         sh = sh;
      |         ~~ ^ ~~
tests/bluetooth/classic/sdp_s/src/sdp_server.c:368:5: error: explicitly
assigning value of variable of type 'const struct shell *' to itself
[-Werror,-Wself-assign]
  368 |         sh = sh;
      |         ~~ ^ ~~
4 errors generated.

The "sh" variable is used later in the functions.

(cherry picked from commit 32b63c63edc82324c4d10b18e79858ad8fa8e56d)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 32b63c63edc82324c4d10b18e79858ad8fa8e56d
Original-Cr-Build-Id: 8692611591669624993
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692611591669624993
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I567c4f39e08465de41855417836080c971d52ce7
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7484460
Original-Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
GitOrigin-RevId: d33c56d7e2d69b3be83b1139a72f031ecbc5e0eb
Cr-Build-Id: 8692121333639279185
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692121333639279185
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I441d6cf59ccaa32ce56c2d69b84c6eccbc0ae869
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7500619
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>