[clang] Remove unused selStructPtrTy in CGObjCGNU.cpp (NFC)
/llvm-project/clang/lib/CodeGen/CGObjCGNU.cpp:3674:15: error: variable 'selStructPtrTy' set but not used [-Werror,-Wunused-but-set-variable]
  llvm::Type *selStructPtrTy = SelectorTy;
              ^
1 error generated.