nvk/meson: add build root dir to nvk_include_directories
The static inline wrapper includes the header file relatively from where
bindgen gets executed, instead of correct relatively from the directory
of static include wrapper.

Add build root to include directories to workaround it, and because meson
doesn't allow us to add absolute paths, fs.relative_to needs to be used.

Similar to #11178 and use the same fix as !29275. Was introduced in new
code of !31867.

    src/nouveau/vulkan/nvk_inline_wrappers.c:1:10: fatal error: ../mesa/src/nouveau/vulkan/rust/bindings.h: No such file or directory
        1 | #include "../mesa/src/nouveau/vulkan/rust/bindings.h"
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.

Fixes: 80ac804d534 ("nvk: Add initial rust support")
Reviewed-by: Mel Henning <mhenning@darkrefraction.com>
Reviewed-by: Mary Guillemard <mary@mary.zone>
Signed-off-by: Celeste "Coelacanthus" Liu <uwu@coelacanthus.name>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/43941>