manifest: Update hostap to fix build error
Fix build error of undefined reference to 'inet_aton' in
hostap/src/utils/ip_addr.c

(cherry picked from commit 244958c9f482ab0980da07d7565bd86cca377ed7)

Original-Original-Signed-off-by: Maochen Wang <maochen.wang@nxp.com>
Original-GitOrigin-RevId: 244958c9f482ab0980da07d7565bd86cca377ed7
Original-Cr-Build-Id: 8733565196572304993
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8733565196572304993
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I5a77f61d19bb9ab951d309c936cdc9486d628a51
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5937727
Original-Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Original-Commit-Queue: Eric Yilun Lin <yllin@google.com>
GitOrigin-RevId: fa9537fb4822ebe675d4074817daa9bcd5ead393
Cr-Build-Id: 8692934434195585665
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692934434195585665
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I778a344d7bcec77381b3cc5c84e98946ffdd3ee2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7445766
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>