Autoupdate of 2 submodules
*chromite updated to cf072fa3ce65a9ef8fc9a43fe5640c64ca7e2c66
cbuildbot: stop exporting metadata to the cloud

The only place that uploads metadata with export=True is the Report
stage, and this script has been failing for months in SDK & factory:

04:22:13.209: INFO: run: .../chromite/bin/export_to_gcloud /creds/service_accounts/service-account-chromeos-datastore-writer-prod.json .../tmpm4dpgeo3
export_to_gcloud: Unhandled exception:
Traceback (most recent call last):
  File ".../chromite/bin/export_to_gcloud", line 51, in <module>
    main()
  File ".../chromite/bin/export_to_gcloud", line 47, in main
    wrapper3.DoMain()
  File ".../chromite/scripts/wrapper3.py", line 213, in DoMain
    commandline.ScriptWrapperMain(FindTarget)
  File ".../chromite/lib/commandline.py", line 1356, in ScriptWrapperMain
    ret = target(argv[1:])
  File ".../chromite/scripts/export_to_gcloud.py", line 131, in main
    dslib.ChunkedBatchWrite(entities, c)
  File ".../chromite/lib/dslib.py", line 60, in ChunkedBatchWrite
    batch.put(entity)
  File ".../site-packages/google/cloud/datastore/batch.py", line 186, in put
    raise ValueError("Batch must be in progress to put()")
ValueError: Batch must be in progress to put()

So if this hasn't worked in a long time and no one has noticed or
cared, let's delete it and be done.

BUG=None
TEST=CQ passes

Change-Id: Ibc70db98aa49519400851dd66bc54a02bc2b1d1f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4701467
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: George Engelbrecht <engeg@google.com>
Reviewed-by: Greg Edelston <gredelston@google.com>
Commit-Queue: Mike Frysinger <vapier@chromium.org>

*infra/chromite-HEAD updated to cf072fa3ce65a9ef8fc9a43fe5640c64ca7e2c66
cbuildbot: stop exporting metadata to the cloud

The only place that uploads metadata with export=True is the Report
stage, and this script has been failing for months in SDK & factory:

04:22:13.209: INFO: run: .../chromite/bin/export_to_gcloud /creds/service_accounts/service-account-chromeos-datastore-writer-prod.json .../tmpm4dpgeo3
export_to_gcloud: Unhandled exception:
Traceback (most recent call last):
  File ".../chromite/bin/export_to_gcloud", line 51, in <module>
    main()
  File ".../chromite/bin/export_to_gcloud", line 47, in main
    wrapper3.DoMain()
  File ".../chromite/scripts/wrapper3.py", line 213, in DoMain
    commandline.ScriptWrapperMain(FindTarget)
  File ".../chromite/lib/commandline.py", line 1356, in ScriptWrapperMain
    ret = target(argv[1:])
  File ".../chromite/scripts/export_to_gcloud.py", line 131, in main
    dslib.ChunkedBatchWrite(entities, c)
  File ".../chromite/lib/dslib.py", line 60, in ChunkedBatchWrite
    batch.put(entity)
  File ".../site-packages/google/cloud/datastore/batch.py", line 186, in put
    raise ValueError("Batch must be in progress to put()")
ValueError: Batch must be in progress to put()

So if this hasn't worked in a long time and no one has noticed or
cared, let's delete it and be done.

BUG=None
TEST=CQ passes

Change-Id: Ibc70db98aa49519400851dd66bc54a02bc2b1d1f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4701467
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: George Engelbrecht <engeg@google.com>
Reviewed-by: Greg Edelston <gredelston@google.com>
Commit-Queue: Mike Frysinger <vapier@chromium.org>