tests: lib: cmsis_dsp: Fix -Wsometimes-uninitialized warning
Building with clang warns:

tests/lib/cmsis_dsp/distance/src/u32.c:82:3: error: variable 'val' is
used uninitialized whenever switch default is taken
[-Werror,-Wsometimes-uninitialized]
                default:
                ^~~~~~~
tests/lib/cmsis_dsp/distance/src/u32.c:87:19: note: uninitialized use
occurs here
                output[index] = val;
                                ^~~
tests/lib/cmsis_dsp/distance/src/u32.c:47:16: note: initialize the
variable 'val' to silence this warning
                float32_t val;
                             ^
                              = 0.0

Hitting the default switch will assert, so this won't cause any problems
as written, but it doesn't hurt to initialize the variable.

(cherry picked from commit 481a3c77c9e7e90cbbfa00886ab6feec45f686cf)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 481a3c77c9e7e90cbbfa00886ab6feec45f686cf
Original-Cr-Build-Id: 8720062473382680481
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8720062473382680481
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ib27ba943ce3e7e2f5113baef661babc04c47a92d
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6367339
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 8c49469a48fe271aa87cfaef341c7115730158e1
Cr-Build-Id: 8692833786728597409
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692833786728597409
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ie7d346b8f73cbf74eb84a7e207643ecc72ffc7e0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7458927
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>