tracing: rtio: fix building error in rtio header file
This patch is to fix the following building issue:
include/zephyr/rtio/rtio.h:1773:51: error: 'rtio' undeclared
(first use in this function)

(cherry picked from commit e2d6af1f55a50ef3856a83f4ba317028a047526b)

Original-Signed-off-by: Jiafei Pan <Jiafei.Pan@nxp.com>
GitOrigin-RevId: e2d6af1f55a50ef3856a83f4ba317028a047526b
Cr-Build-Id: 8698221080423948257
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8698221080423948257
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ic4b2d9a17cc0b9f6c3511fa0209caf778e263bfa
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7158246
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>