sys-devel/llvm: Add missing dep
   /build/amd64-host/tmp/portage/sys-devel/llvm-16.0_pre484197_p20230405-r1/work/llvm-16.0_pre484197_p20230405/llvm/tools/gold/gold-plugin.cpp:38:10: fatal error: 'plugin-api.h' file not found
   #include <plugin-api.h>
            ^~~~~~~~~~~~~~
   1 error generated.

I'm not sure if we ever use the gold plugin, but it's currently getting
built.

BUG=b:278728702
TEST=BOARD=amd64-host bazel run --//bazel/sdk:new-sdk @portage//sys-devel/llvm:debug -- --login=after

Change-Id: Ie5a6ef8c75ac6eaa44d0585167717f7bfad963b3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4509952
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>