UPSTREAM: pw_bytes: Revert moving to whole_static_libs in Android.bp
This can cause duplicate symbol errors in build

```
ld.lld: error: duplicate symbol: pw_StatusString
>>> defined at status.cc:21 (external/pigweed/pw_status/status.cc:21)
>>>            status.o:(pw_StatusString) in archive out/soong/.intermediates/external/pigweed/pw_bytes/pw_bytes/linux_glibc_x86_static/pw_bytes.a
>>> defined at status.cc:21 (external/pigweed/pw_status/status.cc:21)
>>>            status.o:(.text+0x0) in archive out/soong/.intermediates/external/pigweed/pw_status/pw_status/linux_glibc_x86_static/pw_status.a
```

(cherry picked from commit f6da7605cb026e4d142cbd371005a7c8956d4e63)

Original-Change-Id: Ibde403427a07034a5c27b85c1914d97e44fe4205
Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/245753
Original-Presubmit-Verified: CQ Bot Account <pigweed-scoped@luci-project-accounts.iam.gserviceaccount.com>
Original-Docs-Not-Needed: Austin Foxley <afoxley@google.com>
Original-Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Original-Pigweed-Auto-Submit: Austin Foxley <afoxley@google.com>
Original-Reviewed-by: Taylor Cramer <cramertj@google.com>
Original-Commit-Queue: Austin Foxley <afoxley@google.com>
GitOrigin-RevId: f6da7605cb026e4d142cbd371005a7c8956d4e63
Cr-Build-Id: 8730937883504950801
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730937883504950801
Copybot-Job-Name: pigweed-main-copybot-downstream
Change-Id: I0f4c68929327e1ae4444b401b353e3cda862bcc0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/pigweed/pigweed/+/6006960
Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Al Semjonovs <asemjonovs@google.com>