stepper: shell: fix uninitialized variable compiler warning
Fixes:

/__w/zephyr/zephyr/include/zephyr/drivers/stepper.h:429:16: error:
'direction' may be used uninitialized [-Werror=maybe-uninitialized]

found with:

west build -p -b esp32s3_touch_lcd_1_28/esp32s3/appcpu -T
tests/drivers/stepper/shell/drivers.stepper.shell

(cherry picked from commit 5e2203a6cdd0daf395bb3825d416843ecdc40629)

Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 5e2203a6cdd0daf395bb3825d416843ecdc40629
Cr-Build-Id: 8735286451693989857
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8735286451693989857
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I57e6c71c1618fb324690e55620e1c8b8d497d7aa
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5901729
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Tested-by: Al Semjonovs <asemjonovs@google.com>
Reviewed-by: Al Semjonovs <asemjonovs@google.com>