tests: i2c_emul: Remove unused variable
Building with clang warns:

tests/drivers/i2c/i2c_emul/src/test_forwarding_pio.cpp:19:32: error:
unused variable 'targets' [-Werror,-Wunused-const-variable]
constexpr const struct device *targets[FORWARD_COUNT] = {
                               ^

(cherry picked from commit bae8e34a3814acc6b64a7f23b5836f9cd1cde1e9)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: bae8e34a3814acc6b64a7f23b5836f9cd1cde1e9
Cr-Build-Id: 8723052172249940737
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723052172249940737
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Id31aa4ad1d46ce8cc9627c0785d2e48c463db943
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6261361
Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>