drivers: flash: mark unused argument
```
.../zephyr/drivers/flash.h: In function 'flash_params_get_erase_cap':
.../flash.h:106:63: error: unused parameter 'p' [-Werror=unused-parameter]
  106 | int flash_params_get_erase_cap(const struct flash_parameters *p)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

(cherry picked from commit 272d52ff7ad47f43c4dac4976c9b90dc2099fb88)

Original-Fixes:
Original-Original-Signed-off-by: Nerijus Bendžiūnas <nerijus.bendziunas@astrolightspace.com>
Original-GitOrigin-RevId: 272d52ff7ad47f43c4dac4976c9b90dc2099fb88
Original-Change-Id: Id5a1437d1f341b9a869ba86398d9538bdaf3d8e4
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5648161
Original-Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
GitOrigin-RevId: f84716e6fb778e2ceb4ed1fc37c4fad9ab239810
Cr-Build-Id: 8692997918305252721
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692997918305252721
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ia9aadb649688c2d3b786355d6284b5884514d571
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7439530
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>