drivers: mfd: mfd_adp5585: Fix -Wsometimes-uninitialized warning
When building with clang it warns:

drivers/mfd/mfd_adp5585.c:59:6: error: variable 'reg_int_status' is used
uninitialized whenever 'if' condition is false
[-Werror,-Wsometimes-uninitialized]
        if (ret == 0) {
            ^~~~~~~~
drivers/mfd/mfd_adp5585.c:70:7: note: uninitialized use occurs here
        if ((reg_int_status & ADP5585_INT_GPI)
             ^~~~~~~~~~~~~~    && device_is_ready(data->child.gpio_dev)) {
drivers/mfd/mfd_adp5585.c:59:2: note: remove the 'if' if its condition
is always true
        if (ret == 0) {
        ^~~~~~~~~~~~~~
drivers/mfd/mfd_adp5585.c:54:24: note: initialize the variable
'reg_int_status' to silence this warning
        uint8_t reg_int_status;
                              ^
                               = '\0'

(cherry picked from commit 57f38844eed63237ab37e19130ac6e053039c529)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 57f38844eed63237ab37e19130ac6e053039c529
Original-Cr-Build-Id: 8723550454920298305
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723550454920298305
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I9f6e71846539de55e0141738d4597ea5c7360833
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6242999
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Original-Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
Original-Commit-Queue: Jonathon Murphy <jpmurphy@google.com>
Original-Tested-by: Jeremy Bettis <jbettis@chromium.org>
GitOrigin-RevId: b66211edcaeda89266d04af8a5e554fb4476986f
Cr-Build-Id: 8692862747512897393
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692862747512897393
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I8dce83d212b6ba609bef7f8caa9be3f5df06fc0d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7455298
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>