UPSTREAM: b64_decode-test: Properly terminate strings before comparison
Undefined behavior in unit-tests is no fun.  assert_string_equal()
expects properly zero-terminated strings. None of the encoded test
strings contain a termination, hence add it manually.

Without this change, the test was often failing with a wrong error
message:

    [==========] tests_lib_b64_decode-test(tests): Running 1 test(s).
    [ RUN      ] test_b64_decode
    [  ERROR   ] --- "AB" != "AB"
    [   LINE   ] --- tests/lib/b64_decode-test.c:38: error: Failure!
    [  FAILED  ] test_b64_decode
    [==========] tests_lib_b64_decode-test(tests): 1 test(s) run.

Probably due to unprintable characters in the string. No idea why
my system is more susceptible to this issue.

(cherry picked from commit b8a1115f516874156814ffb6f8c2ccf86bce5ae2)

Original-Change-Id: Id1bd2c3ff06bc1d4e5aa21ddd0f1d5802540999d
Original-Signed-off-by: Nico Huber <nico.h@gmx.de>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/84088
Original-Reviewed-by: Jakub Czapiga <czapiga@google.com>
Original-Reviewed-by: Nicholas Sudsgaard <devel+coreboot@nsudsgaard.com>
Original-Reviewed-by: Paul Menzel <paulepanter@mailbox.org>
Original-Reviewed-by: Matt DeVillier <matt.devillier@gmail.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: b8a1115f516874156814ffb6f8c2ccf86bce5ae2
Cr-Build-Id: 8738457433008515361
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8738457433008515361
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: Id85a90d44182dd45d21825dcd5b871eeaf68dc83
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5814940
Tested-by: Jonathon Murphy <jpmurphy@google.com>
Commit-Queue: Jonathon Murphy <jpmurphy@google.com>
Reviewed-by: Nick Vaccaro <nvaccaro@google.com>
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>