tests: testinstance: enforce utf-8 write
as in windows platfrom the format by default is not utf-8,
and we will see below error

Traceback (most recent call last):
  File "...zephyr\scripts\twister", line 211, in <module>
    ret = main(options)
          ^^^^^^^^^^^^^
  File "...scripts/pylib/twister\twisterlib\twister_main.py",
    tplan.load()
  File "...scripts/pylib/twister\twisterlib\testplan.py",
    self.load_from_file(last_run, filter_platform=connected_list)
  File "...scripts/pylib/twister\twisterlib\testplan.py",
    instance.create_overlay(platform, self.options.enable_asan,
        self.options.enable_ubsan, self.options.enable_coverage,
        self.options.coverage_platform)
  File "...scripts/pylib/twister\twisterlib\testinstance.py"
    f.write(content)
 UnicodeEncodeError: 'gbk' codec can't encode character '\xf8'
 in position 64: illegal multibyte sequence

(cherry picked from commit 1dc43605df780c32ae0d1be2f251465ed21c29cb)

Original-Original-Signed-off-by: Hake Huang <hake.huang@oss.nxp.com>
Original-GitOrigin-RevId: 1dc43605df780c32ae0d1be2f251465ed21c29cb
Original-Change-Id: I1c9f340923091c589dbc6a8d503a889b4f6150e4
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5118253
Original-Tested-by: Yuval Peress <peress@google.com>
Original-Reviewed-by: Yuval Peress <peress@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Yuval Peress <peress@google.com>
GitOrigin-RevId: 1fe1f7817fbd66b055c8d1fc9cb1264283516996
Cr-Build-Id: 8693103384354449825
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693103384354449825
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I27fef7fde1243d771d4565769f888df74419a686
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7426899
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>