chromeos-base/cros-camera-libs: Add missing DEPEND
```
 ../../../../../../../../../mnt/host/source/src/platform2/camera/common/camera_mojo_channel_manager_impl.cc:19:10: fatal error: 'chromeos/mojo/service_constants.h' file not found
 #include <chromeos/mojo/service_constants.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1 error generated.
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/cros-camera-libs:9999

Change-Id: I6d60f59c81adb047691826eb1ae6abaaac921a53
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692087
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>