tests: app_dev: ram_context_for_isr: fix irq_num
This commit fixes build issue when multi level interrupts is enabled,
define TEST_IRQ_NUM as (CONFIG_2ND_LVL_ISR_TBL_OFFSET - 1)
  - CMSIS/Core/Include/core_cm33.h:2438:15: error: array subscript 24
    is above array bounds of volatile uint32_t[16]

(cherry picked from commit e6c9feabef87634e1852bd1882f9fad0bf3678d9)

Original-Signed-off-by: Biwen Li <biwen.li@nxp.com>
GitOrigin-RevId: e6c9feabef87634e1852bd1882f9fad0bf3678d9
Cr-Build-Id: 8696507262808549057
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8696507262808549057
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ib18e9d49ab7a9286a9e9c4930a1265cc4194c8ec
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7222133
Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Tested-by: Jeremy Bettis <jbettis@chromium.org>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>