modules: mbedtls: fix pk ecc functions undefined references
Fix undefined reference to mbedtls_pk_ecc_xxx functions following update
to latest mbedtls version.

(cherry picked from commit b876bd26fd7aacbca07041451408425b338e50f2)

Original-Signed-off-by: Joel Guittet <joelguittet@gmail.com>
GitOrigin-RevId: b876bd26fd7aacbca07041451408425b338e50f2
Change-Id: I50100f1af9a96d3f41c81d9bab2d3e2fbd065d6e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5554681
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>