UPSTREAM: util/smmstoretool/Makefile: Add missing includes
The compilation of the tool fails under the

In file included from util/cbfstool/flashmap/kv_pair.c:6:
util/cbfstool/flashmap/kv_pair.h: In function 'kv_pair_fmt':
util/cbfstool/flashmap/kv_pair.h:81:36:
  error: expected declaration specifiers before '__printf'
   81 |                                    __printf(3, 4);
      |                                    ^~~~~~~~

Including the missing compiler definitions from src/commonlib
fixes the issue.

(cherry picked from commit b722f6e4fe1e4a6008ff55cba652f71d48f963a1)

Original-coreboot-sdk: 2025-10-19_4a3cc37cbd with the error:
Original-Change-Id: I6aa274ab44f8381ee4bd7a3ef7ee8b6cf62b2cb6
Original-Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/92058
Original-Reviewed-by: Sergii Dmytruk <sergii.dmytruk@3mdeb.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: b722f6e4fe1e4a6008ff55cba652f71d48f963a1
Cr-Build-Id: 8678969199106001377
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8678969199106001377
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: Icd76277f38ae7a83f01417105eee83ee683166d3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/7939363
Reviewed-by: Kangheui Won <khwon@chromium.org>
Reviewed-by: Kapil Porwal <kapilporwal@chromium.org>
Tested-by: Kangheui Won <khwon@chromium.org>
Commit-Queue: Kangheui Won <khwon@chromium.org>