build: Fix missing include
This fixes the following build error:

profiles/input/manager.c:102:4: error: implicit declaration of function ‘free’ [-Werror=implicit-function-declaration]
  102 |    free(uhid_enabled);
      |    ^~~~