UPSTREAM: compiler/clc: Fix const correctness in libclc_add_generic_variants
Fix compiler error:

../src/compiler/clc/nir_load_libclc.c:266:13: error: initializing
'char *' with an expression of type 'const char *' discards qualifiers
[-Werror,-Wincompatible-pointer-types-discards-qualifiers]
  266 |       char *U3AS1 = strstr(func->name, "U3AS1");
      |             ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~

glibc now provides C23-style type-generic string functions. strstr
returns const char * when passed a const char * argument. Update U3AS1
declaration to const since it's only used for offset calculation.

Fixes: 4a08ee7ecf0 ("spirv/libclc: Add generic versions of arithmetic functions")
Reviewed-by: Karol Herbst <kherbst@redhat.com>
(cherry picked from commit 85fd63068e91d0dd4b9434831ddddbbc2ff07355)

Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/39828>

Backport Notes:
- resolve trivial .pick_status.json conflict

BUG=b:491765858
TEST=Local build on eve with glibc 2.43; CQ.

Change-Id: I1a9fef9f85c197ed9664961718d80f19c3ec6a45
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/mesa/+/7849840
Reviewed-by: Yiwei Zhang <zzyiwei@google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>
Commit-Queue: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: Sean Paul <sean@poorly.run>
Auto-Submit: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>