UPSTREAM: pw_log_android: Update PW_HANDLE_LOG macro
This addresses the issue with the pw_hex_dump:
```
external/pigweed/pw_hex_dump/public/pw_hex_dump/log_bytes.h:99:7: error: use of undeclared identifier '_PW_LOG_ANDROID_LEVEL_log_level'
   99 |       PW_LOG(log_level,
      |       ^
```

(cherry picked from commit 5b53ba86c0cae8defaf490c452c7d237e55c1e37)

Original-Bug: 436643693
Original-Test: validated PW_LOG are the correct level on logcat
Original-Change-Id: I6fe0a040f57d00afc9ee18d285d2912c03c2e077
Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/310772
Original-Presubmit-Verified: CQ Bot Account <pigweed-scoped@luci-project-accounts.iam.gserviceaccount.com>
Original-Tests-Not-Needed: Alan Rosenthal <alanrosenthal@google.com>
Original-Commit-Queue: Alan Rosenthal <alanrosenthal@google.com>
Original-Reviewed-by: Matthew Sedam <matthewsedam@google.com>
Original-Reviewed-by: Carlos Chinchilla <cachinchilla@google.com>
Original-Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Original-Docs-Not-Needed: Alan Rosenthal <alanrosenthal@google.com>
GitOrigin-RevId: 5b53ba86c0cae8defaf490c452c7d237e55c1e37
Cr-Build-Id: 8707261876515415425
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8707261876515415425
Copybot-Job-Name: pigweed-main-copybot-downstream
Change-Id: Ic6ca0d03b36489b9801b642b2cca7f8286f30318
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/pigweed/pigweed/+/6823069
Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Tested-by: Al Semjonovs <asemjonovs@google.com>
Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>