drivers: i2c: dw: guard need_setup write with its Kconfig
The need_setup member of struct i2c_dw_dev_config only exists when
CONFIG_I2C_ALLOW_NO_STOP_TRANSACTIONS is enabled, and every other
access to it in the driver is wrapped in a matching #if. The write
added in i2c_dw_transfer() to require a re-setup after a failed or
aborted transaction was left unguarded, so the driver fails to build
whenever that option is off:

  drivers/i2c/i2c_dw.c:1032:19: error: 'struct i2c_dw_dev_config'
  has no member named 'need_setup'

Wrap the write in the same #if used by the rest of the driver.

Original-Signed-off-by: Anas Nashif <anas.nashif@intel.com>
GitOrigin-RevId: c5dffcb7c9da611b40a828f79fc6a8405416c1ed
Cr-Build-Id: 8673450334443198817
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8673450334443198817
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I1964ada7017d4c49c672c8022ba97de6c7734564
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/8262445
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>