chromeos-base/shill: Add missing BDEPEND
```
FAILED: gen/include/supplicant/dbus-proxies.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

```
FAILED: gen/include/shill/mobile_operator_db/mobile_operator_db.pb.cc gen/include/shill/mobile_operator_db/mobile_operator_db.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/shill:9999

Change-Id: I03050f777e9da53e9d94c5c366520546aec1810c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692132
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>