feedback: perf_data_extract: Improve docs, validation of 'out'
The README has been wrong since:
https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4055244

If we follow the old docs, we get weird Python errors:

Traceback (most recent call last):
  File "[...]/chromiumos/src/platform2/feedback/tools/perf_data_extract.py", line 131, in <module>
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "[...]/chromiumos/src/platform2/feedback/tools/perf_data_extract.py", line 119, in main
    with open(out, "wb") as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'perf.proto/feedback_perf.data'

Turn this into a clearer error message:

  Error: perf.proto is not a directory

Fix up a few other things while at it:

 * Make opts.out consistently a Path type
 * Use Path operations more consistently
 * Make the "defaults to current dir" help text true (currently, the 2nd
   positional argument is required)

BUG=none
TEST=run it / read it

Change-Id: I47b17a13996b33f711685eaaccf9713cebccccd8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/5660922
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: David Padlipsky <dpad@google.com>
Auto-Submit: Brian Norris <briannorris@chromium.org>
Commit-Queue: Brian Norris <briannorris@chromium.org>
Tested-by: Brian Norris <briannorris@chromium.org>