cros-codecs: fix build issues with "queue" for v4l2 stateless decoder
This CL fixes the following build issues with v4l2 stateless decoder in
queue.rs.
- error[E0432]: unresolved import
  `v4l2r::device::queue::qbuf::get_free`
- error[E0432]: unresolved import `v4l2r::device::queue::qbuf::weak`
- error[E0599]: no method named `try_get_free_buffer` found for
  reference `&Queue<v4l2r::device::queue::direction::Output,
  BuffersAllocated<Vec<MmapHandle>>>` in the current scope
- error[E0106]: missing lifetime specifier
- error[E0061]: this method takes 1 argument but 2 arguments were supplied
- error[E0308]: mismatched types

BUG=b:379730690
TEST=cargo build --example=ccenc --features=v4l2
TEST=cargo build --example=ccdec-v4l2-stateless --features=v4l2-experimental

Change-Id: I102db398d2dd9f6c9d0a986fc860c480904e338e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/6044282
Tested-by: Steve Cho <stevecho@chromium.org>
Reviewed-by: Justin Green <greenjustin@google.com>
Commit-Queue: Steve Cho <stevecho@chromium.org>