Autoupdate of 2 submodules
*chromite updated to e086675dc41b173c06b6f7914745f20e2aafdbe0
lib: Rename sysroot.Path -> sysroot.JoinPath

Currently the `Path` method confounds typecheckers, making type
signatures attempting to use pathlib.Path resolve incorrectly:

  lib/sysroot_lib.py:451: error: Function
    "chromite.lib.sysroot_lib.Sysroot.Path" is not valid as a type
    [valid-type]
  lib/sysroot_lib.py:451: note: Perhaps you need "Callable[...]" or a
    callback protocol?
  lib/sysroot_lib.py:454: error: Path? has no attribute "name"
    [attr-defined]

Sysroot already has a `path` data member. The Path method joins it with
os.path.join(). Rename to JoinPath to get some headway on getting more
files typechecking cleanly.

One day the sysroot.path data member will be a pathlib.Path and it will
be simpler just to do `sysroot.path / "foo"`, but today is not that day.

BUG=b:280696893
TEST=./run_tests, CQ

Change-Id: Ic424bb930c0a3d61f9eca562a10beecf669d150a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4929169
Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
Commit-Queue: Trent Apted <tapted@chromium.org>
Tested-by: Trent Apted <tapted@chromium.org>

*infra/chromite-HEAD updated to e086675dc41b173c06b6f7914745f20e2aafdbe0
lib: Rename sysroot.Path -> sysroot.JoinPath

Currently the `Path` method confounds typecheckers, making type
signatures attempting to use pathlib.Path resolve incorrectly:

  lib/sysroot_lib.py:451: error: Function
    "chromite.lib.sysroot_lib.Sysroot.Path" is not valid as a type
    [valid-type]
  lib/sysroot_lib.py:451: note: Perhaps you need "Callable[...]" or a
    callback protocol?
  lib/sysroot_lib.py:454: error: Path? has no attribute "name"
    [attr-defined]

Sysroot already has a `path` data member. The Path method joins it with
os.path.join(). Rename to JoinPath to get some headway on getting more
files typechecking cleanly.

One day the sysroot.path data member will be a pathlib.Path and it will
be simpler just to do `sysroot.path / "foo"`, but today is not that day.

BUG=b:280696893
TEST=./run_tests, CQ

Change-Id: Ic424bb930c0a3d61f9eca562a10beecf669d150a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4929169
Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
Commit-Queue: Trent Apted <tapted@chromium.org>
Tested-by: Trent Apted <tapted@chromium.org>