samples: net: midi2: Fix compiler warning
When building with clang we get the following warning when building the
sample.net.midi2.host_auth_user test:

samples/net/midi2/src/main.c:122:54: error: initializer element is not a
compile-time constant
  122 | NETMIDI2_EP_DEFINE_WITH_USERS(midi_server, ump_ep_dt.name, NULL, 0,
      |                                            ~~~~~~~~~~^~~~
include/zephyr/net/midi2.h:99:12: note: expanded from macro
'NETMIDI2_EP_DEFINE_WITH_USERS'
   99 |                 .name = (_ep_name), \
      |                          ^~~~~~~~

Instead of using ump_ep_dt.name for initialization, we use the
equivalent expression that UMP_ENDPOINT_DT_SPEC_GET(DT_NODELABEL(midi2))
initializes the ".name" member with.

(cherry picked from commit f9664d51c31b2dffaa37c78e4f85db72a77ff232)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: f9664d51c31b2dffaa37c78e4f85db72a77ff232
Cr-Build-Id: 8692045360469606417
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692045360469606417
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I33e94b90507e9db7776515174d83d9c01cb12d45
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7505893
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>