tests: mgmt: mcumgr: Disable clang warning
When building with clang it reports:

tests/subsys/mgmt/mcumgr/settings_mgmt/src/main.c:69:22: error: variable
'test_response_read_data_start' is not needed and will not be emitted
[-Werror,-Wunneeded-internal-declaration]
static const uint8_t test_response_read_data_start[5] = {
                     ^
tests/subsys/mgmt/mcumgr/settings_mgmt/src/main.c:73:22: error: variable
'test_response_read_data_end' is not needed and will not be emitted
[-Werror,-Wunneeded-internal-declaration]
static const uint8_t test_response_read_data_end[1] = {
                     ^

The values of test_response_read_data_start and
test_response_read_data_end are not actually used anywhere in the tests.

(cherry picked from commit 11e3aa89521c7d59b3929b8381c7ab395f743ccc)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: 11e3aa89521c7d59b3929b8381c7ab395f743ccc
Cr-Build-Id: 8718567623776601377
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8718567623776601377
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I5fecb8c8907ed2787bbbcf981e3e22414a8e6721
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6432110
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>