chromeos-base/dlcservice: Add missing BDEPEND
```
FAILED: gen/include/dlcservice/dbus_adaptors/org.chromium.DlcServiceInterface.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

```
/build/arm64-generic/etc/portage/hooks/install/check-seccomp.sh: line 27: compile_seccomp_policy: command not found
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/dlcservice:9999

Change-Id: I2c2bc024311565e93f11437df27fc2012f8160c4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692096
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>