west: build.py: resolve symlinks in cached source directory check
Fixes the following error:

  dir in CMakeCache.txt>", but source directory "<resolved source dir>"
  was specified; please clean it, use --pristine, or use --build-dir to
  set another build directory
FATAL ERROR: refusing to proceed without --force due to above error

Fixes initial commit ab82264ace163 ("scripts: add west build, flash, and
debug commands")

Original-ERROR: Build directory "<whatever>" is for application "<symbolic source
Original-Signed-off-by: Marc Herbert <marc.herbert@intel.com>
GitOrigin-RevId: c2524a07a661828f0e7f65f58cece1023aa9a5d1
Cr-Build-Id: 8693680922092463713
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693680922092463713
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I23c080d0476ea7e5e72ec58ed71961aa32bf6bfa
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7385236
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>