chromeos-base/libbrillo: Add missing BDEPEND
```
FAILED: gen/include/brillo/proto_bindings/install_attributes.pb.cc gen/include/brillo/proto_bindings/install_attributes.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/libbrillo:9999

Change-Id: I1271eabe10208c8d5ab37534bd52f4e2ba401175
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692106
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>