UPSTREAM: drivers/lenovo/hybrid_graphics: Add missing header
Include the missing header stdbool.h

Fixes compilation error
hybrid_graphics.h:6:28: error: unknown type name 'bool'
while refactoring some code.

(cherry picked from commit 6a20caea01c5c72a4e57217990ac6aacdc6b7724)

Original-Change-Id: I96f7255049cd9e24d74838a173e920a00636b09e
Original-Signed-off-by: Patrick Rudolph <patrick.rudolph@9elements.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/88546
Original-Reviewed-by: Paul Menzel <paulepanter@mailbox.org>
Original-Reviewed-by: Angel Pons <th3fanbus@gmail.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: 6a20caea01c5c72a4e57217990ac6aacdc6b7724
Cr-Build-Id: 8708345266036186753
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8708345266036186753
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I6787b26f2fb69af990981758910291bd894f5378
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6788470
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Kshitij Shah <tij@google.com>
Reviewed-by: Kshitij Shah <tij@google.com>