bluetooth: tester: vcp: Remove unused include
Fixes build error:
mesh/keys.h:40:2: error: #error "Crypto library has not been chosen"

(cherry picked from commit 76dc5d37cb136fea15e84a5cdd3c59cc84763784)

Original-Original-Signed-off-by: Magdalena Kasenberg <magdalena.kasenberg@codecoup.pl>
Original-GitOrigin-RevId: 76dc5d37cb136fea15e84a5cdd3c59cc84763784
Original-Change-Id: I1b1ab030521adc333c698d9457e0d82cb0f16a05
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4649631
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
Original-Tested-by: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: 138f913db7833002dddc7aa6d591d1f7ee0a42c0
Cr-Build-Id: 8693193308765882737
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693193308765882737
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ifda8e09f9b0f164960a02b2a87791a5ce5497943
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7419058
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>