net: ipv6: use static inlines where it makes sense for stubs
If we're disabling certain features and instead providing function stubs,
it doesn't make sense to use macros for those routines that return values
that the user may check unless we want to provide them with vague errors

src/coap-server.c:101:55: error: expected expression before ';' token
  101 |  ret = net_ipv6_mld_join(iface, &mcast_addr.sin6_addr);

When a function we're mocking up returns a value, use a static inline
stub.

(cherry picked from commit 7cddc5a6a3301f092fb602ef28b5b2e91c9ceec3)

Original-like:
Original-Original-Signed-off-by: Bartosz Golaszewski <bartosz.golaszewski@huawei.com>
Original-GitOrigin-RevId: 7cddc5a6a3301f092fb602ef28b5b2e91c9ceec3
Original-Change-Id: I9ce3b0a473c501d0bbe965e1c8c5da243cd78dae
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3791123
Original-Tested-by: Al Semjonovs <asemjonovs@google.com>
Original-Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Original-Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
GitOrigin-RevId: d7b6671d5d7a920eac5d96d93262f5d1b65410b4
Cr-Build-Id: 8693500042307236321
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693500042307236321
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Icc1693e6b054762fd07fccf4b61958061222a4fa
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7397350
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>