chromeos-base/u2fd: Add missing BDEPEND
```
FAILED: gen/include/bindings/policy_common_definitions.pb.cc gen/include/bindings/policy_common_definitions.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/u2fd:9999

Change-Id: I67fa88567aaeacde84402701885aa0cefdd070ac
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692141
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>