chromeos-base/vm_protos: Add missing BDEPEND
```
FAILED: gen/go/src/vm_guest.pb.go gen/go/src/vm_host.pb.go
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
FAILED: gen/go/src/vm_guest.pb.go gen/go/src/vm_host.pb.go
protoc-gen-go: program not found or is not executable
```

```
[2/51] ACTION //vm_tools/proto:tremplin-rpcs_gen(//common-mk/toolchain:toolchain)
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/vm_protos:9999

Change-Id: I8fe74105f7a384e420969cbe4d9ba978413d53a4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692144
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>