Bluetooth: Classic: AVRCP: Fix another Clang/LLVM build failure
subsys/bluetooth/host/classic/shell/avrcp.c:407:3: error: label followed
by a declaration is a C23 extension [-Werror,-Wc23-extensions]
  407 |                 uint64_t identifier;
      |                 ^

(cherry picked from commit 3ab1caa87f073893fb564d1bd8062eaa8f8523d5)

Original-Original-Signed-off-by: Johan Hedberg <johan.hedberg@silabs.com>
Original-GitOrigin-RevId: 3ab1caa87f073893fb564d1bd8062eaa8f8523d5
Original-Cr-Build-Id: 8698221080423948257
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8698221080423948257
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I8b4ff695e2c95d11d900c8af5e9bca9a3e2d9e9c
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7158231
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 0b750583658b0dd5129a74da48f7fdecfacec65e
Cr-Build-Id: 8692642471503419777
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692642471503419777
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ide975ed883f063646fc90cbd1b080b3237451a9d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7480246
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>