sys-devel/gcc: Re-enable NLS Android Bringup: See http://go/android-fw-sync
There's a build failure when cross-compiling gcc for RISCV:

In file included from
/var/tmp/portage/cross-riscv32-cros-elf/gcc-10.2.0-r44/work/gcc-10.2.0/libcpp/mkdeps.c:24:
/usr/include/libintl.h:44:14: error: expected unqualified-id before 'const'
   44 | extern char *dgettext (const char *__domainname, const char *__msgid)
      |              ^~~~~~~~
/usr/include/libintl.h:44:14: error: expected ')' before 'const'

The failure occurs while building libcpp. The only configuration that
successfully builds is with NLS enabled for gcc and forcing libcpp to
enable NLS.

BUG=b:405175575, b:355044350, b:248739853
TEST=sudo `which cros_setup_toolchains` -t riscv32-cros-elf --nousepkg
TEST=sudo emerge cross-riscv32-cros-elf/gcc

(cherry picked from commit 9a257d179e7994707a3833f23e02e8f2a998ae09)

Change-Id: Ie9655bb576ec2ac0c16541997b5f1907c67b6a2c
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/6300621
Original-Reviewed-by: Raul Rangel <rrangel@chromium.org>
Original-Commit-Queue: Tom Hughes <tomhughes@chromium.org>
Original-Tested-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: 9a257d179e7994707a3833f23e02e8f2a998ae09
Cr-Build-Id: 8718819295358141265
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8718819295358141265
Copybot-Job-Name: android-main-chromiumos-overlay-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/6421245
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
Commit-Queue: Jonathon Murphy <jpmurphy@google.com>