fix: update boost.detail (#2845)
- add missing textual hdrs
- need skip url stability check
- boost.serialization needs this header
```
~/workspace/serialization tags/boost-1.77.0* 11s
❯ bazelisk build //... --process_headers_in_dependencies
INFO: Analyzed target //:boost.serialization (0 packages loaded, 0 targets configured).
ERROR: /Users/daisuke/workspace/serialization/BUILD.bazel:5:11: Compiling src/utf8_codecvt_facet.cpp failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target //:boost.serialization) external/bazel_tools~cc_configure_extension~local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 483 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
src/utf8_codecvt_facet.cpp:19:10: fatal error: 'boost/detail/utf8_codecvt_facet.ipp' file not found
   19 | #include <boost/detail/utf8_codecvt_facet.ipp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //:boost.serialization failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 13.543s, Critical Path: 3.23s
INFO: 62 processes: 9 internal, 53 darwin-sandbox.
ERROR: Build did NOT complete successfully
```

Signed-off-by: wep21 <daisuke.nishimatsu1021@gmail.com>