mgmt: mcumgr: drop few redeclared/shadowed variables
Drop few redeclared variables, fixes some:

settings_mgmt.c:454:30: error: declaration of ok shadows a previous
local [-Werror=shadow]
  454 |                         bool ok;
      |                              ^~
settings_mgmt.c:436:14: note: shadowed declaration is here
  436 |         bool ok = true;
      |              ^~

(cherry picked from commit 7b59e34a226dafd0e5a07821501170eee5cc3b7f)

Original-Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-GitOrigin-RevId: 7b59e34a226dafd0e5a07821501170eee5cc3b7f
Original-Change-Id: I5c9fbbb3a33307bda2c4bbf052dff9bf3aa36047
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4822146
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Yuval Peress <peress@google.com>
Original-Commit-Queue: Yuval Peress <peress@google.com>
Original-Tested-by: Yuval Peress <peress@google.com>
GitOrigin-RevId: e5c5deefbfeaed7d533fc8f50154a429c8b1b0c8
Cr-Build-Id: 8693167124640721729
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693167124640721729
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I6e75efd25207abd0d8ea0e2e8623803e1bf64762
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7422009
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>