chromeos-base/dlp: Add missing BDEPEND
```
FAILED: gen/include/dlp/dbus-proxies.h gen/include/dlp/dbus-proxy-mocks.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

```
/build/arm64-generic/etc/portage/hooks/install/check-seccomp.sh: line 27: compile_seccomp_policy: command not found
 * ERROR: chromeos-base/dlp-9999::chromiumos failed:
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/dlp:9999

Change-Id: I0aeb5edd9e35230cf81c9fbd07101cd70a88e935
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692097
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>