CHROMIUM: media: platform: mediatek: isp: Remove usage of cmdq_cb_status
Remove usage of error status "cmdq_cb_status". It's removed in UPSTREAM
CL:3244691. Otherwise, there's build error after applied the CL.

CC [M]  drivers/media/platform/mtk-isp/isp_50/dip/mtk_dip-sys.o
/mnt/host/source/src/third_party/kernel/v5.10/drivers/media/platform/mtk-isp/isp_50/dip/mtk_dip-sys.c:233:18:
error: use of undeclared identifier 'CMDQ_CB_NORMAL'
        if (data.sta != CMDQ_CB_NORMAL) {
                        ^
1 error generated.

Signed-off-by: jason-jh.lin <jason-jh.lin@mediatek.com>

Cherry-pick from v5.10 and modify the ISP part only.

BUG=b:341019453
TEST=build pass
UPSTREAM-TASK=b:368493852

Change-Id: I31e560043d1ebce8e9cf6f4bdf8fc6ff277b6270
Signed-off-by: Olivia Wen <olivia.wen@mediatek.corp-partner.google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/5733724
Reviewed-by: Hsin-Te Yuan <yuanhsinte@chromium.org>
Commit-Queue: Hsin-Te Yuan <yuanhsinte@chromium.org>
Tested-by: Hsin-Te Yuan <yuanhsinte@chromium.org>