twister: coverage: guard against unset ZEPHYR_TOOLCHAIN_VARIANT
choose_gcov_tool() called .endswith() directly on the result of
os.environ.get("ZEPHYR_TOOLCHAIN_VARIANT"). When the variable is not
exported in the environment, get() returns None and the coverage run
aborts with:

  AttributeError: 'NoneType' object has no attribute 'endswith'

Provide an empty-string default so an unset variant safely falls
through to the system gcov / Zephyr SDK gcov branches instead of
crashing.

Original-Signed-off-by: Anas Nashif <anas.nashif@intel.com>
GitOrigin-RevId: fbbefff301ca1a882c1b02c57cf65de1f0830883
Cr-Build-Id: 8676190885013464769
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8676190885013464769
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ib1d4814f43c91ad9ca5240aef4ec269a0cb6461f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/8099089
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: Ting Shen <phoenixshen@chromium.org>
Commit-Queue: Ting Shen <phoenixshen@chromium.org>
Reviewed-by: Ting Shen <phoenixshen@chromium.org>