net: Fix alignment error with net_ipaddr_copy()
As struct sockaddr have now alignment of 4 bytes, net_ipaddr_copy()
gives the following error if used for sockaddr:

  error: alignment 1 of ‘struct <anonymous>’ is less than 4
  [-Werror=packed-not-aligned]

Just use memcpy() instead, net_ipaddr_copy() was intended to use with IP
addresses, not socket related structs.

(cherry picked from commit 62a5260e0182f3327982b382922e52deb4fed1d0)

Original-Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>
GitOrigin-RevId: 62a5260e0182f3327982b382922e52deb4fed1d0
Cr-Build-Id: 8710232702044463633
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8710232702044463633
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ia080cc7724d156e0211b64ff88840660ec652a71
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6706040
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>