modules: opentread: platform: inclusion of assert.h header to udp.c
This commit add assert.h header file to avoid compilation warning due to
imnplicit declaration of function assert and respective linking related

Original-error: undefined reference to 'assert'
Original-Signed-off-by: Marcio Ribeiro <marcio.ribeiro@espressif.com>
GitOrigin-RevId: 19f4a75362e98a286d92beb0cc60a8127ebcfecb
Cr-Build-Id: 8684333769233633969
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8684333769233633969
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I563bb23640603e5c6a5b5acaba551b23f87cd917
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7769558
Commit-Queue: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>