sysconfig.py: add posix_user install scheme
This CL cleans up previous hacks to make "python -m ensurepip" work
under Python 3.11.

As noted by gbiv@ in b/378723931, while trying to determine the location
to install packages, pip invokes:

    sysconfig.get_paths(scheme='posix_user', vars={})

(This takes place here:
https://github.com/pypa/pip/blob/97146c7f4cd85551f3dc261830a57f304e43c181/src/pip/_internal/locations/_sysconfig.py#L170.)

However, our custom sysconfig.py module does not have a 'posix_user'
entry in its _INSTALL_SCHEMES dictionary. To compensate,
sysconfig.get_paths() defaults to 'posix_prefix' when 'posix_user' is
specified. Therefore, sysconfig.get_paths() returns the paths to the
system-wide Python installation, and this causes pip to fail with:

    ERROR: Could not install packages due to an OSError:
    [Errno 13] Permission denied: '/usr/lib/python3.11/site-packages/pip'

This CL adds a 'posix_user' entry to the _INSTALL_SCHEMES dictionary
based on the official sysconfig.py module and cleans up a previous
attempt at fixing pip (https://crrev.com/c/6032529).

BUG=b:379681945
TEST=EPYTHON=python3.11 python -m ensurepip
TEST=EPYTHON=python3.8 python -m ensurepip
TEST=CQ

Change-Id: I0734d34086edbc3e4c2316f57bdaa43844a53c63
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/6032420
Auto-Submit: Leandro Lovisolo <lovisolo@google.com>
Tested-by: Leandro Lovisolo <lovisolo@google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>
Commit-Queue: George Burgess <gbiv@chromium.org>