chromeos-base/power_manager: Add missing BDEPEND
```
FAILED: gen/include/modemmanager/dbus-proxies.h
/usr/bin/env ../../../../../../../../../../mnt/host/source/src/platform2/common-mk/file_generator_wrapper.py go-generate-chromeos-dbus-bindings -service-config= -proxy=/build/arm64-generic/tmp/portage/chromeos-base/power_manager-9999/work/build/out/Default/gen/include/modemmanager/dbus-proxies.h ../../../../../../../../usr/share/dbus-1/interfaces/org.freedesktop.ModemManager1.Modem.Sar.xml ../../../../../../../../usr/share/dbus-1/interfaces/org.freedesktop.ModemManager1.Modem.xml ../../../../../../../../usr/share/dbus-1/interfaces/org.freedesktop.ModemManager1.xml ../../../../../../../../../../mnt/host/source/src/platform2/power_manager/dbus_bindings/dbus-objectmanager.dbus-xml
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/power_manager:9999

Change-Id: Ib13072a863fafeadf9f53c023b46606b95673fbd
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692123
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>