drivers: display: ed2208: Fix format warning
%zu should only used for argument of size_t type, but the buf_size is of
uint32_t type. Casting to size_t is required. Otherwise, a warning will
occur with compiler of 64-bit platforms.

    drivers/display/display_ed2208_gca.c:238:25: error: format
    '%zu' expects argument of type 'size_t', but argument 3 has
    type 'uint32_t' {aka 'unsigned int'} [-Werror=format=]

Original-Signed-off-by: Nhut Nguyen <nhut.nguyen.kc@renesas.com>
GitOrigin-RevId: 4cf010b96c7c28ce3b5f73cbb92b93feed5bd3ec
Cr-Build-Id: 8670370036151434993
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8670370036151434993
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I22cacb065ed30889b4e001ffb4f95e99023f9a2f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/8428817
Bot-Commit: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>