tflite: log: Use tflite::Flag instead of absl::Flag
ABSL_FLAG is global by design, which does not play well with the
dlopen() for stable delegate. If the main binary also uses the same
flag, one may get a confusing error like:
```
ERROR: Flag 'v' was defined more than once but with differing types.
Defined in files 'common/log.cc' and 'common/log.cc'.
```

BUG=b:305999697
TEST=Run async_delegate_test with sample delegate

Change-Id: If2221ff3df0f7fad37f6a62a0ff080c77e26f25e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tflite/+/5529158
Tested-by: Tommy Chiang <ototot@google.com>
Reviewed-by: Tommy Chiang <ototot@google.com>
Auto-Submit: Shik Chen <shik@chromium.org>
Commit-Queue: ChromeOS Auto Retry <chromeos-auto-retry@chromeos-bot.iam.gserviceaccount.com>