Autoupdate of 2 submodules
*chromite updated to 4989353921a9f950c3da27416457a5db84686e8b
api: Fix compile_build_api_proto

rglob returns files and folders. We currently have an OWNERS file in
the directory, so this causes:

> NotADirectoryError: [Errno 20] Not a directory: '/home/rrangel/chromiumos/chromite/api/gen/OWNERS/__init__.py'

BUG=b:441551312
TEST=./compile_build_api_proto

Change-Id: I0d20fa190054600a1647ded3299ca41dc2bb75bb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/6892161
Commit-Queue: Greg Edelston <gredelston@google.com>
Auto-Submit: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Greg Edelston <gredelston@google.com>
Commit-Queue: Raul Rangel <rrangel@chromium.org>

*infra/chromite-HEAD updated to 4989353921a9f950c3da27416457a5db84686e8b
api: Fix compile_build_api_proto

rglob returns files and folders. We currently have an OWNERS file in
the directory, so this causes:

> NotADirectoryError: [Errno 20] Not a directory: '/home/rrangel/chromiumos/chromite/api/gen/OWNERS/__init__.py'

BUG=b:441551312
TEST=./compile_build_api_proto

Change-Id: I0d20fa190054600a1647ded3299ca41dc2bb75bb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/6892161
Commit-Queue: Greg Edelston <gredelston@google.com>
Auto-Submit: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Greg Edelston <gredelston@google.com>
Commit-Queue: Raul Rangel <rrangel@chromium.org>