chromeos-base/crosier-chrome: Fix missing BDEPEND
```
  File "/build/brya/tmp/portage/chromeos-base/crosier-chrome-0.0.1-r28/work/crosier-chrome-0.0.1/platform/dev/test/gtest/generate_gtest_metadata.py", line 21, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
 * ERROR: chromeos-base/crosier-chrome-0.0.1-r28::chromiumos failed (install phase):
 *   Failed to generate metadata file 'gtest_metadata.pb'!
```

```
Traceback (most recent call last):
  File "/build/brya/tmp/portage/chromeos-base/crosier-chrome-9999/work/crosier-chrome-9999/platform/dev/test/gtest/generate_gtest_metadata.py", line 23, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
 * ERROR: chromeos-base/crosier-chrome-9999::chromiumos failed (install phase):
```

BUG=b:340139250
TEST=BOARD=brya bazel build -k --config=prebuilts @portage//target/chromeos-base/crosier-chrome

Change-Id: I3f29cf162a60c55e3a6c067597ec80a1b660b6fa
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/5535765
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Tim Bain <tbain@google.com>