meson: Add missing long-long option in conf_data.set for tinystdio
Seems like adding the 'long-long' option to the conf_data.set()
options for 'tinystdio' was accidentally missed. This leads
'_FORMAT_DEFAULT_LONG_LONG' not being set when using the
'format-default=long-long' option, which ultimately leads to the
'vfprintf' etc functions not being registered properly:

    picolibc/newlib/libc/tinystdio/printf.c:41: \
        undefined reference to `vfprintf'

Fix this by adding in the missing entry for the 'long-long' variant.

(cherry picked from commit 4b2b54d03bd300419ac9f8b4e19d5d3b1c7ff957)

Original-Fixes: ca70b2a7ad8b ("libc/tinystdio: Add 'long-long' printf/scanf variants")
Original-Signed-off-by: Louis Peens <louis.peens@corigine.com>
GitOrigin-RevId: 4b2b54d03bd300419ac9f8b4e19d5d3b1c7ff957
Cr-Build-Id: 8723641049794645873
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723641049794645873
Copybot-Job-Name: zephyr-picolibc-copybot-downstream
Change-Id: I9bcf754aafba2b99b8eae5a078ae9fc5f03c34b6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/picolibc/+/6241206
Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>