chromeos-base/patchpanel: Add missing BDEPEND
```
FAILED: gen/include/patchpanel/ipc.pb.cc gen/include/patchpanel/ipc.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```
```
FAILED: gen/include/patchpanel/dbus_adaptors/org.chromium.patchpanel.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/patchpanel:9999

Change-Id: Ie68558e8ec602a9bb166015b04f2348b0c15da94
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692121
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>