UPSTREAM: mb/trulo/var/pujjolo: Fix gtx functions.
Add gtx flag in Kconfig and delete the gtx property to fix build error in below
coreboot-0.0.1-r5710: [01m[K/build/nissa/tmp/portage/sys-boot/coreboot-0.0.1-r5710/work/build/pujjolo/mainboard/google/brya/static.c:213:20:[m[K [01;31m[Kerror: [m[K'[01m[Kstruct drivers_gfx_generic_device_config[m[K' has no member named '[01m[Ktype[m[K'
coreboot-0.0.1-r5710:   213 |         .device[0].[01;31m[Ktype[m[K = panel,
coreboot-0.0.1-r5710:       |                    [01;31m[K^~~~[m[K
coreboot-0.0.1-r5710: [01m[K/build/nissa/tmp/portage/sys-boot/coreboot-0.0.1-r5710/work/build/pujjolo/mainboard/google/brya/static.c:213:27:[m[K [01;31m[Kerror: [m[K'[01m[Kpanel[m[K' undeclared here (not in a function)
coreboot-0.0.1-r5710:   213 |         .device[0].type = [01;31m[Kpanel[m[K,
coreboot-0.0.1-r5710:       |                           [01;31m[K^~~~~[m[K

BUG=b:395763555
BRANCH=none
TEST=Build pujjolo

(cherry picked from commit 24778a25decbcfaa2e8e5daf8c9819d388d86927)

Original-Change-Id: I4e85f3c9acbee66226d8dd195615d9c9dd212709
Original-Signed-off-by: Luca Lai <luca.lai@lcfc.corp-partner.google.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/87956
Original-Reviewed-by: Eric Lai <ericllai@google.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Kapil Porwal <kapilporwal@google.com>
Original-Reviewed-by: Subrata Banik <subratabanik@google.com>
GitOrigin-RevId: 24778a25decbcfaa2e8e5daf8c9819d388d86927
Cr-Build-Id: 8712828215516436401
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8712828215516436401
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I401147735d0195e8d62a72c17d576d0c54c3264a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6625547
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>