net: http: Fix linking issues with clang
There is a linking failure if using clang and no optimizations

subsys/net/lib/http/http_server_core.c:1060:
   (.text.handle_listen_pollin+0x159):
   undefined reference to `accept_h3_connection'
subsys/net/lib/http/http_server_core.c:1101:
   (.text.handle_listen_pollin+0x425):
   undefined reference to `h3_open_uni_streams'

When CONFIG_NO_OPTIMIZATIONS=y was set.

Original-Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
GitOrigin-RevId: 5c60b811f9bc2cd9f4738ec1f7d61ca0dd6f7371
Cr-Build-Id: 8681332269423558993
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8681332269423558993
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ia1bc8204dbe2715fc2fb45d7073a170a4bdcc274
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7861709
Bot-Commit: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Ting Shen <phoenixshen@chromium.org>