sensors: ite_vcmp: fix build error
Fix build error:

error: '((const struct vcmp_it8xxx2_config *)config)->adc' is a pointer

Tested with: west build -p -b it8xxx2_evb samples/sensor/sensor_shell
-DCONFIG_ADC=y -DCONFIG_COMPARATOR=y -DCONFIG_LOG=y

(cherry picked from commit dbcba4794ac5a8e99a9467f4dde03a9616a90368)

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Change-Id: Ia7decee8beed0b7f176715e498fafdc258be107c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7792832
Reviewed-by: Keith Short <keithshort@chromium.org>