floss FROMGIT: osi: compat: fix memset builds with clang+glibc >=2.41 Android Bringup: See http://go/android-fw-sync
The BT tree is used by ChromeOS where it gets built
using clang and glibc. Starting with clang 21 and glibc
2.41 warnings like the following are emitted for memset
and are treated as errors:

/bta/hf_client/bta_hf_client_main.cc:253:10: error: first argument in call to 'memset' is a pointer to non-trivially copyable type 'tBTA_HF_CLIENT_CB_ARR' [-Werror,-Wnontrivial-memcall]
  253 |   memset(&bta_hf_client_cb_arr, 0, sizeof(tBTA_HF_CLIENT_CB_ARR));
      |          ^
bta/hf_client/bta_hf_client_main.cc:253:10: note: explicitly cast the pointer to silence this warning
  253 |   memset(&bta_hf_client_cb_arr, 0, sizeof(tBTA_HF_CLIENT_CB_ARR));
      |          ^
      |          (void*)
1 error generated.

Those in the cleanup functions for simple structures
are ok, the one in hf_client can be replaced with a
simple value init, however the one in btif is more
complex so I added a TODO to eventually write some
proper cleanup logic.

(cherry-pick from http://ag/34093275)

BUG=b:324437695
TEST=m com.android.bt; clang+glibc build in ChromeOS.

(cherry picked from commit ac8e6f15c54a20173b660bac1801507104bd8039)

Change-Id: I0a61bed4e6827a373f6ee722a4845effa8f5ff7f
Cq-Depend: chromium:6678533
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/6678298
Original-Reviewed-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Original-Tested-by: Hsin-chen Chuang <chharry@google.com>
Original-Reviewed-by: Archie Pusaka <apusaka@chromium.org>
Original-Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Original-Commit-Queue: Hsin-chen Chuang <chharry@google.com>
GitOrigin-RevId: ac8e6f15c54a20173b660bac1801507104bd8039
Cr-Build-Id: 8710991451384633281
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8710991451384633281
Copybot-Job-Name: android-main-chromiumos-overlay-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/6679901
Commit-Queue: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>