tests: drivers: build_all: input: Fix warning
When building the drivers.input.adc_keys test with clang and
-Winitializer-overrides, it warns:

subsys/input/input_keymap.c:123:29: error: initializer overrides prior
initialization of this subobject [-Werror,-Winitializer-overrides]
  123 | DT_INST_FOREACH_STATUS_OKAY(INPUT_KEYMAP_DEFINE)
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/include/zephyr/devicetree.h:5306:25: note: expanded from macro
'DT_INST_FOREACH_STATUS_OKAY'
 5304 |         COND_CODE_1(DT_HAS_COMPAT_STATUS_OKAY(DT_DRV_COMPAT),   \
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 5305 |                     (UTIL_CAT(DT_FOREACH_OKAY_INST_,            \
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 5306 |                               DT_DRV_COMPAT)(fn)),              \
      |                               ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
 5307 |                     ())
      |                     ~~~

(cherry picked from commit a0fdebcc908ad484c29092c30be5513b9d346651)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: a0fdebcc908ad484c29092c30be5513b9d346651
Cr-Build-Id: 8692407748655686017
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692407748655686017
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I8c2d3108f1317a7283cd9ed75a54420723d5fd97
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7490974
Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
Tested-by: Dawid Niedźwiecki <dawidn@google.com>