v3: alarm: flash_ec to return error when flashing failed
BUG=b/272065694
TEST=cros@chameleon:~/boot_pkg$ sudo flash_ec v3-139-gb938712.bin; echo exit=$?
....
Wrote and verified address 0x08004d00 (13.06%)
Caught signal 2
exit=1 <<< yay!
TEST=cros@chameleon:~/boot_pkg$ sudo pacman -U ec-firmware-chameleonv3-bin-v3_131_gc7f6ea4-2-armv7h.pkg.tar.zst; echo exit=$?
....
Wrote and verified address 0x0800a300 (27.73%)
Failed to read memory at address 0x0800a300

error: command failed to execute correctly <<< This line is new
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
exit=0 <<< Unfortunatelly this is still a "success" since pacman is ignoring post_install errors

Change-Id: I37de8758d25a706a15c979fc411289da5e29ce68
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/chameleon/+/4320734
Reviewed-by: Paul Fagerburg <pfagerburg@chromium.org>
Tested-by: Alexandru Stan <amstan@chromium.org>
Commit-Queue: Alexandru Stan <amstan@chromium.org>