bindesc: fix compile error when CONFIG_BINDESC_READ_FLASH disabled
The get_entry() function uses IS_ENABLED(CONFIG_BINDESC_READ_FLASH) in
an if statement to guard code that accesses struct members (flash_device,
buffer) which are only defined when CONFIG_BINDESC_READ_FLASH is enabled.

While IS_ENABLED() correctly evaluates to 0 when the config is disabled,
the C compiler still performs type-checking on all code paths before
optimization can eliminate the dead branch. This causes a compile error:

  error: 'struct bindesc_handle' has no member named 'flash_device'
  error: 'struct bindesc_handle' has no member named 'buffer'

Fix by using preprocessor #if directive instead of runtime if statement.
This ensures the flash-specific code is excluded during preprocessing
when CONFIG_BINDESC_READ_FLASH is not enabled.

Original-Origin: Original
Original-Fixes: zephyrproject-rtos/zephyr#103444
Original-Signed-off-by: Jay Beavers <jay@tolttechnologies.com>
GitOrigin-RevId: 4d5477d0f320c1319af8874cbe0081f1de40a752
Cr-Build-Id: 8688954069209394049
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8688954069209394049
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I4c3c460d0ccdef50c73825da54c6c2091ffc749c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7565982
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Keith Short <keithshort@chromium.org>
Commit-Queue: Keith Short <keithshort@chromium.org>
Tested-by: Keith Short <keithshort@chromium.org>