strace: upgraded package to upstream
Upgraded dev-debug/strace to version 6.12.

Version 6.4 does not build with glibc 2.41 due
to the following error, so we bump it.

strace-6.4: In file included from sched.c:14:
strace-6.4: ./sched_attr.h:14:8: error: redefinition of 'sched_attr'
strace-6.4:    14 | struct sched_attr {
strace-6.4:       |        ^
strace-6.4: /build/eve/usr/include/linux/sched/types.h:100:8: note: previous definition is here
strace-6.4:   100 | struct sched_attr {
strace-6.4:       |        ^
strace-6.4: 1 error generated.

BUG=b:387993322
TEST=Local builds on amd64, arm; basic smoke test; CQ.

Cq-Depend: chromium:6316798, chromium:6338546, chromium:6336115
Change-Id: I031c91c5bab68711d73e073abfd5949fbb5b3bed
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/portage-stable/+/6316546
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Auto-Submit: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>