pw_presubmit: Fix OwnersError constructor
The previous OwnersError.__init__ stored the message argument in a
custom attribute rather than passing it to Exception.__init__. This
caused str() of the exception to be empty, (or more precisely, repr() to
show just the exception type name), leading to a confusing backtrace:

    20230405 21:07:40 ERR Presubmit check owners_lint_checks failed!
    Traceback (most recent call last):
      ...
      File ".../pw_presubmit/owners_checks.py", line 131, in __init__
	raise OwnersDependencyError(error_msg)
    pw_presubmit.owners_checks.OwnersDependencyError
                                                      ^^^???^^^

The use of Exception.message is obsolete:
https://stackoverflow.com/q/1272138

We can instead omit OwnersError.__init__ and use the base class
Exception.__init__ which accepts a message as the first argument.
This fixes the backtrace:

    20230406 15:11:15 ERR Presubmit check owners_lint_checks failed!
    Traceback (most recent call last):
      ...
      File ".../pw_presubmit/owners_checks.py", line 126, in __init__
	raise OwnersDependencyError(
    pw_presubmit.owners_checks.OwnersDependencyError: Tried to import
      .../OWNERS but it does not exist

This also required replacing `err.message` with `str(err)` -- or
just `err` if it is being formatted with `%s`.

Also fixed a typo: "exists" -> "exist".

Tested: Ran `pw presubmit --step owners_lint_checks` on a repo with a
  missing OWNERS file, and confirmed that the error message which was
  previously missing is now visible.
Change-Id: I94301255b1b0360aa9efb8d9f6f93b5f7d5f3639
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/137550
Pigweed-Auto-Submit: Jonathon Reinhart <jrreinhart@google.com>
Reviewed-by: Tim Laurence <timlaurence@google.com>
Reviewed-by: Rob Mohr <mohrr@google.com>
Commit-Queue: Auto-Submit <auto-submit@pigweed.google.com.iam.gserviceaccount.com>