fix: lvgl: modules: keypad input log module
Compilation error "undefined reference to log_const_lvgl"
happened in lvgl_keypad_input.c when trying to get logs with
lvgl keypad module. Fixed by adding log level parameter
in log module macro.

(cherry picked from commit 97fce09392053862b3d823f262e6bb15596ca036)

Original-Original-Signed-off-by: Eve Redero <eve.redero@gmail.com>
Original-GitOrigin-RevId: 97fce09392053862b3d823f262e6bb15596ca036
Original-Change-Id: I271fbe0d664f0adc3c9d7240d575c0c6b2b1da0b
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5288871
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 8d67397c9e535eb7ec980fee83569a4c5f866567
Cr-Build-Id: 8693076695425399937
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693076695425399937
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I758f0560f36f399bd40c81609431f3dcc08fa721
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7431850
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>