ctype: align size of category bit fields to small targets needs
E.g. arm ABI requires -fshort-enums for bare-metal toolchains.
Given there are only 29 category enums, the compiler chooses an
8 bit enum type, so a size of 11 bits for the bitfield leads to
a compile time error:

  error: width of 'cat' exceeds its type
    enum category cat: 11;
                  ^~~

Fix this by aligning the size of the category members to byte
borders.

Original-Signed-off-by: Corinna Vinschen <corinna@vinschen.de>
GitOrigin-RevId: 134f93f313db95c394b925716717031a05b2a6d3
Cr-Build-Id: 8694328708600685217
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694328708600685217
Copybot-Job-Name: zephyr-project-picolibc-copybot-downstream
Change-Id: I6538248ee350cc2a7eccbc4f9342e1a7dd568fae
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7340942
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>