chromeos-base/bootsplash: Add missing DEPEND
```
FAILED: obj/bootsplash/bootsplash.main.o
/tmp/portage/chromeos-base/bootsplash-9999/work/bootsplash-9999/platform2/bootsplash/session_manager_client_interface.h:10:10: fatal error: 'session_manager-client/session_manager/dbus-proxies.h' file not found
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/bootsplash:9999

Change-Id: I1d59c7bdfbf05559f1b832b0e0ba74ad58bad44e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4738849
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>