hostap: Enterprise mode needs sha1-internal.c
Without this there is an error

modules/lib/hostap/src/crypto/fips_prf_internal.c:47: \
    undefined reference to `SHA1Transform'

(cherry picked from commit e9ec7a23a32c4a6ba4ba487a95f9cd588aaea893)

Original-Original-Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
Original-GitOrigin-RevId: e9ec7a23a32c4a6ba4ba487a95f9cd588aaea893
Original-Cr-Build-Id: 8732659221460854369
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8732659221460854369
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ibeca74ef1e219acddf483eb21962328f23b372b0
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5976031
Original-Commit-Queue: Ting Shen <phoenixshen@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Ting Shen <phoenixshen@chromium.org>
GitOrigin-RevId: dab21ff2959bede7651227a77a7dc9b9ebcebee2
Cr-Build-Id: 8692928221032965233
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692928221032965233
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I80eb755c259bb588aedd6d0661849601be33ee0a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7446455
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>