CHROMIUM: termina: Enable CONFIG_SQUASHFS_XZ=y and CONFIG_SQUASHFS_ZSTD=y
Snaps require squashfs xz compression support:

$ sudo snap install snapd
error: system does not fully support snapd: cannot mount squashfs image using "squashfs":
       ----- mount: /tmp/syscheck-mountpoint-2158099106: fsconfig() failed: Filesystem uses "xz"
       compression. This is not supported.

       dmesg(1) may have more information after failed mount system call.

       -----

Enable CONFIG_SQUASHFS_XZ=y as required by snap and enable
CONFIG_SQUASHFS_ZSTD=y while we're at it.

This does not cause additional config dependencies to be enabled, meaning
that the kernel already had the xz and zstd compressors built in anyway.
This has been checked by running make olddefconfig and comparing .config
with /proc/config.gz.

BUG=b:514397875
TEST=cat chromeos/config/termina/base.config chromeos/config/termina/x86_64/common.config >.config \
     && make olddefconfig CC=clang LD=ld.lld \
     && make -j12 vmlinux CC=clang LD=ld.lld
     vmc start --kernel /home/chronos/user/MyFiles/Downloads/vmlinux \
         --kernel-param "panic=-1 console=hvc0 earlycon=uart8250,io,0x3f8 root=/dev/vdb rw net.ifnames=0 systemd.log_color=0 printk.devkmsg=on" \
         --enable-gpu --no-shell termina

Change-Id: I5c792decf9e2e67c588c3ec6459b25a9eb36629d
Signed-off-by: Lukas Straub <lukasstraub2@web.de>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/7829788
Reviewed-by: Zihan Chen <zihanchen@google.com>
Reviewed-by: maciek swiech <drmasquatch@google.com>