net: Initialize unspec_addr to avoid -Werror=maybe-uninitialized
The variable 'unspec_addr' in net_dhcpv6_init() is implicitly
initialized on some platforms and optimization levels, but not
guaranteed to be initialized on all code paths when built with
compiler instrumentation.

This leads to a build failure with the strict
'-Werror=maybe-uninitialized' warning when code coverage flags are
enabled (e.g., via twister --coverage).

```
zephyr/subsys/net/lib/dhcpv6/dhcpv6.c:2325:26: error: ‘unspec_addr’
may be used uninitialized [-Werror=maybe-uninitialized]
         net_ipaddr_copy(&net_sin6(&unspec_addr)->sin6_addr,
```

(cherry picked from commit 79a7106f9d15865ecbab8c8f698aace7b09590dd)

Original-Signed-off-by: Nikhil Namjoshi <nikhilnamjoshi@google.com>
GitOrigin-RevId: 79a7106f9d15865ecbab8c8f698aace7b09590dd
Cr-Build-Id: 8696371365796932305
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8696371365796932305
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I6cd8f3dca3976023615b0601a033858b9ba35ec7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7230382
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>