drivers: smbus: stm32: add cast to avoid warning
Previously, the function `smbus_stm32_pcall()` implicitly cast
`uint16_t *` to `uint8_t *`. Add an explicit cast to avoid warning.

```shell
..drivers/smbus/smbus_stm32.c:358:32: error: initialization of \
  'uint8_t *' {aka 'unsigned char *'} from incompatible pointer type \
  'uint16_t *' {aka 'short unsigned int *'} \
  [-Werror=incompatible-pointer-types]
  358 |                         .buf = &send_word,
      |                                ^
..drivers/smbus/smbus_stm32.c:358:32: note: (near initialization \
  for 'messages[1].buf')
..drivers/smbus/smbus_stm32.c:363:32: error: initialization of \
  'uint8_t *' {aka 'unsigned char *'} from incompatible pointer type \
  'uint16_t *' {aka 'short unsigned int *'} \
  [-Werror=incompatible-pointer-types]
  363 |                         .buf = recv_word,
      |                                ^~~~~~~~~
```

(cherry picked from commit e6fcd9e09a7555760f7a5692fcce9b30ee06b1d2)

Original-Original-Signed-off-by: Chris Friedt <cfriedt@tenstorrent.com>
Original-GitOrigin-RevId: e6fcd9e09a7555760f7a5692fcce9b30ee06b1d2
Original-Cr-Build-Id: 8698455093734075649
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8698455093734075649
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I7bbfc9535d685a8e0f6c55fab11f402e1933e86f
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7142153
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: ba08f6e9e4c3400f3c282ce44fff54468454fa5d
Cr-Build-Id: 8692647051261749617
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692647051261749617
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ia223de6db667d301fb644f064ea3df6b0d5dbf13
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7479678
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>