tests: net: socket: Avoid macro error with zsock_sendto
The preprocessor gives this error when calling zsock_sendto
in user mode when there is a mismatch with amount of parameters
to the sendto wrapper call.

  tests/net/socket/udp/src/main.c: In function ‘comm_sendto_recvfrom’:
  tests/net/socket/udp/src/main.c:125:46: error: macro "zsock_sendto" \
                                 requires 6 arguments, but only 5 given
  125 |                             0, &addr, addrlen);
      |                                              ^
  In file included from include/zephyr/net/socket.h:1381,
                 from tests/net/socket/udp/src/main.c:15:
  include/generated/zephyr/syscalls/socket.h:266: note: \
                      macro "zsock_sendto" defined here
  266 | #define zsock_sendto(sock, buf, len, flags, dest_addr, addrlen)

(cherry picked from commit 2b4e137656733f8914a768715c2c3daf39e3414d)

Original-Original-Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
Original-GitOrigin-RevId: 2b4e137656733f8914a768715c2c3daf39e3414d
Original-Change-Id: I5a750d62db2a97395e6a0305b7889fd565e47fae
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5618282
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Original-Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Jeremy Bettis <jbettis@chromium.org>
GitOrigin-RevId: 2cee7b822b68043f164273bf112c809d2f119717
Cr-Build-Id: 8693008678827941153
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693008678827941153
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I1cf25f4f6c3cd02feab12c2bdd0e5f27884c31db
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7438440
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>