Revert "servo_adcs_enabled: accomodate c2d2 + ccd"
This reverts commit 934c9f2a6c6ecce331590aae3a40eace38f540c7 (CL:3046559).

Reason for revert: I think the reverted change is no longer needed with modular servod (commit 3e8df9c0302eaf6b1805b688fa24988fb206dad0 CL:4210334 b:234066908).

Original change's description:
> servo_adcs_enabled: accomodate c2d2 + ccd
>
> In this scenario, we have a redefinition of the control. This is an
> issue, since ccd would overwrite the c2d2 definition (sequencing) but we
> need the c2d2 definition. The solution is to treat the c2d2 definition
> as a special case, so ccd cannot overwrite it.
>
> BUG=None
> TEST=sudo servod -b guybrush -c guybrush_p0.xml &
>      dut-power --vbat-rate 0 -t 3
>
> // symptom without this CL
> TEST=sudo servod -b guybrush -c guybrush_p0.xml &
>
> [...]
> servo.system_config.SystemConfigError: Duplicate control
> servo_adcs_enabled without 'clobber_ok' key
> [...]
>
> Change-Id: I106d1920cd3807a0e7fe3041414f9b24a126d2c1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/hdctools/+/3046559
> Tested-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
> Reviewed-by: Furquan Shaikh <furquan@chromium.org>
> Reviewed-by: Brian Nemec <bnemec@chromium.org>
> Commit-Queue: Ruben Rodriguez Buchillon <coconutruben@chromium.org>

BUG=b:286470045

Change-Id: Ica3f346a76bb60d4e7caaebe57af8000e5140053
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/hdctools/+/4602756
Tested-by: Matthew Blecker <matthewb@chromium.org>
Commit-Queue: Matthew Blecker <matthewb@chromium.org>
Reviewed-by: Brian Nemec <bnemec@google.com>
Reviewed-by: 488603086791@cloudbuild.gserviceaccount.com <488603086791@cloudbuild.gserviceaccount.com>