riscv: linker.ld: Fix undefined reference linker error
The commit a28830b aligned the data and rename some symbols.  However
there are two symbols at riscv linker script that were missing, which
causes below linker error:

kernel/xip.c:28: undefined reference to `__itcm_load_start'
kernel/xip.c:43: undefined reference to `__dtcm_data_load_start'

Rename below symbols to fix the issues.

__itcm_rom_start -> __itcm_load_start
__dtcm_data_rom_start -> __dtcm_data_load_start

(cherry picked from commit 1212ea0c399ab6c029d91195333dd7815a53d0c1)

Original-Signed-off-by: Gerson Fernando Budke <nandojve@gmail.com>
Original-GitOrigin-RevId: 1212ea0c399ab6c029d91195333dd7815a53d0c1
Original-Change-Id: I34923222fcb560f34bea11fc785567fc510c2ad3
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3350681
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Aaron Massey <aaronmassey@google.com>
Original-Commit-Queue: Aaron Massey <aaronmassey@google.com>
GitOrigin-RevId: 6de8d1c03c3af7c2f49a5be280caefe43917aca5
Cr-Build-Id: 8693657076945471489
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693657076945471489
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I26fac9394052f396e0840f201c27a4923685f0f4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7386774
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>