drivers: sensor: fix possible unaligned access bmi08x
bmi08x_accel_frame is defined as packed struct,
while the nested structures are not. It causes an issue of
potential unaligned access to accel member.
The issue was detected by clang compiling with
-Wunaligned-access flag:

```
bmi08x.h:605:2: error: field  within 'struct bmi08x_accel_frame'
is less aligned than 'union bmi08x.h:605:2)' and is usually due
to 'struct bmi08x_accel_frame' being packed,
which can lead to unaligned accesses [-Werror,-Wunaligned-access]
```

This commit resolves the following Zephyr issue:
by adding `packed` attribute to accel member.

(cherry picked from commit bd6a228911059f39cfb83fd9d68cffc93a187119)

Original-https: //github.com/zephyrproject-rtos/zephyr/issues/101142
Original-Signed-off-by: Ivan Iushkov <ivan.iushkov@nordicsemi.no>
GitOrigin-RevId: bd6a228911059f39cfb83fd9d68cffc93a187119
Cr-Build-Id: 8693834649729444993
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693834649729444993
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I4748e0e676d2197dff1d7b03d8975b61a7f23a3b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7376011
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>