drivers: i2c: stm32: don't manage cache aside DMA support
Fix STM32 I2C driver to not call cache management related functions
when DMA is not used. This change fixes an issue introduced by
commit 42c3a7814810 ("i2c: stm32: Add cache memory support"). The issue
makes boards embedding this driver with both CONFIG_I2C_STM32_V2_DMA
and CONFIG_ARCH_MPU disabled to fail to build with an error trace message
like the below:
   .../i2c_ll_stm32_v2.c:701: undefined reference to `mem_attr_check_buf'

(cherry picked from commit d0d8fa444fb308b3c8ba9daff1a58c26093e9f59)

Original-Original-Fixes: 42c3a7814810a60cd23d719264695351ba5b8023
Original-Original-Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
Original-GitOrigin-RevId: d0d8fa444fb308b3c8ba9daff1a58c26093e9f59
Original-Cr-Build-Id: 8719201802424120401
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8719201802424120401
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I22c9c71214cf947c2787c5f571d41ff2c6176494
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6406357
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: d2d0a984ca7e8a7df67040e142e46d992265b477
Cr-Build-Id: 8692825863232243105
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692825863232243105
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I0de64727728bffd01426353f2b997de7b9fe78b4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7459824
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>