mesa: fix some errors about unused parameters
When building without "-Wno-unused-parameter" and without
HAVE_PTHREAD_SETAFFINITY the build can fail with errors like the
following:

-----------------------------------------------------------------------
In file included from external/virglrenderer/server/render_context.c:10:
external/virglrenderer/src/mesa/util/u_thread.h:166:33: error: unused parameter 'thread' [-Werror,-Wunused-parameter]
util_set_thread_affinity(thrd_t thread,
                                ^
external/virglrenderer/src/mesa/util/u_thread.h:167:42: error: unused parameter 'mask' [-Werror,-Wunused-parameter]
                         const uint32_t *mask,
                                         ^
external/virglrenderer/src/mesa/util/u_thread.h:168:36: error: unused parameter 'old_mask' [-Werror,-Wunused-parameter]
                         uint32_t *old_mask,
                                   ^
external/virglrenderer/src/mesa/util/u_thread.h:169:35: error: unused parameter 'num_mask_bits' [-Werror,-Wunused-parameter]
                         unsigned num_mask_bits)
                                  ^
external/virglrenderer/src/mesa/util/u_thread.h:218:50: error: unused parameter 'mask' [-Werror,-Wunused-parameter]
util_set_current_thread_affinity(const uint32_t *mask,
                                                 ^
external/virglrenderer/src/mesa/util/u_thread.h:219:44: error: unused parameter 'old_mask' [-Werror,-Wunused-parameter]
                                 uint32_t *old_mask,
                                           ^
external/virglrenderer/src/mesa/util/u_thread.h:220:43: error: unused parameter 'num_mask_bits' [-Werror,-Wunused-parameter]
                                 unsigned num_mask_bits)
-----------------------------------------------------------------------

Cast the unused parameters to void to fix the errors.

Part-of: <https://gitlab.freedesktop.org/virgl/virglrenderer/-/merge_requests/1430>