common-mk: platform2_test: Run gtest-parallel with sys.executable
Target board sysroots (/build/<board>) do not install /usr/bin/env.
When gtest-parallel is invoked directly inside chroot, the kernel fails
to resolve #!/usr/bin/env python3, causing:
  error: execing ... failed: [Errno 2] No such file or directory

Invoking gtest-parallel explicitly via sys.executable (/usr/bin/python3)
ensures tests run reliably within the target board sysroots.

BUG=None
TEST=cros_run_unit_tests --board=brya --packages "chromeos-base/libhwsec"
TAG=agy
CONV=317b105b-84b7-43f5-ba9f-d499ab9577c8

Change-Id: I33b98ba250d55e131bed6c4b14c14876f886da05
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/8305775
Reviewed-by: Allen Webb <allenwebb@google.com>
Reviewed-by: Andrey Pronin <apronin@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>