tests: lib: mpsc_pbuf: Fix address-of-packed-mem warning
The warning below appears once -Waddress-of-packed-mem is enabled:

/__w/zephyr/zephyr/tests/lib/mpsc_pbuf/src/main.c: In function
'item_put_data_overwrite':
/__w/zephyr/zephyr/tests/lib/mpsc_pbuf/src/main.c:497:3: error:
converting a packed 'struct test_data_ext' pointer (alignment 1) to a
'uint32_t' {aka 'const unsigned int'} pointer (alignment 4) may result
in an unaligned pointer value [-Werror=address-of-packed-member]
  497 |   mpsc_pbuf_put_data(&buffer, (uint32_t *)&item, len);

To avoid the warning, as well as several others related to the same
problem, use an intermediate void * variable.

More info in #16587.

(cherry picked from commit 0b96dd419d83f71072616f0aa00a506dfc021997)

Original-Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>
Original-GitOrigin-RevId: 0b96dd419d83f71072616f0aa00a506dfc021997
Original-Change-Id: I69557d636f06d283340f283a742c65d854dfe36d
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3332181
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: 91f2ae994bd65d126066cf6ab6a5301c5193290f
Cr-Build-Id: 8693663859494856737
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693663859494856737
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Idd3999917090895f802e3fe2fe223dfde1cb9c20
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7386364
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>