pm: device.h: fix pm_device designated initializers order for C++
Fixes the following error appearing in the test coverage added by the
next commit:

In file included from zephyr/tests/lib/cpp/cxx/src/main.cpp:18:
```
zephyr/include/zephyr/pm/device.h:275:9: error: designator order for
  field 'pm_device_base::state' does not match declaration order
                        in 'pm_device_base'
  275 |         }
      |         ^
zephyr/include/zephyr/pm/device.h:315:17: note: in expansion of
                                                macro 'Z_PM_DEVICE_INIT'
  315 |              Z_PM_DEVICE_INIT(Z_PM_DEVICE_NAME(dev_id), node_id,
```

Note this failure is observed with any g++ -std=c++NN standard value -
even before C++20.

(cherry picked from commit c1852b83cd32b78fa7b7ebcf3e92a66a617ee669)

Original-Original-Signed-off-by: Marc Herbert <marc.herbert@intel.com>
Original-GitOrigin-RevId: c1852b83cd32b78fa7b7ebcf3e92a66a617ee669
Original-Change-Id: I680b48d571083b93621e68f1d20fe8b0c7f34bf9
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5687990
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Yuval Peress <peress@google.com>
Original-Commit-Queue: Yuval Peress <peress@google.com>
Original-Tested-by: Yuval Peress <peress@google.com>
GitOrigin-RevId: 2d81054b52172cae2d141fb2062cd31a704b7082
Cr-Build-Id: 8692991340529664881
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692991340529664881
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I0b0f92232fa74174af3adbf6a697264bb6aa9f35
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7440257
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>