target-chromium-os-sdk: add app-text/docbook-xsl-ns-stylesheets Android Bringup: See http://go/android-fw-sync
This is required when cross-compiling the new version
of pam >= 1.7.0 because it expects to pick up these
stylesheets from the host sysroot.

There is no option to disable the pam documentation
(I sent an PR for that, however it's a separate issue)
and the build will attempt to fetch the xsl from the
internet if they are missing, causing failures like:

pam-1.7.0_p20241230-r3: FAILED: doc/man/misc_conv.3
pam-1.7.0_p20241230-r3: /usr/bin/xsltproc -o doc/man/misc_conv.3 --nonet --xinclude --path /build/asurada/tmp/portage/sys-libs/pam-1.7.0_p20241230-r3/work/linux-pam-e634a3a9be9484ada6e93970dfaf0f055ca17332/doc/man --stringparam profile.condition 'without_vendordir;no_openssl_hmac'
doc/custom-man.xsl ../linux-pam-e634a3a9be9484ada6e93970dfaf0f055ca17332/doc/man/misc_conv.3.xml
pam-1.7.0_p20241230-r3: error : Resource temporarily unavailable: getaddrinfo failed
pam-1.7.0_p20241230-r3: warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl-ns/current/manpages/profile-docbook.xsl"
pam-1.7.0_p20241230-r3: compilation error: file doc/custom-man.xsl line 3 element import
pam-1.7.0_p20241230-r3: xsl:import : unable to load http://docbook.sourceforge.net/release/xsl-ns/current/manpages/profile-docbook.xsl
pam-1.7.0_p20241230-r3: ninja: build stopped: subcommand failed.

When testing with emerge-$BOARD pam, it will silently
fetch the xls from the internet and the build passes.

BUG=b:417103947
TEST=Local builds and boot on amd64, arm64; CQ.

(cherry picked from commit 8a8345f60b5f56d77984cf5f9db220854ddf873c)

Change-Id: I986adea6d2db2912a94a86b236204f56ed31a42b
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/6596946
Original-Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Original-Reviewed-by: George Burgess <gbiv@chromium.org>
Original-Reviewed-by: Mike Frysinger <vapier@chromium.org>
Original-Commit-Queue: George Burgess <gbiv@chromium.org>
GitOrigin-RevId: 8a8345f60b5f56d77984cf5f9db220854ddf873c
Cr-Build-Id: 8713505515966074769
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8713505515966074769
Copybot-Job-Name: android-main-chromiumos-overlay-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/6605620
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>