drivers: can: mcp2515: fix build break
Fix build break introduced in 03ab730347:

/zephyr/drivers/can/can_mcp2515.c:871:55: error: 'const struct
mcp2515_config' has no member named 'int_pin'; did you mean 'int_gpio'?
  871 |   LOG_ERR("Unable to configure GPIO pin %u", dev_cfg->int_pin);

/zephyr/drivers/can/can_mcp2515.c:942:14: error: 'GPIO_DT_SPEC_INST_GET'
undeclared here (not in a function)
  942 |  .int_gpio = GPIO_DT_SPEC_INST_GET(0),
      |              ^~~~~~~~~~~~~~~~~~~~~

(cherry picked from commit eb7b3b66a23518c9e126c839c31a1aea8a62165b)

Original-Signed-off-by: Fabio Baltieri <fabio.baltieri@gmail.com>
Original-GitOrigin-RevId: eb7b3b66a23518c9e126c839c31a1aea8a62165b
Original-Change-Id: Id4397afd0ea1b8c7b4a2d95c1443b6be99f97929
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3490968
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Aaron Massey <aaronmassey@google.com>
Original-Commit-Queue: Aaron Massey <aaronmassey@google.com>
Original-Tested-by: Aaron Massey <aaronmassey@google.com>
GitOrigin-RevId: da6b5036339b977d1a084f78b7fc55cde18adf90
Cr-Build-Id: 8693623245984189217
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693623245984189217
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I6089d622baa8ce2e7e5b099c76c0bba17e9a14e6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7389079
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>