tests/amd/amd_fuzzing: Fix compilation error on fedora
Fix compilation error:

../tests/amdgpu/amd_fuzzing.c: In function ‘amd_kgd_multi_ioctl_field_fuzzing’:
../tests/amdgpu/amd_fuzzing.c:1103:13: error: ‘have_amdgpu_dev’ undeclared (first use in this function); did you mean ‘amdgpu_dev’?
 1103 |         if (have_amdgpu_dev) {
      |             ^~~~~~~~~~~~~~~
      |             amdgpu_dev

Cc: Vitaly Prosyak <vitaly.prosyak@amd.com>
Cc: Kamil Konieczny <kamil.konieczny@linux.intel.com>
Fixes: d512e54bbace ("tests/amdgpu/amd_fuzzing: Remove unused variable")
Signed-off-by: Karthik B S <karthik.b.s@intel.com>
Reviewed-by: Kamil Konieczny <kamil.konieczny@linux.intel.com>