Autoupdate of 2 submodules
*chromite updated to 8dae59e2b708a78d882c9cf00abf4cd9b9ff7bc2
Revert "chromite: require Python 3.9 now"

This reverts commit f1861712888c27ef5b14e6f4c3511ff131d55bcc.

Reason for revert: Test service container is importing chromite
externally with old Python versions.

Failure Link: https://ci.chromium.org/b/8679344084242353793

  File "/b/s/w/ir/x/w/rc/chromiumos_workspace/src/platform/dev/src/chromiumos/test/python/src/docker_libs/cli/../../../../../../../setup_chromite.py", line 21, in <module>
    import chromite  # pylint: disable=unused-import
  File "/b/s/w/ir/x/w/rc/chromiumos_workspace/chromite/__init__.py", line 17, in <module>
    assert sys.version_info >= MIN_PYTHON_VERSION, (
AssertionError: Chromite requires Python 3.9+

Original change's description:
> chromite: require Python 3.9 now
>
> We've been warning people using Python <3.11 for over a year that
> they need to upgrade, so bumping the hard requirement to 3.9 should
> not be a problem.
>
> BUG=b:452716731
> TEST=CQ passes
>
> Change-Id: I3c03e59a5e1522d804ed3b966af36e2a3254573b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/7919488
> Tested-by: Mike Frysinger <vapier@chromium.org>
> Commit-Queue: Leandro Lovisolo <lovisolo@google.com>
> Auto-Submit: Mike Frysinger <vapier@chromium.org>
> Reviewed-by: Leandro Lovisolo <lovisolo@google.com>

BUG=b:452716731

Change-Id: I8dc86be26b4474c82dcea1c144385f8e1cfd9e17
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/7921471
Reviewed-by: Leandro Lovisolo <lovisolo@google.com>
Tested-by: Mike Frysinger <vapier@chromium.org>

*infra/chromite-HEAD updated to 8dae59e2b708a78d882c9cf00abf4cd9b9ff7bc2
Revert "chromite: require Python 3.9 now"

This reverts commit f1861712888c27ef5b14e6f4c3511ff131d55bcc.

Reason for revert: Test service container is importing chromite
externally with old Python versions.

Failure Link: https://ci.chromium.org/b/8679344084242353793

  File "/b/s/w/ir/x/w/rc/chromiumos_workspace/src/platform/dev/src/chromiumos/test/python/src/docker_libs/cli/../../../../../../../setup_chromite.py", line 21, in <module>
    import chromite  # pylint: disable=unused-import
  File "/b/s/w/ir/x/w/rc/chromiumos_workspace/chromite/__init__.py", line 17, in <module>
    assert sys.version_info >= MIN_PYTHON_VERSION, (
AssertionError: Chromite requires Python 3.9+

Original change's description:
> chromite: require Python 3.9 now
>
> We've been warning people using Python <3.11 for over a year that
> they need to upgrade, so bumping the hard requirement to 3.9 should
> not be a problem.
>
> BUG=b:452716731
> TEST=CQ passes
>
> Change-Id: I3c03e59a5e1522d804ed3b966af36e2a3254573b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/7919488
> Tested-by: Mike Frysinger <vapier@chromium.org>
> Commit-Queue: Leandro Lovisolo <lovisolo@google.com>
> Auto-Submit: Mike Frysinger <vapier@chromium.org>
> Reviewed-by: Leandro Lovisolo <lovisolo@google.com>

BUG=b:452716731

Change-Id: I8dc86be26b4474c82dcea1c144385f8e1cfd9e17
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/7921471
Reviewed-by: Leandro Lovisolo <lovisolo@google.com>
Tested-by: Mike Frysinger <vapier@chromium.org>