tpm2-simulator: remove unused variable; init local
This result is never read, which leads to errors with Clang:
```
tpm2-simulator/tpm_executor_tpm1_impl.cc:86:14: error: variable 'res'
set but not used [-Werror,-Wunused-but-set-variable]
  TPM_RESULT res;
```

There's no obvious way to communicate an error from this function, and
there's inheritance here, so it's unclear if there's a good way to
bubble this up.

Since errors from TPMLIB_Process aren't handled, we also probably
shouldn't be making assumptions about `rlength` being properly set.

BUG=b:296450693
TEST=emerge-reven

Change-Id: I0a4d6f92ec32c8ed7fb377ed326d8f02de5fedd0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4928720
Reviewed-by: Yi Chou <yich@google.com>
Tested-by: George Burgess <gbiv@chromium.org>
Commit-Queue: George Burgess <gbiv@chromium.org>