Add missing deps for chromeos-base/crosier-chrome
```
01:36:28.155 >>> Install chromeos-base/crosier-chrome-0.0.1-r1 into /build/amd64-generic/tmp/portage/chromeos-base/crosier-chrome-0.0.1-r1/image
 * Deploying Crosier tests to board amd64-generic
chromeos_integration_tests
Traceback (most recent call last):
  File "/build/amd64-generic/tmp/portage/chromeos-base/crosier-chrome-0.0.1-r1/work/crosier-chrome-0.0.1/platform/dev/test/gtest/generate_gtest_metadata.py", line 17, in <module>
    from chromiumos.test.api import test_case_metadata_pb2 as tc_metadata_pb
ModuleNotFoundError: No module named 'chromiumos'
```

```
Traceback (most recent call last):
  File "/build/amd64-generic/tmp/portage/chromeos-base/crosier-chrome-0.0.1-r2/work/crosier-chrome-0.0.1/platform/dev/test/gtest/generate_gtest_metadata.py", line 17, in <module>
    from chromiumos.test.api import test_case_metadata_pb2 as tc_metadata_pb
  File "/usr/lib/python3.8/site-packages/chromiumos/test/api/test_case_metadata_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
```

BUG=b:317944521
TEST=BOARD=amd64-generic /mnt/host/source/chromite/bin/bazel build @portage//target/chromeos-base/crosier-chrome

Change-Id: I3dbdd25f354bddbef3fe4bd5447f810868e05109
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/5151502
Tested-by: Maksim Ivanov <emaxx@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Raul Rangel <rrangel@chromium.org>