chromeos-base/protofiles: Add missing BDEPEND
```
Traceback (most recent call last):
  File "/var/tmp/portage/chromeos-base/protofiles-0.0.102/work/protofiles-0.0.102/cloud/policy/tools/generate_policy_source.py", line 33, in <module>
    import six
ModuleNotFoundError: No module named 'six'
 * ERROR: chromeos-base/protofiles-0.0.102::chromiumos failed (compile phase):
 ```

 ```
 Traceback (most recent call last):
  File "/var/tmp/portage/chromeos-base/protofiles-0.0.102-r1/work/protofiles-0.0.102/cloud/policy/resources/policy_templates.py", line 19, in <module>
    import pyyaml
ModuleNotFoundError: No module named 'pyyaml'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/host/chromiumos/chromeos-base/protofiles:0.0.102-r1

Change-Id: I95563ebc40a7ebea26aa9cf5b8eb15423dab589c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4655485
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>