UPSTREAM: ec/lenovo/pmh7: Include stdbool.h Android Bringup: See http://go/android-fw-sync
When moving headers compilation can fail as pmh7.h is missing
the include for type bool. Add the missing include to make sure
future code refactoring works.

Fixed the error:
src/ec/lenovo/pmh7/pmh7.h:27:1: error: unknown type name 'bool'

(cherry picked from commit b44c0ab25b256edea6b376abe79ae22878adc416)

(cherry picked from commit 336021ad108771c28b905b369cd01235e0c13410)

Original-Original-Change-Id: Ib0a2489a0c461bf021168e98737ecb6062caa696
Original-Original-Signed-off-by: Patrick Rudolph <patrick.rudolph@9elements.com>
Original-Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/88542
Original-Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Original-Reviewed-by: Paul Menzel <paulepanter@mailbox.org>
Original-Original-Reviewed-by: Angel Pons <th3fanbus@gmail.com>
Original-GitOrigin-RevId: b44c0ab25b256edea6b376abe79ae22878adc416
Original-Cr-Build-Id: 8708345266036186753
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8708345266036186753
Original-Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: Ie9b726e6bc6274c785ae979556ed01e74bd863bb
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6788468
Original-Reviewed-by: Kshitij Shah <tij@google.com>
Original-Commit-Queue: Kshitij Shah <tij@google.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 336021ad108771c28b905b369cd01235e0c13410
Cr-Build-Id: 8708092348870309825
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8708092348870309825
Copybot-Job-Name: android-main-coreboot-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6793108
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>