drivers: dai: ssp: remove unused variables
Fix compiler warnings
/zep_workspace/zephyr/drivers/dai/intel/ssp/ssp.c:2079:18: error: \
unused variable 'ssrsa' [-Werror=unused-variable]
 2079 |         uint32_t ssrsa = 0;
      |                  ^~~~~
/zep_workspace/zephyr/drivers/dai/intel/ssp/ssp.c:2078:18: error: \
unused variable 'sstsa' [-Werror=unused-variable]
 2078 |         uint32_t sstsa = 0;
      |                  ^~~~~

(cherry picked from commit 6f1fc6e96c60cbbfacabad9685f4d034f4bed5c1)

Original-Signed-off-by: Guennadi Liakhovetski <guennadi.liakhovetski@linux.intel.com>
GitOrigin-RevId: 6f1fc6e96c60cbbfacabad9685f4d034f4bed5c1
Cr-Build-Id: 8728129377422644657
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8728129377422644657
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I222f82d95dc53e525e57d4710d2ce262ab796f8a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6110923
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>