bluetooth: controller: Fix build with BT_HCI_VS_EXT disabled.
Fixing error: undefined reference to 'vs_set_min_used_chans'
when building with 'BT_HCI_VS_EXT' option disabled.

(cherry picked from commit 5ac063d79374183df756334c3302733c70237666)

Original-Signed-off-by: Michał Grochala <michal.grochala@nordicsemi.no>
GitOrigin-RevId: 5ac063d79374183df756334c3302733c70237666
Change-Id: I548f81c91e3334733d04ceea9685dce36cc10b23
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4626695
Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>