net-wireless/floss_tools: Add missing BDEPEND
```
FAILED: gen/bt/system/gd/packet/parser/language_y.h gen/bt/system/gd/packet/parser/language_y.cc
/usr/bin/env ../../../floss_tools-9999/platform2/common-mk/file_generator_wrapper.py bison --language=c++ --defines=/var/tmp/portage/net-wireless/floss_tools-9999/work/build/out/Default/gen/bt/system/gd/packet/parser/language_y.h -o /var/tmp/portage/net-wireless/floss_tools-9999/work/build/out/Default/gen/bt/system/gd/packet/parser/language_y.cc ../../../floss_tools-9999/platform2/bt/system/gd/packet/parser/language_y.yy
Traceback (most recent call last):
  File "../../../floss_tools-9999/platform2/common-mk/file_generator_wrapper.py", line 19, in <module>
    subprocess.check_call(sys.argv[1:])
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bison'
[2/50] ACTION //bt/system/gd/packet/parser:pktlexer_gen(//common-mk/toolchain:toolchain)
```

```
  File "../../../floss_tools-9999/platform2/common-mk/file_generator_wrapper.py", line 19, in <module>
    subprocess.check_call(sys.argv[1:])
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'flex'
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/host/chromiumos/net-wireless/floss_tools:9999

Change-Id: Ica10def243675eb6539fdcbbba8a7a29b3b40e86
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4655486
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>