drivers: serial: pl011: Fix ignored const qualifiers
When trying to build Zephyr with -Wignored-qualifiers this leads to a
compiler warning like:

zephyr/drivers/serial/uart_pl011_registers.h:40:1: error: type
qualifiers ignored on function return type [-Werror=ignored-qualifiers]

Since the return value is copied by the caller, making it const has no
effect and the compiler warns that this is being ignored. This enables
applications to build with additional compiler warnings turned on.

(cherry picked from commit 47a0813561afb06ba6b681dfcd4d2224847e3962)

Original-Original-Signed-off-by: Benjamin Gwin <bgwin@google.com>
Original-GitOrigin-RevId: 47a0813561afb06ba6b681dfcd4d2224847e3962
Original-Cr-Build-Id: 8739725789595072145
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8739725789595072145
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Id52014024c9503a400179cf4fb0054cc9687208d
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5786055
Original-Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Original-Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
GitOrigin-RevId: 5094dc46f783cec15ca4c281e975be5e0fef8ecd
Cr-Build-Id: 8692976023217314529
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692976023217314529
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I376ddab9e44832e40c80054c5eaf5c3fd154113a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7441676
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>