Bluetooth: Mesh: Fix compile warning when CID check is disabled
Since the entire cid checking function is conditionally included based
on KConfig, the usage site also needs to use #if instead of IS_ENABLED,
otherwise you get the following warning during compilation when the
option is disabled:

`error: implicit declaration of function
‘bt_mesh_vnd_mod_msg_cid_check’`

(cherry picked from commit 23d8ec360b7d51efb5c2ee37de1ad6709bbdbe45)

Original-Signed-off-by: Ludvig Jordet <ludvig.jordet@nordicsemi.no>
GitOrigin-RevId: 23d8ec360b7d51efb5c2ee37de1ad6709bbdbe45
Cr-Build-Id: 8693381667133806833
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693381667133806833
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ia184f8935c0be54b3e0244aa56a9578d2aedde44
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7406142
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>