net-wireless/wireless-regdb: Add missing BDEPEND
```
Generating certificate for chromium...
./gen-pubcert.sh ~/.wireless-regdb-chromium.key.priv.pem chromium.x509.pem chromium
Generating regulatory.bin digitally signed by chromium...
./db2bin.py regulatory.bin db.txt ~/.wireless-regdb-chromium.key.priv.pem
Traceback (most recent call last):
  File "./db2bin.py", line 128, in <module>
    from M2Crypto import RSA
ModuleNotFoundError: No module named 'M2Crypto'
make: *** [Makefile:60: regulatory.bin] Error 1
```
BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/net-wireless/wireless-regdb:20220606-r2

Change-Id: I18bb65f91b82924c3697f8265c0321d75eceeda9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692253
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>