tests: kernel: device: use zephyr/ prefix for generated syscall header
CONFIG_LEGACY_GENERATED_INCLUDE_PATH is deprecated and no longer
enabled by default, so the un-prefixed <syscalls/abstract_driver.h>
include path is not available anymore and the test fails to build:

  fatal error: syscalls/abstract_driver.h: No such file or directory

Use the zephyr/ prefixed path for the generated syscall header, as
done for all other syscall headers in the tree.

Original-Signed-off-by: Anas Nashif <anas.nashif@intel.com>
GitOrigin-RevId: dcde0b35dd0c22ff5a24b3e03b281459ee4fef01
Cr-Build-Id: 8676394734931789729
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8676394734931789729
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I5e6ba5aa8243bd3f4d996e38641b65a2ed4cf5a3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/8084208
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>