heartd-tool: Fix deps on mojo_service_manager, system_api
heartd-tool needs mojo_service_manager already at build time, so the
latter should be in both DEPEND and RDEPEND. Also a build-time
dependency on system_api was missing.

This should fix the errors in Bazel builds:

```
Command: /usr/bin/env /build/amd64-generic/tmp/portage/chromeos-base/heartd-tool-0.0.1-r13/work/heartd-tool-0.0.1/common-mk/pkg-config_wrapper.py /build/amd64-generic/build/bin/pkg-config libbrillo libchrome mojo_service_manager
Returned 1.
stderr:

Package mojo_service_manager was not found in the pkg-config search path.
Perhaps you should add the directory containing `mojo_service_manager.pc'
to the PKG_CONFIG_PATH environment variable
Package 'mojo_service_manager', required by 'virtual:world', not found
```

```
../../../../../../../../../mnt/host/source/src/platform2/heartd/tools/heartd_tool.cc:15:10: fatal error: 'chromeos/mojo/service_constants.h' file not found
   15 | #include <chromeos/mojo/service_constants.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[12/15] CXX obj/gen/include/heartd/mojom/libheartd_mojo_bindings.heartd.mojom.o
ninja: build stopped: subcommand failed.
ERROR:root:Ninja failed
```

BUG=b:320947199,b:309049308
TEST=cros_sdk BOARD=amd64-generic /mnt/host/source/chromite/bin/bazel build @portage//target/chromeos-base/heartd-tool

Change-Id: Ic32b80d6cbcf9ddbd02bb9c60932a1d120c2ebb6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/5210834
Auto-Submit: Maksim Ivanov <emaxx@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Maksim Ivanov <emaxx@chromium.org>
Reviewed-by: Raul Rangel <rrangel@chromium.org>