drivers: timer: nrf_rtc_timer: Fix assert conditions
This commit fixes the incomplete assert conditions for the `chan`
argument passed to the nRF RTC timer functions.

Note that the `chan` argument for this driver is of a **signed**
integer type, so it is necessary to check that its value is
non-negative.

This fixes the warnings generated by the GCC 12 such as:

  error: array subscript -1 is below array bounds of '...'

(cherry picked from commit 4004475e7fbc93f9e845eca7d4bdf36599260d6c)

Original-Original-Signed-off-by: Stephanos Ioannidis <root@stephanos.io>
Original-GitOrigin-RevId: 4004475e7fbc93f9e845eca7d4bdf36599260d6c
Original-Change-Id: I71d8f82115467822481a1ec12fe494765bcc5d34
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3814834
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 9b8ba5d3368263e4e568f8abdbd93b3ebc85e833
Cr-Build-Id: 8693491704402870897
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693491704402870897
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I0ca1af8690817fec3548f5b0a0604350912f505d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7398202
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>