sysconfig.py: fix _{BASE,EXEC,BASE_EXEC}_PREFIX
Today, dev-python/numpy fails to compile against Python 3.11 when
building for a board. The specific error is:

    error: include location '/usr/include/python3.11' is unsafe for
    cross-compilation [-Werror,-Wpoison-system-directories]

I traced this error to the standard library function
distutils.sysconfig.get_python_inc(), which returns the directory
containing installed Python header files. Specifically, on line
https://github.com/python/cpython/blob/0c47759eee3e170e04a5dae82f12f6b375ae78f7/Lib/distutils/sysconfig.py#L276C28-L276C29,
it tries to compute a prefix based either BASE_EXEC_PREFIX or BASE_PREFIX,
which are aliases for sysconfig._BASE_EXEC_PREFIX and
sysconfig._BASE_PREFIX, respectively. In our sysconfig.py module, those
symbols are defined as os.path.normpath(sys.base_exec_prefix) and
os.path.normpath(sys.base_prefix), respectively, both of which always evaluate
to "/usr", regardless of whether we're building for the host or the
board. As a result, distutils.sysconfig.get_python_inc() always returns
"/usr/include/python3.11".

This CL redefines sysconfig._BASE_PREFIX and sysconfig._BASE_EXEC_PREFIX
to be synonyms of sysconfig._PREFIX, which takes into account the
SYSROOT environment variable. Thus, they evaluate to e.g.
"/board/<BOARD_NAME>/usr" when building for a board. I also redefined
sysconfig._EXEC_PREFIX similarly for consistency. If my reading of
https://docs.python.org/3/library/sys.html#sys.base_prefix,
https://docs.python.org/3/library/sys.html#sys.base_exec_prefix and
https://docs.python.org/3/library/sys.html#sys.exec_prefix is correct,
these redefines should be semantically correct. In any case, these
symbols are not part of the public sysconfig API, and we might be able
to drop them when we eventually upgrade to Python >= 3.12, which no longer
includes the distutils module.

Note: The reason why we don't see this error in Python 3.8 is that the
distutils module defines BASE_PREFIX and friends based on the sys module
rather than the sysconfig module; see
https://github.com/python/cpython/blob/v3.8.20/Lib/distutils/sysconfig.py#L24
and
https://github.com/python/cpython/blob/v3.11.10/Lib/distutils/sysconfig.py#L26.

BUG=b:318531403,b:362791110
TEST=CQ
TEST=sudo PYTHON_TARGETS="python3_8 python3_11" PYTHON_SINGLE_TARGET="python3_11" emerge -jv dev-lang/python dev-python/versioneer
TEST=sudo PYTHON_TARGETS="python3_8 python3_11" PYTHON_SINGLE_TARGET="python3_11" emerge-amd64-generic -jv dev-lang/python dev-python/numpy

Change-Id: I51b49bf3cebf948d3f34a5fa6bec17ed4229b8cf
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/5894809
Commit-Queue: Lee Presland <zland@google.com>
Tested-by: Leandro Lovisolo <lovisolo@google.com>
Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
Reviewed-by: Lee Presland <zland@google.com>
Auto-Submit: Leandro Lovisolo <lovisolo@google.com>