tests: arch: arm_custom_interrupt: exclude imx943
Exclude imx943,
  - multi level interrupts feature is enabled defaultly,
    so irqsteer1 driver is enabled, then the test case
    report the build issue:
    multiple definition of z_soc_irq_enable,
    tests/arch/arm/arm_custom_interrupt/src/arm_custom_interrupt.c:47
    first defined here.

(cherry picked from commit 9dcf76c6700ff38f433067e256303a788f7a6b02)

Original-Signed-off-by: Biwen Li <biwen.li@nxp.com>
GitOrigin-RevId: 9dcf76c6700ff38f433067e256303a788f7a6b02
Cr-Build-Id: 8694559427236376193
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694559427236376193
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Iaf26c819c09ec25dcffc70ee64c4045aaa1a49e0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7325288
Commit-Queue: Keith Short <keithshort@chromium.org>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: Keith Short <keithshort@chromium.org>
Reviewed-by: Keith Short <keithshort@chromium.org>