drivers: flash: Fix stm32 ospi and xpsi reset gpios handling
Fix compilation error when reset-gpios is enabled.
Undefined reference to dev_cfg variable.
Reset gpio duration needs to be defined, but is not in binding file.

(cherry picked from commit 04e56f72c71f5e05a2bf5666c67f6f1be13e13ed)

Original-Original-Signed-off-by: Joakim Andersson <joerchan@gmail.com>
Original-GitOrigin-RevId: 04e56f72c71f5e05a2bf5666c67f6f1be13e13ed
Original-Change-Id: I8153369acac95d4e08c29d4913f4c79bef7ba7b7
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5629319
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Jeremy Bettis <jbettis@chromium.org>
Original-Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
GitOrigin-RevId: 47988dceb891a470c008d73cd9bd2a42da0f226e
Cr-Build-Id: 8693006604855368641
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693006604855368641
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I2fab33b5c68b505c170a18857c7ad4aa0e101d2b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7438680
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>