samples: net: Disable native_posix target in more samples
The native_posix compilations fail with various socket
errors like this:

samples/net/sockets/can/src/main.c:65:9: error: implicit \
     declaration of function ‘send’ [-Werror=implicit-function-declaration]
     65 |   ret = send(fd, &sframe, sizeof(sframe), 0);
        |         ^~~~

So disable the native_posix board from networking samples as
native_posix board is not compatible with CONFIG_POSIX_API

This is related to commit b8fc1c4c3e ("samples: net: Disable
native_posix target in samples") but disables more network samples
for native_posix board.

(cherry picked from commit 03c5c0f818bc9e4ae860060ef4732d31717d40e6)

Original-Original-Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
Original-GitOrigin-RevId: 03c5c0f818bc9e4ae860060ef4732d31717d40e6
Original-Change-Id: Idfb25b5fc425d9135c6c53be0855235d98702940
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5465243
Original-Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: Jeremy Bettis <jbettis@chromium.org>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 2f12f71e6b51f99f459f45d25c6ef9a9d5d4d334
Cr-Build-Id: 8693045275188255777
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693045275188255777
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I536560be1b0e4a64aacb60ee0e4020c68ab41add
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7434943
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>