libhwsec-foundation: Work around possible clang bug
When adding to libchrome the Chromium change that gives CHECK failures
noreturn semantics (see the upstream CL at
https://chromium-review.googlesource.com/c/chromium/src/+/6043197), we
get the following build error for libhwsec:

..,/stackable_error.h:468:47: error: parameter 'other' not in expected state when the function returns: expected 'consumed', observed 'unknown' [-Werror,-Wconsumed]
  468 | [[clang::callable_when("unconsumed")]] void WrapInPlace(
      |                                             ^
.../stackable_error.h:519:5: note: in instantiation of function template specialization 'hwsec_foundation::status::_impl_::StackableError<hwsec::TPMError>::WrapInPlace<hwsec::TPMErrorBase>' requested here
  519 | WrapInPlace(std::move(other));
      | ^
1 error generated.

It seems to me that this is a bug in clang's 'consumed' feature (which
is marked as experimental), but I'm not an expert.

This CL implements a workaround so that libchrome can catch up with
Chromium.

BUG=b:381501261
TEST=emerge-hatch libhwsec
TEST=emerge-hatch libchrome libhwsec  # modified libchrome

Change-Id: I22f6c9c2e4e42e26cfe5ba7aec7c19e83dd92c6d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/6733999
Reviewed-by: Andrey Pronin <apronin@chromium.org>
Commit-Queue: Georg Neis <neis@chromium.org>
Tested-by: Georg Neis <neis@chromium.org>