drivers: display: rm67162: avoid uninitialized variable
Warning as error was:

.../drivers/display/display_rm67162.c: In function ‘rm67162_write_fb’:
.../drivers/display/display_rm67162.c:383:9: error: ‘wlen’ may be used
          uninitialized in this function [-Werror=maybe-uninitialized]
  383 |  return wlen;
      |         ^~~~

(cherry picked from commit 8bf8eeb3383d5e2c6eb3495bd3886ce851d3dd70)

Original-cc1: all warnings being treated as errors
Original-Signed-off-by: Stephan Linz <linz@li-pro.net>
GitOrigin-RevId: 8bf8eeb3383d5e2c6eb3495bd3886ce851d3dd70
Cr-Build-Id: 8692022711654242305
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692022711654242305
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I439b1c8830bcea6ef3503afac049c0765a349eba
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7508426
Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>