scripts: compliance: Fix handling of integer node items
Some node items in Kconfig can be kconfiglib.MENU or kconfiglib.COMMENT.
Those are integers and thus do not contain a node.item.name field.
Handle those separately to avoid hitting the followig exception:

Traceback (most recent call last):
  File "/home/runner/work/zephyr/zephyr/./scripts/ci/check_compliance.py",\
  line 1307, in main
    n_fails = _main(args)
  File "/home/runner/work/zephyr/zephyr/./scripts/ci/check_compliance.py",\
  line 1242, in _main
    test.run()
  File "/home/runner/work/zephyr/zephyr/./scripts/ci/check_compliance.py",\
  line 277, in run
    self.check_no_redefined_in_defconfig(kconf)
  File "/home/runner/work/zephyr/zephyr/./scripts/ci/check_compliance.py",\
  line 445, in check_no_redefined_in_defconfig
    Kconfig node '{node.item.name}' found with prompt or help in\
    {node.filename}.

Seen in #58454.

(cherry picked from commit ff2d9cfcb615558db2251f669b014b40bc64879c)

Original-Original-AttributeError: 'int' object has no attribute 'name'
Original-Original-Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>
Original-GitOrigin-RevId: ff2d9cfcb615558db2251f669b014b40bc64879c
Original-Change-Id: Idaf515b76ccd1fccc31d47686da53afcf6f30d59
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4665505
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 4c8140445054ef9d9ffbf53f6413743910828498
Cr-Build-Id: 8693191221522410721
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693191221522410721
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I2d844c5d50b691cdfcc670a6270d1440ed6eafac
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7419327
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>