UPSTREAM: perfetto: Disable rust target for trace proto on MCU's
Building //..." with "--config=rp2040" was giving:

> ERROR: toolchain type @@rules_rust_prost+//:toolchain_type resolved to
    target @@+pw_rust+pw_rust_toolchains//:prost_toolchain_impl, but
    that target does not provide ToolchainInfo

(cherry picked from commit 137aa7821d368af091fa09ac237c67a3075f0271)

Original-Test: Presubmit
Original-Test: bazelisk build --config=rp2040 //... # Needs other patches
Original-Test: bazelisk build --config=rp2350 //... # Needs other patches
Original-Bug: b/485711443
Original-Bug: b/461519669
Original-Change-Id: I599bcc8e541c194031c5196d698dd0e1dbf6a85d
Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/379974
GitOrigin-RevId: 137aa7821d368af091fa09ac237c67a3075f0271
Cr-Build-Id: 8688666850120209457
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8688666850120209457
Copybot-Job-Name: pigweed-main-copybot-downstream
Change-Id: I0bea5ab4c3e4dd89b15c76aa85a3c1866ac24617
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/pigweed/pigweed/+/7617277
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>