manifest: update hal_espressif for missing source
Adds the missing SPI sources on the C5, C6 and H2 ports.

Without this fix, any image that pulls in the SPI master driver
fails to link with:

  undefined reference to 'spi_periph_signal'

The following build_all targets are restored by the bump:

  tests/drivers/build_all/eeprom on esp32c5_devkitc
  tests/drivers/build_all/gpio   on esp32c6_devkitc
  tests/drivers/spi/spi_loopback on esp32h2_devkitm

Original-Signed-off-by: Sylvio Alves <sylvio.alves@espressif.com>
GitOrigin-RevId: 0f27ac51b77d2abcc2b55136dae30aec2c261185
Cr-Build-Id: 8680539547227215297
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8680539547227215297
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I378c55be88afba2163097710a52846db7e5466db
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7874359
Tested-by: Rob Barnes <robbarnes@google.com>
Reviewed-by: Rob Barnes <robbarnes@google.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Rob Barnes <robbarnes@google.com>