net: lib: coap: Remove unused function
Building with clang warns:

subsys/net/lib/coap/coap_link_format.c:39:20: error: unused function
'append_be16' [-Werror,-Wunused-function]
static inline bool append_be16(struct coap_packet *cpkt, uint16_t data)

(cherry picked from commit d81176077994da3135f813bef6b9029a399d2497)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: d81176077994da3135f813bef6b9029a399d2497
Original-Cr-Build-Id: 8723142769276654049
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723142769276654049
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I4fd59b9f09879eb0c0f5f2a5879b331e3d146944
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6257284
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 9efb8d4a00dee713cca3f1623dd7094d5d7b26d2
Cr-Build-Id: 8692857091111002929
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692857091111002929
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Icec79fea0a70057082f58b91d31b604ed2c356fc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7455904
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>