Autoupdate of 2 submodules
*chromite updated to 4784895bd9e986fb98d71780e93a161b3759828f
scripts: pylint: update to 3.2 version

We skip pylint 2.15 thru 3.1 because our code hits a recursion error
in the astroid logic, and it isn't fixed until the 3.2 series.  So
rather than try to rewrite our code to workaround the error, fast
forward to this version.

$ cros lint lib/request_build_unittest.py
Exception on node <AssignAttr.return_value l.81 at 0x7fe9fd136190> in file '.../chromite/lib/request_build_unittest.py'
...a lot more frames...
  File ".../lib/python3.11/site-packages/astroid/decorators.py", line 99, in inner
    raise InferenceError(
          ^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
...another exception...
lib/request_build_unittest.py:1:0: F0002: lib/request_build_unittest.py: Fatal error while checking 'lib/request_build_unittest.py'. Please open an issue in our bug tracker so we address this. (astroid-error)

Also update our custom pylint plugins to drop the interface APIs.
Upstream dropped them entirely with the 3.x series.

BUG=b:318532035
TEST=linting all files in chromite is mostly the same

Change-Id: Ie2fdca161df3f7db6717b49f275ca102d57811bc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/6217999
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Leandro Lovisolo <lovisolo@google.com>
Tested-by: Mike Frysinger <vapier@chromium.org>

*infra/chromite-HEAD updated to 4784895bd9e986fb98d71780e93a161b3759828f
scripts: pylint: update to 3.2 version

We skip pylint 2.15 thru 3.1 because our code hits a recursion error
in the astroid logic, and it isn't fixed until the 3.2 series.  So
rather than try to rewrite our code to workaround the error, fast
forward to this version.

$ cros lint lib/request_build_unittest.py
Exception on node <AssignAttr.return_value l.81 at 0x7fe9fd136190> in file '.../chromite/lib/request_build_unittest.py'
...a lot more frames...
  File ".../lib/python3.11/site-packages/astroid/decorators.py", line 99, in inner
    raise InferenceError(
          ^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
...another exception...
lib/request_build_unittest.py:1:0: F0002: lib/request_build_unittest.py: Fatal error while checking 'lib/request_build_unittest.py'. Please open an issue in our bug tracker so we address this. (astroid-error)

Also update our custom pylint plugins to drop the interface APIs.
Upstream dropped them entirely with the 3.x series.

BUG=b:318532035
TEST=linting all files in chromite is mostly the same

Change-Id: Ie2fdca161df3f7db6717b49f275ca102d57811bc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/6217999
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Leandro Lovisolo <lovisolo@google.com>
Tested-by: Mike Frysinger <vapier@chromium.org>