drivers: rtc: maxim,ds3231: avoid compilation error
Because of wrong integer type syntax following error occurred:

drivers/rtc/rtc_ds3231.c:361:76: error: unknown type name 'u'
  361 | static int rtc_ds3231_alarm_get_supported_fields(
      |                    const struct device *dev, u int16_t id,
      |                                              ^

(cherry picked from commit cca2053448c3d7a2abf699fd12ac29a34bbd0e25)

Original-Signed-off-by: Stephan Linz <linz@li-pro.net>
GitOrigin-RevId: cca2053448c3d7a2abf699fd12ac29a34bbd0e25
Cr-Build-Id: 8723776949373603889
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723776949373603889
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I454e92d0bcf9676399461b1d4ac5830a847dd66e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6234543
Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>