drivers: hwinfo: fix build with NEWLIB_LIBC=y
When NEWLIB_LIBC=y, building the hwinfo drivers fails with:

In file included from ZEPHYR_ROOT/drivers/hwinfo/hwinfo_weak_impl.c:7:0:
ZEPHYR_ROOT/include/hwinfo.h:43:1: error: unknown type name '__syscall';
did you mean '__fastcall'?
 __syscall ssize_t hwinfo_get_device_id(u8_t *buffer, size_t length);
 ^~~~~~~~~
 __fastcall
ZEPHYR_ROOT/include/hwinfo.h:43:19: error: expected '=', ',', ';', 'asm'
or '__attribute__' before 'hwinfo_get_device_id'
 __syscall ssize_t hwinfo_get_device_id(u8_t *buffer, size_t length);
                   ^~~~~~~~~~~~~~~~~~~~
ZEPHYR_ROOT/drivers/hwinfo/hwinfo_weak_impl.c:9:16: error: expected '=',
',', ';', 'asm' or '__attribute__' before '_impl_hwinfo_get_device_id'
 ssize_t __weak _impl_hwinfo_get_device_id(u8_t *buffer, size_t length)
                ^~~~~~~~~~~~~~~~~~~~~~~~~~

The <hwinfo.h> file uses __syscall and this symbols is defined by
<kernel.h>. This doesn't happen with the real drivers as they include
<device.h> and thus <kernel.h>.

Fix that by including <kernel.h> from <hwinfo.h>

Original-ninja: build stopped: subcommand failed.
Original-Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>
GitOrigin-RevId: 1d8a0bc1aad4412ec5954a1fc2f9fb5e8a9eef8b
Cr-Build-Id: 8694321715276821841
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694321715276821841
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I51405b0e00d043fdb099affdafcbf6c8faaf70f2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7341768
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>