chromeos-base/debugd: Add missing BDEPEND
```
FAILED: gen/include/debugd/dbus_adaptors/org.chromium.debugd.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

```
FAILED: gen/include/key.pb.cc gen/include/key.pb.h gen/include/rpc.pb.cc gen/include/rpc.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
/build/arm64-generic/etc/portage/hooks/install/check-seccomp.sh: line 27: compile_seccomp_policy: command not found
 * ERROR: chromeos-base/debugd-9999::chromiumos failed:
 ```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/debugd:9999

Change-Id: Idc1bb1577f3a5e608036f551d9df35cd289a1026
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692094
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>