soc: ti: k3: guard the NS16550 word-access select on the M4 series
SOC_SERIES_AM62X_M4 and SOC_SERIES_AM64X_M4 select
UART_NS16550_ACCESS_WORD_ONLY unconditionally, but that symbol depends
on UART_NS16550 && SERIAL. A build with no ns16550 node enabled in the
devicetree therefore aborts on an unsatisfied select:

  warning: UART_NS16550_ACCESS_WORD_ONLY ... has direct dependencies
  UART_NS16550 && SERIAL with value n, but is currently being
  y-selected by the following symbols:
   - SOC_SERIES_AM62X_M4
  error: Aborting due to Kconfig warnings

Add the `if UART_NS16550` guard that the R5 series in this directory
already use. The symbol keeps its value wherever UART_NS16550 is y, so
no board with a serial port is affected.

Original-Signed-off-by: Chrispine Tinega <dev@chrispinetinega.com>
GitOrigin-RevId: e323eb981a98a63e007c800459606cf0297ab122
Cr-Build-Id: 8668920485926419441
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8668920485926419441
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I7d2c3da487b3ac4cc68eef6752fad8138414fc87
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/8511207
Commit-Queue: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>