media-sound/cras-client: Add missing BDEPEND
```
  thread 'main' panicked at 'dbus-codegen-rust required, but not found: CannotFindBinaryPath', cras_tests/build.rs:22:9
 * ERROR: media-sound/cras-client-9999::chromiumos failed (compile phase):
```

```
../../include/cras_audio_format.h:45:10: fatal error: 'alsa/asoundlib.h' file not found
```

Why this is linking against the BHOST's libraries is a different
question...

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/media-sound/cras-client:9999

Change-Id: I3bc8c984120e347f6c89d843bc807f84b2e92b4a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692152
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>