sys-fs/lxcfs: fix strchr/strrchr const breakage with glibc 2.43
glibc 2.43 implements strchr()/strrchr() via a _Generic macro
that propagates the input const qualifier to the return type.

Together with clang's -Werror=incompatible-pointer-types this
breaks the lxcfs-5.0.4 build:

  src/cpuset_parse.c:24:4: error: assigning to 'char *' from
      'const char *' discards qualifiers
  src/cgroup_fuse.c:148:8: error: assigning to 'char *' from
      'const char *' discards qualifiers

Add a patch fixing both sites, which is a backport of upstream
commit 724163721bfa ("cpuset_parse: constify return value of
cpuset_nexttok"), which fixed lxcfs issue #707.

I opted for a backport instead of upreving because lxcfs 7.x
hard requires fuse 3 and will likely trigger a cascade of
upgrades for other components. We only need to unblock glibc.

BUG=b:491765858
TEST=emerge-tael sys-fs/lxcfs

Change-Id: I610d5d324ebaffaa22afae294b22aadcc7de85c1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/8119451
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: Zihan Chen <zihanchen@google.com>
Commit-Queue: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Auto-Submit: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: Leandro Lovisolo <lovisolo@google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>