UPSTREAM: pw_snaphot: Fix processor argparse types
This fixes two bytes-vs-str related issues:

1. `--out-file` should be a text file, not a binary file, indicated by
   the `out_file: TextIO` parameter of _load_and_dump_snapshots().

   This fixes the following error when running with no --out-file
   argument:

   TypeError: a bytes-like object is required, not 'str'

2. Change `--token-db` just a string, and update the
   _load_and_dump_snapshots() parameter accordingly.
   pw_tokenizer.Detokenizer() accepts plain paths, and intelligently
   opens files.

   This avoids the following error down in elf_reader.py when passing an
   ELF (binary):

   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in
   position 100: invalid continuation byte

(cherry picked from commit 75b65593ebea4d9c7c96f47776bdc8cdf7f4ae48)

Original-Test: python3 -m pw_snapshot.processor --token-db firmware.elf crash.binpb
Original-Change-Id: Ida4f2a0d180a99605614f61e4a4da70b5f3bfbf9
Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/301134
Original-Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Original-Presubmit-Verified: CQ Bot Account <pigweed-scoped@luci-project-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: Jonathon Reinhart <jrreinhart@google.com>
Original-Docs-Not-Needed: Jonathon Reinhart <jrreinhart@google.com>
Original-Tests-Not-Needed: Jonathon Reinhart <jrreinhart@google.com>
Original-Reviewed-by: Carlos Chinchilla <cachinchilla@google.com>
Original-Copybara-Verified: Copybara Prod <copybara-worker-blackhole@google.com>
GitOrigin-RevId: 75b65593ebea4d9c7c96f47776bdc8cdf7f4ae48
Cr-Build-Id: 8709957135378456545
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8709957135378456545
Copybot-Job-Name: pigweed-main-copybot-downstream
Change-Id: I1e9c1901993adbf4129f2dba9dc128aa533538d8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/pigweed/pigweed/+/6711046
Tested-by: Yuval Peress <peress@google.com>
Commit-Queue: Yuval Peress <peress@google.com>
Reviewed-by: Yuval Peress <peress@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>