ectool: add support for lightbar
Adds lightbar option to ectool led command.

BUG=b:440339256
TEST=ectool led light off
         Bad LED name: light
         Valid LED names: battery power adapter left right
         recovery_hwreinit sysrq debug lightbar
     ectool lightbar
         EC result 1 (INVALID_COMMAND)
         warning: ectool lightbar is depricated. Use ectool led lightbar
         instead.
     ectool led lightbar query
         EC result 3 (INVALID_PARAM)
         Brightness range for LED 7:
         Error: Unsupported LED.
The DUT doesn't actually have a lightbar so the last error is expected.

Change-Id: I6117cfe3f2bcbd941d4917a44d8f9f16419a39c9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/6887048
Tested-by: zhi cheng yuan <jasonyuan@chromium.org>
Reviewed-by: Boris Mittelberg <bmbm@google.com>
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
Commit-Queue: zhi cheng yuan <jasonyuan@chromium.org>