UPSTREAM: bazel: Update rules_cc to 0.2.16
This is a prerequisite to updating protobuf.

MODULE.bazel file for now, to avoid a build error:

    ERROR: Failed to load Starlark extension
    '@@cc_compatibility_proxy//:symbols.bzl

The patch is:

    cc_compatibility_proxy =
        use_extension("@rules_cc//cc:extensions.bzl",
                      "compatibility_proxy")
    use_repo(cc_compatibility_proxy, "cc_compatibility_proxy")

(cherry picked from commit a421bbdcfaf316ced3536ea3db367c7860072d5d)

Original-Note: Unfortunately downstream Bazel users may need to patch their
Original-Bug: 436600181
Original-Change-Id: I9982021f834da768f7bfc840081ac29dda65a0e0
Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/370752
GitOrigin-RevId: a421bbdcfaf316ced3536ea3db367c7860072d5d
Cr-Build-Id: 8689572817712811761
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8689572817712811761
Copybot-Job-Name: pigweed-main-copybot-downstream
Change-Id: I6e57d99fe61f7ebba7ed35e0f9c007af1fd599d1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/pigweed/pigweed/+/7586157
Reviewed-by: Keith Short <keithshort@chromium.org>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: Keith Short <keithshort@chromium.org>
Commit-Queue: Keith Short <keithshort@chromium.org>