Revert "profiles: add package-name CFLAG hook"
This reverts commit 3a7f5e5c955c956d1fa6facd7c6122c870d50162.

Reason for revert: Breaks chromeos-chrome build.

e.g. http://ci.chromium.org/b/8714909975670731777

Error: "--rewrapper-path must be specified if --rewrapper-cfg is"

Suspecting it's caused by missing space before "--rewrapper-cfg"
arg, as shown in log:

-D_CROSTC_ADD_IMPLICIT_CFLAGS_FOR=chromeos-base/chromeos-chrome--rewrapper-path <path-goes-here>

Here's likely where "--rewrapper-cfg" gets appended, without
leading space:
https://crsrc.org/c/build/toolchain/cros/BUILD.gn;l=32;bpv=1

whereas construction of "-D_CROSTC_ADD_IMPLICIT_CFLAGS_FOR="
(newly added by the CL being reverted) doesn't have a trailing
space either.


Original change's description:
> profiles: add package-name CFLAG hook
>
> This adds the current package name to each package's CFLAGS and env, to
> power b/405989954.
>
> Generally speaking, a CFLAG would be nicer than env, since:
> 1. `env` is less copy-pasteable.
> 2. Some build systems filter out `env`; fewer filter CFLAGS
>
> However, using both gets us better out-of-the-box coverage. If there's
> a strong desire for one or the other, happy to talk about it and/or
> file FRs to trim down to one of the two. That said, having both doesn't
> seem like a terrible hack.
>
> The layer of indirection of "tell the compiler wrapper what the package
> is, so it can figure out what flags to apply" rather than "just have the
> flags to apply in a large map here" is because:
> 1. The warning-disable flags we want to apply with this mechanism should
>    override flags applied in ebuilds, so need to be appended after the
>    ebuild has appended its own flags. If we prepend them, an ebuild
>    could easily `-Wfoo -Werror=foo`, which would partially defeat the
>    purpose of this initiative.
> 2. Toolchain has OWNERship in sys-devel/llvm, and isn't necessarily
>    equipped to do OWNERS reviews here.
> 3. compiler_wrapper changes are more thoroughly tested (it sits in
>    sys-devel/llvm, so the CQ will rebuild everything from source).
>
> BUG=b:403315166
> TEST=`emerge-amd64-generic minijail` printed this flag
> TEST=`sudo emerge coreutils` printed this flag
>
> Change-Id: I34b62f4e4a9236dc2f581d5b7885ee0c929b866f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/6388817
> Reviewed-by: Raul Rangel <rrangel@chromium.org>
> Commit-Queue: George Burgess <gbiv@chromium.org>
> Tested-by: George Burgess <gbiv@chromium.org>
> Reviewed-by: Bob Haarman <inglorion@chromium.org>

BUG=b:403315166

Change-Id: If8d5fc5a9ccbf1b756ff1bed045db7ba1de41d19
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/6543398
Tested-by: Bao-Duy Tran <tranbaoduy@chromium.org>
Commit-Queue: Bao-Duy Tran <tranbaoduy@chromium.org>
Auto-Submit: Bao-Duy Tran <tranbaoduy@chromium.org>
Owners-Override: Bao-Duy Tran <tranbaoduy@chromium.org>
Tested-by: Chuong Ho <hdchuong@chromium.org>
Commit-Queue: Chuong Ho <hdchuong@chromium.org>
Reviewed-by: Chuong Ho <hdchuong@chromium.org>
Reviewed-by: George Burgess <gbiv@chromium.org>