chromeos-base/autotest-chrome: Add missing rsync BDEPEND
```
ModuleNotFoundError: No module named 'telemetry'
ERROR:root:video_AVAnalysis import error: No module named 'telemetry'.  Skipping video_AVAnalysis
```

rsync is called in `src_prepare`.

BUG=b:317413089
TEST=bazel CQ

Change-Id: I0389dd874ec22b2e19f15e2bd6a9aa9cdc85503e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/5235129
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>