chromeos-installer: Support lvm_stateful from Rust
When chromeos-install was a shell script handling of the
`lvm_stateful_partition` USE flag was done by running sed on
chromeos-install to replace the default value. That's not going to work
with rust. Instead the default is controlled by a crate feature
`lvm_stateful_partition`. Set that feature based on the USE flag.

BUG=b:356344778
TEST=With the changes from crrev.com/c/5830990 :
     $ cros_sdk USE=-lvm_stateful_partition -- emerge-reven \
                                               chromeos-installer
     $ cros deploy vm chromeos-installer
     $ ssh vm chromeos-install
     > Running: [...] FLAGS_lvm_stateful="1" [...] chromeos-install.sh"
     > Error: can not determine destination device. Specify --dst yourself.

     $ cros_sdk USE=lvm_stateful_partition -- emerge-reven \
                                              chromeos-installer
     $ cros deploy vm chromeos-installer
     $ ssh vm chromeos-install
     > Running: [...] FLAGS_lvm_stateful="0" [...] chromeos-install.sh"
     > Error: can not determine destination device. Specify --dst yourself.

Cq-Depend: chromium:5830990
Change-Id: If99c38cc33f36011e4a086b3b999df4f1a2d7fc0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/5835576
Reviewed-by: Nicholas Bishop <nicholasbishop@google.com>
Commit-Queue: Ted Brandston <tbrandston@google.com>
Tested-by: Ted Brandston <tbrandston@google.com>
Reviewed-by: Sarthak Kukreti <sarthakkukreti@google.com>