chromeos-base/chromeos-login: Add missing BDEPEND
```
FAILED: gen/include/bindings/install_attributes.pb.cc gen/include/bindings/install_attributes.pb.h
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
```

```
FAILED: gen/include/login_manager/dbus_adaptors/org.chromium.SessionManagerInterface.h
FileNotFoundError: [Errno 2] No such file or directory: 'go-generate-chromeos-dbus-bindings'
```

```
/build/arm64-generic/tmp/portage/chromeos-base/chromeos-login-9999/temp/environment: line 4675: certutil: command not found
```

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build @portage//internal/packages/stage2/target/board/chromiumos/chromeos-base/chromeos-login:9999

Change-Id: I07ccdbc223c881c1bd5a3d33e527f27d79d6cf82
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4692083
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>