scripts: west_commands: patch: treat all subprocess output as text
Pass 'encoding="utf-8"' to all 'subprocess.run()' calls.
This treats the captured stdout and stderr streams as text rather than
byte sequences.

Example without this patch:
west patch apply --roll-back
FATAL ERROR: failed to apply patch libcsp/test.patch

Example with this patch:
west patch apply --roll-back

FATAL ERROR: failed to apply patch libcsp/test.patch

(cherry picked from commit 039013f8ef39fc818d6fe4417f92b04005a35368)

Original-ERROR: b'error: patch failed: examples/csp_server_client.py:32\n
Original-error: examples/csp_server_client.py: patch does not apply\n'
Original-ERROR: error: patch failed: examples/csp_server_client.py:32
Original-error: examples/csp_server_client.py: patch does not apply
Original-Signed-off-by: Mirai SHINJO <oss@mshinjo.com>
GitOrigin-RevId: 039013f8ef39fc818d6fe4417f92b04005a35368
Cr-Build-Id: 8697956813069601489
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8697956813069601489
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I1686cabdc38232ac53e1d9dea82f92ab6ca0df15
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7159641
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>