samples: net: Disable native_posix target in samples
The native_posix compilations fail with various socket
errors like this:

samples/net/sockets/echo_server/src/udp.c:45:26: error: implicit \
 declaration of function ‘socket’ [-Werror=implicit-function-declaration]
 45 |         data->udp.sock = socket(bind_addr->sa_family, SOCK_DGRAM,
    |                                 IPPROTO_UDP);

Disable the native_posix board from networking samples so that CI can pass.

(cherry picked from commit b8fc1c4c3e0b2bbf0a6403c185a60db104b900a3)

Original-Original-Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
Original-GitOrigin-RevId: b8fc1c4c3e0b2bbf0a6403c185a60db104b900a3
Original-Change-Id: I5feb7ab422ed48c0380cc31ea269414933aeded0
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5427359
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: 850cc1e15915ce3aace70b084297921b5e1ffe17
Cr-Build-Id: 8693049822557258897
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693049822557258897
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I44b2d34ad6130676612ab9f6ac629985e85af4c7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7434491
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>