chrome_ti50: Fix taskinfo flake
Improve get_taskinfo_output from CL:4810091 to avoid flaky failure
of firmware_Cr50DeviceState. Depending on UART timing, the "Stack
sizes and utilization" section may or may not be included in output.
Make sure we don't pass it on, since get_irq_counts will turn it into
invalid IRQ counts, causing failure like:
TestNAError: 1 test found negative idle in S5 count -1432 (likely due to servo dropping characters)
https://ci.chromium.org/ui/p/chromeos/builders/test_runner/test_runner/b8768243786746312977/overview

> taskinfo
IRQ counts by type:
   0      168
   7        2
  27        1
  34        1
  35        1
  36        1
  40        1
  47        1
  54        1
 108       13
 256        1

Stack sizes and utilization
 Name          Size  Room
--------------------------
kernel      : 16384 13916
fw_updater  :  2000  1432
tpm2        :  4096  2464
sys_mgr     :  2400   136
u2f         :  2048  1640
pinweaver   :  2560  2000

BUG=none
TEST=none

Change-Id: I5798d0c3e16cf040b31c01a3e27a93ee45caadbd
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/4910032
Commit-Queue: Edward Hill <ecgh@chromium.org>
Commit-Queue: Mary Ruthven <mruthven@chromium.org>
Auto-Submit: Edward Hill <ecgh@chromium.org>
Tested-by: Edward Hill <ecgh@chromium.org>
Reviewed-by: Mary Ruthven <mruthven@chromium.org>